// AUTO-GENERATED by scripts/generate-category-icons.mjs — do not edit by hand.
// Source layout: assets/icon-packs/<pack>/<Group>/<icon>.png
import type { ImageSourcePropType } from 'react-native';

export interface GeneratedIconPack {
  /** Slug of the pack folder. */
  id: string;
  /** Pack folder name, used as the fallback label. */
  name: string;
}

export interface GeneratedCategoryIcon {
  /** Stable id (the PNG filename without extension). This is the value stored
   *  on categories.icon / accounts.goal_emoji / budget_templates.emoji. */
  id: string;
  /** Slug of the pack folder this icon came from. */
  pack: string;
  /** Slug of the group folder, i.e. its section in the picker. */
  group: string;
  /** Title-cased id, used when categoryIconGroups.ts sets no explicit name. */
  fallbackName: string;
}

export const ICON_PACKS: GeneratedIconPack[] = [{ id: 'default', name: 'default' }];

export const CATEGORY_ICON_SOURCES: Record<string, ImageSourcePropType> = {
  'bill-calendar': require('../assets/icon-packs/default/Bills/bill-calendar.png'),
  invoice: require('../assets/icon-packs/default/Bills/invoice.png'),
  warning: require('../assets/icon-packs/default/Bills/warning.png'),
  balloon: require('../assets/icon-packs/default/Family/balloon.png'),
  cat: require('../assets/icon-packs/default/Family/cat.png'),
  dog: require('../assets/icon-packs/default/Family/dog.png'),
  'paw-print': require('../assets/icon-packs/default/Family/paw-print.png'),
  alcohol: require('../assets/icon-packs/default/Food and drink/alcohol.png'),
  coffee: require('../assets/icon-packs/default/Food and drink/coffee.png'),
  'grocery-basket': require('../assets/icon-packs/default/Food and drink/grocery-basket.png'),
  meal: require('../assets/icon-packs/default/Food and drink/meal.png'),
  'boxing-gloves': require('../assets/icon-packs/default/Health/boxing-gloves.png'),
  dumbbell: require('../assets/icon-packs/default/Health/dumbbell.png'),
  heart: require('../assets/icon-packs/default/Health/heart.png'),
  medicine: require('../assets/icon-packs/default/Health/medicine.png'),
  stethoscope: require('../assets/icon-packs/default/Health/stethoscope.png'),
  'yoga-mat': require('../assets/icon-packs/default/Health/yoga-mat.png'),
  faucet: require('../assets/icon-packs/default/Home/faucet.png'),
  house: require('../assets/icon-packs/default/Home/house.png'),
  keys: require('../assets/icon-packs/default/Home/keys.png'),
  'light-bulb': require('../assets/icon-packs/default/Home/light-bulb.png'),
  'potted-plant': require('../assets/icon-packs/default/Home/potted-plant.png'),
  sofa: require('../assets/icon-packs/default/Home/sofa.png'),
  wrench: require('../assets/icon-packs/default/Home/wrench.png'),
  ballone: require('../assets/icon-packs/default/Leisure/ballone.png'),
  'chess-knight': require('../assets/icon-packs/default/Leisure/chess-knight.png'),
  clapperboard: require('../assets/icon-packs/default/Leisure/clapperboard.png'),
  'game-controller': require('../assets/icon-packs/default/Leisure/game-controller.png'),
  gift: require('../assets/icon-packs/default/Leisure/gift.png'),
  headphone: require('../assets/icon-packs/default/Leisure/headphone.png'),
  bank: require('../assets/icon-packs/default/Money/bank.png'),
  cash: require('../assets/icon-packs/default/Money/cash.png'),
  'coins-checkmark': require('../assets/icon-packs/default/Money/coins-checkmark.png'),
  'coins-euro': require('../assets/icon-packs/default/Money/coins-euro.png'),
  coins: require('../assets/icon-packs/default/Money/coins.png'),
  'credit-card': require('../assets/icon-packs/default/Money/credit-card.png'),
  'globe-money': require('../assets/icon-packs/default/Money/globe-money.png'),
  'globe-shield': require('../assets/icon-packs/default/Money/globe-shield.png'),
  'piggy-bank': require('../assets/icon-packs/default/Money/piggy-bank.png'),
  wallet: require('../assets/icon-packs/default/Money/wallet.png'),
  'question-mark': require('../assets/icon-packs/default/Other/question-mark.png'),
  target: require('../assets/icon-packs/default/Other/target.png'),
  cosmetics: require('../assets/icon-packs/default/Shopping/cosmetics.png'),
  dress: require('../assets/icon-packs/default/Shopping/dress.png'),
  'price-tag': require('../assets/icon-packs/default/Shopping/price-tag.png'),
  'shopping-bag': require('../assets/icon-packs/default/Shopping/shopping-bag.png'),
  sneaker: require('../assets/icon-packs/default/Shopping/sneaker.png'),
  't-shirt': require('../assets/icon-packs/default/Shopping/t-shirt.png'),
  bus: require('../assets/icon-packs/default/Transport/bus.png'),
  'camper-van': require('../assets/icon-packs/default/Transport/camper-van.png'),
  car: require('../assets/icon-packs/default/Transport/car.png'),
  'gas-pump': require('../assets/icon-packs/default/Transport/gas-pump.png'),
  plane: require('../assets/icon-packs/default/Transport/plane.png'),
  van: require('../assets/icon-packs/default/Transport/van.png'),
  beach: require('../assets/icon-packs/default/Travel/beach.png'),
  camera: require('../assets/icon-packs/default/Travel/camera.png'),
  mountain: require('../assets/icon-packs/default/Travel/mountain.png'),
  'work-bag': require('../assets/icon-packs/default/Travel/work-bag.png'),
  briefcase: require('../assets/icon-packs/default/Work/briefcase.png'),
  gear: require('../assets/icon-packs/default/Work/gear.png'),
  'graduation-cap': require('../assets/icon-packs/default/Work/graduation-cap.png'),
  laptop: require('../assets/icon-packs/default/Work/laptop.png'),
};

export const GENERATED_CATEGORY_ICONS: GeneratedCategoryIcon[] = [
  { id: 'bill-calendar', pack: 'default', group: 'bills', fallbackName: 'Bill Calendar' },
  { id: 'invoice', pack: 'default', group: 'bills', fallbackName: 'Invoice' },
  { id: 'warning', pack: 'default', group: 'bills', fallbackName: 'Warning' },
  { id: 'balloon', pack: 'default', group: 'family', fallbackName: 'Balloon' },
  { id: 'cat', pack: 'default', group: 'family', fallbackName: 'Cat' },
  { id: 'dog', pack: 'default', group: 'family', fallbackName: 'Dog' },
  { id: 'paw-print', pack: 'default', group: 'family', fallbackName: 'Paw Print' },
  { id: 'alcohol', pack: 'default', group: 'food-and-drink', fallbackName: 'Alcohol' },
  { id: 'coffee', pack: 'default', group: 'food-and-drink', fallbackName: 'Coffee' },
  {
    id: 'grocery-basket',
    pack: 'default',
    group: 'food-and-drink',
    fallbackName: 'Grocery Basket',
  },
  { id: 'meal', pack: 'default', group: 'food-and-drink', fallbackName: 'Meal' },
  { id: 'boxing-gloves', pack: 'default', group: 'health', fallbackName: 'Boxing Gloves' },
  { id: 'dumbbell', pack: 'default', group: 'health', fallbackName: 'Dumbbell' },
  { id: 'heart', pack: 'default', group: 'health', fallbackName: 'Heart' },
  { id: 'medicine', pack: 'default', group: 'health', fallbackName: 'Medicine' },
  { id: 'stethoscope', pack: 'default', group: 'health', fallbackName: 'Stethoscope' },
  { id: 'yoga-mat', pack: 'default', group: 'health', fallbackName: 'Yoga Mat' },
  { id: 'faucet', pack: 'default', group: 'home', fallbackName: 'Faucet' },
  { id: 'house', pack: 'default', group: 'home', fallbackName: 'House' },
  { id: 'keys', pack: 'default', group: 'home', fallbackName: 'Keys' },
  { id: 'light-bulb', pack: 'default', group: 'home', fallbackName: 'Light Bulb' },
  { id: 'potted-plant', pack: 'default', group: 'home', fallbackName: 'Potted Plant' },
  { id: 'sofa', pack: 'default', group: 'home', fallbackName: 'Sofa' },
  { id: 'wrench', pack: 'default', group: 'home', fallbackName: 'Wrench' },
  { id: 'ballone', pack: 'default', group: 'leisure', fallbackName: 'Ballone' },
  { id: 'chess-knight', pack: 'default', group: 'leisure', fallbackName: 'Chess Knight' },
  { id: 'clapperboard', pack: 'default', group: 'leisure', fallbackName: 'Clapperboard' },
  { id: 'game-controller', pack: 'default', group: 'leisure', fallbackName: 'Game Controller' },
  { id: 'gift', pack: 'default', group: 'leisure', fallbackName: 'Gift' },
  { id: 'headphone', pack: 'default', group: 'leisure', fallbackName: 'Headphone' },
  { id: 'bank', pack: 'default', group: 'money', fallbackName: 'Bank' },
  { id: 'cash', pack: 'default', group: 'money', fallbackName: 'Cash' },
  { id: 'coins-checkmark', pack: 'default', group: 'money', fallbackName: 'Coins Checkmark' },
  { id: 'coins-euro', pack: 'default', group: 'money', fallbackName: 'Coins Euro' },
  { id: 'coins', pack: 'default', group: 'money', fallbackName: 'Coins' },
  { id: 'credit-card', pack: 'default', group: 'money', fallbackName: 'Credit Card' },
  { id: 'globe-money', pack: 'default', group: 'money', fallbackName: 'Globe Money' },
  { id: 'globe-shield', pack: 'default', group: 'money', fallbackName: 'Globe Shield' },
  { id: 'piggy-bank', pack: 'default', group: 'money', fallbackName: 'Piggy Bank' },
  { id: 'wallet', pack: 'default', group: 'money', fallbackName: 'Wallet' },
  { id: 'question-mark', pack: 'default', group: 'other', fallbackName: 'Question Mark' },
  { id: 'target', pack: 'default', group: 'other', fallbackName: 'Target' },
  { id: 'cosmetics', pack: 'default', group: 'shopping', fallbackName: 'Cosmetics' },
  { id: 'dress', pack: 'default', group: 'shopping', fallbackName: 'Dress' },
  { id: 'price-tag', pack: 'default', group: 'shopping', fallbackName: 'Price Tag' },
  { id: 'shopping-bag', pack: 'default', group: 'shopping', fallbackName: 'Shopping Bag' },
  { id: 'sneaker', pack: 'default', group: 'shopping', fallbackName: 'Sneaker' },
  { id: 't-shirt', pack: 'default', group: 'shopping', fallbackName: 'T Shirt' },
  { id: 'bus', pack: 'default', group: 'transport', fallbackName: 'Bus' },
  { id: 'camper-van', pack: 'default', group: 'transport', fallbackName: 'Camper Van' },
  { id: 'car', pack: 'default', group: 'transport', fallbackName: 'Car' },
  { id: 'gas-pump', pack: 'default', group: 'transport', fallbackName: 'Gas Pump' },
  { id: 'plane', pack: 'default', group: 'transport', fallbackName: 'Plane' },
  { id: 'van', pack: 'default', group: 'transport', fallbackName: 'Van' },
  { id: 'beach', pack: 'default', group: 'travel', fallbackName: 'Beach' },
  { id: 'camera', pack: 'default', group: 'travel', fallbackName: 'Camera' },
  { id: 'mountain', pack: 'default', group: 'travel', fallbackName: 'Mountain' },
  { id: 'work-bag', pack: 'default', group: 'travel', fallbackName: 'Work Bag' },
  { id: 'briefcase', pack: 'default', group: 'work', fallbackName: 'Briefcase' },
  { id: 'gear', pack: 'default', group: 'work', fallbackName: 'Gear' },
  { id: 'graduation-cap', pack: 'default', group: 'work', fallbackName: 'Graduation Cap' },
  { id: 'laptop', pack: 'default', group: 'work', fallbackName: 'Laptop' },
];
