import {
  AlarmClock,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart3,
  Banknote,
  Bell,
  BellOff,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleX,
  Clock3,
  CloudOff,
  CloudUpload,
  Coins,
  CreditCard,
  Crown,
  DatabaseBackup,
  Delete,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Fingerprint,
  Flame,
  FolderTree,
  Frown,
  Gift,
  GripVertical,
  HandCoins,
  Handshake,
  Heart,
  History,
  Home,
  Hourglass,
  ImageOff,
  ImagePlus,
  Images,
  Info,
  Landmark,
  LayoutGrid,
  LineChart,
  ListChecks,
  Lock,
  type LucideIcon,
  Maximize2,
  Meh,
  MessageCircle,
  Mic,
  Minus,
  MoreHorizontal,
  MousePointerClick,
  Newspaper,
  Nfc,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Pencil,
  PieChart,
  PiggyBank,
  Plus,
  QrCode,
  ReceiptText,
  RefreshCcw,
  Repeat2,
  Scale,
  ScanLine,
  Search,
  SearchX,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  SplitSquareHorizontal,
  Sprout,
  SquarePen,
  SquarePlus,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Undo2,
  Upload,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  WifiOff,
  X,
  Zap,
} from 'lucide-react-native';

import type { ClayIconName } from './clayIcons.generated';

/**
 * Which theme colour a flat icon is drawn in. Clay carries its own colour, so
 * these tones only exist on the flat side.
 */
export type FlatIconTone = 'primary' | 'text' | 'muted' | 'success' | 'destructive' | 'white';

export interface FlatIconSpec {
  icon: LucideIcon;
  tone?: FlatIconTone;
  strokeWidth?: number;
  /** Draw the glyph solid as well as stroked (an active tab, a Pro crown). */
  filled?: boolean;
}

/**
 * The flat line icon each clay illustration stands in for, used when the user
 * sets `iconStyle: 'flat'` (see `~/components/ui/ClayIcon`).
 *
 * Where the clay adoption replaced a specific Lucide icon, this map names that
 * exact icon so flat mode restores what was there before, not an approximation.
 * The handful of clay names that had no flat predecessor get the closest
 * Lucide equivalent. A call site whose old icon differed from the entry here
 * (the same clay art is reused in more than one place) passes its own `flat`
 * override rather than bending this map.
 *
 * `tone` is the *default* colour; every site can override it, and the sizes
 * stay at the call sites since flat line art reads at roughly 60-75% of the
 * clay size and the exact ratio differed per surface.
 */
export const FLAT_ICON_FOR_CLAY: Record<ClayIconName, FlatIconSpec> = {
  // entry/ — transaction-editor and quick-add affordances
  'entry/add-square': { icon: SquarePlus, tone: 'primary' },
  'entry/backspace': { icon: Delete, tone: 'muted' },
  'entry/calendar': { icon: Calendar, tone: 'primary' },
  'entry/camera': { icon: Camera, tone: 'primary' },
  'entry/check-mark': { icon: Check, tone: 'primary' },
  'entry/chevron-down': { icon: ChevronDown, tone: 'muted' },
  'entry/close-round': { icon: CircleX, tone: 'muted' },
  'entry/drag-handle': { icon: GripVertical, tone: 'muted' },
  'entry/expand': { icon: Maximize2, tone: 'muted' },
  'entry/history': { icon: History, tone: 'muted' },
  'entry/image-off': { icon: ImageOff, tone: 'muted' },
  'entry/image-plus': { icon: ImagePlus, tone: 'primary' },
  'entry/keypad': { icon: Zap, tone: 'primary' },
  'entry/mic': { icon: Mic, tone: 'primary' },
  'entry/paperclip': { icon: Paperclip, tone: 'muted' },
  'entry/pencil-edit': { icon: Pencil, tone: 'primary' },
  'entry/press-button': { icon: MousePointerClick, tone: 'primary' },
  'entry/qr-code': { icon: QrCode, tone: 'primary' },
  'entry/quick-timer': { icon: Timer, tone: 'primary' },
  'entry/scan-receipt': { icon: ScanLine, tone: 'primary' },
  'entry/send': { icon: Send, tone: 'primary' },
  'entry/settings-sliders': { icon: SlidersHorizontal, tone: 'primary' },
  'entry/split-notes': { icon: SplitSquareHorizontal, tone: 'primary' },
  'entry/square-pen': { icon: SquarePen, tone: 'primary' },
  'entry/trash': { icon: Trash2, tone: 'destructive' },

  // insights/ — the insight-type art. The selector itself keeps its clay
  // illustrations either way (it reads them through `constants/utilityIcons`),
  // so these only cover the few places a ClayIcon draws one directly.
  'insights/calendar-clock': { icon: CalendarClock, tone: 'primary' },
  'insights/growth-analysis': { icon: TrendingUp, tone: 'primary' },
  'insights/home-savings': { icon: PiggyBank, tone: 'primary' },
  'insights/market-analysis': { icon: LineChart, tone: 'primary' },
  'insights/money-bags': { icon: Wallet, tone: 'primary' },
  'insights/mood-faces': { icon: Smile, tone: 'primary' },
  'insights/pie-chart': { icon: PieChart, tone: 'primary' },
  'insights/piggy-bank-coins': { icon: PiggyBank, tone: 'primary' },
  'insights/profit-analysis': { icon: BarChart3, tone: 'primary' },
  'insights/property-listing': { icon: Home, tone: 'primary' },
  'insights/receipt-scan': { icon: Camera, tone: 'primary' },
  'insights/revenue-growth': { icon: TrendingUp, tone: 'primary' },
  'insights/split-bill': { icon: SplitSquareHorizontal, tone: 'primary' },
  'insights/time-money': { icon: Clock3, tone: 'primary' },
  'insights/wallet-cash-blue': { icon: Wallet, tone: 'primary' },
  'insights/wallet-cash': { icon: Wallet, tone: 'primary' },

  // money-time/
  'money-time/alarm-clock-coin': { icon: AlarmClock, tone: 'primary' },
  'money-time/balance-scale': { icon: Scale, tone: 'primary' },
  'money-time/bank': { icon: Landmark, tone: 'primary' },
  'money-time/banknote': { icon: Banknote, tone: 'primary' },
  'money-time/bar-chart': { icon: BarChart3, tone: 'primary' },
  'money-time/calendar-clock': { icon: CalendarClock, tone: 'primary' },
  'money-time/card': { icon: CreditCard, tone: 'primary' },
  'money-time/chart-down': { icon: TrendingDown, tone: 'destructive' },
  'money-time/chart-up': { icon: TrendingUp, tone: 'success' },
  'money-time/clock': { icon: Clock3, tone: 'primary' },
  'money-time/coin': { icon: Coins, tone: 'primary' },
  'money-time/coins-stack': { icon: Coins, tone: 'primary' },
  'money-time/donut-chart': { icon: PieChart, tone: 'primary' },
  'money-time/hourglass': { icon: Hourglass, tone: 'primary' },
  'money-time/invoice': { icon: FileText, tone: 'primary' },
  'money-time/piggy-bank': { icon: PiggyBank, tone: 'primary' },
  'money-time/price-tag': { icon: Tag, tone: 'primary' },
  'money-time/receipt': { icon: ReceiptText, tone: 'primary' },
  'money-time/split-bill': { icon: SplitSquareHorizontal, tone: 'primary' },
  'money-time/stopwatch': { icon: Timer, tone: 'primary' },
  'money-time/target': { icon: Target, tone: 'primary' },
  'money-time/transfer': { icon: ArrowLeftRight, tone: 'primary' },
  'money-time/wallet-in': { icon: ArrowDownLeft, tone: 'success' },
  'money-time/wallet-out': { icon: ArrowUpRight, tone: 'destructive' },
  'money-time/wallet': { icon: Wallet, tone: 'primary' },

  // nav/ — the bottom bar draws its own flat SVGs (components/icons/NavIcons)
  // so the tint-and-fill active state comes back with them; these entries
  // cover the other places nav art is reused.
  'nav/add-active': { icon: Plus, tone: 'white', strokeWidth: 2.8 },
  'nav/add': { icon: Plus, tone: 'white', strokeWidth: 2.8 },
  'nav/chevron-left-nav': { icon: ChevronLeft, tone: 'muted' },
  'nav/chevron-right-alt': { icon: ChevronRight, tone: 'muted' },
  'nav/chevron-right-nav': { icon: ChevronRight, tone: 'muted' },
  'nav/grid': { icon: LayoutGrid, tone: 'muted' },
  'nav/home-active': { icon: Home, tone: 'primary', filled: true },
  'nav/home': { icon: Home, tone: 'muted' },
  'nav/insights-active': { icon: PieChart, tone: 'primary', filled: true },
  'nav/insights': { icon: PieChart, tone: 'muted' },
  'nav/more': { icon: MoreHorizontal, tone: 'muted' },
  'nav/settings-active': { icon: Settings, tone: 'primary', filled: true },
  'nav/settings': { icon: Settings, tone: 'muted' },
  'nav/wallet-active': { icon: Wallet, tone: 'primary', filled: true },
  'nav/wallet': { icon: Wallet, tone: 'muted' },

  // sentiment/ — SentimentIcons redraws its own flat faces, so these are the
  // fallback for anywhere else a sentiment glyph is asked for by name.
  'sentiment/happy': { icon: Smile, tone: 'success' },
  'sentiment/neutral': { icon: Meh, tone: 'muted' },
  'sentiment/regret': { icon: Frown, tone: 'destructive' },

  // settings/ — one per SettingsGridTile, restoring the exact pre-clay icons
  'settings/account-settings': { icon: SlidersHorizontal, tone: 'primary' },
  'settings/accounts': { icon: Landmark, tone: 'primary' },
  'settings/albums': { icon: Images, tone: 'primary' },
  'settings/app-lock': { icon: Fingerprint, tone: 'primary' },
  'settings/auto-log': { icon: Nfc, tone: 'primary' },
  'settings/budget': { icon: PiggyBank, tone: 'primary' },
  'settings/categories': { icon: FolderTree, tone: 'primary' },
  'settings/contact': { icon: MessageCircle, tone: 'primary' },
  'settings/data-management': { icon: DatabaseBackup, tone: 'primary' },
  'settings/display': { icon: Palette, tone: 'primary' },
  'settings/exchange-rates': { icon: Coins, tone: 'primary' },
  'settings/hourly-value': { icon: Clock3, tone: 'primary' },
  'settings/items': { icon: Package, tone: 'primary' },
  'settings/news': { icon: Newspaper, tone: 'primary' },
  'settings/notifications': { icon: Bell, tone: 'primary' },
  'settings/pro': { icon: Crown, tone: 'primary' },
  'settings/profile': { icon: UserRound, tone: 'primary' },
  'settings/quick-entry': { icon: Zap, tone: 'primary' },
  'settings/rate': { icon: Heart, tone: 'primary' },
  'settings/receipts': { icon: ReceiptText, tone: 'primary' },
  'settings/recurring': { icon: Repeat2, tone: 'primary' },
  'settings/replay': { icon: RefreshCcw, tone: 'primary' },
  'settings/settle-up': { icon: HandCoins, tone: 'primary' },
  'settings/share-earn': { icon: Gift, tone: 'primary' },
  'settings/statement-import': { icon: FileText, tone: 'primary' },

  // status/ — empty-state and warning art
  'status/award': { icon: Award, tone: 'primary' },
  'status/calendar-check': { icon: CalendarCheck, tone: 'primary' },
  'status/celebrate': { icon: PartyPopper, tone: 'primary' },
  'status/chat': { icon: MessageCircle, tone: 'primary' },
  'status/cloud-off': { icon: CloudOff, tone: 'muted' },
  'status/cloud-upload': { icon: CloudUpload, tone: 'primary' },
  'status/download-tray': { icon: Download, tone: 'primary' },
  'status/empty-box': { icon: Package, tone: 'muted' },
  'status/external-link': { icon: ExternalLink, tone: 'muted' },
  'status/goal-target': { icon: Target, tone: 'primary' },
  'status/group': { icon: Users, tone: 'primary' },
  'status/growing-plant': { icon: Sprout, tone: 'success' },
  'status/handshake': { icon: Handshake, tone: 'primary' },
  'status/info': { icon: Info, tone: 'muted' },
  'status/lock-closed': { icon: Lock, tone: 'muted' },
  'status/no-results': { icon: SearchX, tone: 'muted' },
  'status/offline': { icon: WifiOff, tone: 'muted' },
  'status/people-two': { icon: Users, tone: 'primary' },
  'status/person-add': { icon: UserPlus, tone: 'primary' },
  'status/shield-check': { icon: ShieldCheck, tone: 'success' },
  'status/streak': { icon: Flame, tone: 'primary' },
  'status/success': { icon: CircleCheck, tone: 'success' },
  'status/trending-up': { icon: TrendingUp, tone: 'success' },
  'status/trophy': { icon: Trophy, tone: 'primary' },
  'status/warning': { icon: TriangleAlert, tone: 'destructive' },

  // ui/ — generic interface chrome
  'ui/arrow-down': { icon: ArrowDown, tone: 'muted' },
  'ui/arrow-up': { icon: ArrowUp, tone: 'muted' },
  'ui/bell-off': { icon: BellOff, tone: 'muted' },
  'ui/bell': { icon: Bell, tone: 'primary' },
  'ui/calendar': { icon: Calendar, tone: 'primary' },
  'ui/check': { icon: Check, tone: 'success' },
  'ui/checklist': { icon: ListChecks, tone: 'primary' },
  'ui/chevron-left': { icon: ChevronLeft, tone: 'muted' },
  'ui/chevron-right': { icon: ChevronRight, tone: 'muted' },
  'ui/clock': { icon: Clock3, tone: 'muted' },
  'ui/close': { icon: X, tone: 'muted' },
  'ui/download': { icon: Download, tone: 'primary' },
  'ui/eye-off': { icon: EyeOff, tone: 'muted' },
  'ui/eye': { icon: Eye, tone: 'muted' },
  'ui/filter-sliders': { icon: SlidersHorizontal, tone: 'primary' },
  'ui/lock': { icon: Lock, tone: 'muted' },
  'ui/minus': { icon: Minus, tone: 'muted' },
  'ui/pencil': { icon: Pencil, tone: 'primary' },
  'ui/plus': { icon: Plus, tone: 'primary' },
  'ui/refresh': { icon: RefreshCcw, tone: 'primary' },
  'ui/search': { icon: Search, tone: 'primary' },
  'ui/settings': { icon: Settings, tone: 'muted' },
  'ui/share': { icon: Share2, tone: 'primary' },
  'ui/trash': { icon: Trash2, tone: 'destructive' },
  'ui/undo': { icon: Undo2, tone: 'muted' },
  'ui/upload': { icon: Upload, tone: 'primary' },
};

/**
 * Flat line art reads noticeably smaller than the clay illustration it stands
 * in for, because clay art is padded inside its own square while a Lucide glyph
 * fills its box. Sites that had a documented pre-clay size pass `flatSize`;
 * everything else lands here.
 */
export const DEFAULT_FLAT_SIZE_RATIO = 0.72;
