import { LONG_RANGE_PAGER_CENTER_INDEX, LONG_RANGE_PAGER_TOTAL_SLOTS } from '~/constants/pager';

export const MONTH_PAGER_TOTAL_SLOTS = LONG_RANGE_PAGER_TOTAL_SLOTS;
export const MONTH_PAGER_CENTER_INDEX = LONG_RANGE_PAGER_CENTER_INDEX;
