import type { CategoryNames, PreviewProfile } from '../shared';

const AMERICAN_CATEGORIES: CategoryNames = {
  home: 'Home',
  rent: 'Rent',
  utilities: 'Utilities',
  internet: 'Internet',
  home_supplies: 'Home Supplies',
  food: 'Food',
  groceries: 'Groceries',
  dining: 'Dining Out',
  coffee: 'Coffee',
  transport: 'Transport',
  fuel: 'Fuel',
  rideshare: 'Ride Share',
  parking: 'Parking',
  lifestyle: 'Lifestyle',
  shopping: 'Shopping',
  entertainment: 'Entertainment',
  subscriptions: 'Subscriptions',
  health: 'Health',
  healthcare: 'Healthcare',
  fitness: 'Fitness',
  travel_root: 'Travel',
  flights: 'Flights',
  hotels: 'Hotels',
  local_travel: 'Local Transit',
  family: 'Family',
  gifts: 'Gifts',
  education: 'Learning',
  salary_root: 'Salary',
  salary: 'Paycheck',
  bonus: 'Bonus',
  side_root: 'Side Work',
  freelance: 'Freelance',
  consulting: 'Consulting',
  invest_root: 'Investments',
  dividends: 'Dividends',
  interest: 'Interest',
};

export const americanProfile: PreviewProfile = {
  seed: 20260308,
  locale: 'en',
  currencyCode: 'USD',
  currencySymbol: '$',
  profileName: 'Jordan Miller',
  accountGroups: {
    everyday: 'Everyday',
    goals: 'Goals',
    credit: 'Credit',
    investing: 'Investing',
  },
  accounts: {
    checking: { name: 'Daily Checking', startingBalance: 2650, logoId: 'united-states/chase' },
    savings: {
      name: 'High Yield Savings',
      startingBalance: 7400,
      logoId: 'united-states/marcus-by-goldman-sachs',
    },
    travel: { name: 'Travel Fund', startingBalance: 900, logoId: 'united-states/capital-one' },
    card: { name: 'Discover it', startingBalance: 185, logoId: 'united-states/discover' },
    cash: { name: 'Cash Wallet', startingBalance: 120, logoId: 'united-states/cash-app' },
    brokerage: { name: 'Brokerage', startingBalance: 5200, logoId: 'united-states/fidelity' },
  },
  extraAccounts: [
    {
      name: 'Venmo',
      type: 'debit',
      startingBalance: 240,
      logoId: 'united-states/venmo',
      groupKey: 'everyday',
    },
    {
      name: 'PayPal',
      type: 'debit',
      startingBalance: 310,
      logoId: 'global/paypal',
      groupKey: 'everyday',
    },
    {
      name: 'Wise',
      type: 'debit',
      startingBalance: 1450,
      logoId: 'global/wise',
      groupKey: 'everyday',
    },
    {
      name: 'Robinhood',
      type: 'debit',
      startingBalance: 3800,
      logoId: 'united-states/robinhood',
      groupKey: 'investing',
    },
    {
      name: 'Coinbase',
      type: 'debit',
      startingBalance: 2100,
      logoId: 'global/coinbase',
      groupKey: 'investing',
    },
    {
      name: 'Chase Sapphire Preferred',
      type: 'credit',
      startingBalance: 1240,
      logoId: 'united-states/chase',
      groupKey: 'credit',
    },
    {
      name: 'Amex Gold Card',
      type: 'credit',
      startingBalance: 860,
      logoId: 'global/american-express',
      groupKey: 'credit',
    },
    {
      name: 'Capital One Venture',
      type: 'credit',
      startingBalance: 540,
      logoId: 'united-states/capital-one',
      groupKey: 'credit',
    },
    {
      name: 'Apple Card',
      type: 'credit',
      startingBalance: 320,
      logoId: 'global/apple-pay',
      groupKey: 'credit',
    },
  ],
  categories: AMERICAN_CATEGORIES,
  career: [
    {
      durationMonths: 10,
      monthlySalary: 4485,
      hoursWorkedPerWeek: 40,
      commuteMinutesPerWorkday: 25,
    },
    {
      durationMonths: 16,
      monthlySalary: 4050,
      hoursWorkedPerWeek: 40,
      commuteMinutesPerWorkday: 40,
    },
    {
      durationMonths: 24,
      monthlySalary: 3600,
      hoursWorkedPerWeek: 42,
      commuteMinutesPerWorkday: 45,
    },
  ],
  budgets: {
    templateName: 'Monthly Budget',
    templateEmoji: '🎯',
    totalAmount: 3600,
    allocations: [
      { categoryKey: 'home', amount: 1750 },
      { categoryKey: 'food', amount: 720 },
      { categoryKey: 'transport', amount: 380 },
      { categoryKey: 'lifestyle', amount: 340 },
      { categoryKey: 'health', amount: 160 },
    ],
    monthsToSeed: 6,
  },
  secondBudget: {
    templateName: 'No-Spend Month',
    templateEmoji: '🌱',
    totalAmount: 2900,
    allocations: [
      { categoryKey: 'home', amount: 1750 },
      { categoryKey: 'food', amount: 560 },
      { categoryKey: 'transport', amount: 320 },
      { categoryKey: 'lifestyle', amount: 120 },
      { categoryKey: 'health', amount: 150 },
    ],
    monthsToSeed: 0,
  },
  splits: [
    {
      merchant: 'Shake Shack',
      note: 'Team lunch — I covered the tab',
      categoryKey: 'dining',
      monthsAgo: 0,
      day: 12,
      account: 'card',
      selfShare: 18,
      participants: [
        { name: 'Alex', share: 17, paid: true },
        { name: 'Sam', share: 16.5, paid: false },
        { name: 'Taylor', share: 18, paid: false },
      ],
    },
    {
      merchant: 'Airbnb — Lake Tahoe',
      note: 'Ski trip cabin, split 4 ways',
      categoryKey: 'travel_root',
      monthsAgo: 2,
      day: 8,
      account: 'card',
      selfShare: 240,
      participants: [
        { name: 'Chris', share: 240, paid: true },
        { name: 'Priya', share: 240, paid: true },
        { name: 'Marcus', share: 240, paid: true },
      ],
    },
  ],
  recurring: {
    salary: { name: 'Monthly Paycheck', amount: 4485, note: 'Payroll' },
    rent: { name: 'Apartment Rent', amount: 1495, note: 'Riverside Apartments' },
    fitness: { name: 'Gym Membership', amount: 42, note: 'Crunch Fitness' },
    subscriptions: [
      { name: 'Netflix', amount: 22.99, note: 'Netflix Premium' },
      { name: 'Spotify', amount: 11.99, note: 'Spotify Premium' },
      { name: 'Disney+', amount: 13.99, note: 'Disney+' },
      { name: 'Amazon Prime', amount: 14.99, note: 'Amazon Prime' },
      { name: 'ChatGPT Plus', amount: 20, note: 'ChatGPT Plus' },
    ],
    investment: { name: 'Brokerage Auto-Invest', amount: 225, note: 'Auto-invest' },
  },
  transactions: {
    merchants: {
      grocery: ["Trader Joe's", 'Whole Foods', 'Safeway', 'Costco', 'Kroger'],
      dining: ['Chipotle', 'Shake Shack', 'Olive Garden', 'Panera Bread', 'Chick-fil-A'],
      coffee: ['Starbucks', "Dunkin'", 'Blue Bottle', "Peet's Coffee"],
      fuel: ['Shell', 'Chevron', 'Costco Gas', 'ExxonMobil'],
      shopping: ['Target', 'Amazon', 'Best Buy', 'IKEA', 'Walmart'],
      entertainment: ['AMC Theatres', 'Regal Cinemas', "Dave & Buster's", 'Ticketmaster'],
      rideshare: ['Uber', 'Lyft'],
      healthcare: ['CVS Pharmacy', 'Walgreens', 'One Medical'],
      hotels: ['Marriott', 'Hilton', 'Airbnb'],
      flights: ['Delta', 'United Airlines', 'Southwest'],
    },
    notes: {
      salary: 'Payroll',
      bonus: 'Performance bonus',
      freelance: 'Client retainer',
      consulting: 'Advisory session',
      dividends: 'Quarterly dividends',
      interest: 'Savings interest',
      rent: 'Riverside Apartments',
      utilities: 'PG&E bill',
      internet: 'Xfinity',
      fitness: 'Crunch Fitness',
      homeSupplies: 'Target run',
      subscriptions: ['Netflix', 'Spotify', 'iCloud+'],
      education: 'Coursera',
      atmWithdrawal: 'ATM withdrawal',
      parkingPrimary: 'Downtown parking',
      parkingAlternate: 'Station parking',
      savingsTransfer: 'Savings transfer',
      investmentTransfer: 'Auto-invest',
      travelTopUp: 'Travel top-up',
      localTravel: 'Airport rail',
      tripDining: 'Trip dinner',
      holidayGifts: 'Holiday gifts',
      familyCelebration: 'Family celebration',
      cardPayment: 'Card payment',
    },
    subscriptions: [22.99, 11.99, 2.99],
    income: {
      bonusBase: 950,
      bonusGrowth: 18,
      bonusSpread: 140,
      freelanceBase: 320,
      freelanceGrowth: 8,
      freelanceSpread: 90,
      consultingBase: 210,
      consultingStep: 35,
      consultingSpread: 60,
      dividendsBase: 42,
      dividendsGrowth: 1.5,
      dividendsSpread: 12,
      interestBase: 12,
      interestGrowth: 0.4,
      interestSpread: 3.5,
    },
    housing: {
      rentBase: 1495,
      rentGrowth: 1.5,
      rentSpread: 15,
      utilitiesBase: 108,
      utilitiesSpread: 16,
      internetBase: 69,
      internetSpread: 5,
      fitnessBase: 42,
      fitnessSpread: 2,
      homeSuppliesBase: 34,
      homeSuppliesSpread: 14,
      healthcareBase: 82,
      healthcareSpread: 24,
      educationBase: 86,
      educationSpread: 20,
    },
    weekly: {
      cashTopUpFourWeek: 90,
      cashTopUpFiveWeek: 110,
      cashTopUpSpread: 10,
      groceryBase: 96,
      groceryWeekStep: 4,
      grocerySpread: 18,
      diningBase: 34,
      diningWeekStep: 2.5,
      diningSpread: 12,
      coffeeBase: 6.5,
      coffeeSpread: 1.8,
      fuelBase: 42,
      fuelSpread: 8,
      parkingPrimaryBase: 18,
      parkingPrimarySpread: 6,
      parkingAlternateBase: 8.5,
      parkingAlternateSpread: 3,
    },
    lifestyle: {
      shoppingBase: 56,
      shoppingTripStep: 22,
      shoppingSpread: 24,
      entertainmentBase: 32,
      entertainmentTripStep: 18,
      entertainmentSpread: 14,
      rideshareBase: 18,
      rideshareSpread: 6,
    },
    transfers: {
      savingsBase: 360,
      savingsGrowth: 10,
      savingsSpread: 30,
      investmentBase: 215,
      investmentGrowth: 6,
      investmentSpread: 22,
      travelBase: 110,
      travelPeak: 240,
      travelSpread: 30,
      cardPaymentRatio: 0.96,
    },
    travel: {
      months: [2, 8],
      giftMonth: 11,
      flightsBase: 315,
      flightsSpread: 65,
      hotelsBase: 465,
      hotelsSpread: 95,
      localTransitBase: 58,
      localTransitSpread: 16,
      diningBase: 74,
      diningSpread: 18,
      holidayGiftsBase: 240,
      holidayGiftsSpread: 70,
      familyCelebrationBase: 165,
      familyCelebrationSpread: 45,
    },
  },
  albums: [
    {
      name: 'Tokyo Getaway',
      placeName: 'Tokyo',
      placeAdmin: 'Japan',
      countryCode: 'JP',
      latitude: 35.6762,
      longitude: 139.6503,
      currencyCode: 'JPY',
      fxRate: 150,
    },
    {
      name: 'Iceland Road Trip',
      placeName: 'Reykjavík',
      placeAdmin: 'Iceland',
      countryCode: 'IS',
      latitude: 64.1466,
      longitude: -21.9426,
      currencyCode: 'ISK',
      fxRate: 138,
    },
    {
      name: 'NYC Long Weekend',
      placeName: 'New York City',
      placeAdmin: 'New York',
      countryCode: 'US',
      latitude: 40.7128,
      longitude: -74.006,
      currencyCode: 'USD',
      fxRate: 1,
    },
    {
      name: 'Cancún Escape',
      placeName: 'Cancún',
      placeAdmin: 'Mexico',
      countryCode: 'MX',
      latitude: 21.1619,
      longitude: -86.8515,
      currencyCode: 'MXN',
      fxRate: 18,
    },
  ],
  items: [
    {
      name: 'iPhone 15 Pro',
      iconId: 'smartphone',
      purchaseMonthsAgo: 13,
      purchaseDay: 22,
      purchasePrice: 999,
      note: 'Natural Titanium, 256GB',
    },
    {
      name: 'MacBook Air M3',
      iconId: 'laptop',
      purchaseMonthsAgo: 20,
      purchaseDay: 9,
      purchasePrice: 1299,
      note: 'Daily driver for side projects',
    },
    {
      name: 'Sony WH-1000XM5',
      iconId: 'headphones',
      purchaseMonthsAgo: 8,
      purchaseDay: 4,
      purchasePrice: 399,
    },
    {
      name: 'Apple Watch Series 9',
      iconId: 'smartwatch',
      purchaseMonthsAgo: 11,
      purchaseDay: 17,
      purchasePrice: 429,
    },
    {
      name: 'Sony A7 IV',
      iconId: 'dslr-camera',
      purchaseMonthsAgo: 26,
      purchaseDay: 12,
      purchasePrice: 2498,
      note: 'Travel + vlog camera',
    },
    {
      name: 'Specialized Turbo Vado',
      iconId: 'e-bike',
      purchaseMonthsAgo: 18,
      purchaseDay: 28,
      purchasePrice: 2800,
      note: 'Bike-to-work commuter',
    },
    {
      name: 'PlayStation 5',
      iconId: 'playstation',
      purchaseMonthsAgo: 30,
      purchaseDay: 6,
      purchasePrice: 499,
    },
    {
      name: 'iPhone 13 (sold)',
      iconId: 'smartphone',
      purchaseMonthsAgo: 38,
      purchaseDay: 15,
      purchasePrice: 799,
      retiredMonthsAgo: 13,
      salePrice: 360,
      note: 'Traded in for the 15 Pro',
    },
  ],
};
