import { buildLocalizedProfile } from './localized';

export const brazilianProfile = buildLocalizedProfile({
  seed: 20260510,
  locale: 'pt',
  currencyCode: 'BRL',
  currencySymbol: 'R$',
  priceScale: 0.9,
  decimals: 2,
  monthlySalary: 9000,
  monthlyRent: 2800,
  profileName: 'Ana Souza',
  accountGroups: {
    everyday: 'Dia a dia',
    goals: 'Metas',
    credit: 'Crédito',
    investing: 'Investimentos',
  },
  accounts: {
    checking: { name: 'Conta Nubank', logoId: 'brazil/nubank' },
    savings: { name: 'Poupança Bradesco', logoId: 'brazil/bradesco' },
    travel: { name: 'Caixinha viagem', logoId: 'brazil/c6-bank' },
    card: { name: 'Cartão Santander', logoId: 'brazil/santander-brasil' },
    cash: { name: 'Dinheiro', logoId: 'global/visa' },
    brokerage: { name: 'XP Investimentos', logoId: 'brazil/xp-investimentos' },
  },
  extraAccounts: [
    { name: 'Mercado Pago', type: 'debit', logoId: 'brazil/mercado-pago', groupKey: 'everyday' },
    { name: 'PicPay', type: 'debit', logoId: 'brazil/picpay', groupKey: 'everyday' },
    {
      name: 'Banco do Brasil',
      type: 'debit',
      logoId: 'brazil/banco-do-brasil',
      groupKey: 'everyday',
    },
    { name: 'Cartão Neon', type: 'credit', logoId: 'brazil/neon', groupKey: 'credit' },
  ],
  categories: {
    home: 'Casa',
    rent: 'Aluguel',
    utilities: 'Luz e água',
    internet: 'Internet',
    home_supplies: 'Utilidades',
    food: 'Alimentação',
    groceries: 'Mercado',
    dining: 'Restaurantes',
    coffee: 'Café',
    transport: 'Transporte',
    fuel: 'Combustível',
    rideshare: 'Uber e 99',
    parking: 'Estacionamento',
    lifestyle: 'Lazer',
    shopping: 'Compras',
    entertainment: 'Diversão',
    subscriptions: 'Assinaturas',
    health: 'Saúde',
    healthcare: 'Farmácia e médico',
    fitness: 'Academia',
    travel_root: 'Viagens',
    flights: 'Passagens',
    hotels: 'Hotéis',
    local_travel: 'Transporte local',
    family: 'Família',
    gifts: 'Presentes',
    education: 'Cursos',
    salary_root: 'Salário',
    salary: 'Salário',
    bonus: '13º e bônus',
    side_root: 'Renda extra',
    freelance: 'Freelas',
    consulting: 'Consultoria',
    invest_root: 'Investimentos',
    dividends: 'Dividendos',
    interest: 'Rendimentos',
  },
  budgetName: 'Orçamento mensal',
  split: {
    merchant: 'Churrascaria Fogo de Chão',
    note: 'Jantar com amigos, eu paguei',
    people: ['Pedro', 'Juliana', 'Rafael'],
  },
  recurring: {
    salary: { name: 'Salário', note: 'Salário do mês' },
    rent: { name: 'Aluguel', note: 'Aluguel do apê' },
    fitness: { name: 'Academia', amount: 119.9, note: 'Smart Fit', logoId: 'brazil/smart-fit' },
    subscriptions: [
      { name: 'Netflix', amount: 44.9, note: 'Netflix Padrão' },
      { name: 'Spotify', amount: 21.9, note: 'Spotify Premium' },
      { name: 'Globoplay', amount: 24.9, note: 'Globoplay', logoId: 'brazil/globoplay' },
      { name: 'iFood Clube', amount: 12.9, note: 'iFood Clube', logoId: 'brazil/ifood' },
      { name: 'iCloud+', amount: 14.9, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Aporte mensal', note: 'Tesouro Direto' },
  },
  merchants: {
    grocery: ['Pão de Açúcar', 'Carrefour', 'Assaí', 'Hortifruti', 'Extra'],
    dining: [
      'Churrascaria Fogo de Chão',
      'Outback',
      'Coco Bambu',
      'Padaria Bella Paulista',
      'Madero',
    ],
    coffee: ['Starbucks', 'Café Cultura', 'Octavio Café', 'Fran’s Café'],
    fuel: ['Posto Ipiranga', 'Shell', 'Petrobras'],
    shopping: ['Mercado Livre', 'Magazine Luiza', 'Renner', 'Amazon.com.br'],
    entertainment: ['Cinemark', 'Ingresso.com', 'Teatro Renault'],
    rideshare: ['Uber', '99'],
    healthcare: ['Drogasil', 'Droga Raia', 'Consulta médica'],
    hotels: ['Ibis', 'Pousada Paraty'],
    flights: ['LATAM', 'GOL'],
    delivery: ['iFood', 'Rappi', 'Zé Delivery'],
    convenience: ['Oxxo', 'BR Mania', 'Am Pm'],
  },
  notes: {
    salary: 'Salário',
    bonus: '13º salário',
    freelance: 'Freela',
    consulting: 'Consultoria',
    dividends: 'Dividendos FII',
    interest: 'Rendimento CDB',
    rent: 'Aluguel do mês',
    utilities: 'Luz e água',
    internet: 'Internet Vivo',
    fitness: 'Smart Fit',
    homeSupplies: 'Coisas de casa',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Curso online',
    atmWithdrawal: 'Saque no caixa',
    parkingPrimary: 'Estacionamento',
    parkingAlternate: 'Zona Azul',
    savingsTransfer: 'Para a poupança',
    investmentTransfer: 'Aporte Tesouro',
    travelTopUp: 'Caixinha viagem',
    localTravel: 'Ônibus pro aeroporto',
    tripDining: 'Comida na viagem',
    holidayGifts: 'Presentes de Natal',
    familyCelebration: 'Almoço de família',
    cardPayment: 'Fatura do cartão',
  },
});
