import type { CategoryNames, PreviewProfile } from '../shared';

const CHINESE_CATEGORIES: CategoryNames = {
  home: '居住',
  rent: '房租',
  utilities: '水电燃气',
  internet: '网络通信',
  home_supplies: '日用品',
  food: '饮食',
  groceries: '买菜',
  dining: '外食',
  coffee: '咖啡奶茶',
  transport: '交通',
  fuel: '加油',
  rideshare: '打车',
  parking: '停车',
  lifestyle: '生活',
  shopping: '购物',
  entertainment: '娱乐',
  subscriptions: '订阅',
  health: '健康',
  healthcare: '医疗',
  fitness: '健身',
  travel_root: '旅行',
  flights: '机票',
  hotels: '酒店',
  local_travel: '本地交通',
  family: '家庭',
  gifts: '礼物',
  education: '学习',
  salary_root: '工资',
  salary: '工资到账',
  bonus: '奖金',
  side_root: '副业',
  freelance: '自由职业',
  consulting: '咨询',
  invest_root: '投资',
  dividends: '分红',
  interest: '利息',
};

export const chineseProfile: PreviewProfile = {
  seed: 20260318,
  locale: 'zh',
  currencyCode: 'CNY',
  currencySymbol: '¥',
  profileName: '林思远',
  accountGroups: {
    everyday: '日常',
    goals: '目标',
    credit: '信用',
    investing: '投资',
  },
  accounts: {
    checking: { name: '工资卡', startingBalance: 18600, logoId: 'china/china-merchants-bank' },
    savings: { name: '活期储蓄', startingBalance: 64800, logoId: 'china/icbc' },
    travel: { name: '旅行基金', startingBalance: 5200, logoId: 'china/bank-of-china' },
    card: { name: '建行信用卡', startingBalance: 680, logoId: 'china/china-construction-bank' },
    cash: { name: '现金', startingBalance: 280, logoId: 'china/unionpay' },
    brokerage: { name: '基金账户', startingBalance: 22800, logoId: 'china/ping-an-bank' },
  },
  extraAccounts: [
    {
      name: '支付宝',
      type: 'debit',
      startingBalance: 1860,
      logoId: 'china/alipay',
      groupKey: 'everyday',
    },
    {
      name: '微信钱包',
      type: 'debit',
      startingBalance: 1240,
      logoId: 'china/wechat-pay',
      groupKey: 'everyday',
    },
    {
      name: 'Wise',
      type: 'debit',
      startingBalance: 5200,
      logoId: 'global/wise',
      groupKey: 'everyday',
    },
    {
      name: '币安',
      type: 'debit',
      startingBalance: 9800,
      logoId: 'global/binance',
      groupKey: 'investing',
    },
    {
      name: '招商银行信用卡',
      type: 'credit',
      startingBalance: 2400,
      logoId: 'china/china-merchants-bank',
      groupKey: 'credit',
    },
    {
      name: '蚂蚁花呗',
      type: 'credit',
      startingBalance: 860,
      logoId: 'china/alipay',
      groupKey: 'credit',
    },
    {
      name: '京东白条',
      type: 'credit',
      startingBalance: 430,
      logoId: 'china/jdcom',
      groupKey: 'credit',
    },
    {
      name: '交通银行信用卡',
      type: 'credit',
      startingBalance: 1500,
      logoId: 'china/bank-of-communications',
      groupKey: 'credit',
    },
  ],
  categories: CHINESE_CATEGORIES,
  career: [
    {
      durationMonths: 10,
      monthlySalary: 16800,
      hoursWorkedPerWeek: 44,
      commuteMinutesPerWorkday: 38,
    },
    {
      durationMonths: 16,
      monthlySalary: 15200,
      hoursWorkedPerWeek: 44,
      commuteMinutesPerWorkday: 43,
    },
    {
      durationMonths: 24,
      monthlySalary: 13500,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 48,
    },
  ],
  budgets: {
    templateName: '每月预算',
    templateEmoji: '🎯',
    totalAmount: 12000,
    allocations: [
      { categoryKey: 'home', amount: 5400 },
      { categoryKey: 'food', amount: 2600 },
      { categoryKey: 'transport', amount: 1200 },
      { categoryKey: 'lifestyle', amount: 1500 },
      { categoryKey: 'health', amount: 700 },
    ],
    monthsToSeed: 6,
  },
  secondBudget: {
    templateName: '省钱月',
    templateEmoji: '🌱',
    totalAmount: 9800,
    allocations: [
      { categoryKey: 'home', amount: 5400 },
      { categoryKey: 'food', amount: 2000 },
      { categoryKey: 'transport', amount: 900 },
      { categoryKey: 'lifestyle', amount: 700 },
      { categoryKey: 'health', amount: 600 },
    ],
    monthsToSeed: 0,
  },
  splits: [
    {
      merchant: '海底捞',
      note: '同事聚餐，我先垫付',
      categoryKey: 'dining',
      monthsAgo: 0,
      day: 14,
      account: 'card',
      selfShare: 120,
      participants: [
        { name: '小美', share: 118, paid: true },
        { name: '阿强', share: 120, paid: false },
        { name: '婷婷', share: 115, paid: false },
      ],
    },
    {
      merchant: '大理民宿',
      note: '大理旅行住宿，四人平摊',
      categoryKey: 'travel_root',
      monthsAgo: 3,
      day: 9,
      account: 'card',
      selfShare: 460,
      participants: [
        { name: '小美', share: 460, paid: true },
        { name: '大伟', share: 460, paid: true },
        { name: '子涵', share: 460, paid: true },
      ],
    },
  ],
  recurring: {
    salary: { name: '每月工资', amount: 16800, note: '工资入账' },
    rent: { name: '房租', amount: 4900, note: '青年公寓' },
    fitness: { name: '健身月卡', amount: 199, note: '乐刻运动' },
    subscriptions: [
      { name: '腾讯视频VIP', amount: 30, note: '腾讯视频会员' },
      { name: '爱奇艺黄金会员', amount: 25, note: '爱奇艺会员' },
      { name: '网易云音乐黑胶VIP', amount: 18, note: '网易云音乐' },
      { name: '哔哩哔哩大会员', amount: 25, note: 'B站大会员' },
      { name: '百度网盘超级会员', amount: 30, note: '百度网盘' },
    ],
    investment: { name: '基金定投', amount: 1200, note: '自动定投' },
  },
  transactions: {
    merchants: {
      grocery: ['盒马鲜生', '永辉超市', '叮咚买菜', '社区生鲜'],
      dining: ['兰州拉面', '小馆子', '粤式茶餐厅', '川味小馆'],
      coffee: ['瑞幸咖啡', 'Manner Coffee', '幸运咖', '库迪咖啡'],
      fuel: ['中石化', '中石油', '壳牌'],
      shopping: ['万象城', '宜家', '数码城', '生活广场'],
      entertainment: ['万达影城', 'Livehouse', 'KTV', '周末演出'],
      rideshare: ['滴滴出行', '高德打车', '曹操出行'],
      healthcare: ['社区医院', '口腔诊所', '连锁药房'],
      hotels: ['亚朵酒店', '全季酒店', '桔子酒店'],
      flights: ['南方航空', '中国国航', '东方航空'],
    },
    notes: {
      salary: '工资入账',
      bonus: '季度奖金',
      freelance: '副业项目',
      consulting: '顾问项目',
      dividends: '基金分红',
      interest: '活期利息',
      rent: '青年公寓',
      utilities: '水电燃气',
      internet: '家庭宽带',
      fitness: '乐刻运动',
      homeSupplies: '日用品补货',
      subscriptions: ['腾讯视频VIP', '网易云音乐', '百度网盘会员'],
      education: '线上课程',
      atmWithdrawal: '取现',
      parkingPrimary: '商场停车',
      parkingAlternate: '路边停车',
      savingsTransfer: '转入储蓄',
      investmentTransfer: '自动定投',
      travelTopUp: '旅行备用金',
      localTravel: '机场快线',
      tripDining: '旅行聚餐',
      holidayGifts: '节日礼物',
      familyCelebration: '家庭聚餐',
      cardPayment: '信用卡还款',
    },
    subscriptions: [25, 15, 12],
    income: {
      bonusBase: 3600,
      bonusGrowth: 80,
      bonusSpread: 500,
      freelanceBase: 1350,
      freelanceGrowth: 35,
      freelanceSpread: 260,
      consultingBase: 820,
      consultingStep: 120,
      consultingSpread: 180,
      dividendsBase: 110,
      dividendsGrowth: 6,
      dividendsSpread: 35,
      interestBase: 38,
      interestGrowth: 1,
      interestSpread: 10,
    },
    housing: {
      rentBase: 4900,
      rentGrowth: 12,
      rentSpread: 80,
      utilitiesBase: 230,
      utilitiesSpread: 45,
      internetBase: 89,
      internetSpread: 8,
      fitnessBase: 199,
      fitnessSpread: 10,
      homeSuppliesBase: 110,
      homeSuppliesSpread: 40,
      healthcareBase: 160,
      healthcareSpread: 55,
      educationBase: 220,
      educationSpread: 60,
    },
    weekly: {
      cashTopUpFourWeek: 220,
      cashTopUpFiveWeek: 280,
      cashTopUpSpread: 30,
      groceryBase: 175,
      groceryWeekStep: 8,
      grocerySpread: 40,
      diningBase: 72,
      diningWeekStep: 5,
      diningSpread: 25,
      coffeeBase: 16,
      coffeeSpread: 5,
      fuelBase: 180,
      fuelSpread: 35,
      parkingPrimaryBase: 24,
      parkingPrimarySpread: 8,
      parkingAlternateBase: 15,
      parkingAlternateSpread: 5,
    },
    lifestyle: {
      shoppingBase: 190,
      shoppingTripStep: 70,
      shoppingSpread: 80,
      entertainmentBase: 88,
      entertainmentTripStep: 42,
      entertainmentSpread: 30,
      rideshareBase: 32,
      rideshareSpread: 10,
    },
    transfers: {
      savingsBase: 3200,
      savingsGrowth: 65,
      savingsSpread: 180,
      investmentBase: 1450,
      investmentGrowth: 40,
      investmentSpread: 120,
      travelBase: 260,
      travelPeak: 880,
      travelSpread: 100,
      cardPaymentRatio: 0.97,
    },
    travel: {
      months: [0, 9],
      giftMonth: 0,
      flightsBase: 980,
      flightsSpread: 220,
      hotelsBase: 880,
      hotelsSpread: 160,
      localTransitBase: 42,
      localTransitSpread: 12,
      diningBase: 148,
      diningSpread: 35,
      holidayGiftsBase: 860,
      holidayGiftsSpread: 200,
      familyCelebrationBase: 520,
      familyCelebrationSpread: 120,
    },
  },
  albums: [
    {
      name: '东京之旅',
      placeName: '东京',
      placeAdmin: '日本',
      countryCode: 'JP',
      latitude: 35.6762,
      longitude: 139.6503,
      currencyCode: 'JPY',
      fxRate: 21,
    },
    {
      name: '普吉岛度假',
      placeName: '普吉岛',
      placeAdmin: '泰国',
      countryCode: 'TH',
      latitude: 7.8804,
      longitude: 98.3923,
      currencyCode: 'THB',
      fxRate: 5,
    },
    {
      name: '云南大理',
      placeName: '大理',
      placeAdmin: '云南',
      countryCode: 'CN',
      latitude: 25.6065,
      longitude: 100.2676,
      currencyCode: 'CNY',
      fxRate: 1,
    },
    {
      name: '香港购物游',
      placeName: '香港',
      placeAdmin: '香港特别行政区',
      countryCode: 'HK',
      latitude: 22.3193,
      longitude: 114.1694,
      currencyCode: 'HKD',
      fxRate: 1.09,
    },
  ],
  items: [
    {
      name: 'iPhone 15 Pro',
      iconId: 'smartphone',
      purchaseMonthsAgo: 12,
      purchaseDay: 20,
      purchasePrice: 8999,
      note: '原色钛金属 256G',
    },
    {
      name: '华为 MateBook X Pro',
      iconId: 'laptop',
      purchaseMonthsAgo: 19,
      purchaseDay: 8,
      purchasePrice: 9999,
    },
    {
      name: '索尼 WH-1000XM5',
      iconId: 'headphones',
      purchaseMonthsAgo: 7,
      purchaseDay: 14,
      purchasePrice: 2899,
    },
    {
      name: 'Apple Watch S9',
      iconId: 'smartwatch',
      purchaseMonthsAgo: 10,
      purchaseDay: 3,
      purchasePrice: 3199,
    },
    {
      name: '大疆 Pocket 3',
      iconId: 'action-camera',
      purchaseMonthsAgo: 9,
      purchaseDay: 26,
      purchasePrice: 3499,
      note: '旅行 vlog 神器',
    },
    {
      name: '石头扫地机器人',
      iconId: 'robot-vacuum',
      purchaseMonthsAgo: 22,
      purchaseDay: 11,
      purchasePrice: 3299,
    },
    {
      name: '任天堂 Switch OLED',
      iconId: 'handheld-game-console',
      purchaseMonthsAgo: 28,
      purchaseDay: 5,
      purchasePrice: 2099,
    },
    {
      name: '大疆 Mini 3（已出）',
      iconId: 'drone',
      purchaseMonthsAgo: 34,
      purchaseDay: 18,
      purchasePrice: 4788,
      retiredMonthsAgo: 11,
      salePrice: 2600,
      note: '升级 Mini 4 后转卖',
    },
  ],
};
