import { buildLocalizedProfile } from './localized';

export const danishProfile = buildLocalizedProfile({
  seed: 20260506,
  locale: 'da',
  currencyCode: 'DKK',
  currencySymbol: 'kr.',
  priceScale: 3.5,
  decimals: 2,
  monthlySalary: 42000,
  monthlyRent: 9500,
  profileName: 'Freja Nielsen',
  accountGroups: { everyday: 'Hverdag', goals: 'Mål', credit: 'Kredit', investing: 'Investering' },
  accounts: {
    checking: { name: 'Danske Bank Budget', logoId: 'denmark/danske-bank' },
    savings: { name: 'Nordea Opsparing', logoId: 'denmark/nordea' },
    travel: { name: 'Ferieopsparing', logoId: 'denmark/lunar' },
    card: { name: 'Jyske Mastercard', logoId: 'denmark/jyske-bank' },
    cash: { name: 'Kontanter', logoId: 'global/visa' },
    brokerage: { name: 'Nordnet', logoId: 'global/saxo' },
  },
  extraAccounts: [
    { name: 'MobilePay', type: 'debit', logoId: 'denmark/mobilepay', groupKey: 'everyday' },
    {
      name: 'Arbejdernes Landsbank',
      type: 'debit',
      logoId: 'denmark/arbejdernes-landsbank',
      groupKey: 'everyday',
    },
    { name: 'Nykredit', type: 'debit', logoId: 'denmark/nykredit', groupKey: 'goals' },
    { name: 'Spar Nord Kort', type: 'credit', logoId: 'denmark/spar-nord', groupKey: 'credit' },
  ],
  categories: {
    home: 'Bolig',
    rent: 'Husleje',
    utilities: 'El & vand',
    internet: 'Internet',
    home_supplies: 'Husholdning',
    food: 'Mad',
    groceries: 'Dagligvarer',
    dining: 'Restaurant',
    coffee: 'Kaffe',
    transport: 'Transport',
    fuel: 'Benzin',
    rideshare: 'Taxa',
    parking: 'Parkering',
    lifestyle: 'Fritid',
    shopping: 'Shopping',
    entertainment: 'Underholdning',
    subscriptions: 'Abonnementer',
    health: 'Sundhed',
    healthcare: 'Apotek & læge',
    fitness: 'Fitness',
    travel_root: 'Rejser',
    flights: 'Fly',
    hotels: 'Hotel',
    local_travel: 'Lokal transport',
    family: 'Familie',
    gifts: 'Gaver',
    education: 'Kurser',
    salary_root: 'Løn',
    salary: 'Løn',
    bonus: 'Bonus',
    side_root: 'Bijob',
    freelance: 'Freelance',
    consulting: 'Rådgivning',
    invest_root: 'Investeringer',
    dividends: 'Udbytte',
    interest: 'Renter',
  },
  budgetName: 'Månedsbudget',
  split: {
    merchant: 'Madklubben',
    note: 'Middag med vennerne, jeg lagde ud',
    people: ['Mads', 'Ida', 'Oliver'],
  },
  recurring: {
    salary: { name: 'Løn', note: 'Månedsløn' },
    rent: { name: 'Husleje', note: 'Husleje lejlighed' },
    fitness: { name: 'Fitness', amount: 299, note: 'PureGym', logoId: 'denmark/puregym' },
    subscriptions: [
      { name: 'Netflix', amount: 129, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 119, note: 'Spotify Premium' },
      { name: 'TV 2 Play', amount: 109, note: 'TV 2 Play', logoId: 'denmark/tv2-play' },
      { name: 'Viaplay', amount: 149, note: 'Viaplay', logoId: 'denmark/viaplay' },
      { name: 'iCloud+', amount: 29, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Månedsopsparing', note: 'Indeksfond' },
  },
  merchants: {
    grocery: ['Netto', 'Føtex', 'Rema 1000', 'Irma', 'Lidl'],
    dining: ['Madklubben', 'Sticks’n’Sushi', 'Joe & The Juice', 'Tivoli Food Hall', 'Mother'],
    coffee: ['Espresso House', 'Lagkagehuset', 'Original Coffee', 'Coffee Collective'],
    fuel: ['Circle K', 'Q8', 'OK Benzin'],
    shopping: ['Magasin', 'Matas', 'Elgiganten', 'IKEA'],
    entertainment: ['Nordisk Film Biografer', 'Tivoli', 'Royal Arena'],
    rideshare: ['Dantaxi', 'Uber'],
    healthcare: ['Apoteket', 'Lægen', 'Matas'],
    hotels: ['Hotel Skt. Petri', 'Comwell'],
    flights: ['SAS', 'Norwegian'],
    delivery: ['Wolt', 'Just Eat', 'Too Good To Go'],
    convenience: ['7-Eleven', 'Kiosk', 'Coop 365'],
  },
  notes: {
    salary: 'Løn',
    bonus: 'Årsbonus',
    freelance: 'Freelanceopgave',
    consulting: 'Rådgivning',
    dividends: 'Udbytte',
    interest: 'Renter opsparing',
    rent: 'Husleje',
    utilities: 'El & vand',
    internet: 'YouSee internet',
    fitness: 'PureGym',
    homeSupplies: 'Husholdningsting',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Onlinekursus',
    atmWithdrawal: 'Hævet kontanter',
    parkingPrimary: 'P-hus',
    parkingAlternate: 'Parkering',
    savingsTransfer: 'Til opsparing',
    investmentTransfer: 'Månedsopsparing',
    travelTopUp: 'Ferieopsparing',
    localTravel: 'Metro til lufthavnen',
    tripDining: 'Mad på ferien',
    holidayGifts: 'Julegaver',
    familyCelebration: 'Familiefest',
    cardPayment: 'Kreditkort betalt',
  },
});
