import { buildLocalizedProfile } from './localized';

export const dutchProfile = buildLocalizedProfile({
  seed: 20260505,
  locale: 'nl',
  currencyCode: 'EUR',
  currencySymbol: '€',
  priceScale: 0.35,
  decimals: 2,
  monthlySalary: 4000,
  monthlyRent: 1450,
  profileName: 'Sanne de Vries',
  accountGroups: {
    everyday: 'Dagelijks',
    goals: 'Doelen',
    credit: 'Krediet',
    investing: 'Beleggen',
  },
  accounts: {
    checking: { name: 'ING Betaalrekening', logoId: 'netherlands/ing' },
    savings: { name: 'Rabo Spaarrekening', logoId: 'netherlands/rabobank' },
    travel: { name: 'Vakantiepot', logoId: 'netherlands/bunq' },
    card: { name: 'ABN AMRO Creditcard', logoId: 'netherlands/abn-amro' },
    cash: { name: 'Contant', logoId: 'global/visa' },
    brokerage: { name: 'DEGIRO', logoId: 'global/interactive-brokers' },
  },
  extraAccounts: [
    { name: 'Tikkie', type: 'debit', logoId: 'netherlands/tikkie', groupKey: 'everyday' },
    { name: 'Knab', type: 'debit', logoId: 'netherlands/knab', groupKey: 'everyday' },
    { name: 'ASN Bank', type: 'debit', logoId: 'netherlands/asn-bank', groupKey: 'goals' },
    { name: 'Amex Green', type: 'credit', logoId: 'global/american-express', groupKey: 'credit' },
  ],
  categories: {
    home: 'Wonen',
    rent: 'Huur',
    utilities: 'Energie & water',
    internet: 'Internet',
    home_supplies: 'Huishouden',
    food: 'Eten',
    groceries: 'Boodschappen',
    dining: 'Uit eten',
    coffee: 'Koffie',
    transport: 'Vervoer',
    fuel: 'Brandstof',
    rideshare: 'Taxi',
    parking: 'Parkeren',
    lifestyle: 'Vrije tijd',
    shopping: 'Winkelen',
    entertainment: 'Uitgaan',
    subscriptions: 'Abonnementen',
    health: 'Gezondheid',
    healthcare: 'Apotheek & huisarts',
    fitness: 'Sportschool',
    travel_root: 'Reizen',
    flights: 'Vluchten',
    hotels: 'Hotels',
    local_travel: 'OV',
    family: 'Familie',
    gifts: 'Cadeaus',
    education: 'Cursussen',
    salary_root: 'Salaris',
    salary: 'Salaris',
    bonus: 'Bonus',
    side_root: 'Bijverdiensten',
    freelance: 'Freelance',
    consulting: 'Advies',
    invest_root: 'Beleggingen',
    dividends: 'Dividend',
    interest: 'Rente',
  },
  budgetName: 'Maandbudget',
  split: {
    merchant: 'Café de Jaren',
    note: 'Etentje met vrienden, ik heb voorgeschoten',
    people: ['Daan', 'Emma', 'Bram'],
  },
  recurring: {
    salary: { name: 'Salaris', note: 'Maandsalaris' },
    rent: { name: 'Huur', note: 'Huur appartement' },
    fitness: {
      name: 'Sportschool',
      amount: 29.99,
      note: 'Basic-Fit',
      logoId: 'netherlands/basic-fit',
    },
    subscriptions: [
      { name: 'Netflix', amount: 13.99, note: 'Netflix Standaard' },
      { name: 'Spotify', amount: 11.99, note: 'Spotify Premium' },
      { name: 'Videoland', amount: 9.99, note: 'Videoland', logoId: 'netherlands/videoland' },
      { name: 'NS Flex', amount: 32.4, note: 'NS Dal Voordeel', logoId: 'netherlands/ns' },
      { name: 'iCloud+', amount: 2.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Beleggen ETF', note: 'Maandelijkse inleg' },
  },
  merchants: {
    grocery: ['Albert Heijn', 'Jumbo', 'Lidl', 'Picnic', 'Dirk'],
    dining: ['Café de Jaren', 'Wagamama', 'FEBO', 'De Kas', 'Vapiano'],
    coffee: ['Coffee Company', 'Starbucks', 'Bagels & Beans', 'Anne&Max'],
    fuel: ['Shell', 'Tango', 'TinQ'],
    shopping: ['Bol.com', 'HEMA', 'Coolblue', 'IKEA'],
    entertainment: ['Pathé', 'Concertgebouw', 'Efteling'],
    rideshare: ['Uber', 'TCA Taxi'],
    healthcare: ['Apotheek', 'Huisarts', 'Etos'],
    hotels: ['citizenM', 'Van der Valk'],
    flights: ['KLM', 'Transavia'],
    delivery: ['Thuisbezorgd', 'Uber Eats', 'Flink'],
    convenience: ['AH to go', 'Spar', 'Kruidvat'],
  },
  notes: {
    salary: 'Salaris',
    bonus: 'Eindejaarsbonus',
    freelance: 'Freelance klus',
    consulting: 'Adviesuren',
    dividends: 'Dividend ETF',
    interest: 'Spaarrente',
    rent: 'Huur deze maand',
    utilities: 'Energie & water',
    internet: 'Ziggo internet',
    fitness: 'Basic-Fit',
    homeSupplies: 'Huishoudspullen',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Online cursus',
    atmWithdrawal: 'Geld gepind',
    parkingPrimary: 'Parkeergarage',
    parkingAlternate: 'Parkeermeter',
    savingsTransfer: 'Naar spaarrekening',
    investmentTransfer: 'Inleg beleggen',
    travelTopUp: 'Vakantiepot',
    localTravel: 'Trein naar Schiphol',
    tripDining: 'Eten op vakantie',
    holidayGifts: 'Sinterklaascadeaus',
    familyCelebration: 'Verjaardag familie',
    cardPayment: 'Creditcard afgelost',
  },
});
