import { buildLocalizedProfile } from './localized';

// The Philippines in Filipino: Taglish where people genuinely use English
// (brands, "Grab", "credit card"), Filipino for everything else.
export const filipinoProfile = buildLocalizedProfile({
  seed: 20260516,
  locale: 'fil',
  currencyCode: 'PHP',
  currencySymbol: '₱',
  priceScale: 5.3,
  decimals: 2,
  monthlySalary: 55000,
  monthlyRent: 18000,
  profileName: 'Andrea Santos',
  accountGroups: {
    everyday: 'Pang-araw-araw',
    goals: 'Mga Layunin',
    credit: 'Credit',
    investing: 'Pamumuhunan',
  },
  accounts: {
    checking: { name: 'BDO Savings', logoId: 'philippines/bdo-unibank' },
    savings: { name: 'BPI Ipon', logoId: 'philippines/bpi' },
    travel: { name: 'Pang-bakasyon', logoId: 'philippines/tonik' },
    card: { name: 'Metrobank Card', logoId: 'philippines/metrobank' },
    cash: { name: 'Cash', logoId: 'global/visa' },
    brokerage: { name: 'COL Financial', logoId: 'philippines/col-financial' },
  },
  extraAccounts: [
    { name: 'GCash', type: 'debit', logoId: 'philippines/gcash', groupKey: 'everyday' },
    { name: 'Maya', type: 'debit', logoId: 'philippines/maya', groupKey: 'everyday' },
    { name: 'GoTyme', type: 'debit', logoId: 'philippines/gotyme-bank', groupKey: 'goals' },
    { name: 'UnionBank Card', type: 'credit', logoId: 'philippines/unionbank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Bahay',
    rent: 'Upa',
    utilities: 'Kuryente at Tubig',
    internet: 'Internet',
    home_supplies: 'Gamit sa Bahay',
    food: 'Pagkain',
    groceries: 'Grocery',
    dining: 'Kain sa Labas',
    coffee: 'Kape',
    transport: 'Transportasyon',
    fuel: 'Gasolina',
    rideshare: 'Grab',
    parking: 'Parking at Toll',
    lifestyle: 'Libangan',
    shopping: 'Pamimili',
    entertainment: 'Gimik',
    subscriptions: 'Subscriptions',
    health: 'Kalusugan',
    healthcare: 'Botika at Doktor',
    fitness: 'Gym',
    travel_root: 'Biyahe',
    flights: 'Flights',
    hotels: 'Hotel',
    local_travel: 'Lokal na Biyahe',
    family: 'Pamilya',
    gifts: 'Regalo',
    education: 'Kurso',
    salary_root: 'Sahod',
    salary: 'Sahod',
    bonus: '13th Month',
    side_root: 'Raket',
    freelance: 'Freelance',
    consulting: 'Consulting',
    invest_root: 'Pamumuhunan',
    dividends: 'Dibidendo',
    interest: 'Interes',
  },
  budgetName: 'Buwanang Budget',
  split: {
    merchant: 'Max’s Restaurant',
    note: 'Hapunan kasama barkada, ako muna nagbayad',
    people: ['Miguel', 'Bea', 'Paolo'],
  },
  recurring: {
    salary: { name: 'Sahod', note: 'Buwanang sahod' },
    rent: { name: 'Upa sa Condo', note: 'Buwanang upa' },
    fitness: {
      name: 'Gym',
      amount: 2500,
      note: 'Anytime Fitness',
      logoId: 'philippines/anytime-fitness-ph',
    },
    subscriptions: [
      { name: 'Netflix', amount: 459, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 169, note: 'Spotify Premium' },
      { name: 'Viu', amount: 149, note: 'Viu Premium' },
      { name: 'Disney+', amount: 369, note: 'Disney+' },
      { name: 'iCloud+', amount: 149, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Hulog sa UITF', note: 'Buwanang ipon' },
  },
  merchants: {
    grocery: ['SM Supermarket', 'Puregold', 'Robinsons Supermarket', 'S&R', 'Landers'],
    dining: ['Max’s Restaurant', 'Jollibee', 'Mang Inasal', 'Chowking', 'Manam'],
    coffee: ['Starbucks', 'Tim Hortons', 'Coffee Project', 'Bo’s Coffee'],
    fuel: ['Petron', 'Shell', 'Caltex'],
    shopping: ['SM Megamall', 'Shopee', 'Lazada', 'Uniqlo'],
    entertainment: ['SM Cinema', 'Ayala Malls Cinemas', 'Timezone'],
    rideshare: ['Grab', 'Angkas'],
    healthcare: ['Mercury Drug', 'Watsons', 'St. Luke’s'],
    hotels: ['Hotel sa Boracay', 'Seda Hotel'],
    flights: ['Cebu Pacific', 'Philippine Airlines'],
    delivery: ['GrabFood', 'foodpanda', 'Jollibee Delivery'],
    convenience: ['7-Eleven', 'Ministop', 'FamilyMart'],
  },
  notes: {
    salary: 'Sahod',
    bonus: '13th month pay',
    freelance: 'Raket',
    consulting: 'Consulting fee',
    dividends: 'Dibidendo',
    interest: 'Interes sa ipon',
    rent: 'Upa ngayong buwan',
    utilities: 'Meralco at Maynilad',
    internet: 'PLDT Fibr',
    fitness: 'Anytime Fitness',
    homeSupplies: 'Gamit sa bahay',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Online course',
    atmWithdrawal: 'Withdraw sa ATM',
    parkingPrimary: 'Parking sa mall',
    parkingAlternate: 'Toll sa SLEX',
    savingsTransfer: 'Lipat sa ipon',
    investmentTransfer: 'Hulog sa UITF',
    travelTopUp: 'Pang-bakasyon',
    localTravel: 'P2P bus papuntang NAIA',
    tripDining: 'Kain sa biyahe',
    holidayGifts: 'Pamasko',
    familyCelebration: 'Handaan ng pamilya',
    cardPayment: 'Bayad sa credit card',
  },
});
