import { buildLocalizedProfile } from './localized';

export const frenchProfile = buildLocalizedProfile({
  seed: 20260502,
  locale: 'fr',
  currencyCode: 'EUR',
  currencySymbol: '€',
  priceScale: 0.33,
  decimals: 2,
  monthlySalary: 3300,
  monthlyRent: 1050,
  profileName: 'Camille Martin',
  accountGroups: {
    everyday: 'Quotidien',
    goals: 'Objectifs',
    credit: 'Crédit',
    investing: 'Placements',
  },
  accounts: {
    checking: { name: 'Compte courant BNP', logoId: 'france/bnp-paribas' },
    savings: { name: 'Livret A', logoId: 'france/la-banque-postale' },
    travel: { name: 'Cagnotte vacances', logoId: 'france/boursorama' },
    card: { name: 'Visa Crédit Agricole', logoId: 'france/credit-agricole' },
    cash: { name: 'Espèces', logoId: 'global/visa' },
    brokerage: { name: 'PEA Fortuneo', logoId: 'france/fortuneo' },
  },
  extraAccounts: [
    { name: 'Lydia', type: 'debit', logoId: 'france/lydia', groupKey: 'everyday' },
    { name: 'Revolut', type: 'debit', logoId: 'global/revolut', groupKey: 'everyday' },
    {
      name: 'Société Générale',
      type: 'debit',
      logoId: 'france/societe-generale',
      groupKey: 'everyday',
    },
    { name: 'Carte LCL', type: 'credit', logoId: 'france/lcl', groupKey: 'credit' },
  ],
  categories: {
    home: 'Logement',
    rent: 'Loyer',
    utilities: 'Électricité & eau',
    internet: 'Box internet',
    home_supplies: 'Maison',
    food: 'Alimentation',
    groceries: 'Courses',
    dining: 'Restaurant',
    coffee: 'Café',
    transport: 'Transport',
    fuel: 'Carburant',
    rideshare: 'VTC',
    parking: 'Parking & péage',
    lifestyle: 'Loisirs',
    shopping: 'Shopping',
    entertainment: 'Sorties',
    subscriptions: 'Abonnements',
    health: 'Santé',
    healthcare: 'Pharmacie & médecin',
    fitness: 'Sport',
    travel_root: 'Voyages',
    flights: 'Vols',
    hotels: 'Hôtels',
    local_travel: 'Transports locaux',
    family: 'Famille',
    gifts: 'Cadeaux',
    education: 'Formation',
    salary_root: 'Salaire',
    salary: 'Salaire',
    bonus: 'Prime',
    side_root: 'Revenus annexes',
    freelance: 'Freelance',
    consulting: 'Conseil',
    invest_root: 'Placements',
    dividends: 'Dividendes',
    interest: 'Intérêts',
  },
  budgetName: 'Budget du mois',
  split: {
    merchant: 'Bistrot du Coin',
    note: "Dîner entre amis, j'ai avancé",
    people: ['Lucas', 'Léa', 'Hugo'],
  },
  recurring: {
    salary: { name: 'Salaire', note: 'Salaire mensuel' },
    rent: { name: 'Loyer', note: 'Loyer appartement' },
    fitness: {
      name: 'Salle de sport',
      amount: 29.99,
      note: 'Basic-Fit',
      logoId: 'netherlands/basic-fit',
    },
    subscriptions: [
      { name: 'Netflix', amount: 13.49, note: 'Netflix Standard' },
      { name: 'Deezer', amount: 11.99, note: 'Deezer Premium', logoId: 'global/deezer' },
      { name: 'Canal+', amount: 24.99, note: 'Canal+', logoId: 'france/canal-plus' },
      { name: 'Navigo', amount: 86.4, note: 'Passe Navigo', logoId: 'france/ratp-navigo' },
      { name: 'iCloud+', amount: 2.99, note: 'iCloud 200 Go' },
    ],
    investment: { name: 'Versement PEA', note: 'Versement programmé' },
  },
  merchants: {
    grocery: ['Carrefour', 'Monoprix', 'Leclerc', 'Franprix', 'Picard'],
    dining: ['Bistrot du Coin', 'Brasserie Lipp', 'Big Mamma', 'Crêperie Bretonne', 'Sushi Shop'],
    coffee: ['Boulangerie Paul', 'Starbucks', 'Café de Flore', 'Columbus Café'],
    fuel: ['TotalEnergies', 'Esso', 'Intermarché carburant'],
    shopping: ['Fnac', 'Zara', 'Decathlon', 'Amazon.fr'],
    entertainment: ['UGC Ciné Cité', 'Pathé', 'Fnac Spectacles'],
    rideshare: ['Uber', 'G7 Taxi'],
    healthcare: ['Pharmacie Centrale', 'Médecin généraliste', 'Doctolib'],
    hotels: ['Hôtel Ibis', 'Airbnb Nice'],
    flights: ['Air France', 'easyJet'],
    delivery: ['Uber Eats', 'Deliveroo', 'Just Eat'],
    convenience: ['Carrefour City', 'Franprix', 'Monop'],
  },
  notes: {
    salary: 'Salaire',
    bonus: 'Prime annuelle',
    freelance: 'Mission freelance',
    consulting: 'Honoraires de conseil',
    dividends: 'Dividendes PEA',
    interest: 'Intérêts Livret A',
    rent: 'Loyer du mois',
    utilities: 'EDF & eau',
    internet: 'Freebox',
    fitness: 'Basic-Fit',
    homeSupplies: 'Courses maison',
    subscriptions: ['Netflix', 'Deezer', 'iCloud'],
    education: 'Formation en ligne',
    atmWithdrawal: "Retrait d'espèces",
    parkingPrimary: 'Parking',
    parkingAlternate: 'Péage autoroute',
    savingsTransfer: 'Virement Livret A',
    investmentTransfer: 'Versement PEA',
    travelTopUp: 'Cagnotte vacances',
    localTravel: "RER vers l'aéroport",
    tripDining: 'Repas en vacances',
    holidayGifts: 'Cadeaux de Noël',
    familyCelebration: 'Repas de famille',
    cardPayment: 'Remboursement carte',
  },
});
