import { buildLocalizedProfile } from './localized';

export const germanProfile = buildLocalizedProfile({
  seed: 20260501,
  locale: 'de',
  currencyCode: 'EUR',
  currencySymbol: '€',
  priceScale: 0.45,
  decimals: 2,
  monthlySalary: 4200,
  monthlyRent: 1150,
  profileName: 'Lena Schneider',
  accountGroups: {
    everyday: 'Alltag',
    goals: 'Sparziele',
    credit: 'Kredit',
    investing: 'Investieren',
  },
  accounts: {
    checking: { name: 'Sparkasse Giro', logoId: 'germany/sparkasse' },
    savings: { name: 'DKB Tagesgeld', logoId: 'germany/dkb' },
    travel: { name: 'Urlaubskasse', logoId: 'germany/ing-deutschland' },
    card: { name: 'Comdirect Visa', logoId: 'germany/comdirect' },
    cash: { name: 'Bargeld', logoId: 'global/visa' },
    brokerage: { name: 'Trade Republic', logoId: 'germany/trade-republic' },
  },
  extraAccounts: [
    { name: 'PayPal', type: 'debit', logoId: 'global/paypal', groupKey: 'everyday' },
    { name: 'N26', type: 'debit', logoId: 'global/n26', groupKey: 'everyday' },
    {
      name: 'Scalable Capital',
      type: 'debit',
      logoId: 'germany/scalable-capital',
      groupKey: 'investing',
    },
    { name: 'Amex Gold', type: 'credit', logoId: 'global/american-express', groupKey: 'credit' },
  ],
  categories: {
    home: 'Wohnen',
    rent: 'Miete',
    utilities: 'Strom & Wasser',
    internet: 'Internet',
    home_supplies: 'Haushalt',
    food: 'Essen',
    groceries: 'Lebensmittel',
    dining: 'Restaurant',
    coffee: 'Kaffee',
    transport: 'Mobilität',
    fuel: 'Tanken',
    rideshare: 'Taxi',
    parking: 'Parken',
    lifestyle: 'Freizeit',
    shopping: 'Shopping',
    entertainment: 'Unterhaltung',
    subscriptions: 'Abos',
    health: 'Gesundheit',
    healthcare: 'Apotheke & Arzt',
    fitness: 'Fitness',
    travel_root: 'Reisen',
    flights: 'Flüge',
    hotels: 'Hotels',
    local_travel: 'ÖPNV',
    family: 'Familie',
    gifts: 'Geschenke',
    education: 'Weiterbildung',
    salary_root: 'Gehalt',
    salary: 'Gehalt',
    bonus: 'Bonus',
    side_root: 'Nebenjob',
    freelance: 'Freelance',
    consulting: 'Beratung',
    invest_root: 'Kapitalerträge',
    dividends: 'Dividenden',
    interest: 'Zinsen',
  },
  budgetName: 'Monatsbudget',
  split: {
    merchant: 'Pizzeria Da Mario',
    note: 'Abendessen, ich hab ausgelegt',
    people: ['Jonas', 'Mia', 'Felix'],
  },
  recurring: {
    salary: { name: 'Gehalt', note: 'Monatsgehalt' },
    rent: { name: 'Miete', note: 'Warmmiete' },
    fitness: { name: 'Fitnessstudio', amount: 29.9, note: 'McFit', logoId: 'germany/mcfit' },
    subscriptions: [
      { name: 'Netflix', amount: 13.99, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 10.99, note: 'Spotify Premium' },
      { name: 'Disney+', amount: 9.99, note: 'Disney+' },
      { name: 'Deutschlandticket', amount: 58, note: 'ÖPNV-Abo', logoId: 'germany/deutsche-bahn' },
      { name: 'iCloud+', amount: 2.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'ETF-Sparplan', note: 'MSCI World Sparplan' },
  },
  merchants: {
    grocery: ['REWE', 'EDEKA', 'Aldi Süd', 'Lidl', 'dm-Drogerie'],
    dining: ['Pizzeria Da Mario', 'Döner am Eck', 'Vapiano', 'Burgermeister', 'Brauhaus Lemke'],
    coffee: ['Café Einstein', 'Tchibo', 'Starbucks', 'Bäckerei Kamps'],
    fuel: ['Aral', 'Shell', 'JET'],
    shopping: ['Zalando', 'Amazon.de', 'MediaMarkt', 'IKEA'],
    entertainment: ['CinemaxX', 'Eventim', 'Bowling Center'],
    rideshare: ['FREE NOW', 'Uber'],
    healthcare: ['Apotheke am Markt', 'Hausarzt', 'Rossmann'],
    hotels: ['Motel One', 'Hotel am Strand'],
    flights: ['Lufthansa', 'Eurowings'],
    delivery: ['Lieferando', 'Wolt', 'Uber Eats'],
    convenience: ['Kiosk', 'Späti', 'Rossmann'],
  },
  notes: {
    salary: 'Gehalt',
    bonus: 'Jahresbonus',
    freelance: 'Freelance-Projekt',
    consulting: 'Beratungshonorar',
    dividends: 'ETF-Ausschüttung',
    interest: 'Tagesgeldzinsen',
    rent: 'Miete',
    utilities: 'Strom & Wasser',
    internet: 'Telekom DSL',
    fitness: 'Fitnessstudio',
    homeSupplies: 'Haushaltseinkauf',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Online-Kurs',
    atmWithdrawal: 'Bargeld abgehoben',
    parkingPrimary: 'Parkhaus',
    parkingAlternate: 'Parkautomat',
    savingsTransfer: 'Aufs Tagesgeld',
    investmentTransfer: 'ETF-Sparplan',
    travelTopUp: 'Urlaubskasse',
    localTravel: 'S-Bahn zum Flughafen',
    tripDining: 'Essen im Urlaub',
    holidayGifts: 'Weihnachtsgeschenke',
    familyCelebration: 'Familienfeier',
    cardPayment: 'Kreditkarte ausgeglichen',
  },
});
