import { buildLocalizedProfile } from './localized';

// India in Hindi: brand names stay in Latin script, the way they appear on the
// apps and receipts people actually use; everything else is Devanagari.
export const indianProfile = buildLocalizedProfile({
  seed: 20260514,
  locale: 'hi',
  currencyCode: 'INR',
  currencySymbol: '₹',
  priceScale: 12.5,
  decimals: 2,
  monthlySalary: 110000,
  monthlyRent: 28000,
  profileName: 'प्रिया शर्मा',
  accountGroups: { everyday: 'रोज़मर्रा', goals: 'लक्ष्य', credit: 'क्रेडिट', investing: 'निवेश' },
  accounts: {
    checking: { name: 'HDFC बचत खाता', logoId: 'india/hdfc-bank' },
    savings: { name: 'SBI FD', logoId: 'india/state-bank-of-india' },
    travel: { name: 'यात्रा फंड', logoId: 'india/kotak-mahindra-bank' },
    card: { name: 'ICICI क्रेडिट कार्ड', logoId: 'india/icici-bank' },
    cash: { name: 'नकद', logoId: 'india/bhim' },
    brokerage: { name: 'Zerodha', logoId: 'india/zerodha' },
  },
  extraAccounts: [
    { name: 'PhonePe', type: 'debit', logoId: 'india/phonepe', groupKey: 'everyday' },
    { name: 'Paytm', type: 'debit', logoId: 'india/paytm', groupKey: 'everyday' },
    { name: 'Groww', type: 'debit', logoId: 'india/groww', groupKey: 'investing' },
    { name: 'Axis क्रेडिट कार्ड', type: 'credit', logoId: 'india/axis-bank', groupKey: 'credit' },
  ],
  categories: {
    home: 'घर',
    rent: 'किराया',
    utilities: 'बिजली-पानी',
    internet: 'इंटरनेट',
    home_supplies: 'घरेलू सामान',
    food: 'खाना',
    groceries: 'किराना',
    dining: 'बाहर खाना',
    coffee: 'चाय-कॉफ़ी',
    transport: 'यातायात',
    fuel: 'पेट्रोल',
    rideshare: 'कैब',
    parking: 'पार्किंग',
    lifestyle: 'लाइफ़स्टाइल',
    shopping: 'शॉपिंग',
    entertainment: 'मनोरंजन',
    subscriptions: 'सब्सक्रिप्शन',
    health: 'स्वास्थ्य',
    healthcare: 'दवा और डॉक्टर',
    fitness: 'जिम',
    travel_root: 'यात्रा',
    flights: 'फ़्लाइट',
    hotels: 'होटल',
    local_travel: 'लोकल यात्रा',
    family: 'परिवार',
    gifts: 'उपहार',
    education: 'पढ़ाई',
    salary_root: 'वेतन',
    salary: 'वेतन',
    bonus: 'बोनस',
    side_root: 'साइड इनकम',
    freelance: 'फ्रीलांस',
    consulting: 'कंसल्टिंग',
    invest_root: 'निवेश',
    dividends: 'डिविडेंड',
    interest: 'ब्याज',
  },
  budgetName: 'मासिक बजट',
  split: {
    merchant: 'Haldiram’s',
    note: 'दोस्तों के साथ डिनर, मैंने पे किया',
    people: ['राहुल', 'अंजलि', 'विक्रम'],
  },
  recurring: {
    salary: { name: 'वेतन', note: 'मासिक वेतन' },
    rent: { name: 'किराया', note: 'फ़्लैट का किराया' },
    fitness: { name: 'जिम', amount: 1999, note: 'cult.fit', logoId: 'india/cult-fit' },
    subscriptions: [
      { name: 'JioHotstar', amount: 299, note: 'JioHotstar', logoId: 'india/jiohotstar' },
      { name: 'Netflix', amount: 499, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 119, note: 'Spotify Premium' },
      { name: 'Amazon Prime', amount: 299, note: 'Amazon Prime' },
      { name: 'Swiggy One', amount: 149, note: 'Swiggy One', logoId: 'india/swiggy' },
    ],
    investment: { name: 'म्यूचुअल फंड SIP', note: 'हर महीने SIP' },
  },
  merchants: {
    grocery: ['BigBasket', 'DMart', 'Blinkit', 'Reliance Fresh', 'Zepto'],
    dining: ['Haldiram’s', 'Saravana Bhavan', 'Barbeque Nation', 'Bikanervala', 'Domino’s'],
    coffee: ['Chaayos', 'Café Coffee Day', 'Starbucks', 'Third Wave Coffee'],
    fuel: ['Indian Oil', 'HP Petrol', 'Bharat Petroleum'],
    shopping: ['Amazon.in', 'Flipkart', 'Myntra', 'Croma'],
    entertainment: ['PVR INOX', 'BookMyShow', 'Cinepolis'],
    rideshare: ['Ola', 'Uber'],
    healthcare: ['Apollo Pharmacy', 'PharmEasy', 'Practo डॉक्टर'],
    hotels: ['Taj', 'OYO'],
    flights: ['IndiGo', 'Air India'],
    delivery: ['Swiggy', 'Zomato', 'Blinkit'],
    convenience: ['Swiggy Instamart', 'Zepto', 'More Supermarket'],
  },
  notes: {
    salary: 'वेतन',
    bonus: 'सालाना बोनस',
    freelance: 'फ्रीलांस प्रोजेक्ट',
    consulting: 'कंसल्टिंग फ़ीस',
    dividends: 'डिविडेंड',
    interest: 'FD का ब्याज',
    rent: 'इस महीने का किराया',
    utilities: 'बिजली और पानी का बिल',
    internet: 'Airtel ब्रॉडबैंड',
    fitness: 'cult.fit',
    homeSupplies: 'घर का सामान',
    subscriptions: ['JioHotstar', 'Spotify', 'iCloud'],
    education: 'ऑनलाइन कोर्स',
    atmWithdrawal: 'ATM से नकद',
    parkingPrimary: 'मॉल पार्किंग',
    parkingAlternate: 'टोल',
    savingsTransfer: 'बचत में ट्रांसफ़र',
    investmentTransfer: 'SIP',
    travelTopUp: 'यात्रा फंड',
    localTravel: 'मेट्रो से एयरपोर्ट',
    tripDining: 'यात्रा में खाना',
    holidayGifts: 'दिवाली के उपहार',
    familyCelebration: 'पारिवारिक दावत',
    cardPayment: 'क्रेडिट कार्ड बिल',
  },
});
