import { buildLocalizedProfile } from './localized';

export const indonesianProfile = buildLocalizedProfile({
  seed: 20260515,
  locale: 'id',
  currencyCode: 'IDR',
  currencySymbol: 'Rp',
  priceScale: 1400,
  decimals: 0,
  monthlySalary: 14000000,
  monthlyRent: 4500000,
  profileName: 'Putri Lestari',
  accountGroups: { everyday: 'Harian', goals: 'Tujuan', credit: 'Kredit', investing: 'Investasi' },
  accounts: {
    checking: { name: 'BCA Tahapan', logoId: 'indonesia/bank-central-asia' },
    savings: { name: 'Tabungan Mandiri', logoId: 'indonesia/bank-mandiri' },
    travel: { name: 'Dana Liburan', logoId: 'indonesia/bank-jago' },
    card: { name: 'Kartu Kredit BNI', logoId: 'indonesia/bank-negara-indonesia' },
    cash: { name: 'Tunai', logoId: 'global/visa' },
    brokerage: { name: 'Bibit', logoId: 'indonesia/bibit' },
  },
  extraAccounts: [
    { name: 'Jenius', type: 'debit', logoId: 'indonesia/jenius', groupKey: 'everyday' },
    { name: 'CIMB Niaga', type: 'debit', logoId: 'indonesia/cimb-niaga', groupKey: 'everyday' },
    { name: 'Stockbit', type: 'debit', logoId: 'indonesia/stockbit', groupKey: 'investing' },
    { name: 'Kartu Danamon', type: 'credit', logoId: 'indonesia/bank-danamon', groupKey: 'credit' },
  ],
  categories: {
    home: 'Rumah',
    rent: 'Sewa',
    utilities: 'Listrik & Air',
    internet: 'Internet',
    home_supplies: 'Kebutuhan Rumah',
    food: 'Makanan',
    groceries: 'Belanja Dapur',
    dining: 'Makan di Luar',
    coffee: 'Kopi',
    transport: 'Transportasi',
    fuel: 'Bensin',
    rideshare: 'Ojol',
    parking: 'Parkir & Tol',
    lifestyle: 'Gaya Hidup',
    shopping: 'Belanja',
    entertainment: 'Hiburan',
    subscriptions: 'Langganan',
    health: 'Kesehatan',
    healthcare: 'Apotek & Dokter',
    fitness: 'Gym',
    travel_root: 'Liburan',
    flights: 'Tiket Pesawat',
    hotels: 'Hotel',
    local_travel: 'Transportasi Lokal',
    family: 'Keluarga',
    gifts: 'Hadiah & THR',
    education: 'Kursus',
    salary_root: 'Gaji',
    salary: 'Gaji',
    bonus: 'Bonus',
    side_root: 'Sampingan',
    freelance: 'Freelance',
    consulting: 'Konsultasi',
    invest_root: 'Investasi',
    dividends: 'Dividen',
    interest: 'Bunga',
  },
  budgetName: 'Anggaran Bulanan',
  split: {
    merchant: 'Sate Khas Senayan',
    note: 'Makan bareng teman, aku talangin dulu',
    people: ['Budi', 'Sari', 'Dimas'],
  },
  recurring: {
    salary: { name: 'Gaji', note: 'Gaji bulanan' },
    rent: { name: 'Sewa Apartemen', note: 'Sewa bulanan' },
    fitness: { name: 'Gym', amount: 450000, note: 'FitHub', logoId: 'indonesia/fithub' },
    subscriptions: [
      { name: 'Netflix', amount: 120000, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 54990, note: 'Spotify Premium' },
      { name: 'Vidio', amount: 39000, note: 'Vidio Platinum', logoId: 'indonesia/vidio' },
      { name: 'Disney+ Hotstar', amount: 39000, note: 'Disney+ Hotstar' },
      { name: 'iCloud+', amount: 45000, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Reksa Dana', note: 'Investasi rutin' },
  },
  merchants: {
    grocery: ['Indomaret', 'Alfamart', 'Superindo', 'Ranch Market', 'Hypermart'],
    dining: ['Sate Khas Senayan', 'Bakmi GM', 'Warung Padang', 'Solaria', 'Hokben'],
    coffee: ['Kopi Kenangan', 'Janji Jiwa', 'Fore Coffee', 'Starbucks'],
    fuel: ['Pertamina', 'Shell', 'BP AKR'],
    shopping: ['Tokopedia', 'Shopee', 'Uniqlo Grand Indonesia', 'IKEA'],
    entertainment: ['CGV', 'XXI Cinema', 'Dufan'],
    rideshare: ['Gojek', 'Grab'],
    healthcare: ['Apotek K-24', 'Kimia Farma', 'Halodoc'],
    hotels: ['Hotel Bali', 'Aston'],
    flights: ['Garuda Indonesia', 'Citilink'],
    delivery: ['GoFood', 'GrabFood', 'ShopeeFood'],
    convenience: ['Indomaret', 'Alfamart', 'Lawson'],
  },
  notes: {
    salary: 'Gaji',
    bonus: 'Bonus tahunan',
    freelance: 'Proyek freelance',
    consulting: 'Biaya konsultasi',
    dividends: 'Dividen saham',
    interest: 'Bunga deposito',
    rent: 'Sewa bulan ini',
    utilities: 'Token listrik & PDAM',
    internet: 'IndiHome',
    fitness: 'FitHub',
    homeSupplies: 'Kebutuhan rumah',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Kursus online',
    atmWithdrawal: 'Tarik tunai ATM',
    parkingPrimary: 'Parkir mal',
    parkingAlternate: 'Tol',
    savingsTransfer: 'Pindah ke tabungan',
    investmentTransfer: 'Reksa dana',
    travelTopUp: 'Dana liburan',
    localTravel: 'Kereta bandara',
    tripDining: 'Makan pas liburan',
    holidayGifts: 'THR keluarga',
    familyCelebration: 'Kumpul keluarga',
    cardPayment: 'Bayar kartu kredit',
  },
});
