import { buildLocalizedProfile } from './localized';

export const italianProfile = buildLocalizedProfile({
  seed: 20260504,
  locale: 'it',
  currencyCode: 'EUR',
  currencySymbol: '€',
  priceScale: 0.29,
  decimals: 2,
  monthlySalary: 2800,
  monthlyRent: 850,
  profileName: 'Giulia Rossi',
  accountGroups: {
    everyday: 'Quotidiano',
    goals: 'Obiettivi',
    credit: 'Credito',
    investing: 'Investimenti',
  },
  accounts: {
    checking: { name: 'Conto Intesa', logoId: 'italy/intesa-sanpaolo' },
    savings: { name: 'Risparmio Fineco', logoId: 'italy/finecobank' },
    travel: { name: 'Salvadanaio viaggi', logoId: 'italy/hype' },
    card: { name: 'Carta UniCredit', logoId: 'italy/unicredit' },
    cash: { name: 'Contanti', logoId: 'global/visa' },
    brokerage: { name: 'Banca Mediolanum', logoId: 'italy/banca-mediolanum' },
  },
  extraAccounts: [
    { name: 'Satispay', type: 'debit', logoId: 'italy/satispay', groupKey: 'everyday' },
    { name: 'PostePay', type: 'debit', logoId: 'italy/postepay', groupKey: 'everyday' },
    { name: 'BNL', type: 'debit', logoId: 'italy/bnl', groupKey: 'everyday' },
    { name: 'Carta Nexi', type: 'credit', logoId: 'italy/nexi', groupKey: 'credit' },
  ],
  categories: {
    home: 'Casa',
    rent: 'Affitto',
    utilities: 'Luce e acqua',
    internet: 'Internet',
    home_supplies: 'Spese casa',
    food: 'Cibo',
    groceries: 'Spesa',
    dining: 'Ristoranti',
    coffee: 'Caffè',
    transport: 'Trasporti',
    fuel: 'Benzina',
    rideshare: 'Taxi',
    parking: 'Parcheggio',
    lifestyle: 'Tempo libero',
    shopping: 'Shopping',
    entertainment: 'Svago',
    subscriptions: 'Abbonamenti',
    health: 'Salute',
    healthcare: 'Farmacia e medico',
    fitness: 'Palestra',
    travel_root: 'Viaggi',
    flights: 'Voli',
    hotels: 'Hotel',
    local_travel: 'Mezzi locali',
    family: 'Famiglia',
    gifts: 'Regali',
    education: 'Formazione',
    salary_root: 'Stipendio',
    salary: 'Stipendio',
    bonus: 'Tredicesima',
    side_root: 'Entrate extra',
    freelance: 'Freelance',
    consulting: 'Consulenze',
    invest_root: 'Investimenti',
    dividends: 'Dividendi',
    interest: 'Interessi',
  },
  budgetName: 'Budget mensile',
  split: {
    merchant: 'Trattoria da Enzo',
    note: 'Cena tra amici, ho pagato io',
    people: ['Marco', 'Chiara', 'Luca'],
  },
  recurring: {
    salary: { name: 'Stipendio', note: 'Stipendio mensile' },
    rent: { name: 'Affitto', note: "Affitto dell'appartamento" },
    fitness: {
      name: 'Palestra',
      amount: 39,
      note: 'Virgin Active',
      logoId: 'italy/virgin-active-it',
    },
    subscriptions: [
      { name: 'Netflix', amount: 13.99, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 10.99, note: 'Spotify Premium' },
      { name: 'DAZN', amount: 34.99, note: 'DAZN Serie A', logoId: 'global/dazn' },
      { name: 'Disney+', amount: 9.99, note: 'Disney+' },
      { name: 'iCloud+', amount: 2.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'PAC ETF', note: 'Piano di accumulo' },
  },
  merchants: {
    grocery: ['Esselunga', 'Coop', 'Conad', 'Carrefour', 'Lidl'],
    dining: ['Trattoria da Enzo', 'Pizzeria Sorbillo', 'Roscioli', 'Osteria del Ponte', 'Spontini'],
    coffee: ['Bar Centrale', 'Caffè Vergnano', 'Pasticceria Marchesi', 'Starbucks Reserve'],
    fuel: ['Eni', 'Q8', 'IP'],
    shopping: ['Zara', 'Rinascente', 'MediaWorld', 'Amazon.it'],
    entertainment: ['UCI Cinemas', 'The Space Cinema', 'TicketOne'],
    rideshare: ['itTaxi', 'Uber'],
    healthcare: ['Farmacia Comunale', 'Medico di base', 'Dentista'],
    hotels: ['Hotel Roma', 'Agriturismo Toscana'],
    flights: ['ITA Airways', 'Ryanair'],
    delivery: ['Glovo', 'Deliveroo', 'Just Eat'],
    convenience: ['Carrefour Express', 'Tabaccheria', 'Pam'],
  },
  notes: {
    salary: 'Stipendio',
    bonus: 'Tredicesima',
    freelance: 'Progetto freelance',
    consulting: 'Consulenza',
    dividends: 'Dividendi ETF',
    interest: 'Interessi conto',
    rent: 'Affitto del mese',
    utilities: 'Bolletta luce e acqua',
    internet: 'Fibra TIM',
    fitness: 'Palestra',
    homeSupplies: 'Spese per la casa',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Corso online',
    atmWithdrawal: 'Prelievo bancomat',
    parkingPrimary: 'Parcheggio',
    parkingAlternate: 'Pedaggio',
    savingsTransfer: 'Giro su risparmio',
    investmentTransfer: 'Versamento PAC',
    travelTopUp: 'Salvadanaio viaggi',
    localTravel: "Treno per l'aeroporto",
    tripDining: 'Cena in vacanza',
    holidayGifts: 'Regali di Natale',
    familyCelebration: 'Pranzo in famiglia',
    cardPayment: 'Saldo carta',
  },
});
