import { buildLocalizedProfile } from './localized';

export const japaneseProfile = buildLocalizedProfile({
  seed: 20260519,
  locale: 'ja',
  currencyCode: 'JPY',
  currencySymbol: '¥',
  priceScale: 30,
  decimals: 0,
  monthlySalary: 380000,
  monthlyRent: 95000,
  profileName: '佐藤 美咲',
  accountGroups: { everyday: '日常', goals: '目標', credit: 'クレジット', investing: '投資' },
  accounts: {
    checking: { name: 'みずほ普通', logoId: 'japan/mizuho-bank' },
    savings: { name: 'ゆうちょ貯金', logoId: 'japan/japan-post-bank' },
    travel: { name: '旅行積立', logoId: 'japan/sbi-sumishin-net-bank' },
    card: { name: '楽天カード', logoId: 'japan/rakuten-bank' },
    cash: { name: '現金', logoId: 'global/visa' },
    brokerage: { name: 'NISA口座', logoId: 'japan/nomura' },
  },
  extraAccounts: [
    { name: 'PayPay', type: 'debit', logoId: 'japan/paypay', groupKey: 'everyday' },
    { name: 'りそな銀行', type: 'debit', logoId: 'japan/resona-bank', groupKey: 'everyday' },
    { name: 'メルペイ', type: 'debit', logoId: 'japan/merpay', groupKey: 'everyday' },
    { name: 'JCBカード', type: 'credit', logoId: 'japan/jcb', groupKey: 'credit' },
  ],
  categories: {
    home: '住まい',
    rent: '家賃',
    utilities: '水道光熱費',
    internet: 'ネット',
    home_supplies: '日用品',
    food: '食費',
    groceries: 'スーパー',
    dining: '外食',
    coffee: 'カフェ',
    transport: '交通',
    fuel: 'ガソリン',
    rideshare: 'タクシー',
    parking: '駐車場',
    lifestyle: '趣味',
    shopping: '買い物',
    entertainment: 'エンタメ',
    subscriptions: 'サブスク',
    health: '健康',
    healthcare: '病院・薬局',
    fitness: 'ジム',
    travel_root: '旅行',
    flights: '航空券',
    hotels: 'ホテル',
    local_travel: '現地交通',
    family: '家族',
    gifts: 'プレゼント',
    education: '習い事',
    salary_root: '給与',
    salary: '給与',
    bonus: 'ボーナス',
    side_root: '副業',
    freelance: 'フリーランス',
    consulting: 'コンサル',
    invest_root: '投資',
    dividends: '配当',
    interest: '利息',
  },
  budgetName: '毎月の予算',
  split: { merchant: '鳥貴族', note: '友達と飲み会、立て替え', people: ['健太', 'さくら', '大輔'] },
  recurring: {
    salary: { name: '給料', note: '月給' },
    rent: { name: '家賃', note: 'マンション家賃' },
    fitness: {
      name: 'ジム',
      amount: 7678,
      note: 'エニタイムフィットネス',
      logoId: 'japan/anytime-fitness-japan',
    },
    subscriptions: [
      { name: 'Netflix', amount: 1590, note: 'Netflix スタンダード' },
      { name: 'Spotify', amount: 980, note: 'Spotify Premium' },
      { name: 'U-NEXT', amount: 2189, note: 'U-NEXT' },
      { name: 'Amazon Prime', amount: 600, note: 'Amazonプライム' },
      { name: 'iCloud+', amount: 450, note: 'iCloud 200GB' },
    ],
    investment: { name: 'つみたてNISA', note: '毎月積立' },
  },
  merchants: {
    grocery: ['イオン', 'ライフ', '成城石井', '業務スーパー', '西友'],
    dining: ['鳥貴族', '一蘭', 'サイゼリヤ', 'すき家', '大戸屋'],
    coffee: ['スターバックス', 'ドトール', 'タリーズ', 'コメダ珈琲'],
    fuel: ['ENEOS', '出光', 'コスモ石油'],
    shopping: ['ユニクロ', '無印良品', 'ヨドバシカメラ', 'Amazon.co.jp'],
    entertainment: ['TOHOシネマズ', 'カラオケ館', '東京ディズニーランド'],
    rideshare: ['GO タクシー', 'Uber'],
    healthcare: ['マツモトキヨシ', 'ウエルシア', '内科クリニック'],
    hotels: ['東横イン', '温泉旅館'],
    flights: ['ANA', 'JAL'],
    delivery: ['Uber Eats', '出前館', 'Wolt'],
    convenience: ['セブン-イレブン', 'ファミリーマート', 'ローソン'],
  },
  notes: {
    salary: '給料',
    bonus: '冬のボーナス',
    freelance: '副業案件',
    consulting: 'コンサル報酬',
    dividends: '配当金',
    interest: '預金利息',
    rent: '今月の家賃',
    utilities: '電気・ガス・水道',
    internet: '光回線',
    fitness: 'ジム月会費',
    homeSupplies: '日用品まとめ買い',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'オンライン講座',
    atmWithdrawal: 'ATM 引き出し',
    parkingPrimary: 'コインパーキング',
    parkingAlternate: '高速道路',
    savingsTransfer: '貯金へ振替',
    investmentTransfer: 'つみたてNISA',
    travelTopUp: '旅行積立',
    localTravel: '成田エクスプレス',
    tripDining: '旅行中の食事',
    holidayGifts: 'お年玉',
    familyCelebration: '家族の食事会',
    cardPayment: 'カード引き落とし',
  },
});
