import { buildLocalizedProfile } from './localized';

export const koreanProfile = buildLocalizedProfile({
  seed: 20260520,
  locale: 'ko',
  currencyCode: 'KRW',
  currencySymbol: '₩',
  priceScale: 280,
  decimals: 0,
  monthlySalary: 4200000,
  monthlyRent: 900000,
  profileName: '김지은',
  accountGroups: { everyday: '생활비', goals: '목표', credit: '신용카드', investing: '투자' },
  accounts: {
    checking: { name: '국민은행 입출금', logoId: 'south-korea/kb-kookmin-bank' },
    savings: { name: '카카오뱅크 적금', logoId: 'south-korea/kakaobank' },
    travel: { name: '여행 통장', logoId: 'south-korea/toss-bank' },
    card: { name: '신한카드', logoId: 'south-korea/shinhan-bank' },
    cash: { name: '현금', logoId: 'global/visa' },
    brokerage: { name: '미래에셋 ISA', logoId: 'south-korea/mirae-asset' },
  },
  extraAccounts: [
    { name: '토스', type: 'debit', logoId: 'south-korea/toss', groupKey: 'everyday' },
    { name: '우리은행', type: 'debit', logoId: 'south-korea/woori-bank', groupKey: 'everyday' },
    { name: '하나은행', type: 'debit', logoId: 'south-korea/hana-bank', groupKey: 'goals' },
    { name: 'NH농협카드', type: 'credit', logoId: 'south-korea/nonghyup-bank', groupKey: 'credit' },
  ],
  categories: {
    home: '주거',
    rent: '월세',
    utilities: '관리비',
    internet: '인터넷',
    home_supplies: '생활용품',
    food: '식비',
    groceries: '장보기',
    dining: '외식',
    coffee: '카페',
    transport: '교통',
    fuel: '주유',
    rideshare: '택시',
    parking: '주차',
    lifestyle: '여가',
    shopping: '쇼핑',
    entertainment: '문화생활',
    subscriptions: '구독',
    health: '건강',
    healthcare: '병원·약국',
    fitness: '헬스',
    travel_root: '여행',
    flights: '항공권',
    hotels: '숙박',
    local_travel: '현지 교통',
    family: '가족',
    gifts: '선물',
    education: '자기계발',
    salary_root: '급여',
    salary: '월급',
    bonus: '상여금',
    side_root: '부수입',
    freelance: '프리랜스',
    consulting: '컨설팅',
    invest_root: '투자',
    dividends: '배당',
    interest: '이자',
  },
  budgetName: '월 예산',
  split: {
    merchant: '교촌치킨',
    note: '친구들이랑 저녁, 내가 먼저 결제',
    people: ['민준', '서연', '현우'],
  },
  recurring: {
    salary: { name: '월급', note: '이번 달 월급' },
    rent: { name: '월세', note: '오피스텔 월세' },
    fitness: { name: '헬스장', amount: 70000, note: '헬스장 회원권' },
    subscriptions: [
      { name: '쿠팡 와우', amount: 7890, note: '쿠팡 와우 멤버십', logoId: 'south-korea/coupang' },
      { name: 'Netflix', amount: 13500, note: 'Netflix 스탠다드' },
      { name: 'TVING', amount: 13900, note: '티빙', logoId: 'south-korea/tving' },
      { name: '멜론', amount: 10900, note: '멜론 스트리밍', logoId: 'south-korea/melon' },
      { name: 'YouTube Premium', amount: 14900, note: 'YouTube Premium' },
    ],
    investment: { name: 'ISA 적립', note: '매달 적립식' },
  },
  merchants: {
    grocery: ['이마트', '홈플러스', '마켓컬리', 'GS더프레시', '롯데마트'],
    dining: ['교촌치킨', '김밥천국', '본죽', '백종원 빽다방', '명동교자'],
    coffee: ['스타벅스', '메가커피', '투썸플레이스', '이디야'],
    fuel: ['SK에너지', 'GS칼텍스', 'S-OIL'],
    shopping: ['쿠팡', '올리브영', '무신사', '다이소'],
    entertainment: ['CGV', '메가박스', '롯데월드'],
    rideshare: ['카카오T', '우티'],
    healthcare: ['온누리약국', '내과의원', '치과'],
    hotels: ['제주 호텔', '야놀자 숙소'],
    flights: ['대한항공', '제주항공'],
    delivery: ['배달의민족', '쿠팡이츠', '요기요'],
    convenience: ['CU', 'GS25', '세븐일레븐'],
  },
  notes: {
    salary: '월급',
    bonus: '연말 상여금',
    freelance: '프리랜스 작업',
    consulting: '컨설팅 비용',
    dividends: '배당금',
    interest: '예금 이자',
    rent: '이번 달 월세',
    utilities: '관리비',
    internet: 'KT 인터넷',
    fitness: '헬스장',
    homeSupplies: '생활용품',
    subscriptions: ['Netflix', '멜론', 'iCloud'],
    education: '온라인 강의',
    atmWithdrawal: 'ATM 출금',
    parkingPrimary: '주차비',
    parkingAlternate: '고속도로 통행료',
    savingsTransfer: '적금 이체',
    investmentTransfer: 'ISA 적립',
    travelTopUp: '여행 통장',
    localTravel: '공항철도',
    tripDining: '여행 중 식사',
    holidayGifts: '설날 선물',
    familyCelebration: '가족 모임',
    cardPayment: '카드값 결제',
  },
});
