import type { CategoryNames, PreviewProfile } from '../shared';

// Malaysian English: mostly English, with the local terms Malaysians genuinely
// use even when speaking English (Unifi, Grab, kopi, Astro, duit raya, FD).
const MALAYSIAN_EN_CATEGORIES: CategoryNames = {
  home: 'Home',
  rent: 'Rent',
  utilities: 'TNB & Water',
  internet: 'Unifi',
  home_supplies: 'Household',
  food: 'Food',
  groceries: 'Groceries',
  dining: 'Eating Out',
  coffee: 'Kopi & Tea',
  transport: 'Transport',
  fuel: 'Petrol',
  rideshare: 'Grab',
  parking: 'Tolls & Parking',
  lifestyle: 'Lifestyle',
  shopping: 'Shopping',
  entertainment: 'Entertainment',
  subscriptions: 'Subscriptions',
  health: 'Health',
  healthcare: 'Clinic & Pharmacy',
  fitness: 'Gym',
  travel_root: 'Travel',
  flights: 'Flights',
  hotels: 'Hotels',
  local_travel: 'Local Transit',
  family: 'Family',
  gifts: 'Duit Raya & Gifts',
  education: 'Courses',
  salary_root: 'Salary',
  salary: 'Salary',
  bonus: 'Bonus',
  side_root: 'Side Hustle',
  freelance: 'Freelance',
  consulting: 'Consulting',
  invest_root: 'Investments',
  dividends: 'Dividends',
  interest: 'FD Interest',
};

export const malaysianEnProfile: PreviewProfile = {
  seed: 20260411,
  locale: 'en',
  currencyCode: 'MYR',
  currencySymbol: 'RM',
  profileName: 'Aiman Tan',
  accountGroups: {
    everyday: 'Everyday',
    goals: 'Goals',
    credit: 'Credit',
    investing: 'Investing',
  },
  accounts: {
    checking: { name: 'Maybank2u', startingBalance: 4850, logoId: 'malaysia/maybank' },
    savings: { name: 'CIMB Savings', startingBalance: 28600, logoId: 'malaysia/cimb' },
    travel: { name: 'Cuti Tabung', startingBalance: 2400, logoId: 'malaysia/hsbc-malaysia' },
    card: { name: 'Maybank 2 Card', startingBalance: 320, logoId: 'malaysia/maybank' },
    cash: { name: 'Wallet Cash', startingBalance: 180, logoId: 'malaysia/touch-n-go-ewallet' },
    brokerage: { name: 'StashAway', startingBalance: 16800, logoId: 'malaysia/stashaway' },
  },
  extraAccounts: [
    {
      name: 'GrabPay',
      type: 'debit',
      startingBalance: 220,
      logoId: 'malaysia/grabpay',
      groupKey: 'everyday',
    },
    {
      name: 'Boost',
      type: 'debit',
      startingBalance: 140,
      logoId: 'malaysia/boost-bank',
      groupKey: 'everyday',
    },
    {
      name: 'Wise',
      type: 'debit',
      startingBalance: 1900,
      logoId: 'global/wise',
      groupKey: 'everyday',
    },
    {
      name: 'Rakuten Trade',
      type: 'debit',
      startingBalance: 7400,
      logoId: 'malaysia/rakuten-trade',
      groupKey: 'investing',
    },
    {
      name: 'CIMB Cash Rebate',
      type: 'credit',
      startingBalance: 640,
      logoId: 'malaysia/cimb',
      groupKey: 'credit',
    },
    {
      name: 'UOB One Card',
      type: 'credit',
      startingBalance: 920,
      logoId: 'malaysia/uob-malaysia',
      groupKey: 'credit',
    },
    {
      name: 'Hong Leong Wise Card',
      type: 'credit',
      startingBalance: 410,
      logoId: 'malaysia/hong-leong-bank',
      groupKey: 'credit',
    },
    {
      name: 'AEON Visa Card',
      type: 'credit',
      startingBalance: 280,
      logoId: 'malaysia/aeon-bank',
      groupKey: 'credit',
    },
  ],
  categories: MALAYSIAN_EN_CATEGORIES,
  career: [
    {
      durationMonths: 10,
      monthlySalary: 6800,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 42,
    },
    {
      durationMonths: 16,
      monthlySalary: 6100,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 48,
    },
    {
      durationMonths: 24,
      monthlySalary: 5400,
      hoursWorkedPerWeek: 46,
      commuteMinutesPerWorkday: 52,
    },
  ],
  budgets: {
    templateName: 'Monthly Budget',
    templateEmoji: '🎯',
    totalAmount: 5000,
    allocations: [
      { categoryKey: 'home', amount: 2250 },
      { categoryKey: 'food', amount: 1150 },
      { categoryKey: 'transport', amount: 520 },
      { categoryKey: 'lifestyle', amount: 620 },
      { categoryKey: 'health', amount: 260 },
    ],
    monthsToSeed: 6,
  },
  secondBudget: {
    templateName: 'Raya Month',
    templateEmoji: '🌙',
    totalAmount: 6500,
    allocations: [
      { categoryKey: 'home', amount: 2250 },
      { categoryKey: 'food', amount: 1300 },
      { categoryKey: 'family', amount: 1200 },
      { categoryKey: 'transport', amount: 700 },
      { categoryKey: 'lifestyle', amount: 700 },
    ],
    monthsToSeed: 0,
  },
  splits: [
    {
      merchant: 'Bak Kut Teh Klang',
      note: 'Makan session, I belanja first',
      categoryKey: 'dining',
      monthsAgo: 0,
      day: 13,
      account: 'card',
      selfShare: 32,
      participants: [
        { name: 'Wei Jie', share: 30, paid: true },
        { name: 'Farah', share: 28, paid: false },
        { name: 'Kumar', share: 31, paid: false },
      ],
    },
    {
      merchant: 'Langkawi Airbnb',
      note: 'Langkawi trip villa, split 4 ways',
      categoryKey: 'travel_root',
      monthsAgo: 4,
      day: 10,
      account: 'card',
      selfShare: 210,
      participants: [
        { name: 'Wei Jie', share: 210, paid: true },
        { name: 'Mei Ling', share: 210, paid: true },
        { name: 'Haziq', share: 210, paid: true },
      ],
    },
  ],
  recurring: {
    salary: { name: 'Gaji Masuk', amount: 6800, note: 'Gaji bulan ni' },
    rent: { name: 'Sewa Rumah', amount: 1850, note: 'Sewa kondo' },
    fitness: { name: 'Gym Bulanan', amount: 158, note: 'Anytime Fitness' },
    subscriptions: [
      { name: 'Astro Family Pack', amount: 89.9, note: 'Astro pakej family' },
      { name: 'Netflix', amount: 54.9, note: 'Netflix Premium' },
      { name: 'Spotify Family', amount: 23.9, note: 'Spotify Family' },
      { name: 'Disney+ Hotstar', amount: 19.9, note: 'Disney+ Hotstar' },
      { name: 'iCloud+', amount: 11.9, note: 'iCloud 200GB' },
    ],
    investment: { name: 'StashAway Auto-Debit', amount: 600, note: 'StashAway top-up bulanan' },
  },
  transactions: {
    merchants: {
      grocery: [
        "Lotus's Damansara",
        'Mydin USJ',
        'Jaya Grocer',
        'Village Grocer',
        '99 Speedmart',
        'AEON Big',
        'Cold Storage',
      ],
      dining: [
        'Mamak Pelita',
        "Devi's Corner mamak",
        'Nasi Kandar Pelita',
        'Restoran Yut Kee',
        'Old Town White Coffee',
        'The Chicken Rice Shop',
        'Bak Kut Teh Klang',
        'Char Kway Teow PJ',
        'Pavilion Food Republic',
        'Sushi King',
      ],
      coffee: [
        'ZUS Coffee drive-thru',
        'Starbucks KLCC',
        'Coffee Bean Pavilion',
        'Gigi Coffee',
        'Old Town kopitiam',
      ],
      fuel: ['Petronas pump', 'Shell Select', 'Petron RON95', 'BHPetrol'],
      shopping: [
        'Pavilion KL',
        'Mid Valley Megamall',
        '1 Utama',
        'Sunway Pyramid',
        'IKEA Damansara',
        'Uniqlo Mid Valley',
        'Mr DIY',
      ],
      entertainment: [
        'GSC Mid Valley',
        'TGV 1 Utama',
        'Sunway Lagoon',
        'Genting SkyWorlds',
        'Karaoke Manhattan',
        'Aquaria KLCC',
      ],
      rideshare: ['Grab Car', 'Grab Bike', 'AirAsia Ride', 'inDrive'],
      healthcare: [
        'Klinik Mediviron',
        'Watsons Pharmacy',
        'Guardian Pharmacy',
        'Caring Pharmacy',
        'KPJ checkup',
      ],
      hotels: ['Hilton KL', 'Berjaya Times Square', 'Sunway Resort', 'Genting First World'],
      flights: ['AirAsia', 'Malaysia Airlines', 'Batik Air', 'Firefly'],
    },
    notes: {
      salary: 'Gaji masuk dah',
      bonus: 'Year-end bonus',
      freelance: 'Side project',
      consulting: 'Advisory retainer',
      dividends: 'StashAway dividend',
      interest: 'FD interest',
      rent: 'Sewa kondo bulan ni',
      utilities: 'Letrik + air',
      internet: 'Unifi 500Mbps',
      fitness: 'Gym bulanan',
      homeSupplies: 'Tesco run, restock barang',
      subscriptions: ['Astro pakej family', 'Spotify Family', 'iCloud 200GB'],
      education: 'Udemy course, kepala panas',
      atmWithdrawal: 'ATM Maybank tarik tunai',
      parkingPrimary: 'Mall parking',
      parkingAlternate: 'TnG tol',
      savingsTransfer: 'Pindah masuk CIMB',
      investmentTransfer: 'StashAway top-up bulanan',
      travelTopUp: 'Tabung cuti-cuti',
      localTravel: 'KLIA Ekspres ke airport',
      tripDining: 'Trip makan-makan',
      holidayGifts: 'Duit raya bagi sedara',
      familyCelebration: 'CNY reunion makan',
      cardPayment: 'Bayar credit card',
    },
    subscriptions: [69.9, 19.9, 12],
    income: {
      bonusBase: 1850,
      bonusGrowth: 28,
      bonusSpread: 240,
      freelanceBase: 620,
      freelanceGrowth: 14,
      freelanceSpread: 160,
      consultingBase: 380,
      consultingStep: 70,
      consultingSpread: 110,
      dividendsBase: 78,
      dividendsGrowth: 3,
      dividendsSpread: 22,
      interestBase: 26,
      interestGrowth: 0.8,
      interestSpread: 7,
    },
    housing: {
      rentBase: 1850,
      rentGrowth: 2,
      rentSpread: 25,
      utilitiesBase: 168,
      utilitiesSpread: 32,
      internetBase: 139,
      internetSpread: 8,
      fitnessBase: 158,
      fitnessSpread: 6,
      homeSuppliesBase: 78,
      homeSuppliesSpread: 28,
      healthcareBase: 145,
      healthcareSpread: 50,
      educationBase: 180,
      educationSpread: 60,
    },
    weekly: {
      cashTopUpFourWeek: 360,
      cashTopUpFiveWeek: 440,
      cashTopUpSpread: 40,
      groceryBase: 165,
      groceryWeekStep: 8,
      grocerySpread: 32,
      diningBase: 95,
      diningWeekStep: 6,
      diningSpread: 28,
      coffeeBase: 13.5,
      coffeeSpread: 4,
      fuelBase: 110,
      fuelSpread: 22,
      parkingPrimaryBase: 14,
      parkingPrimarySpread: 5,
      parkingAlternateBase: 6.5,
      parkingAlternateSpread: 2.5,
    },
    lifestyle: {
      shoppingBase: 145,
      shoppingTripStep: 55,
      shoppingSpread: 60,
      entertainmentBase: 78,
      entertainmentTripStep: 36,
      entertainmentSpread: 28,
      rideshareBase: 32,
      rideshareSpread: 12,
    },
    transfers: {
      savingsBase: 850,
      savingsGrowth: 22,
      savingsSpread: 80,
      investmentBase: 600,
      investmentGrowth: 18,
      investmentSpread: 60,
      travelBase: 220,
      travelPeak: 620,
      travelSpread: 70,
      cardPaymentRatio: 0.96,
    },
    travel: {
      months: [3, 11],
      giftMonth: 1,
      flightsBase: 720,
      flightsSpread: 180,
      hotelsBase: 980,
      hotelsSpread: 220,
      localTransitBase: 96,
      localTransitSpread: 28,
      diningBase: 165,
      diningSpread: 45,
      holidayGiftsBase: 680,
      holidayGiftsSpread: 180,
      familyCelebrationBase: 420,
      familyCelebrationSpread: 110,
    },
    extras: {
      weekendBrunchCount: 3,
      weekendBrunchBase: 48,
      weekendBrunchSpread: 18,
      weekendBrunchMerchants: [
        'PappaRich brunch',
        'Old Town kopitiam',
        'Yut Kee weekend',
        "Devi's Corner roti",
        'Antipodean Bangsar',
      ],
      weekendBrunchNote: 'Sunday brunch session',
      bubbleTeaCount: 5,
      bubbleTeaBase: 14.5,
      bubbleTeaSpread: 4,
      bubbleTeaMerchants: ['Tealive', 'Chagee', 'Gong Cha', 'Sharetea', 'Coco Fresh'],
      hangoutBase: 95,
      hangoutSpread: 35,
      hangoutMerchants: [
        'Bangsar yumcha',
        'TREC KL lepak',
        'PJ Mamak supper',
        'Jalan Alor street food',
        'Cheras kopitiam lim teh',
      ],
      hangoutNote: 'Yumcha lepak session',
      deliveryCount: 4,
      deliveryBase: 32,
      deliverySpread: 12,
      deliveryMerchants: ['GrabFood tapau', 'foodpanda', 'ShopeeFood promo', 'McDelivery midnight'],
      deliveryNote: 'Tapau supper, malas masak',
      rideshareExtraCount: 3,
      rideshareExtraBase: 22,
      rideshareExtraSpread: 9,
      convenienceCount: 6,
      convenienceBase: 18,
      convenienceSpread: 7,
      convenienceMerchants: ['7-Eleven', 'Family Mart', 'KK Super Mart', 'MyNews', 'Speedmart 99'],
    },
  },
  albums: [
    {
      name: 'Bali Trip',
      placeName: 'Bali',
      placeAdmin: 'Indonesia',
      countryCode: 'ID',
      latitude: -8.4095,
      longitude: 115.1889,
      currencyCode: 'IDR',
      fxRate: 3550,
    },
    {
      name: 'Tokyo Holiday',
      placeName: 'Tokyo',
      placeAdmin: 'Japan',
      countryCode: 'JP',
      latitude: 35.6762,
      longitude: 139.6503,
      currencyCode: 'JPY',
      fxRate: 33,
    },
    {
      name: 'Bangkok Weekend',
      placeName: 'Bangkok',
      placeAdmin: 'Thailand',
      countryCode: 'TH',
      latitude: 13.7563,
      longitude: 100.5018,
      currencyCode: 'THB',
      fxRate: 7.6,
    },
    {
      name: 'Langkawi Getaway',
      placeName: 'Langkawi',
      placeAdmin: 'Kedah',
      countryCode: 'MY',
      latitude: 6.35,
      longitude: 99.8,
      currencyCode: 'MYR',
      fxRate: 1,
    },
  ],
  items: [
    {
      name: 'iPhone 15 Pro',
      iconId: 'smartphone',
      purchaseMonthsAgo: 12,
      purchaseDay: 21,
      purchasePrice: 5499,
      note: 'Natural Titanium 256GB',
    },
    {
      name: 'ASUS Zenbook 14',
      iconId: 'laptop',
      purchaseMonthsAgo: 18,
      purchaseDay: 7,
      purchasePrice: 4999,
    },
    {
      name: 'Sony WH-1000XM5',
      iconId: 'headphones',
      purchaseMonthsAgo: 8,
      purchaseDay: 15,
      purchasePrice: 1799,
    },
    {
      name: 'Apple Watch S9',
      iconId: 'smartwatch',
      purchaseMonthsAgo: 10,
      purchaseDay: 2,
      purchasePrice: 1899,
    },
    {
      name: 'DJI Osmo Pocket 3',
      iconId: 'action-camera',
      purchaseMonthsAgo: 9,
      purchaseDay: 24,
      purchasePrice: 2199,
      note: 'Travel vlogging',
    },
    {
      name: 'Dyson V12 Detect',
      iconId: 'cordless-vacuum',
      purchaseMonthsAgo: 21,
      purchaseDay: 12,
      purchasePrice: 2799,
    },
    {
      name: 'Nintendo Switch OLED',
      iconId: 'handheld-game-console',
      purchaseMonthsAgo: 27,
      purchaseDay: 5,
      purchasePrice: 1299,
    },
    {
      name: 'iPhone 12 (sold)',
      iconId: 'smartphone',
      purchaseMonthsAgo: 36,
      purchaseDay: 16,
      purchasePrice: 3199,
      retiredMonthsAgo: 12,
      salePrice: 900,
      note: 'Sold to upgrade',
    },
  ],
};
