import type { CategoryNames, PreviewProfile } from '../shared';

// Malaysian Chinese vernacular: local terms Malaysians actually use — 巴刹
// (pasar), 入油 (pump petrol), 屋租, 花红 (bonus), Gaji, Unifi, Grab, 青包.
const MALAYSIAN_ZH_CATEGORIES: CategoryNames = {
  home: '住家',
  rent: '屋租',
  utilities: '水电费',
  internet: 'Unifi 上网',
  home_supplies: '家用',
  food: '吃喝',
  groceries: '巴刹买菜',
  dining: '出外食',
  coffee: 'Kopi 茶水',
  transport: '交通',
  fuel: '入油',
  rideshare: 'Grab 叫车',
  parking: '过路费 / 泊车',
  lifestyle: '生活',
  shopping: '购物',
  entertainment: '娱乐',
  subscriptions: '订阅',
  health: '健康',
  healthcare: '诊所药房',
  fitness: '健身',
  travel_root: 'Cuti 旅游',
  flights: '机票',
  hotels: '酒店',
  local_travel: '当地交通',
  family: '家人',
  gifts: '青包礼物',
  education: '上课',
  salary_root: '薪水',
  salary: 'Gaji 入账',
  bonus: '花红',
  side_root: '副业',
  freelance: '自由接案',
  consulting: '顾问',
  invest_root: '投资',
  dividends: '股息',
  interest: '定期利息',
};

export const malaysianZhProfile: PreviewProfile = {
  seed: 20260424,
  locale: 'zh',
  currencyCode: 'MYR',
  currencySymbol: 'RM',
  profileName: '陈慧敏',
  accountGroups: {
    everyday: '日常',
    goals: '目标',
    credit: '信用',
    investing: '投资',
  },
  accounts: {
    checking: { name: '马银行', startingBalance: 4850, logoId: 'malaysia/maybank' },
    savings: { name: '联昌定期', startingBalance: 28600, logoId: 'malaysia/cimb' },
    travel: { name: 'Cuti 基金', startingBalance: 2400, logoId: 'malaysia/hsbc-malaysia' },
    card: { name: '马银行信用卡', startingBalance: 320, logoId: 'malaysia/maybank' },
    cash: { name: '钱包现金', startingBalance: 180, logoId: 'malaysia/touch-n-go-ewallet' },
    brokerage: { name: 'StashAway', startingBalance: 16800, logoId: 'malaysia/stashaway' },
  },
  extraAccounts: [
    {
      name: 'GrabPay',
      type: 'debit',
      startingBalance: 220,
      logoId: 'malaysia/grabpay',
      groupKey: 'everyday',
    },
    {
      name: 'Boost',
      type: 'debit',
      startingBalance: 140,
      logoId: 'malaysia/boost-bank',
      groupKey: 'everyday',
    },
    {
      name: 'Wise',
      type: 'debit',
      startingBalance: 1900,
      logoId: 'global/wise',
      groupKey: 'everyday',
    },
    {
      name: 'Rakuten Trade',
      type: 'debit',
      startingBalance: 7400,
      logoId: 'malaysia/rakuten-trade',
      groupKey: 'investing',
    },
    {
      name: '联昌现金回扣卡',
      type: 'credit',
      startingBalance: 640,
      logoId: 'malaysia/cimb',
      groupKey: 'credit',
    },
    {
      name: 'UOB One 卡',
      type: 'credit',
      startingBalance: 920,
      logoId: 'malaysia/uob-malaysia',
      groupKey: 'credit',
    },
    {
      name: '丰隆 Wise 卡',
      type: 'credit',
      startingBalance: 410,
      logoId: 'malaysia/hong-leong-bank',
      groupKey: 'credit',
    },
    {
      name: 'AEON 信用卡',
      type: 'credit',
      startingBalance: 280,
      logoId: 'malaysia/aeon-bank',
      groupKey: 'credit',
    },
  ],
  categories: MALAYSIAN_ZH_CATEGORIES,
  career: [
    {
      durationMonths: 10,
      monthlySalary: 6800,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 42,
    },
    {
      durationMonths: 16,
      monthlySalary: 6100,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 48,
    },
    {
      durationMonths: 24,
      monthlySalary: 5400,
      hoursWorkedPerWeek: 46,
      commuteMinutesPerWorkday: 52,
    },
  ],
  budgets: {
    templateName: '每月预算',
    templateEmoji: '🎯',
    totalAmount: 5000,
    allocations: [
      { categoryKey: 'home', amount: 2250 },
      { categoryKey: 'food', amount: 1150 },
      { categoryKey: 'transport', amount: 520 },
      { categoryKey: 'lifestyle', amount: 620 },
      { categoryKey: 'health', amount: 260 },
    ],
    monthsToSeed: 6,
  },
  secondBudget: {
    templateName: '过年月',
    templateEmoji: '🧧',
    totalAmount: 6500,
    allocations: [
      { categoryKey: 'home', amount: 2250 },
      { categoryKey: 'food', amount: 1300 },
      { categoryKey: 'family', amount: 1200 },
      { categoryKey: 'transport', amount: 700 },
      { categoryKey: 'lifestyle', amount: 700 },
    ],
    monthsToSeed: 0,
  },
  splits: [
    {
      merchant: '巴生肉骨茶',
      note: '朋友聚餐，我先 belanja',
      categoryKey: 'dining',
      monthsAgo: 0,
      day: 13,
      account: 'card',
      selfShare: 32,
      participants: [
        { name: '伟杰', share: 30, paid: true },
        { name: 'Farah', share: 28, paid: false },
        { name: '阿明', share: 31, paid: false },
      ],
    },
    {
      merchant: '浮罗交怡民宿',
      note: '浮罗交怡旅行住宿，四人平摊',
      categoryKey: 'travel_root',
      monthsAgo: 4,
      day: 10,
      account: 'card',
      selfShare: 210,
      participants: [
        { name: '伟杰', share: 210, paid: true },
        { name: '美玲', share: 210, paid: true },
        { name: '志豪', share: 210, paid: true },
      ],
    },
  ],
  recurring: {
    salary: { name: 'Gaji 入账', amount: 6800, note: '这个月 gaji' },
    rent: { name: '屋租', amount: 1850, note: '公寓屋租' },
    fitness: { name: '健身月费', amount: 158, note: 'Anytime Fitness' },
    subscriptions: [
      { name: 'Astro 家庭配套', amount: 89.9, note: 'Astro 家庭配套' },
      { name: 'Netflix', amount: 54.9, note: 'Netflix 高级版' },
      { name: 'Spotify 家庭版', amount: 23.9, note: 'Spotify Family' },
      { name: 'Disney+ Hotstar', amount: 19.9, note: 'Disney+ Hotstar' },
      { name: 'iCloud+', amount: 11.9, note: 'iCloud 200GB' },
    ],
    investment: { name: 'StashAway 月供', amount: 600, note: 'StashAway 每月供款' },
  },
  transactions: {
    merchants: {
      grocery: [
        '永旺 AEON',
        "Lotus's 莲花",
        '巨人 Giant',
        'Mydin 美丹',
        'Jaya Grocer',
        '99 速达',
        '巴刹买菜',
      ],
      dining: [
        '茨厂街云吞面',
        '巴生肉骨茶',
        '海南鸡饭档',
        '槟城炒粿条',
        '嘛嘛档 Mamak',
        'Devi 印度煎饼',
        '旧街场白咖啡',
        '茶餐室经济饭',
        '寿司王',
        'PJ 大牌档',
      ],
      coffee: ['ZUS 咖啡', '星巴克 KLCC', 'Coffee Bean', '茶餐室 lim kopi', '老街场早茶'],
      fuel: ['Petronas 国油', 'Shell 壳牌', 'Petron 95', 'BHPetrol'],
      shopping: [
        'Pavilion 柏威年',
        'Mid Valley 谷中城',
        '1 Utama 万达广场',
        'Sunway Pyramid 双威',
        'IKEA 宜家',
        '屈臣氏 Watsons',
        'Uniqlo',
        'Mr DIY',
      ],
      entertainment: [
        'GSC 金狮戏院',
        'TGV 戏院',
        '云顶 Genting',
        'Sunway Lagoon 水上乐园',
        'Aquaria 水族馆',
        'KTV 包厢',
      ],
      rideshare: ['Grab 召车', 'Grab Bike 摩多', 'AirAsia Ride', '德士'],
      healthcare: ['私人诊所', '屈臣氏药房', 'Guardian 药房', 'Caring 康宁药剂', 'KPJ 检查'],
      hotels: ['希尔顿 KL', '云顶第一酒店', 'Sunway 度假村', 'Berjaya 时代广场'],
      flights: ['亚航 AirAsia', '马航 MAS', '萤火虫 Firefly', 'Batik Air'],
    },
    notes: {
      salary: 'Gaji 入账啦',
      bonus: '年终花红',
      freelance: '副业进账',
      consulting: '顾问 fee',
      dividends: 'StashAway 派息',
      interest: '定期利息',
      rent: '公寓屋租',
      utilities: 'TNB + 水费',
      internet: 'Unifi 500Mbps',
      fitness: 'Anytime Fitness 月费',
      homeSupplies: '巴刹补货 + 日用品',
      subscriptions: ['Astro 家庭配套', 'Spotify 家庭', 'iCloud 200GB'],
      education: 'Udemy 课程',
      atmWithdrawal: '马银行 ATM 提款',
      parkingPrimary: '商场泊车',
      parkingAlternate: 'TnG 过路费',
      savingsTransfer: '过账去 CIMB 储蓄',
      investmentTransfer: 'StashAway 月供款',
      travelTopUp: 'Cuti-cuti 基金',
      localTravel: 'KLIA Ekspres 快铁',
      tripDining: '旅行 yumcha',
      holidayGifts: 'Hari Raya duit raya',
      familyCelebration: '新年团圆饭',
      cardPayment: '还信用卡',
    },
    subscriptions: [69.9, 19.9, 12],
    income: {
      bonusBase: 1850,
      bonusGrowth: 28,
      bonusSpread: 240,
      freelanceBase: 620,
      freelanceGrowth: 14,
      freelanceSpread: 160,
      consultingBase: 380,
      consultingStep: 70,
      consultingSpread: 110,
      dividendsBase: 78,
      dividendsGrowth: 3,
      dividendsSpread: 22,
      interestBase: 26,
      interestGrowth: 0.8,
      interestSpread: 7,
    },
    housing: {
      rentBase: 1850,
      rentGrowth: 2,
      rentSpread: 25,
      utilitiesBase: 168,
      utilitiesSpread: 32,
      internetBase: 139,
      internetSpread: 8,
      fitnessBase: 158,
      fitnessSpread: 6,
      homeSuppliesBase: 78,
      homeSuppliesSpread: 28,
      healthcareBase: 145,
      healthcareSpread: 50,
      educationBase: 180,
      educationSpread: 60,
    },
    weekly: {
      cashTopUpFourWeek: 360,
      cashTopUpFiveWeek: 440,
      cashTopUpSpread: 40,
      groceryBase: 165,
      groceryWeekStep: 8,
      grocerySpread: 32,
      diningBase: 95,
      diningWeekStep: 6,
      diningSpread: 28,
      coffeeBase: 13.5,
      coffeeSpread: 4,
      fuelBase: 110,
      fuelSpread: 22,
      parkingPrimaryBase: 14,
      parkingPrimarySpread: 5,
      parkingAlternateBase: 6.5,
      parkingAlternateSpread: 2.5,
    },
    lifestyle: {
      shoppingBase: 145,
      shoppingTripStep: 55,
      shoppingSpread: 60,
      entertainmentBase: 78,
      entertainmentTripStep: 36,
      entertainmentSpread: 28,
      rideshareBase: 32,
      rideshareSpread: 12,
    },
    transfers: {
      savingsBase: 850,
      savingsGrowth: 22,
      savingsSpread: 80,
      investmentBase: 600,
      investmentGrowth: 18,
      investmentSpread: 60,
      travelBase: 220,
      travelPeak: 620,
      travelSpread: 70,
      cardPaymentRatio: 0.96,
    },
    travel: {
      months: [3, 11],
      giftMonth: 1,
      flightsBase: 720,
      flightsSpread: 180,
      hotelsBase: 980,
      hotelsSpread: 220,
      localTransitBase: 96,
      localTransitSpread: 28,
      diningBase: 165,
      diningSpread: 45,
      holidayGiftsBase: 680,
      holidayGiftsSpread: 180,
      familyCelebrationBase: 420,
      familyCelebrationSpread: 110,
    },
    extras: {
      weekendBrunchCount: 3,
      weekendBrunchBase: 48,
      weekendBrunchSpread: 18,
      weekendBrunchMerchants: [
        'PappaRich 早茶',
        '旧街场早餐',
        '点心餐室',
        'Devi 印度煎饼',
        '茶餐室 brunch',
      ],
      weekendBrunchNote: '周末 yumcha',
      bubbleTeaCount: 5,
      bubbleTeaBase: 14.5,
      bubbleTeaSpread: 4,
      bubbleTeaMerchants: ['Tealive', '霸王茶姬 Chagee', '贡茶', 'Sharetea', 'Coco 都可'],
      hangoutBase: 95,
      hangoutSpread: 35,
      hangoutMerchants: [
        '孟沙 Bangsar bar',
        'TREC KL lepak',
        'PJ 嘛嘛档宵夜',
        '茨厂街夜市',
        'Cheras 茶餐室',
      ],
      hangoutNote: 'Yumcha lepak 时间',
      deliveryCount: 4,
      deliveryBase: 32,
      deliverySpread: 12,
      deliveryMerchants: ['GrabFood 打包', 'foodpanda', 'ShopeeFood 优惠', 'McDelivery 宵夜'],
      deliveryNote: 'Tapau 宵夜，懒得煮',
      rideshareExtraCount: 3,
      rideshareExtraBase: 22,
      rideshareExtraSpread: 9,
      convenienceCount: 6,
      convenienceBase: 18,
      convenienceSpread: 7,
      convenienceMerchants: ['7-Eleven', 'Family Mart', 'KK 超市', 'MyNews', '99 速达'],
    },
  },
  albums: [
    {
      name: '巴厘岛之旅',
      placeName: '巴厘岛',
      placeAdmin: '印尼',
      countryCode: 'ID',
      latitude: -8.4095,
      longitude: 115.1889,
      currencyCode: 'IDR',
      fxRate: 3550,
    },
    {
      name: '东京假期',
      placeName: '东京',
      placeAdmin: '日本',
      countryCode: 'JP',
      latitude: 35.6762,
      longitude: 139.6503,
      currencyCode: 'JPY',
      fxRate: 33,
    },
    {
      name: '曼谷周末游',
      placeName: '曼谷',
      placeAdmin: '泰国',
      countryCode: 'TH',
      latitude: 13.7563,
      longitude: 100.5018,
      currencyCode: 'THB',
      fxRate: 7.6,
    },
    {
      name: '浮罗交怡',
      placeName: '浮罗交怡',
      placeAdmin: '吉打',
      countryCode: 'MY',
      latitude: 6.35,
      longitude: 99.8,
      currencyCode: 'MYR',
      fxRate: 1,
    },
  ],
  items: [
    {
      name: 'iPhone 15 Pro',
      iconId: 'smartphone',
      purchaseMonthsAgo: 12,
      purchaseDay: 21,
      purchasePrice: 5499,
      note: '原色钛金属 256G',
    },
    {
      name: '华硕 Zenbook 14',
      iconId: 'laptop',
      purchaseMonthsAgo: 18,
      purchaseDay: 7,
      purchasePrice: 4999,
    },
    {
      name: '索尼 WH-1000XM5',
      iconId: 'headphones',
      purchaseMonthsAgo: 8,
      purchaseDay: 15,
      purchasePrice: 1799,
    },
    {
      name: 'Apple Watch S9',
      iconId: 'smartwatch',
      purchaseMonthsAgo: 10,
      purchaseDay: 2,
      purchasePrice: 1899,
    },
    {
      name: '大疆 Osmo Pocket 3',
      iconId: 'action-camera',
      purchaseMonthsAgo: 9,
      purchaseDay: 24,
      purchasePrice: 2199,
      note: '旅行 vlog',
    },
    {
      name: '戴森 V12 吸尘器',
      iconId: 'cordless-vacuum',
      purchaseMonthsAgo: 21,
      purchaseDay: 12,
      purchasePrice: 2799,
    },
    {
      name: '任天堂 Switch OLED',
      iconId: 'handheld-game-console',
      purchaseMonthsAgo: 27,
      purchaseDay: 5,
      purchasePrice: 1299,
    },
    {
      name: 'iPhone 12（已出）',
      iconId: 'smartphone',
      purchaseMonthsAgo: 36,
      purchaseDay: 16,
      purchasePrice: 3199,
      retiredMonthsAgo: 12,
      salePrice: 900,
      note: '升级后转卖',
    },
  ],
};
