import { buildLocalizedProfile } from './localized';

// Malaysia in Bahasa Melayu: same household as the English and Chinese
// Malaysian profiles, written the way a Malay speaker would log it.
export const malaysianMsProfile = buildLocalizedProfile({
  seed: 20260412,
  locale: 'ms',
  currencyCode: 'MYR',
  currencySymbol: 'RM',
  priceScale: 1,
  decimals: 2,
  monthlySalary: 6800,
  monthlyRent: 1850,
  profileName: 'Nurul Aisyah',
  accountGroups: {
    everyday: 'Harian',
    goals: 'Matlamat',
    credit: 'Kredit',
    investing: 'Pelaburan',
  },
  accounts: {
    checking: { name: 'Maybank2u', logoId: 'malaysia/maybank' },
    savings: { name: 'Simpanan Bank Islam', logoId: 'malaysia/bank-islam' },
    travel: { name: 'Tabung Cuti', logoId: 'malaysia/bank-rakyat' },
    card: { name: 'Kad Kredit CIMB', logoId: 'malaysia/cimb' },
    cash: { name: "Touch 'n Go", logoId: 'malaysia/touch-n-go-ewallet' },
    brokerage: { name: 'StashAway', logoId: 'malaysia/stashaway' },
  },
  extraAccounts: [
    { name: 'GrabPay', type: 'debit', logoId: 'malaysia/grabpay', groupKey: 'everyday' },
    { name: 'RHB', type: 'debit', logoId: 'malaysia/rhb-bank', groupKey: 'everyday' },
    { name: 'Public Bank', type: 'debit', logoId: 'malaysia/public-bank', groupKey: 'everyday' },
    { name: 'Kad Maybank Ikhwan', type: 'credit', logoId: 'malaysia/maybank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Rumah',
    rent: 'Sewa',
    utilities: 'Elektrik & Air',
    internet: 'Internet',
    home_supplies: 'Barang Rumah',
    food: 'Makanan',
    groceries: 'Barang Dapur',
    dining: 'Makan Luar',
    coffee: 'Kopi & Teh',
    transport: 'Pengangkutan',
    fuel: 'Minyak',
    rideshare: 'Grab',
    parking: 'Tol & Parking',
    lifestyle: 'Gaya Hidup',
    shopping: 'Membeli-belah',
    entertainment: 'Hiburan',
    subscriptions: 'Langganan',
    health: 'Kesihatan',
    healthcare: 'Klinik & Farmasi',
    fitness: 'Gim',
    travel_root: 'Melancong',
    flights: 'Penerbangan',
    hotels: 'Hotel',
    local_travel: 'Pengangkutan Awam',
    family: 'Keluarga',
    gifts: 'Duit Raya & Hadiah',
    education: 'Kursus',
    salary_root: 'Gaji',
    salary: 'Gaji',
    bonus: 'Bonus',
    side_root: 'Kerja Sampingan',
    freelance: 'Bebas',
    consulting: 'Perundingan',
    invest_root: 'Pelaburan',
    dividends: 'Dividen',
    interest: 'Faedah FD',
  },
  budgetName: 'Bajet Bulanan',
  split: {
    merchant: 'Nasi Kandar Pelita',
    note: 'Makan malam, saya bayar dulu',
    people: ['Hafiz', 'Siti', 'Arif'],
  },
  recurring: {
    salary: { name: 'Gaji Bulanan', note: 'Gaji masuk' },
    rent: { name: 'Sewa Rumah', note: 'Sewa kondo' },
    fitness: { name: 'Yuran Gim', amount: 158, note: 'Anytime Fitness' },
    subscriptions: [
      { name: 'Astro', amount: 89.9, note: 'Pakej keluarga', logoId: 'malaysia/astro' },
      { name: 'Netflix', amount: 54.9, note: 'Netflix Premium' },
      { name: 'Spotify', amount: 23.9, note: 'Spotify Family' },
      { name: 'Disney+ Hotstar', amount: 19.9, note: 'Disney+ Hotstar' },
      { name: 'iCloud+', amount: 11.9, note: 'iCloud 200GB' },
    ],
    investment: { name: 'Simpanan ASB', note: 'Simpan setiap bulan' },
  },
  merchants: {
    grocery: ["Lotus's", 'Mydin', 'Jaya Grocer', '99 Speedmart', 'AEON Big'],
    dining: [
      'Nasi Kandar Pelita',
      'Restoran Kak Wok',
      'Mamak Ali',
      'Nasi Lemak Wanjo',
      'Sate Kajang',
    ],
    coffee: ['ZUS Coffee', 'Kopi Tenggiri', 'Tealive', 'Gigi Coffee'],
    fuel: ['Petronas', 'Shell', 'BHPetrol'],
    shopping: ['Mid Valley', 'Sunway Pyramid', 'Mr DIY', 'Shopee'],
    entertainment: ['GSC Mid Valley', 'TGV Sunway', 'Sunway Lagoon'],
    rideshare: ['Grab', 'AirAsia Ride'],
    healthcare: ['Klinik Mediviron', 'Watsons', 'Guardian'],
    hotels: ['Hotel Langkawi', 'Resort Cherating'],
    flights: ['AirAsia', 'Malaysia Airlines'],
    delivery: ['GrabFood', 'foodpanda', 'ShopeeFood'],
    convenience: ['7-Eleven', 'KK Mart', 'myNEWS'],
  },
  notes: {
    salary: 'Gaji bulanan',
    bonus: 'Bonus akhir tahun',
    freelance: 'Projek sampingan',
    consulting: 'Yuran perundingan',
    dividends: 'Dividen ASB',
    interest: 'Faedah simpanan',
    rent: 'Sewa bulan ini',
    utilities: 'Bil elektrik & air',
    internet: 'Unifi',
    fitness: 'Yuran gim',
    homeSupplies: 'Barang rumah',
    subscriptions: ['Astro', 'Spotify', 'iCloud'],
    education: 'Kursus dalam talian',
    atmWithdrawal: 'Keluar duit ATM',
    parkingPrimary: 'Parking mall',
    parkingAlternate: 'Tol',
    savingsTransfer: 'Pindah ke simpanan',
    investmentTransfer: 'Simpanan ASB',
    travelTopUp: 'Tabung cuti',
    localTravel: 'KLIA Ekspres',
    tripDining: 'Makan masa bercuti',
    holidayGifts: 'Duit raya',
    familyCelebration: 'Kenduri keluarga',
    cardPayment: 'Bayar kad kredit',
  },
});
