import { buildLocalizedProfile } from './localized';

export const norwegianProfile = buildLocalizedProfile({
  seed: 20260507,
  locale: 'nb',
  currencyCode: 'NOK',
  currencySymbol: 'kr',
  priceScale: 4.8,
  decimals: 2,
  monthlySalary: 58000,
  monthlyRent: 14000,
  profileName: 'Ingrid Hansen',
  accountGroups: { everyday: 'Hverdag', goals: 'Mål', credit: 'Kreditt', investing: 'Investering' },
  accounts: {
    checking: { name: 'DNB Brukskonto', logoId: 'norway/dnb' },
    savings: { name: 'SpareBank 1 Sparekonto', logoId: 'norway/sparebank-1' },
    travel: { name: 'Feriesparing', logoId: 'norway/sbanken' },
    card: { name: 'Bank Norwegian Kort', logoId: 'norway/bank-norwegian' },
    cash: { name: 'Kontanter', logoId: 'global/visa' },
    brokerage: { name: 'Nordnet ASK', logoId: 'global/saxo' },
  },
  extraAccounts: [
    { name: 'Gjensidige Bank', type: 'debit', logoId: 'norway/gjensidige', groupKey: 'everyday' },
    { name: 'Handelsbanken', type: 'debit', logoId: 'norway/handelsbanken', groupKey: 'everyday' },
    { name: 'Storebrand', type: 'debit', logoId: 'norway/storebrand', groupKey: 'investing' },
    { name: 'Instabank Kort', type: 'credit', logoId: 'norway/instabank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Bolig',
    rent: 'Husleie',
    utilities: 'Strøm & vann',
    internet: 'Internett',
    home_supplies: 'Husholdning',
    food: 'Mat',
    groceries: 'Dagligvarer',
    dining: 'Restaurant',
    coffee: 'Kaffe',
    transport: 'Transport',
    fuel: 'Drivstoff',
    rideshare: 'Taxi',
    parking: 'Parkering & bom',
    lifestyle: 'Fritid',
    shopping: 'Shopping',
    entertainment: 'Underholdning',
    subscriptions: 'Abonnementer',
    health: 'Helse',
    healthcare: 'Apotek & lege',
    fitness: 'Trening',
    travel_root: 'Reise',
    flights: 'Fly',
    hotels: 'Hotell',
    local_travel: 'Kollektivtransport',
    family: 'Familie',
    gifts: 'Gaver',
    education: 'Kurs',
    salary_root: 'Lønn',
    salary: 'Lønn',
    bonus: 'Bonus',
    side_root: 'Ekstrajobb',
    freelance: 'Frilans',
    consulting: 'Rådgivning',
    invest_root: 'Investeringer',
    dividends: 'Utbytte',
    interest: 'Renter',
  },
  budgetName: 'Månedsbudsjett',
  split: {
    merchant: 'Lofoten Fiskerestaurant',
    note: 'Middag med venner, jeg la ut',
    people: ['Jakob', 'Nora', 'Emil'],
  },
  recurring: {
    salary: { name: 'Lønn', note: 'Månedslønn' },
    rent: { name: 'Husleie', note: 'Husleie leilighet' },
    fitness: { name: 'Treningssenter', amount: 449, note: 'SATS', logoId: 'norway/sats' },
    subscriptions: [
      { name: 'Netflix', amount: 159, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 129, note: 'Spotify Premium' },
      { name: 'TV 2 Play', amount: 149, note: 'TV 2 Play', logoId: 'norway/tv2-play' },
      { name: 'Viaplay', amount: 199, note: 'Viaplay', logoId: 'denmark/viaplay' },
      { name: 'iCloud+', amount: 39, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Fondsparing', note: 'Indeksfond' },
  },
  merchants: {
    grocery: ['Rema 1000', 'Kiwi', 'Meny', 'Coop Extra', 'Oda'],
    dining: ['Lofoten Fiskerestaurant', 'Peppes Pizza', 'Egon', 'Mathallen Oslo', 'Burger Joint'],
    coffee: ['Kaffebrenneriet', 'Espresso House', 'Tim Wendelboe', 'Joe & The Juice'],
    fuel: ['Circle K', 'Esso', 'Uno-X'],
    shopping: ['Elkjøp', 'Komplett', 'XXL', 'IKEA'],
    entertainment: ['Odeon Kino', 'Nationaltheatret', 'Ticketmaster'],
    rideshare: ['Oslo Taxi', 'Bolt'],
    healthcare: ['Apotek 1', 'Fastlegen', 'Vitusapotek'],
    hotels: ['Thon Hotel', 'Scandic'],
    flights: ['Norwegian', 'SAS'],
    delivery: ['Foodora', 'Wolt', 'Oda'],
    convenience: ['Narvesen', '7-Eleven', 'Joker'],
  },
  notes: {
    salary: 'Lønn',
    bonus: 'Årsbonus',
    freelance: 'Frilansoppdrag',
    consulting: 'Rådgivning',
    dividends: 'Utbytte fond',
    interest: 'Sparerente',
    rent: 'Husleie',
    utilities: 'Strøm & vann',
    internet: 'Telenor fiber',
    fitness: 'SATS',
    homeSupplies: 'Husholdningsartikler',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Nettkurs',
    atmWithdrawal: 'Tatt ut kontanter',
    parkingPrimary: 'Parkeringshus',
    parkingAlternate: 'Bompenger',
    savingsTransfer: 'Til sparekonto',
    investmentTransfer: 'Fondsparing',
    travelTopUp: 'Feriesparing',
    localTravel: 'Flytoget',
    tripDining: 'Mat på ferie',
    holidayGifts: 'Julegaver',
    familyCelebration: 'Familieselskap',
    cardPayment: 'Kredittkort nedbetalt',
  },
});
