import { buildLocalizedProfile } from './localized';

export const polishProfile = buildLocalizedProfile({
  seed: 20260509,
  locale: 'pl',
  currencyCode: 'PLN',
  currencySymbol: 'zł',
  priceScale: 1,
  decimals: 2,
  monthlySalary: 9500,
  monthlyRent: 3200,
  profileName: 'Zofia Kowalska',
  accountGroups: {
    everyday: 'Codzienne',
    goals: 'Cele',
    credit: 'Kredyt',
    investing: 'Inwestycje',
  },
  accounts: {
    checking: { name: 'Konto mBank', logoId: 'poland/mbank' },
    savings: { name: 'Oszczędności Millennium', logoId: 'poland/bank-millennium' },
    travel: { name: 'Skarbonka wakacje', logoId: 'poland/alior-bank' },
    card: { name: 'Karta Citi Handlowy', logoId: 'poland/citi-handlowy' },
    cash: { name: 'Gotówka', logoId: 'global/visa' },
    brokerage: { name: 'XTB', logoId: 'global/xtb' },
  },
  extraAccounts: [
    { name: 'BLIK', type: 'debit', logoId: 'poland/blik', groupKey: 'everyday' },
    { name: 'Revolut', type: 'debit', logoId: 'global/revolut', groupKey: 'everyday' },
    { name: 'Nest Bank', type: 'debit', logoId: 'poland/nest-bank', groupKey: 'goals' },
    { name: 'Karta Plus Bank', type: 'credit', logoId: 'poland/plus-bank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Dom',
    rent: 'Czynsz',
    utilities: 'Prąd i woda',
    internet: 'Internet',
    home_supplies: 'Chemia domowa',
    food: 'Jedzenie',
    groceries: 'Zakupy spożywcze',
    dining: 'Restauracje',
    coffee: 'Kawa',
    transport: 'Transport',
    fuel: 'Paliwo',
    rideshare: 'Taxi',
    parking: 'Parking',
    lifestyle: 'Rozrywka',
    shopping: 'Zakupy',
    entertainment: 'Kino i wyjścia',
    subscriptions: 'Subskrypcje',
    health: 'Zdrowie',
    healthcare: 'Apteka i lekarz',
    fitness: 'Siłownia',
    travel_root: 'Podróże',
    flights: 'Loty',
    hotels: 'Hotele',
    local_travel: 'Komunikacja',
    family: 'Rodzina',
    gifts: 'Prezenty',
    education: 'Kursy',
    salary_root: 'Wynagrodzenie',
    salary: 'Pensja',
    bonus: 'Premia',
    side_root: 'Dodatkowe',
    freelance: 'Zlecenia',
    consulting: 'Doradztwo',
    invest_root: 'Inwestycje',
    dividends: 'Dywidendy',
    interest: 'Odsetki',
  },
  budgetName: 'Budżet miesięczny',
  split: {
    merchant: 'Pierogarnia Stary Młyn',
    note: 'Kolacja ze znajomymi, zapłaciłam',
    people: ['Kuba', 'Ola', 'Michał'],
  },
  recurring: {
    salary: { name: 'Pensja', note: 'Wynagrodzenie' },
    rent: { name: 'Czynsz', note: 'Czynsz za mieszkanie' },
    fitness: { name: 'Siłownia', amount: 139, note: 'Zdrofit', logoId: 'poland/zdrofit' },
    subscriptions: [
      { name: 'Netflix', amount: 49, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 23.99, note: 'Spotify Premium' },
      { name: 'Player', amount: 29.99, note: 'Player.pl', logoId: 'poland/player' },
      { name: 'Allegro Smart!', amount: 11.99, note: 'Allegro Smart!', logoId: 'poland/allegro' },
      { name: 'iCloud+', amount: 12.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'ETF co miesiąc', note: 'Regularne inwestowanie' },
  },
  merchants: {
    grocery: ['Biedronka', 'Lidl', 'Żabka', 'Carrefour', 'Auchan'],
    dining: ['Pierogarnia Stary Młyn', 'Bar Mleczny', 'Pizza Hut', 'Hala Koszyki', 'Sushi Kushi'],
    coffee: ['Costa Coffee', 'Starbucks', 'Green Caffè Nero', 'Coffeedesk'],
    fuel: ['Orlen', 'BP', 'Shell'],
    shopping: ['Allegro', 'Empik', 'Media Expert', 'Rossmann'],
    entertainment: ['Cinema City', 'Multikino', 'Ticketmaster'],
    rideshare: ['Bolt', 'Uber'],
    healthcare: ['Apteka Gemini', 'Lux Med', 'Medicover'],
    hotels: ['Hotel Mercure', 'Apartamenty Zakopane'],
    flights: ['LOT', 'Wizz Air'],
    delivery: ['Pyszne.pl', 'Glovo', 'Wolt'],
    convenience: ['Żabka', 'Carrefour Express', 'Lewiatan'],
  },
  notes: {
    salary: 'Pensja',
    bonus: 'Premia roczna',
    freelance: 'Zlecenie',
    consulting: 'Doradztwo',
    dividends: 'Dywidenda',
    interest: 'Odsetki z konta',
    rent: 'Czynsz',
    utilities: 'Prąd i woda',
    internet: 'Internet Orange',
    fitness: 'Zdrofit',
    homeSupplies: 'Chemia domowa',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Kurs online',
    atmWithdrawal: 'Wypłata z bankomatu',
    parkingPrimary: 'Parking',
    parkingAlternate: 'Parkomat',
    savingsTransfer: 'Na oszczędności',
    investmentTransfer: 'ETF co miesiąc',
    travelTopUp: 'Skarbonka wakacje',
    localTravel: 'Pociąg na lotnisko',
    tripDining: 'Jedzenie na wakacjach',
    holidayGifts: 'Prezenty świąteczne',
    familyCelebration: 'Obiad rodzinny',
    cardPayment: 'Spłata karty',
  },
});
