import { buildLocalizedProfile } from './localized';

export const russianProfile = buildLocalizedProfile({
  seed: 20260511,
  locale: 'ru',
  currencyCode: 'RUB',
  currencySymbol: '₽',
  priceScale: 10,
  decimals: 0,
  monthlySalary: 120000,
  monthlyRent: 45000,
  profileName: 'Анна Смирнова',
  accountGroups: {
    everyday: 'Повседневное',
    goals: 'Цели',
    credit: 'Кредит',
    investing: 'Инвестиции',
  },
  accounts: {
    checking: { name: 'Сбер Дебетовая', logoId: 'russia/sberbank' },
    savings: { name: 'Накопительный ВТБ', logoId: 'russia/vtb' },
    travel: { name: 'Копилка на отпуск', logoId: 'russia/otkritie' },
    card: { name: 'Кредитка Альфа', logoId: 'russia/alfa-bank' },
    cash: { name: 'Наличные', logoId: 'global/visa' },
    brokerage: { name: 'Брокерский счёт', logoId: 'russia/gazprombank' },
  },
  extraAccounts: [
    { name: 'ЮMoney', type: 'debit', logoId: 'russia/yoomoney', groupKey: 'everyday' },
    { name: 'Совкомбанк', type: 'debit', logoId: 'russia/sovcombank', groupKey: 'everyday' },
    { name: 'Росбанк', type: 'debit', logoId: 'russia/rosbank', groupKey: 'goals' },
    { name: 'Карта МТС Банка', type: 'credit', logoId: 'russia/mts-bank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Жильё',
    rent: 'Аренда',
    utilities: 'Коммуналка',
    internet: 'Интернет',
    home_supplies: 'Для дома',
    food: 'Еда',
    groceries: 'Продукты',
    dining: 'Кафе и рестораны',
    coffee: 'Кофе',
    transport: 'Транспорт',
    fuel: 'Бензин',
    rideshare: 'Такси',
    parking: 'Парковка',
    lifestyle: 'Досуг',
    shopping: 'Покупки',
    entertainment: 'Развлечения',
    subscriptions: 'Подписки',
    health: 'Здоровье',
    healthcare: 'Аптека и врач',
    fitness: 'Фитнес',
    travel_root: 'Путешествия',
    flights: 'Авиабилеты',
    hotels: 'Отели',
    local_travel: 'Общественный транспорт',
    family: 'Семья',
    gifts: 'Подарки',
    education: 'Обучение',
    salary_root: 'Зарплата',
    salary: 'Зарплата',
    bonus: 'Премия',
    side_root: 'Подработка',
    freelance: 'Фриланс',
    consulting: 'Консультации',
    invest_root: 'Инвестиции',
    dividends: 'Дивиденды',
    interest: 'Проценты',
  },
  budgetName: 'Бюджет на месяц',
  split: {
    merchant: 'Хачапури и вино',
    note: 'Ужин с друзьями, я заплатила',
    people: ['Дима', 'Катя', 'Артём'],
  },
  recurring: {
    salary: { name: 'Зарплата', note: 'Зарплата за месяц' },
    rent: { name: 'Аренда', note: 'Аренда квартиры' },
    fitness: { name: 'Фитнес', amount: 3500, note: 'World Class', logoId: 'russia/world-class' },
    subscriptions: [
      { name: 'Яндекс Плюс', amount: 399, note: 'Яндекс Плюс', logoId: 'russia/yandex-plus' },
      { name: 'Кинопоиск', amount: 299, note: 'Кинопоиск', logoId: 'russia/kinopoisk' },
      { name: 'Okko', amount: 399, note: 'Okko', logoId: 'russia/okko' },
      { name: 'VK Музыка', amount: 199, note: 'VK Музыка', logoId: 'russia/vk-muzyka' },
      { name: 'СберПрайм', amount: 299, note: 'СберПрайм', logoId: 'russia/sber' },
    ],
    investment: { name: 'Пополнение ИИС', note: 'Ежемесячно' },
  },
  merchants: {
    grocery: ['Пятёрочка', 'Перекрёсток', 'ВкусВилл', 'Магнит', 'Лента'],
    dining: ['Хачапури и вино', 'Теремок', 'Шоколадница', 'Вкусно и точка', 'Додо Пицца'],
    coffee: ['Кофемания', 'Cofix', 'Surf Coffee', 'Даблби'],
    fuel: ['Лукойл', 'Газпромнефть', 'Роснефть'],
    shopping: ['Ozon', 'Wildberries', 'М.Видео', 'Золотое яблоко'],
    entertainment: ['Каро Фильм', 'Синема Парк', 'Большой театр'],
    rideshare: ['Яндекс Go', 'Ситимобил'],
    healthcare: ['Аптека Ригла', 'Клиника Медси', 'Стоматология'],
    hotels: ['Азимут Отель', 'Отель в Сочи'],
    flights: ['Аэрофлот', 'S7'],
    delivery: ['Яндекс Еда', 'Самокат', 'Delivery Club'],
    convenience: ['ВкусВилл', 'Магнит у дома', 'Дикси'],
  },
  notes: {
    salary: 'Зарплата',
    bonus: 'Годовая премия',
    freelance: 'Фриланс-проект',
    consulting: 'Консультация',
    dividends: 'Дивиденды',
    interest: 'Проценты по вкладу',
    rent: 'Аренда за месяц',
    utilities: 'Коммунальные услуги',
    internet: 'Домашний интернет',
    fitness: 'Абонемент в фитнес',
    homeSupplies: 'Покупки для дома',
    subscriptions: ['Яндекс Плюс', 'Кинопоиск', 'VK Музыка'],
    education: 'Онлайн-курс',
    atmWithdrawal: 'Снятие наличных',
    parkingPrimary: 'Парковка',
    parkingAlternate: 'Платная дорога',
    savingsTransfer: 'На накопительный',
    investmentTransfer: 'Пополнение ИИС',
    travelTopUp: 'Копилка на отпуск',
    localTravel: 'Аэроэкспресс',
    tripDining: 'Еда в поездке',
    holidayGifts: 'Новогодние подарки',
    familyCelebration: 'Семейный ужин',
    cardPayment: 'Погашение кредитки',
  },
});
