import { buildLocalizedProfile } from './localized';

export const spanishProfile = buildLocalizedProfile({
  seed: 20260503,
  locale: 'es',
  currencyCode: 'EUR',
  currencySymbol: '€',
  priceScale: 0.28,
  decimals: 2,
  monthlySalary: 2900,
  monthlyRent: 950,
  profileName: 'Lucía García',
  accountGroups: {
    everyday: 'Día a día',
    goals: 'Metas',
    credit: 'Crédito',
    investing: 'Inversión',
  },
  accounts: {
    checking: { name: 'Cuenta BBVA', logoId: 'spain/bbva' },
    savings: { name: 'Ahorro Openbank', logoId: 'spain/openbank' },
    travel: { name: 'Hucha viajes', logoId: 'spain/ing-espana' },
    card: { name: 'Tarjeta Santander', logoId: 'spain/santander' },
    cash: { name: 'Efectivo', logoId: 'global/visa' },
    brokerage: { name: 'MyInvestor', logoId: 'spain/myinvestor' },
  },
  extraAccounts: [
    { name: 'Bizum', type: 'debit', logoId: 'spain/bizum', groupKey: 'everyday' },
    { name: 'CaixaBank', type: 'debit', logoId: 'spain/caixabank', groupKey: 'everyday' },
    { name: 'Revolut', type: 'debit', logoId: 'global/revolut', groupKey: 'everyday' },
    { name: 'Tarjeta WiZink', type: 'credit', logoId: 'spain/wizink', groupKey: 'credit' },
  ],
  categories: {
    home: 'Hogar',
    rent: 'Alquiler',
    utilities: 'Luz y agua',
    internet: 'Fibra',
    home_supplies: 'Casa',
    food: 'Comida',
    groceries: 'Supermercado',
    dining: 'Restaurantes',
    coffee: 'Café',
    transport: 'Transporte',
    fuel: 'Gasolina',
    rideshare: 'Taxi y VTC',
    parking: 'Parking',
    lifestyle: 'Ocio',
    shopping: 'Compras',
    entertainment: 'Entretenimiento',
    subscriptions: 'Suscripciones',
    health: 'Salud',
    healthcare: 'Farmacia y médico',
    fitness: 'Gimnasio',
    travel_root: 'Viajes',
    flights: 'Vuelos',
    hotels: 'Hoteles',
    local_travel: 'Transporte local',
    family: 'Familia',
    gifts: 'Regalos',
    education: 'Formación',
    salary_root: 'Nómina',
    salary: 'Nómina',
    bonus: 'Paga extra',
    side_root: 'Extras',
    freelance: 'Freelance',
    consulting: 'Consultoría',
    invest_root: 'Inversiones',
    dividends: 'Dividendos',
    interest: 'Intereses',
  },
  budgetName: 'Presupuesto mensual',
  split: {
    merchant: 'Taberna La Bola',
    note: 'Cena con amigos, pagué yo',
    people: ['Pablo', 'Marta', 'Javi'],
  },
  recurring: {
    salary: { name: 'Nómina', note: 'Nómina mensual' },
    rent: { name: 'Alquiler', note: 'Alquiler del piso' },
    fitness: { name: 'Gimnasio', amount: 34.9, note: 'VivaGym', logoId: 'spain/vivagym' },
    subscriptions: [
      { name: 'Netflix', amount: 13.99, note: 'Netflix Estándar' },
      { name: 'Spotify', amount: 11.99, note: 'Spotify Premium' },
      {
        name: 'Movistar Plus+',
        amount: 9.99,
        note: 'Movistar Plus+',
        logoId: 'spain/movistar-plus',
      },
      { name: 'Disney+', amount: 9.99, note: 'Disney+' },
      { name: 'iCloud+', amount: 2.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Fondo indexado', note: 'Aportación mensual' },
  },
  merchants: {
    grocery: ['Mercadona', 'Carrefour', 'Lidl', 'Día', 'El Corte Inglés'],
    dining: ['Taberna La Bola', 'Lateral', 'Casa Lucio', 'Telepizza', 'Vips'],
    coffee: ['Café de Oriente', 'Starbucks', 'Granier', 'Rodilla'],
    fuel: ['Repsol', 'Cepsa', 'BP'],
    shopping: ['Zara', 'El Corte Inglés', 'Primark', 'Amazon.es'],
    entertainment: ['Cines Yelmo', 'Kinépolis', 'Teatro Lope de Vega'],
    rideshare: ['Cabify', 'Uber'],
    healthcare: ['Farmacia', 'Clínica Sanitas', 'Dentista'],
    hotels: ['NH Hoteles', 'Meliá'],
    flights: ['Iberia', 'Vueling'],
    delivery: ['Glovo', 'Just Eat', 'Uber Eats'],
    convenience: ['Carrefour Express', 'Supercor', 'Ahorramás'],
  },
  notes: {
    salary: 'Nómina',
    bonus: 'Paga extra',
    freelance: 'Proyecto freelance',
    consulting: 'Consultoría',
    dividends: 'Dividendos',
    interest: 'Intereses cuenta',
    rent: 'Alquiler del mes',
    utilities: 'Luz y agua',
    internet: 'Fibra Movistar',
    fitness: 'VivaGym',
    homeSupplies: 'Cosas para casa',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Curso online',
    atmWithdrawal: 'Retirada de efectivo',
    parkingPrimary: 'Parking',
    parkingAlternate: 'Peaje',
    savingsTransfer: 'Traspaso a ahorro',
    investmentTransfer: 'Aportación fondo',
    travelTopUp: 'Hucha viajes',
    localTravel: 'Metro al aeropuerto',
    tripDining: 'Comida de viaje',
    holidayGifts: 'Regalos de Reyes',
    familyCelebration: 'Comida familiar',
    cardPayment: 'Pago tarjeta',
  },
});
