import { buildLocalizedProfile } from './localized';

export const swedishProfile = buildLocalizedProfile({
  seed: 20260508,
  locale: 'sv',
  currencyCode: 'SEK',
  currencySymbol: 'kr',
  priceScale: 4.4,
  decimals: 2,
  monthlySalary: 46000,
  monthlyRent: 11000,
  profileName: 'Elsa Andersson',
  accountGroups: { everyday: 'Vardag', goals: 'Mål', credit: 'Kredit', investing: 'Investeringar' },
  accounts: {
    checking: { name: 'Swedbank Lönekonto', logoId: 'sweden/swedbank' },
    savings: { name: 'SBAB Sparkonto', logoId: 'sweden/sbab' },
    travel: { name: 'Semesterkassa', logoId: 'sweden/ica-banken' },
    card: { name: 'Handelsbanken Kort', logoId: 'sweden/handelsbanken' },
    cash: { name: 'Kontanter', logoId: 'global/visa' },
    brokerage: { name: 'Avanza ISK', logoId: 'sweden/avanza' },
  },
  extraAccounts: [
    { name: 'Nordea', type: 'debit', logoId: 'sweden/nordea', groupKey: 'everyday' },
    {
      name: 'Länsförsäkringar',
      type: 'debit',
      logoId: 'sweden/lansforsakringar',
      groupKey: 'everyday',
    },
    { name: 'Nordnet', type: 'debit', logoId: 'sweden/nordnet', groupKey: 'investing' },
    { name: 'Klarna Kort', type: 'credit', logoId: 'global/klarna', groupKey: 'credit' },
  ],
  categories: {
    home: 'Boende',
    rent: 'Hyra',
    utilities: 'El & vatten',
    internet: 'Bredband',
    home_supplies: 'Hushåll',
    food: 'Mat',
    groceries: 'Matvaror',
    dining: 'Restaurang',
    coffee: 'Fika',
    transport: 'Transport',
    fuel: 'Bensin',
    rideshare: 'Taxi',
    parking: 'Parkering',
    lifestyle: 'Fritid',
    shopping: 'Shopping',
    entertainment: 'Nöje',
    subscriptions: 'Prenumerationer',
    health: 'Hälsa',
    healthcare: 'Apotek & vård',
    fitness: 'Gym',
    travel_root: 'Resor',
    flights: 'Flyg',
    hotels: 'Hotell',
    local_travel: 'Kollektivtrafik',
    family: 'Familj',
    gifts: 'Presenter',
    education: 'Kurser',
    salary_root: 'Lön',
    salary: 'Lön',
    bonus: 'Bonus',
    side_root: 'Extrajobb',
    freelance: 'Frilans',
    consulting: 'Konsultuppdrag',
    invest_root: 'Investeringar',
    dividends: 'Utdelning',
    interest: 'Ränta',
  },
  budgetName: 'Månadsbudget',
  split: {
    merchant: 'Pelikan',
    note: 'Middag med vänner, jag lade ut',
    people: ['William', 'Maja', 'Lucas'],
  },
  recurring: {
    salary: { name: 'Lön', note: 'Månadslön' },
    rent: { name: 'Hyra', note: 'Hyra lägenhet' },
    fitness: { name: 'Gymkort', amount: 399, note: 'SATS', logoId: 'sweden/sats' },
    subscriptions: [
      { name: 'Netflix', amount: 149, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 129, note: 'Spotify Premium' },
      { name: 'Storytel', amount: 229, note: 'Storytel', logoId: 'sweden/storytel' },
      { name: 'Viaplay', amount: 189, note: 'Viaplay', logoId: 'sweden/viaplay' },
      { name: 'iCloud+', amount: 39, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Månadssparande', note: 'Indexfond' },
  },
  merchants: {
    grocery: ['ICA Maxi', 'Coop', 'Willys', 'Hemköp', 'Lidl'],
    dining: ['Pelikan', 'Max Burgers', 'Vapiano', 'Hötorgshallen', 'Bastard Burgers'],
    coffee: ['Espresso House', 'Wayne’s Coffee', 'Pressbyrån', 'Gateau'],
    fuel: ['Circle K', 'Preem', 'OKQ8'],
    shopping: ['H&M', 'Åhléns', 'Elgiganten', 'IKEA'],
    entertainment: ['Filmstaden', 'Gröna Lund', 'Ticketmaster'],
    rideshare: ['Taxi Stockholm', 'Bolt'],
    healthcare: ['Apotek Hjärtat', 'Vårdcentralen', 'Kry'],
    hotels: ['Scandic', 'Elite Hotels'],
    flights: ['SAS', 'Norwegian'],
    delivery: ['Foodora', 'Wolt', 'Uber Eats'],
    convenience: ['Pressbyrån', '7-Eleven', 'Coop Nära'],
  },
  notes: {
    salary: 'Lön',
    bonus: 'Årsbonus',
    freelance: 'Frilansuppdrag',
    consulting: 'Konsultarvode',
    dividends: 'Utdelning',
    interest: 'Sparränta',
    rent: 'Hyra',
    utilities: 'El & vatten',
    internet: 'Bahnhof bredband',
    fitness: 'SATS',
    homeSupplies: 'Hushållsartiklar',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Onlinekurs',
    atmWithdrawal: 'Uttag kontanter',
    parkingPrimary: 'Parkeringshus',
    parkingAlternate: 'Trängselskatt',
    savingsTransfer: 'Till sparkonto',
    investmentTransfer: 'Månadssparande',
    travelTopUp: 'Semesterkassa',
    localTravel: 'Arlanda Express',
    tripDining: 'Mat på semestern',
    holidayGifts: 'Julklappar',
    familyCelebration: 'Familjefest',
    cardPayment: 'Kortskuld betald',
  },
});
