import type { CategoryNames, PreviewProfile } from '../shared';

const TAIWANESE_CATEGORIES: CategoryNames = {
  home: '居住',
  rent: '房租',
  utilities: '水電瓦斯',
  internet: '網路通訊',
  home_supplies: '日用品',
  food: '飲食',
  groceries: '生鮮採買',
  dining: '外食',
  coffee: '咖啡手搖',
  transport: '交通',
  fuel: '加油',
  rideshare: '叫車',
  parking: '停車',
  lifestyle: '生活',
  shopping: '購物',
  entertainment: '娛樂',
  subscriptions: '訂閱',
  health: '健康',
  healthcare: '醫療',
  fitness: '健身',
  travel_root: '旅遊',
  flights: '機票',
  hotels: '住宿',
  local_travel: '當地交通',
  family: '家庭',
  gifts: '禮金',
  education: '進修',
  salary_root: '薪資',
  salary: '薪水入帳',
  bonus: '獎金',
  side_root: '副業',
  freelance: '接案',
  consulting: '顧問',
  invest_root: '投資',
  dividends: '股利',
  interest: '利息',
};

export const taiwaneseProfile: PreviewProfile = {
  seed: 20260721,
  locale: 'zh',
  currencyCode: 'TWD',
  currencySymbol: 'NT$',
  profileName: '陳彥廷',
  accountGroups: {
    everyday: '日常',
    goals: '目標',
    credit: '信用卡',
    investing: '投資',
  },
  accounts: {
    checking: { name: '中信薪轉戶', startingBalance: 96400, logoId: 'taiwan/ctbc-bank' },
    savings: {
      name: '國泰世華數位帳戶',
      startingBalance: 348000,
      logoId: 'taiwan/cathay-united-bank',
    },
    travel: { name: '旅遊基金', startingBalance: 42600, logoId: 'taiwan/esun-bank' },
    card: { name: '台新 @GoGo 卡', startingBalance: 8600, logoId: 'taiwan/taishin-bank' },
    cash: { name: '現金', startingBalance: 2400, logoId: 'taiwan/bank-of-taiwan' },
    brokerage: { name: '元大證券', startingBalance: 285000, logoId: 'taiwan/yuanta-bank' },
  },
  extraAccounts: [
    {
      name: '悠遊卡',
      type: 'debit',
      startingBalance: 1250,
      logoId: 'taiwan/easycard',
      groupKey: 'everyday',
    },
    {
      name: 'LINE Pay',
      type: 'debit',
      startingBalance: 3400,
      logoId: 'taiwan/line-pay',
      groupKey: 'everyday',
    },
    {
      name: '街口支付',
      type: 'debit',
      startingBalance: 1880,
      logoId: 'taiwan/jkopay',
      groupKey: 'everyday',
    },
    {
      name: 'Richart 數位帳戶',
      type: 'debit',
      startingBalance: 62000,
      logoId: 'taiwan/richart',
      groupKey: 'everyday',
    },
    {
      name: '樂天銀行',
      type: 'debit',
      startingBalance: 28000,
      logoId: 'taiwan/rakuten-bank-taiwan',
      groupKey: 'goals',
    },
    {
      name: '凱基證券',
      type: 'debit',
      startingBalance: 132000,
      logoId: 'taiwan/kgi-securities',
      groupKey: 'investing',
    },
    {
      name: '幣託 BitoPro',
      type: 'debit',
      startingBalance: 46000,
      logoId: 'taiwan/bitopro',
      groupKey: 'investing',
    },
    {
      name: '國泰 CUBE 卡',
      type: 'credit',
      startingBalance: 12400,
      logoId: 'taiwan/cathay-united-bank',
      groupKey: 'credit',
    },
    {
      name: '富邦 J 卡',
      type: 'credit',
      startingBalance: 6800,
      logoId: 'taiwan/fubon-bank',
      groupKey: 'credit',
    },
    {
      name: '永豐 DAWHO 現金回饋卡',
      type: 'credit',
      startingBalance: 4200,
      logoId: 'taiwan/bank-sinopac',
      groupKey: 'credit',
    },
    {
      name: '兆豐利多卡',
      type: 'credit',
      startingBalance: 3100,
      logoId: 'taiwan/mega-bank',
      groupKey: 'credit',
    },
  ],
  categories: TAIWANESE_CATEGORIES,
  career: [
    {
      durationMonths: 11,
      monthlySalary: 82000,
      hoursWorkedPerWeek: 45,
      commuteMinutesPerWorkday: 35,
    },
    {
      durationMonths: 18,
      monthlySalary: 68000,
      hoursWorkedPerWeek: 46,
      commuteMinutesPerWorkday: 50,
    },
    {
      durationMonths: 24,
      monthlySalary: 55000,
      hoursWorkedPerWeek: 47,
      commuteMinutesPerWorkday: 58,
    },
  ],
  budgets: {
    templateName: '每月預算',
    templateEmoji: '🎯',
    totalAmount: 52000,
    allocations: [
      { categoryKey: 'home', amount: 22000 },
      { categoryKey: 'food', amount: 12000 },
      { categoryKey: 'transport', amount: 4500 },
      { categoryKey: 'lifestyle', amount: 7500 },
      { categoryKey: 'health', amount: 3000 },
    ],
    monthsToSeed: 6,
  },
  secondBudget: {
    templateName: '省錢月',
    templateEmoji: '🌱',
    totalAmount: 44000,
    allocations: [
      { categoryKey: 'home', amount: 22000 },
      { categoryKey: 'food', amount: 9000 },
      { categoryKey: 'transport', amount: 3500 },
      { categoryKey: 'lifestyle', amount: 4000 },
      { categoryKey: 'health', amount: 2500 },
    ],
    monthsToSeed: 0,
  },
  splits: [
    {
      merchant: '熱炒 100',
      note: '同事聚餐，我先刷卡',
      categoryKey: 'dining',
      monthsAgo: 0,
      day: 12,
      account: 'card',
      selfShare: 380,
      participants: [
        { name: '怡君', share: 380, paid: true },
        { name: '家豪', share: 380, paid: false },
        { name: '雅婷', share: 360, paid: false },
      ],
    },
    {
      merchant: '礁溪溫泉民宿',
      note: '宜蘭兩天一夜，四人均分',
      categoryKey: 'travel_root',
      monthsAgo: 4,
      day: 6,
      account: 'card',
      selfShare: 1450,
      participants: [
        { name: '怡君', share: 1450, paid: true },
        { name: '志明', share: 1450, paid: true },
        { name: '宗翰', share: 1450, paid: true },
      ],
    },
  ],
  recurring: {
    salary: { name: '每月薪資', amount: 82000, note: '薪水入帳' },
    rent: { name: '房租', amount: 18500, note: '套房月租' },
    fitness: { name: '健身房月費', amount: 1188, note: 'World Gym 月費' },
    subscriptions: [
      { name: 'Netflix 標準方案', amount: 330, note: 'Netflix 月費' },
      { name: 'Spotify Premium', amount: 149, note: 'Spotify 音樂' },
      { name: 'KKBOX 音樂', amount: 149, note: 'KKBOX 月費' },
      { name: 'YouTube Premium', amount: 179, note: 'YouTube 免廣告' },
      { name: 'Disney+ 月費', amount: 270, note: 'Disney+ 影音' },
    ],
    investment: { name: '定期定額 0050', amount: 5000, note: '每月自動扣款' },
  },
  transactions: {
    merchants: {
      grocery: ['全聯福利中心', '家樂福', '美廉社', '大潤發'],
      dining: ['八方雲集', '鬍鬚張魯肉飯', '三商巧福', '池上木片便當'],
      coffee: ['路易莎咖啡', 'cama café', '星巴克', '全家 Let’s Café'],
      fuel: ['台灣中油', '台塑石油', '全國加油站'],
      shopping: ['新光三越', '誠品生活', '蝦皮購物', 'PChome 24h'],
      entertainment: ['威秀影城', '錢櫃 KTV', 'Legacy Taipei', '華山文創園區'],
      rideshare: ['台灣大車隊', 'Uber', 'LINE TAXI', 'yoxi'],
      healthcare: ['家醫科診所', '牙醫診所', '大樹藥局'],
      hotels: ['礁溪老爺酒店', '誠品行旅', '福容大飯店'],
      flights: ['中華航空', '長榮航空', '星宇航空'],
    },
    notes: {
      salary: '薪水入帳',
      bonus: '季獎金',
      freelance: '接案專案',
      consulting: '顧問案',
      dividends: '股利入帳',
      interest: '活存利息',
      rent: '套房月租',
      utilities: '水電瓦斯',
      internet: '中華電信光世代',
      fitness: 'World Gym 月費',
      homeSupplies: '日用品補貨',
      subscriptions: ['Netflix 月費', 'Spotify 音樂', 'KKBOX 月費'],
      education: '線上課程',
      atmWithdrawal: 'ATM 提款',
      parkingPrimary: '百貨停車',
      parkingAlternate: '路邊停車格',
      savingsTransfer: '轉入存款',
      investmentTransfer: '定期定額扣款',
      travelTopUp: '旅遊基金',
      localTravel: '機場捷運',
      tripDining: '旅途聚餐',
      holidayGifts: '過年紅包',
      familyCelebration: '家庭聚餐',
      cardPayment: '信用卡繳款',
    },
    subscriptions: [330, 149, 149],
    income: {
      bonusBase: 24000,
      bonusGrowth: 400,
      bonusSpread: 3000,
      freelanceBase: 9800,
      freelanceGrowth: 220,
      freelanceSpread: 1800,
      consultingBase: 6200,
      consultingStep: 800,
      consultingSpread: 1200,
      dividendsBase: 1800,
      dividendsGrowth: 60,
      dividendsSpread: 450,
      interestBase: 320,
      interestGrowth: 8,
      interestSpread: 70,
    },
    housing: {
      rentBase: 18500,
      rentGrowth: 40,
      rentSpread: 200,
      utilitiesBase: 1420,
      utilitiesSpread: 380,
      internetBase: 899,
      internetSpread: 20,
      fitnessBase: 1188,
      fitnessSpread: 30,
      homeSuppliesBase: 680,
      homeSuppliesSpread: 220,
      healthcareBase: 900,
      healthcareSpread: 400,
      educationBase: 1600,
      educationSpread: 500,
    },
    weekly: {
      cashTopUpFourWeek: 3000,
      cashTopUpFiveWeek: 3600,
      cashTopUpSpread: 400,
      groceryBase: 1580,
      groceryWeekStep: 60,
      grocerySpread: 320,
      diningBase: 880,
      diningWeekStep: 40,
      diningSpread: 260,
      coffeeBase: 68,
      coffeeSpread: 22,
      fuelBase: 620,
      fuelSpread: 140,
      parkingPrimaryBase: 120,
      parkingPrimarySpread: 40,
      parkingAlternateBase: 50,
      parkingAlternateSpread: 20,
    },
    lifestyle: {
      shoppingBase: 1450,
      shoppingTripStep: 480,
      shoppingSpread: 620,
      entertainmentBase: 620,
      entertainmentTripStep: 280,
      entertainmentSpread: 220,
      rideshareBase: 195,
      rideshareSpread: 65,
    },
    transfers: {
      savingsBase: 18000,
      savingsGrowth: 350,
      savingsSpread: 1500,
      investmentBase: 6000,
      investmentGrowth: 180,
      investmentSpread: 800,
      travelBase: 2000,
      travelPeak: 7000,
      travelSpread: 600,
      cardPaymentRatio: 0.97,
    },
    travel: {
      months: [1, 7],
      giftMonth: 1,
      flightsBase: 12800,
      flightsSpread: 2600,
      hotelsBase: 9600,
      hotelsSpread: 1800,
      localTransitBase: 380,
      localTransitSpread: 90,
      diningBase: 1080,
      diningSpread: 280,
      holidayGiftsBase: 6800,
      holidayGiftsSpread: 1500,
      familyCelebrationBase: 4200,
      familyCelebrationSpread: 900,
    },
    extras: {
      weekendBrunchCount: 3,
      weekendBrunchBase: 190,
      weekendBrunchSpread: 70,
      weekendBrunchMerchants: ['美而美早餐店', '阜杭豆漿', '興隆居', '拉亞漢堡', '永和豆漿大王'],
      weekendBrunchNote: '週末早午餐',
      bubbleTeaCount: 5,
      bubbleTeaBase: 60,
      bubbleTeaSpread: 18,
      bubbleTeaMerchants: ['五十嵐', '清心福全', '迷客夏', '可不可熟成紅茶', '大苑子'],
      hangoutBase: 520,
      hangoutSpread: 180,
      hangoutMerchants: ['饒河街夜市', '士林夜市', '公館居酒屋', '信義區酒吧', '寧夏夜市'],
      hangoutNote: '和朋友吃宵夜',
      deliveryCount: 4,
      deliveryBase: 260,
      deliverySpread: 90,
      deliveryMerchants: ['foodpanda', 'Uber Eats', '麥當勞歡樂送', '摩斯漢堡外送'],
      deliveryNote: '懶得煮，叫外送',
      rideshareExtraCount: 3,
      rideshareExtraBase: 210,
      rideshareExtraSpread: 70,
      convenienceCount: 6,
      convenienceBase: 95,
      convenienceSpread: 45,
      convenienceMerchants: ['7-ELEVEN', '全家便利商店', '萊爾富', 'OK 超商'],
    },
  },
  albums: [
    {
      name: '東京自由行',
      placeName: '東京',
      placeAdmin: '日本',
      countryCode: 'JP',
      latitude: 35.6762,
      longitude: 139.6503,
      currencyCode: 'JPY',
      fxRate: 4.7,
    },
    {
      name: '首爾購物之旅',
      placeName: '首爾',
      placeAdmin: '韓國',
      countryCode: 'KR',
      latitude: 37.5665,
      longitude: 126.978,
      currencyCode: 'KRW',
      fxRate: 43,
    },
    {
      name: '花蓮台東環島',
      placeName: '花蓮',
      placeAdmin: '花蓮縣',
      countryCode: 'TW',
      latitude: 23.9871,
      longitude: 121.6015,
      currencyCode: 'TWD',
      fxRate: 1,
    },
    {
      name: '曼谷小旅行',
      placeName: '曼谷',
      placeAdmin: '泰國',
      countryCode: 'TH',
      latitude: 13.7563,
      longitude: 100.5018,
      currencyCode: 'THB',
      fxRate: 1.05,
    },
  ],
  items: [
    {
      name: 'iPhone 16 Pro',
      iconId: 'smartphone',
      purchaseMonthsAgo: 9,
      purchaseDay: 22,
      purchasePrice: 36900,
      note: '原色鈦金屬 256G',
    },
    {
      name: 'MacBook Air M3',
      iconId: 'laptop',
      purchaseMonthsAgo: 17,
      purchaseDay: 6,
      purchasePrice: 37900,
    },
    {
      name: 'AirPods Pro 2',
      iconId: 'wireless-earbuds',
      purchaseMonthsAgo: 8,
      purchaseDay: 15,
      purchasePrice: 7490,
    },
    {
      name: 'Apple Watch S10',
      iconId: 'smartwatch',
      purchaseMonthsAgo: 11,
      purchaseDay: 4,
      purchasePrice: 12900,
    },
    {
      name: 'Gogoro VIVA MIX',
      iconId: 'electric-scooter',
      purchaseMonthsAgo: 26,
      purchaseDay: 19,
      purchasePrice: 68800,
      note: '通勤代步，電池月租另計',
    },
    {
      name: '捷安特 Escape 3',
      iconId: 'e-bike',
      purchaseMonthsAgo: 21,
      purchaseDay: 9,
      purchasePrice: 15800,
      note: '河濱騎車用',
    },
    {
      name: 'Switch OLED',
      iconId: 'handheld-game-console',
      purchaseMonthsAgo: 30,
      purchaseDay: 12,
      purchasePrice: 10480,
    },
    {
      name: 'Dyson 吹風機',
      iconId: 'cordless-vacuum',
      purchaseMonthsAgo: 14,
      purchaseDay: 27,
      purchasePrice: 14800,
    },
    {
      name: 'Sony A7C（已售出）',
      iconId: 'dslr-camera',
      purchaseMonthsAgo: 33,
      purchaseDay: 16,
      purchasePrice: 52000,
      retiredMonthsAgo: 10,
      salePrice: 31000,
      note: '換 A7C II 後在蝦皮出掉',
    },
  ],
};
