import { buildLocalizedProfile } from './localized';

export const thaiProfile = buildLocalizedProfile({
  seed: 20260517,
  locale: 'th',
  currencyCode: 'THB',
  currencySymbol: '฿',
  priceScale: 6,
  decimals: 2,
  monthlySalary: 65000,
  monthlyRent: 15000,
  profileName: 'ปิยะนุช ศรีสุข',
  accountGroups: {
    everyday: 'ใช้จ่ายประจำวัน',
    goals: 'เป้าหมาย',
    credit: 'บัตรเครดิต',
    investing: 'การลงทุน',
  },
  accounts: {
    checking: { name: 'กสิกรไทย', logoId: 'thailand/kasikornbank' },
    savings: { name: 'ออมทรัพย์กรุงเทพ', logoId: 'thailand/bangkok-bank' },
    travel: { name: 'เงินเที่ยว', logoId: 'thailand/ttb-bank' },
    card: { name: 'บัตรกรุงศรี', logoId: 'thailand/krungsri' },
    cash: { name: 'เงินสด', logoId: 'global/visa' },
    brokerage: { name: 'กองทุนเกียรตินาคิน', logoId: 'thailand/kiatnakin-phatra' },
  },
  extraAccounts: [
    { name: 'TrueMoney', type: 'debit', logoId: 'thailand/truemoney', groupKey: 'everyday' },
    {
      name: 'ออมสิน',
      type: 'debit',
      logoId: 'thailand/government-savings-bank',
      groupKey: 'goals',
    },
    {
      name: 'ShopeePay',
      type: 'debit',
      logoId: 'thailand/shopeepay-thailand',
      groupKey: 'everyday',
    },
    { name: 'บัตร LH Bank', type: 'credit', logoId: 'thailand/lh-bank', groupKey: 'credit' },
  ],
  categories: {
    home: 'ที่พัก',
    rent: 'ค่าเช่า',
    utilities: 'ค่าน้ำค่าไฟ',
    internet: 'อินเทอร์เน็ต',
    home_supplies: 'ของใช้ในบ้าน',
    food: 'อาหาร',
    groceries: 'ซื้อของเข้าบ้าน',
    dining: 'กินข้าวนอกบ้าน',
    coffee: 'กาแฟ',
    transport: 'เดินทาง',
    fuel: 'น้ำมัน',
    rideshare: 'แท็กซี่',
    parking: 'ทางด่วนและที่จอด',
    lifestyle: 'ไลฟ์สไตล์',
    shopping: 'ช้อปปิ้ง',
    entertainment: 'บันเทิง',
    subscriptions: 'สมาชิกรายเดือน',
    health: 'สุขภาพ',
    healthcare: 'ร้านยาและหมอ',
    fitness: 'ฟิตเนส',
    travel_root: 'ท่องเที่ยว',
    flights: 'ตั๋วเครื่องบิน',
    hotels: 'โรงแรม',
    local_travel: 'รถไฟฟ้า',
    family: 'ครอบครัว',
    gifts: 'ของขวัญ',
    education: 'คอร์สเรียน',
    salary_root: 'เงินเดือน',
    salary: 'เงินเดือน',
    bonus: 'โบนัส',
    side_root: 'รายได้เสริม',
    freelance: 'ฟรีแลนซ์',
    consulting: 'ที่ปรึกษา',
    invest_root: 'การลงทุน',
    dividends: 'เงินปันผล',
    interest: 'ดอกเบี้ย',
  },
  budgetName: 'งบประจำเดือน',
  split: {
    merchant: 'MK Restaurants',
    note: 'กินข้าวกับเพื่อน ฉันจ่ายไปก่อน',
    people: ['ต้น', 'แพร', 'บอส'],
  },
  recurring: {
    salary: { name: 'เงินเดือน', note: 'เงินเดือนเข้า' },
    rent: { name: 'ค่าเช่าคอนโด', note: 'ค่าเช่ารายเดือน' },
    fitness: {
      name: 'ฟิตเนส',
      amount: 1500,
      note: 'Jetts Fitness',
      logoId: 'thailand/jetts-fitness',
    },
    subscriptions: [
      { name: 'Netflix', amount: 349, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 139, note: 'Spotify Premium' },
      { name: 'TrueID', amount: 119, note: 'TrueID+', logoId: 'thailand/trueid' },
      { name: 'Disney+ Hotstar', amount: 129, note: 'Disney+ Hotstar' },
      { name: 'iCloud+', amount: 99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'ลงทุน SSF', note: 'ลงทุนรายเดือน' },
  },
  merchants: {
    grocery: ['Lotus’s', 'Big C', 'Tops', 'Gourmet Market', 'Makro'],
    dining: ['MK Restaurants', 'ส้มตำนัว', 'After You', 'Bar B Q Plaza', 'Thipsamai'],
    coffee: ['Café Amazon', 'Starbucks', 'Inthanin', 'True Coffee'],
    fuel: ['PTT', 'Bangchak', 'Shell'],
    shopping: ['Central World', 'Siam Paragon', 'Shopee', 'Lazada'],
    entertainment: ['SF Cinema', 'Major Cineplex', 'Thai Ticket Major'],
    rideshare: ['Grab', 'Bolt'],
    healthcare: ['Boots', 'Watsons', 'Bumrungrad'],
    hotels: ['Hotel Phuket', 'Centara'],
    flights: ['Thai Airways', 'AirAsia'],
    delivery: ['LINE MAN', 'GrabFood', 'foodpanda'],
    convenience: ['7-Eleven', 'FamilyMart', 'Lawson 108'],
  },
  notes: {
    salary: 'เงินเดือน',
    bonus: 'โบนัสสิ้นปี',
    freelance: 'งานฟรีแลนซ์',
    consulting: 'ค่าที่ปรึกษา',
    dividends: 'เงินปันผล',
    interest: 'ดอกเบี้ยเงินฝาก',
    rent: 'ค่าเช่าเดือนนี้',
    utilities: 'ค่าไฟและค่าน้ำ',
    internet: 'AIS Fibre',
    fitness: 'Jetts Fitness',
    homeSupplies: 'ของใช้ในบ้าน',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'คอร์สออนไลน์',
    atmWithdrawal: 'ถอนเงินสด',
    parkingPrimary: 'ที่จอดรถห้าง',
    parkingAlternate: 'ทางด่วน',
    savingsTransfer: 'โอนเข้าบัญชีออม',
    investmentTransfer: 'ลงทุน SSF',
    travelTopUp: 'เงินเที่ยว',
    localTravel: 'Airport Rail Link',
    tripDining: 'กินตอนเที่ยว',
    holidayGifts: 'ของขวัญปีใหม่',
    familyCelebration: 'เลี้ยงครอบครัว',
    cardPayment: 'จ่ายบัตรเครดิต',
  },
});
