import { buildLocalizedProfile } from './localized';

export const turkishProfile = buildLocalizedProfile({
  seed: 20260513,
  locale: 'tr',
  currencyCode: 'TRY',
  currencySymbol: '₺',
  priceScale: 9,
  decimals: 2,
  monthlySalary: 85000,
  monthlyRent: 25000,
  profileName: 'Zeynep Yılmaz',
  accountGroups: { everyday: 'Günlük', goals: 'Hedefler', credit: 'Kredi', investing: 'Yatırım' },
  accounts: {
    checking: { name: 'Garanti BBVA', logoId: 'turkey/garanti-bbva' },
    savings: { name: 'Akbank Vadeli', logoId: 'turkey/akbank' },
    travel: { name: 'Tatil Kumbarası', logoId: 'turkey/enpara' },
    card: { name: 'Yapı Kredi World', logoId: 'turkey/yap-kredi' },
    cash: { name: 'Nakit', logoId: 'global/visa' },
    brokerage: { name: 'Midas', logoId: 'turkey/midas' },
  },
  extraAccounts: [
    { name: 'Papara', type: 'debit', logoId: 'turkey/papara', groupKey: 'everyday' },
    { name: 'İş Bankası', type: 'debit', logoId: 'turkey/isbank', groupKey: 'everyday' },
    { name: 'Ziraat Bankası', type: 'debit', logoId: 'turkey/ziraat-bankas', groupKey: 'goals' },
    { name: 'QNB Kart', type: 'credit', logoId: 'turkey/qnb-finansbank', groupKey: 'credit' },
  ],
  categories: {
    home: 'Ev',
    rent: 'Kira',
    utilities: 'Elektrik & Su',
    internet: 'İnternet',
    home_supplies: 'Ev ihtiyaçları',
    food: 'Yemek',
    groceries: 'Market',
    dining: 'Restoran',
    coffee: 'Kahve',
    transport: 'Ulaşım',
    fuel: 'Akaryakıt',
    rideshare: 'Taksi',
    parking: 'Otopark',
    lifestyle: 'Eğlence',
    shopping: 'Alışveriş',
    entertainment: 'Etkinlik',
    subscriptions: 'Abonelikler',
    health: 'Sağlık',
    healthcare: 'Eczane & doktor',
    fitness: 'Spor salonu',
    travel_root: 'Seyahat',
    flights: 'Uçak',
    hotels: 'Otel',
    local_travel: 'Toplu taşıma',
    family: 'Aile',
    gifts: 'Hediyeler',
    education: 'Kurslar',
    salary_root: 'Maaş',
    salary: 'Maaş',
    bonus: 'İkramiye',
    side_root: 'Ek gelir',
    freelance: 'Serbest iş',
    consulting: 'Danışmanlık',
    invest_root: 'Yatırımlar',
    dividends: 'Temettü',
    interest: 'Faiz',
  },
  budgetName: 'Aylık bütçe',
  split: {
    merchant: 'Hamdi Restoran',
    note: 'Arkadaşlarla akşam yemeği, ben ödedim',
    people: ['Emre', 'Elif', 'Burak'],
  },
  recurring: {
    salary: { name: 'Maaş', note: 'Aylık maaş' },
    rent: { name: 'Kira', note: 'Daire kirası' },
    fitness: { name: 'Spor salonu', amount: 1950, note: 'MACFit', logoId: 'turkey/macfit' },
    subscriptions: [
      { name: 'Netflix', amount: 229.99, note: 'Netflix Standart' },
      { name: 'Spotify', amount: 99, note: 'Spotify Premium' },
      { name: 'Exxen', amount: 199.9, note: 'Exxen', logoId: 'turkey/exxen' },
      { name: 'BluTV', amount: 149.9, note: 'BluTV', logoId: 'turkey/blutv' },
      { name: 'iCloud+', amount: 79.99, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Fon alımı', note: 'Aylık birikim' },
  },
  merchants: {
    grocery: ['Migros', 'A101', 'BİM', 'ŞOK', 'CarrefourSA'],
    dining: ['Hamdi Restoran', 'Kebapçı Halil', 'Nusr-Et', 'Simit Sarayı', 'Big Chefs'],
    coffee: ['Kahve Dünyası', 'Starbucks', 'Espressolab', 'Mado'],
    fuel: ['Opet', 'Shell', 'Petrol Ofisi'],
    shopping: ['Trendyol', 'Hepsiburada', 'LC Waikiki', 'Zara'],
    entertainment: ['Cinemaximum', 'Biletix', 'Zorlu PSM'],
    rideshare: ['BiTaksi', 'Uber'],
    healthcare: ['Eczane', 'Acıbadem', 'Diş hekimi'],
    hotels: ['Otel Bodrum', 'Kapadokya Otel'],
    flights: ['Türk Hava Yolları', 'Pegasus'],
    delivery: ['Yemeksepeti', 'Getir', 'Trendyol Yemek'],
    convenience: ['Getir', 'Bakkal', 'Migros Jet'],
  },
  notes: {
    salary: 'Maaş',
    bonus: 'Yıl sonu ikramiyesi',
    freelance: 'Serbest proje',
    consulting: 'Danışmanlık ücreti',
    dividends: 'Temettü',
    interest: 'Mevduat faizi',
    rent: 'Kira',
    utilities: 'Elektrik & su faturası',
    internet: 'Türk Telekom internet',
    fitness: 'MACFit',
    homeSupplies: 'Ev alışverişi',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Online kurs',
    atmWithdrawal: 'ATM nakit çekme',
    parkingPrimary: 'Otopark',
    parkingAlternate: 'Köprü geçişi',
    savingsTransfer: 'Birikime aktarım',
    investmentTransfer: 'Fon alımı',
    travelTopUp: 'Tatil kumbarası',
    localTravel: 'Havalimanı servisi',
    tripDining: 'Tatilde yemek',
    holidayGifts: 'Bayram hediyeleri',
    familyCelebration: 'Aile yemeği',
    cardPayment: 'Kredi kartı ödemesi',
  },
});
