import { buildLocalizedProfile } from './localized';

export const ukrainianProfile = buildLocalizedProfile({
  seed: 20260512,
  locale: 'uk',
  currencyCode: 'UAH',
  currencySymbol: '₴',
  priceScale: 4.3,
  decimals: 2,
  monthlySalary: 45000,
  monthlyRent: 15000,
  profileName: 'Олена Коваленко',
  accountGroups: { everyday: 'Щоденне', goals: 'Цілі', credit: 'Кредит', investing: 'Інвестиції' },
  accounts: {
    checking: { name: 'Monobank', logoId: 'ukraine/monobank' },
    savings: { name: 'Депозит Приват', logoId: 'ukraine/privat24' },
    travel: { name: 'Банка на відпустку', logoId: 'ukraine/monobank' },
    card: { name: 'Кредитка ПУМБ', logoId: 'ukraine/pumb' },
    cash: { name: 'Готівка', logoId: 'global/visa' },
    brokerage: { name: 'ОВДП', logoId: 'ukraine/ukrsibbank' },
  },
  extraAccounts: [
    { name: 'Sense Bank', type: 'debit', logoId: 'ukraine/sense-bank', groupKey: 'everyday' },
    { name: 'А-Банк', type: 'debit', logoId: 'ukraine/a-bank', groupKey: 'everyday' },
    {
      name: 'Райффайзен',
      type: 'debit',
      logoId: 'ukraine/raiffeisen-bank-ukraine',
      groupKey: 'goals',
    },
    { name: 'Картка Восток', type: 'credit', logoId: 'ukraine/bank-vostok', groupKey: 'credit' },
  ],
  categories: {
    home: 'Житло',
    rent: 'Оренда',
    utilities: 'Комуналка',
    internet: 'Інтернет',
    home_supplies: 'Для дому',
    food: 'Їжа',
    groceries: 'Продукти',
    dining: 'Кафе та ресторани',
    coffee: 'Кава',
    transport: 'Транспорт',
    fuel: 'Пальне',
    rideshare: 'Таксі',
    parking: 'Паркування',
    lifestyle: 'Дозвілля',
    shopping: 'Покупки',
    entertainment: 'Розваги',
    subscriptions: 'Підписки',
    health: "Здоров'я",
    healthcare: 'Аптека та лікар',
    fitness: 'Спорт',
    travel_root: 'Подорожі',
    flights: 'Авіаквитки',
    hotels: 'Готелі',
    local_travel: 'Громадський транспорт',
    family: "Сім'я",
    gifts: 'Подарунки',
    education: 'Навчання',
    salary_root: 'Зарплата',
    salary: 'Зарплата',
    bonus: 'Премія',
    side_root: 'Підробіток',
    freelance: 'Фриланс',
    consulting: 'Консультації',
    invest_root: 'Інвестиції',
    dividends: 'Дивіденди',
    interest: 'Відсотки',
  },
  budgetName: 'Бюджет на місяць',
  split: {
    merchant: 'Пузата Хата',
    note: 'Вечеря з друзями, я заплатила',
    people: ['Андрій', 'Марія', 'Тарас'],
  },
  recurring: {
    salary: { name: 'Зарплата', note: 'Зарплата за місяць' },
    rent: { name: 'Оренда', note: 'Оренда квартири' },
    fitness: { name: 'Спортзал', amount: 1200, note: 'Sport Life', logoId: 'ukraine/sport-life' },
    subscriptions: [
      { name: 'Netflix', amount: 279, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 159, note: 'Spotify Premium' },
      { name: 'MEGOGO', amount: 199, note: 'MEGOGO', logoId: 'ukraine/megogo' },
      { name: 'Київстар ТБ', amount: 149, note: 'Київстар ТБ', logoId: 'ukraine/kyivstar-tv' },
      { name: 'iCloud+', amount: 99, note: 'iCloud 200 ГБ' },
    ],
    investment: { name: 'Купівля ОВДП', note: 'Щомісяця' },
  },
  merchants: {
    grocery: ['Сільпо', 'АТБ', 'Novus', 'Фора', 'Ашан'],
    dining: ['Пузата Хата', 'Львівська майстерня шоколаду', 'Хінкальня', 'Dominos', 'Musafir'],
    coffee: ['Aroma Kava', 'One Love', 'Львівська кава', 'Starbucks'],
    fuel: ['ОККО', 'WOG', 'SOCAR'],
    shopping: ['Rozetka', 'Епіцентр', 'Comfy', 'Prom.ua'],
    entertainment: ['Multiplex', 'Планета Кіно', 'Concert.ua'],
    rideshare: ['Uklon', 'Bolt'],
    healthcare: ['Аптека АНЦ', 'Аптека Доброго Дня', 'Добробут'],
    hotels: ['Готель у Львові', 'Буковель'],
    flights: ['МАУ', 'Wizz Air'],
    delivery: ['Glovo', 'Bolt Food', 'Сільпо доставка'],
    convenience: ['Близенько', 'АТБ', 'WOG Маркет'],
  },
  notes: {
    salary: 'Зарплата',
    bonus: 'Річна премія',
    freelance: 'Фриланс-проєкт',
    consulting: 'Консультація',
    dividends: 'Дивіденди',
    interest: 'Відсотки депозиту',
    rent: 'Оренда за місяць',
    utilities: 'Комунальні послуги',
    internet: 'Домашній інтернет',
    fitness: 'Абонемент у зал',
    homeSupplies: 'Покупки для дому',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Онлайн-курс',
    atmWithdrawal: 'Зняття готівки',
    parkingPrimary: 'Паркування',
    parkingAlternate: 'Паркування в центрі',
    savingsTransfer: 'На депозит',
    investmentTransfer: 'Купівля ОВДП',
    travelTopUp: 'Банка на відпустку',
    localTravel: 'Поїзд до Львова',
    tripDining: 'Їжа в поїздці',
    holidayGifts: 'Новорічні подарунки',
    familyCelebration: 'Сімейна вечеря',
    cardPayment: 'Погашення кредитки',
  },
});
