import { buildLocalizedProfile } from './localized';

export const vietnameseProfile = buildLocalizedProfile({
  seed: 20260518,
  locale: 'vi',
  currencyCode: 'VND',
  currencySymbol: '₫',
  priceScale: 3300,
  decimals: 0,
  monthlySalary: 30000000,
  monthlyRent: 8000000,
  profileName: 'Nguyễn Thu Hà',
  accountGroups: {
    everyday: 'Hằng ngày',
    goals: 'Mục tiêu',
    credit: 'Tín dụng',
    investing: 'Đầu tư',
  },
  accounts: {
    checking: { name: 'Vietcombank', logoId: 'vietnam/vietcombank' },
    savings: { name: 'Tiết kiệm Techcombank', logoId: 'vietnam/techcombank' },
    travel: { name: 'Quỹ du lịch', logoId: 'vietnam/tpbank' },
    card: { name: 'Thẻ tín dụng VPBank', logoId: 'vietnam/vpbank' },
    cash: { name: 'Tiền mặt', logoId: 'global/visa' },
    brokerage: { name: 'Finhay', logoId: 'vietnam/finhay' },
  },
  extraAccounts: [
    { name: 'MoMo', type: 'debit', logoId: 'vietnam/momo', groupKey: 'everyday' },
    { name: 'ZaloPay', type: 'debit', logoId: 'vietnam/zalopay', groupKey: 'everyday' },
    { name: 'BIDV', type: 'debit', logoId: 'vietnam/bidv', groupKey: 'goals' },
    { name: 'Thẻ ACB', type: 'credit', logoId: 'vietnam/acb', groupKey: 'credit' },
  ],
  categories: {
    home: 'Nhà ở',
    rent: 'Tiền thuê nhà',
    utilities: 'Điện nước',
    internet: 'Internet',
    home_supplies: 'Đồ gia dụng',
    food: 'Ăn uống',
    groceries: 'Đi chợ',
    dining: 'Ăn ngoài',
    coffee: 'Cà phê',
    transport: 'Đi lại',
    fuel: 'Xăng',
    rideshare: 'Gọi xe',
    parking: 'Gửi xe',
    lifestyle: 'Giải trí',
    shopping: 'Mua sắm',
    entertainment: 'Vui chơi',
    subscriptions: 'Đăng ký',
    health: 'Sức khỏe',
    healthcare: 'Nhà thuốc & bác sĩ',
    fitness: 'Phòng gym',
    travel_root: 'Du lịch',
    flights: 'Vé máy bay',
    hotels: 'Khách sạn',
    local_travel: 'Đi lại địa phương',
    family: 'Gia đình',
    gifts: 'Quà & lì xì',
    education: 'Khóa học',
    salary_root: 'Lương',
    salary: 'Lương',
    bonus: 'Thưởng',
    side_root: 'Thu nhập phụ',
    freelance: 'Freelance',
    consulting: 'Tư vấn',
    invest_root: 'Đầu tư',
    dividends: 'Cổ tức',
    interest: 'Lãi tiết kiệm',
  },
  budgetName: 'Ngân sách tháng',
  split: {
    merchant: 'Lẩu Phan',
    note: 'Ăn tối với bạn, mình trả trước',
    people: ['Minh', 'Linh', 'Tuấn'],
  },
  recurring: {
    salary: { name: 'Lương', note: 'Lương tháng' },
    rent: { name: 'Tiền nhà', note: 'Thuê căn hộ' },
    fitness: {
      name: 'Phòng gym',
      amount: 800000,
      note: 'California Fitness',
      logoId: 'vietnam/california-fitness',
    },
    subscriptions: [
      { name: 'Netflix', amount: 220000, note: 'Netflix Standard' },
      { name: 'Spotify', amount: 59000, note: 'Spotify Premium' },
      { name: 'FPT Play', amount: 80000, note: 'FPT Play', logoId: 'vietnam/fpt-play' },
      { name: 'Zing MP3', amount: 49000, note: 'Zing MP3 VIP', logoId: 'vietnam/zing-mp3' },
      { name: 'iCloud+', amount: 59000, note: 'iCloud 200 GB' },
    ],
    investment: { name: 'Chứng chỉ quỹ', note: 'Đầu tư hằng tháng' },
  },
  merchants: {
    grocery: ['WinMart', 'Co.opmart', 'Bách Hóa Xanh', 'AEON Mall', 'Lotte Mart'],
    dining: ['Lẩu Phan', 'Phở Thìn', 'Bún chả Hương Liên', 'Pizza 4P’s', 'Cơm Tấm Ba Ghiền'],
    coffee: ['Highlands Coffee', 'Phúc Long', 'The Coffee House', 'Cộng Cà Phê'],
    fuel: ['Petrolimex', 'PV Oil', 'Mipec'],
    shopping: ['Shopee', 'Lazada', 'Tiki', 'Vincom'],
    entertainment: ['CGV', 'Galaxy Cinema', 'Lotte Cinema'],
    rideshare: ['Grab', 'Be'],
    healthcare: ['Long Châu', 'Pharmacity', 'Vinmec'],
    hotels: ['Khách sạn Đà Lạt', 'Vinpearl'],
    flights: ['Vietnam Airlines', 'Vietjet'],
    delivery: ['ShopeeFood', 'GrabFood', 'Baemin'],
    convenience: ['Circle K', 'GS25', 'FamilyMart'],
  },
  notes: {
    salary: 'Lương',
    bonus: 'Thưởng Tết',
    freelance: 'Dự án freelance',
    consulting: 'Phí tư vấn',
    dividends: 'Cổ tức',
    interest: 'Lãi tiết kiệm',
    rent: 'Tiền nhà tháng này',
    utilities: 'Tiền điện nước',
    internet: 'Internet Viettel',
    fitness: 'California Fitness',
    homeSupplies: 'Đồ dùng trong nhà',
    subscriptions: ['Netflix', 'Spotify', 'iCloud'],
    education: 'Khóa học online',
    atmWithdrawal: 'Rút tiền ATM',
    parkingPrimary: 'Gửi xe trung tâm thương mại',
    parkingAlternate: 'Gửi xe máy',
    savingsTransfer: 'Chuyển tiết kiệm',
    investmentTransfer: 'Mua chứng chỉ quỹ',
    travelTopUp: 'Quỹ du lịch',
    localTravel: 'Taxi ra sân bay',
    tripDining: 'Ăn uống khi đi chơi',
    holidayGifts: 'Lì xì Tết',
    familyCelebration: 'Họp mặt gia đình',
    cardPayment: 'Thanh toán thẻ tín dụng',
  },
});
