const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/**
 * Android "share a screenshot to log it": the Android counterpart of the iOS
 * "Log Screenshot" Shortcuts action (see withMoney2TimeAutoLog.js).
 *
 * Android has no Back Tap and no Shortcuts, but it has something better suited
 * to the job: the system share sheet. This plugin registers money2time as a
 * share target for images. Sharing a screenshot (or a photo of a receipt) from
 * the gallery, the screenshot toolbar or any app lands in `ShareScanActivity`,
 * which copies the images into the app's own files directory and opens the app.
 * The app then drains that folder through the same screenshot-scan pipeline the
 * iOS intent feeds (`ScreenshotScanSync` in App.tsx), so the Worker mode,
 * account detection, "save screenshot" opt-in and silent auto-create all stay in
 * one place.
 *
 * Three decisions here are deliberate:
 *
 * - **A dedicated activity, not filters on MainActivity.** Picking an alternate
 *   app icon disables MainActivity (see withAndroidAlternateIcons.js), and a
 *   share target on a disabled component silently vanishes from the share
 *   sheet. This activity is never disabled, and it opens the app through
 *   `getLaunchIntentForPackage`, which resolves to whichever launcher entry is
 *   live.
 * - **Copy before handing off.** A shared `content://` URI is only readable
 *   while the grant the sender gave this activity lasts, so the bytes are
 *   copied here rather than passed along for JS to read later. The app never
 *   sees the sender's URI at all.
 * - **A folder, not a JSON queue.** Each image is written as `<part>` then
 *   renamed into place, so a file the drain can see is always complete, and the
 *   folder listing is the queue. The file name carries the share time
 *   (`<epochMillis>-<uuid>.<ext>`), which is all the drain needs to order and
 *   identify an entry. `parseSharedScanFileNames` in
 *   features/transactions/lib/autoLog.ts reads it.
 */

const PACKAGE_PATH = 'com/nelsongan/money2time';
const SHARE_PACKAGE = 'com.nelsongan.money2time.share';
const ACTIVITY_NAME = '.share.ShareScanActivity';
/** Must match SHARED_SCANS_DIR in features/transactions/lib/autoLog.ts. */
const SHARED_SCANS_DIR = 'shared-scans';
/** A share of more than this many images keeps the first ones only. */
const MAX_IMAGES_PER_SHARE = 10;
/** Larger files are skipped: no screenshot or phone photo comes near this. */
const MAX_IMAGE_BYTES = 30 * 1024 * 1024;

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfChanged(filePath, contents) {
  ensureDir(path.dirname(filePath));
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === contents) return;
  fs.writeFileSync(filePath, contents);
}

const SHARE_ACTIVITY_SOURCE = `package ${SHARE_PACKAGE}

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.util.Log
import java.io.File
import java.util.UUID

/**
 * Generated by plugins/withMoney2TimeShareScan.js. Do not edit by hand.
 *
 * Receives images shared to money2time, copies them into
 * filesDir/${SHARED_SCANS_DIR}, then opens the app, which scans them in the
 * background. Has no UI of its own (translucent theme, finishes immediately).
 */
class ShareScanActivity : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val uris = sharedUris(intent).take(${MAX_IMAGES_PER_SHARE})
    Thread {
      uris.forEach { uri ->
        try {
          copyIntoQueue(uri)
        } catch (error: Exception) {
          // One unreadable item must not cost the rest of the share.
          Log.w(TAG, "Could not copy shared image", error)
        }
      }
      runOnUiThread {
        openApp()
        finish()
      }
    }.start()
  }

  private fun sharedUris(intent: Intent?): List<Uri> {
    if (intent == null) return emptyList()
    val found = LinkedHashSet<Uri>()
    when (intent.action) {
      Intent.ACTION_SEND -> streamExtra(intent)?.let { found.add(it) }
      Intent.ACTION_SEND_MULTIPLE -> streamListExtra(intent)?.let { found.addAll(it) }
    }
    // Some senders only fill ClipData (it is what carries the read grant).
    intent.clipData?.let { clip ->
      for (i in 0 until clip.itemCount) clip.getItemAt(i).uri?.let { found.add(it) }
    }
    return found.toList()
  }

  @Suppress("DEPRECATION")
  private fun streamExtra(intent: Intent): Uri? =
    if (Build.VERSION.SDK_INT >= 33) {
      intent.getParcelableExtra(Intent.EXTRA_STREAM, Uri::class.java)
    } else {
      intent.getParcelableExtra(Intent.EXTRA_STREAM) as? Uri
    }

  @Suppress("DEPRECATION")
  private fun streamListExtra(intent: Intent): List<Uri>? =
    if (Build.VERSION.SDK_INT >= 33) {
      intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM, Uri::class.java)
    } else {
      intent.getParcelableArrayListExtra<Uri>(Intent.EXTRA_STREAM)
    }

  private fun copyIntoQueue(uri: Uri) {
    val mime = contentResolver.getType(uri) ?: ""
    if (!mime.startsWith("image/")) return
    val dir = File(filesDir, "${SHARED_SCANS_DIR}")
    if (!dir.exists() && !dir.mkdirs()) return
    val name = "\${System.currentTimeMillis()}-\${UUID.randomUUID()}.\${extensionFor(mime)}"
    val part = File(dir, "$name.part")
    var written = 0L
    var tooLarge = false
    contentResolver.openInputStream(uri)?.use { input ->
      part.outputStream().use { output ->
        val buffer = ByteArray(64 * 1024)
        while (true) {
          val read = input.read(buffer)
          if (read < 0) break
          written += read
          if (written > ${MAX_IMAGE_BYTES}L) {
            tooLarge = true
            break
          }
          output.write(buffer, 0, read)
        }
      }
    } ?: return
    // Only a complete file is renamed into place, so the drain never reads a
    // half-written image.
    if (tooLarge || written == 0L || !part.renameTo(File(dir, name))) part.delete()
  }

  private fun extensionFor(mime: String): String =
    when (mime.lowercase()) {
      "image/png" -> "png"
      "image/webp" -> "webp"
      "image/heic", "image/heif" -> "heic"
      else -> "jpg"
    }

  private fun openApp() {
    val launch = packageManager.getLaunchIntentForPackage(packageName) ?: return
    launch.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
    try {
      startActivity(launch)
    } catch (error: Exception) {
      Log.w(TAG, "Could not open the app after a share", error)
    }
  }

  companion object {
    private const val TAG = "Money2TimeShareScan"
  }
}
`;

function withShareScanActivitySource(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const sourceRoot = path.join(
        cfg.modRequest.projectRoot,
        'android/app/src/main/java',
        PACKAGE_PATH,
      );
      writeFileIfChanged(
        path.join(sourceRoot, 'share/ShareScanActivity.kt'),
        SHARE_ACTIVITY_SOURCE,
      );
      return cfg;
    },
  ]);
}

function imageSendFilter(action) {
  return {
    action: [{ $: { 'android:name': action } }],
    category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
    data: [{ $: { 'android:mimeType': 'image/*' } }],
  };
}

function withShareScanActivityManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.activity = (app.activity ?? []).filter(
      (activity) => activity.$?.['android:name'] !== ACTIVITY_NAME,
    );
    app.activity.push({
      $: {
        'android:name': ACTIVITY_NAME,
        'android:exported': 'true',
        // No UI: the activity copies the images and hands off to the app. Its
        // own task affinity and noHistory keep it out of the sender's back
        // stack and out of recents.
        'android:theme': '@android:style/Theme.Translucent.NoTitleBar',
        'android:excludeFromRecents': 'true',
        'android:noHistory': 'true',
        'android:taskAffinity': '',
      },
      'intent-filter': [
        imageSendFilter('android.intent.action.SEND'),
        imageSendFilter('android.intent.action.SEND_MULTIPLE'),
      ],
    });
    return cfg;
  });
}

module.exports = function withMoney2TimeShareScan(config) {
  config = withShareScanActivityManifest(config);
  config = withShareScanActivitySource(config);
  return config;
};

module.exports.SHARED_SCANS_DIR = SHARED_SCANS_DIR;
