const fs = require('fs');
const path = require('path');

const {
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require('@expo/config-plugins');

/**
 * iOS auto-log: the App Intents that back the Shortcuts "Transaction"
 * automation (Mode A) and Back Tap (Mode B).
 *
 * Everything lives in the HOST app target rather than an App Intents
 * extension: it needs no new bundle id or provisioning profile, and it keeps
 * `app.config.ts`'s dev-variant plugin filter (which is name-specific to
 * withMoney2TimeWidgets) from having to know about a second target whose
 * hardcoded bundle id would not be a child of `com.nelsongan.money2time.dev`.
 * The cost is that iOS background-launches the app to run the intent; the
 * intent itself touches no React Native and returns as soon as it has written
 * to the App Group, so the Swift here ports to an extension unchanged if that
 * ever needs to happen.
 *
 * The intent never touches the database. It queues taps into the App Group and
 * the app drains them through the normal `createTransaction` path, so the FX
 * snapshot / album auto-add / account-amount rules stay in one tested place.
 *
 * The Xcode/file helpers below are intentional copies of the private ones in
 * withMoney2TimeWidgets.js — config plugins are conventionally self-contained,
 * and hoisting them would mean editing a working 5k-line widget generator.
 */

const APP_GROUP = 'group.com.nelsongan.money2time.widgets';
const CATALOG_KEY = 'autolog_catalog';
const PENDING_KEY = 'autolog_pending';
const CATALOG_SCHEMA_VERSION = 1;
const IOS_APP_TARGET_NAME = 'Money2Time';
/**
 * Back Tap deep link. The `action` is whatever the user picked in Auto-log
 * settings (quick | full | scan | voice), carried in the catalog; the app's
 * deep-link handler falls back to quick entry if it is missing or unknown.
 */
const ADD_URL_PREFIX = 'money2time://add?action=';
const DEFAULT_BACK_TAP_ACTION = 'quick';
/**
 * Seconds within which a re-run of `perform()` (after the category prompt is
 * answered) is treated as the same tap. See `upsertProvisional` in the Swift.
 */
const UPSERT_WINDOW_SECONDS = 120;

const SWIFT_SOURCES = [
  'Money2TimeAutoLogStore.swift',
  'Money2TimeAutoLogEntities.swift',
  'Money2TimeLogTransactionIntent.swift',
  'Money2TimeAddTransactionIntent.swift',
  'Money2TimeAppShortcuts.swift',
  'Money2TimeAutoLogModule.swift',
];

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfChanged(filePath, contents) {
  ensureDir(path.dirname(filePath));
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === contents) return;
  fs.writeFileSync(filePath, contents);
}

function unquoteXcodeValue(value) {
  return typeof value === 'string' ? value.replace(/^"|"$/g, '') : value;
}

function findNativeTargetByName(project, name) {
  const targets = project.pbxNativeTargetSection();
  const entry = Object.entries(targets).find(([key, target]) => {
    if (key.endsWith('_comment')) return false;
    return unquoteXcodeValue(target.name) === name;
  });
  if (!entry) return null;
  return { uuid: entry[0], ...entry[1] };
}

function getOrCreateGroup(project, name, groupPath) {
  const existingGroup = project.pbxGroupByName(name);
  if (existingGroup) {
    return project.findPBXGroupKey({ name });
  }

  const group = project.addPbxGroup([], name, groupPath);
  const mainGroupKey = project.getFirstProject().firstProject.mainGroup;
  project.hash.project.objects.PBXGroup[mainGroupKey].children.push({
    value: group.uuid,
    comment: name,
  });
  return group.uuid;
}

function ensureSourceFile(project, filePath, targetUuid, groupKey) {
  const basename = path.basename(filePath);
  const existingFileReference = Object.values(project.pbxFileReferenceSection()).find(
    (entry) => entry && entry.name === `"${basename}"`,
  );
  if (existingFileReference) {
    existingFileReference.path = `"${filePath}"`;
  }

  const fileExists = Object.values(project.pbxBuildFileSection()).some(
    (entry) => entry && entry.fileRef_comment === basename,
  );
  if (fileExists) return;
  project.addSourceFile(filePath, { target: targetUuid }, groupKey);
}

// ---------------------------------------------------------------------------
// Swift sources
// ---------------------------------------------------------------------------

const AUTO_LOG_STORE_SWIFT = `import Foundation

/// Shared App Group storage for auto-log.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.
enum AutoLogStore {
  static let appGroup = "${APP_GROUP}"
  static let catalogKey = "${CATALOG_KEY}"
  static let pendingKey = "${PENDING_KEY}"
  static let schemaVersion = ${CATALOG_SCHEMA_VERSION}
  static let upsertWindow: TimeInterval = ${UPSERT_WINDOW_SECONDS}

  struct CatalogAccount: Codable {
    let id: String
    let name: String
    let currency: String
  }

  struct CatalogCategory: Codable {
    let id: String
    let name: String
    let emoji: String
  }

  struct Catalog: Codable {
    let schemaVersion: Int
    let reportingCurrency: String
    let isSimpleMode: Bool
    let isPro: Bool
    /// nil means unlimited (Pro).
    let remaining: Int?
    let defaultAccountId: String?
    let defaultExpenseCategoryId: String?
    /// Entry flow Back Tap opens: quick | full | scan | voice.
    let backTapAction: String?
    let accounts: [CatalogAccount]
    let categories: [CatalogCategory]
  }

  struct PendingEntry: Codable {
    var id: String
    var createdAt: String
    var amountRaw: String
    var merchant: String?
    var cardName: String?
    var accountId: String?
    var categoryId: String?
    var provisional: Bool
  }

  static var defaults: UserDefaults? {
    UserDefaults(suiteName: appGroup)
  }

  private static let isoFormatter: ISO8601DateFormatter = {
    let formatter = ISO8601DateFormatter()
    formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    return formatter
  }()

  /// The catalog the app publishes. A version we do not recognise is treated as
  /// absent so a stale build never renders a picker from a shape it misreads.
  static func loadCatalog() -> Catalog? {
    guard
      let json = defaults?.string(forKey: catalogKey),
      let data = json.data(using: .utf8),
      let catalog = try? JSONDecoder().decode(Catalog.self, from: data),
      catalog.schemaVersion == schemaVersion
    else {
      return nil
    }
    return catalog
  }

  static func loadPending() -> [PendingEntry] {
    guard
      let json = defaults?.string(forKey: pendingKey),
      let data = json.data(using: .utf8),
      let entries = try? JSONDecoder().decode([PendingEntry].self, from: data)
    else {
      return []
    }
    return entries
  }

  static func savePending(_ entries: [PendingEntry]) {
    guard
      let data = try? JSONEncoder().encode(entries),
      let json = String(data: data, encoding: .utf8)
    else {
      return
    }
    defaults?.set(json, forKey: pendingKey)
    defaults?.synchronize()
  }

  /// Auto-logs still allowed before the free cap bites.
  ///
  /// Queued rows have not reached the app's lifetime counter yet, so they are
  /// subtracted here. The app recomputes \`remaining\` every time it rewrites the
  /// catalog, so the two self-correct without any extra shared counter.
  static func remaining(catalog: Catalog) -> Int {
    guard let remaining = catalog.remaining else { return Int.max }
    return max(0, remaining - loadPending().count)
  }

  /// Id of the provisional row this run would merge onto, if any.
  ///
  /// Non-nil means \`perform()\` is running a second time for a tap that is
  /// already queued, which is what tells the intent to skip the free-limit
  /// check: the row is committed, and re-checking would reject the user's own
  /// answer on their last free auto-log.
  static func provisionalMatchId(
    amountRaw: String,
    merchant: String?,
    cardName: String?
  ) -> String? {
    let now = Date()
    return loadPending().first { entry in
      guard entry.provisional else { return false }
      guard
        entry.amountRaw == amountRaw,
        entry.merchant == merchant,
        entry.cardName == cardName
      else {
        return false
      }
      guard let created = isoFormatter.date(from: entry.createdAt) else { return false }
      return now.timeIntervalSince(created) <= upsertWindow
    }?.id
  }

  /// Queue a tap, or patch the row this same run already queued.
  ///
  /// App Intents re-invokes \`perform()\` from the top once a parameter prompt is
  /// answered, so a plain append would log the same tap twice. Matching an
  /// existing *provisional* row on (amount, merchant, card) inside
  /// \`upsertWindow\` collapses that re-run onto the original row.
  ///
  /// Known edge: two genuinely identical purchases — same amount, same
  /// merchant, same card — both left un-answered inside the window would merge
  /// into one. Rare, and it only ever costs a duplicate, never the first tap.
  @discardableResult
  static func upsertProvisional(
    amountRaw: String,
    merchant: String?,
    cardName: String?,
    accountId: String?,
    categoryId: String?
  ) -> String {
    var entries = loadPending()
    let now = Date()

    let matchId = provisionalMatchId(amountRaw: amountRaw, merchant: merchant, cardName: cardName)
    let match = matchId.flatMap { id in entries.firstIndex { $0.id == id } }

    if let index = match {
      // createdAt stays put: it is the tap time, not the retry time.
      if let accountId = accountId {
        entries[index].accountId = accountId
      }
      if let categoryId = categoryId {
        entries[index].categoryId = categoryId
      }
      let id = entries[index].id
      savePending(entries)
      return id
    }

    let entry = PendingEntry(
      id: UUID().uuidString,
      createdAt: isoFormatter.string(from: now),
      amountRaw: amountRaw,
      merchant: merchant,
      cardName: cardName,
      accountId: accountId,
      categoryId: categoryId,
      provisional: true
    )
    entries.append(entry)
    savePending(entries)
    return entry.id
  }

  /// Settle a row so no later run can merge onto it.
  static func finalize(id: String, categoryId: String?) {
    var entries = loadPending()
    guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
    if let categoryId = categoryId {
      entries[index].categoryId = categoryId
    }
    entries[index].provisional = false
    savePending(entries)
  }

  static func clearPending(ids: [String]) {
    let removing = Set(ids)
    savePending(loadPending().filter { !removing.contains($0.id) })
  }
}

enum AutoLogError: Error, CustomLocalizedStringResourceConvertible {
  case notReady
  case limitReached

  var localizedStringResource: LocalizedStringResource {
    switch self {
    case .notReady:
      return "Open Money2Time once to finish setting up auto-log."
    case .limitReached:
      return "You have used all your free auto-logs. Upgrade to Pro in Money2Time for unlimited."
    }
  }
}
`;

const AUTO_LOG_ENTITIES_SWIFT = `import AppIntents
import Foundation

/// Account / category pickers for the auto-log intents, populated from the
/// catalog the app publishes into the App Group.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.

struct AutoLogAccountEntity: AppEntity {
  let id: String
  let name: String
  let currency: String

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    TypeDisplayRepresentation(name: "Account")
  }

  var displayRepresentation: DisplayRepresentation {
    DisplayRepresentation(title: "\\(name)", subtitle: "\\(currency)")
  }

  static var defaultQuery: AutoLogAccountQuery { AutoLogAccountQuery() }
}

struct AutoLogAccountQuery: EntityQuery {
  func entities(for identifiers: [String]) async throws -> [AutoLogAccountEntity] {
    let all = try await suggestedEntities()
    return all.filter { identifiers.contains($0.id) }
  }

  func suggestedEntities() async throws -> [AutoLogAccountEntity] {
    guard let catalog = AutoLogStore.loadCatalog() else { return [] }
    return catalog.accounts.map {
      AutoLogAccountEntity(id: $0.id, name: $0.name, currency: $0.currency)
    }
  }
}

struct AutoLogCategoryEntity: AppEntity {
  let id: String
  let name: String
  let emoji: String

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    TypeDisplayRepresentation(name: "Category")
  }

  var displayRepresentation: DisplayRepresentation {
    let label = emoji.isEmpty ? name : "\\(emoji) \\(name)"
    return DisplayRepresentation(title: "\\(label)")
  }

  static var defaultQuery: AutoLogCategoryQuery { AutoLogCategoryQuery() }
}

struct AutoLogCategoryQuery: EntityQuery {
  func entities(for identifiers: [String]) async throws -> [AutoLogCategoryEntity] {
    let all = try await suggestedEntities()
    return all.filter { identifiers.contains($0.id) }
  }

  func suggestedEntities() async throws -> [AutoLogCategoryEntity] {
    guard let catalog = AutoLogStore.loadCatalog() else { return [] }
    return catalog.categories.map {
      AutoLogCategoryEntity(id: $0.id, name: $0.name, emoji: $0.emoji)
    }
  }
}
`;

const LOG_TRANSACTION_INTENT_SWIFT = `import AppIntents
import Foundation

/// Mode A: the action a Shortcuts "Transaction" automation runs on every
/// Apple Pay tap. Amount / Merchant / Card come from the trigger; Account is
/// normally preset per automation so a card lands in its own account.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.
struct LogTransactionIntent: AppIntent {
  static var title: LocalizedStringResource = "Log Transaction"

  static var description = IntentDescription(
    "Log a tap-to-pay transaction to Money2Time. Leave Category set to Ask Each Time to choose one as you pay; otherwise your default category is used.",
    categoryName: "Transactions"
  )

  /// Stays in the background: the whole job is a small App Group write.
  static var openAppWhenRun: Bool = false

  @Parameter(title: "Amount")
  var amount: String

  @Parameter(title: "Merchant")
  var merchant: String?

  @Parameter(title: "Card")
  var card: String?

  @Parameter(title: "Account")
  var account: AutoLogAccountEntity?

  @Parameter(title: "Category")
  var category: AutoLogCategoryEntity?

  static var parameterSummary: some ParameterSummary {
    Summary("Log \\(\\.$amount) at \\(\\.$merchant)") {
      \\.$card
      \\.$account
      \\.$category
    }
  }

  func perform() async throws -> some IntentResult {
    guard let catalog = AutoLogStore.loadCatalog() else {
      throw AutoLogError.notReady
    }
    // Only gate a brand-new tap. On the re-run after the category prompt the
    // row is already queued and already counted against \`remaining\`, so
    // re-checking here would throw "limit reached" at the exact moment the user
    // answers the prompt on their last free auto-log, discarding their pick.
    let isRerun =
      AutoLogStore.provisionalMatchId(amountRaw: amount, merchant: merchant, cardName: card) != nil
    if !isRerun, AutoLogStore.remaining(catalog: catalog) <= 0 {
      throw AutoLogError.limitReached
    }

    // Queue first, ask second. This is what makes the tap survive an ignored
    // prompt: the row already exists (with whatever category we know) before
    // any UI is requested. The upsert is what keeps the re-run from doubling
    // it — see AutoLogStore.upsertProvisional.
    let id = AutoLogStore.upsertProvisional(
      amountRaw: amount,
      merchant: merchant,
      cardName: card,
      accountId: account?.id,
      categoryId: category?.id
    )

    // Preset at setup time, or answered and re-run: nothing left to ask.
    if let category = category {
      AutoLogStore.finalize(id: id, categoryId: category.id)
      return .result()
    }

    let options = catalog.categories.map {
      AutoLogCategoryEntity(id: $0.id, name: $0.name, emoji: $0.emoji)
    }
    guard !options.isEmpty else { return .result() }

    // Must be allowed to throw: App Intents catches it, prompts, and re-invokes
    // perform() with \`category\` populated, which returns above. If the user
    // never answers, the row queued above simply drains with the default
    // category. Handling a returned value too keeps this correct whichever way
    // the framework resolves the request.
    let picked = try await $category.requestDisambiguation(
      among: options,
      dialog: "Which category?"
    )
    AutoLogStore.finalize(id: id, categoryId: picked.id)
    return .result()
  }
}
`;

const ADD_TRANSACTION_INTENT_SWIFT = `import AppIntents
import Foundation
import UIKit

/// Mode B: what Back Tap runs. Opens whichever entry flow the user chose in
/// Auto-log settings, by deep link — so the app's existing add-action
/// dispatcher does the work and no routing is duplicated here.
///
/// Back Tap only lists shortcuts the user has saved in the Shortcuts app, so
/// this intent has to be wrapped in a one-action shortcut before it can be
/// assigned — the in-app tutorial walks through that.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.
struct AddTransactionIntent: AppIntent {
  static var title: LocalizedStringResource = "Add Transaction"

  static var description = IntentDescription(
    "Open Money2Time on the entry screen you picked in Auto-log settings.",
    categoryName: "Transactions"
  )

  static var openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    // No catalog yet (app never opened) still opens quick entry rather than
    // doing nothing — a gesture that silently no-ops reads as broken.
    let action = AutoLogStore.loadCatalog()?.backTapAction ?? "${DEFAULT_BACK_TAP_ACTION}"
    if let url = URL(string: "${ADD_URL_PREFIX}\\(action)") {
      await UIApplication.shared.open(url)
    }
    return .result()
  }
}
`;

const APP_SHORTCUTS_SWIFT = `import AppIntents

/// Surfaces the intents in the Shortcuts app and Siri without any setup.
///
/// Only the open-the-app intent is offered as a phrase: LogTransactionIntent
/// needs an Amount from the automation trigger, so it is not something worth
/// asking Siri for. It is still available in the Shortcuts action list.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.
struct Money2TimeAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: AddTransactionIntent(),
      phrases: [
        "Add a transaction in \\(.applicationName)",
        "Log an expense in \\(.applicationName)",
        "New transaction in \\(.applicationName)",
      ],
      shortTitle: "Add Transaction",
      systemImageName: "plus.circle.fill"
    )
  }
}
`;

const AUTO_LOG_MODULE_SWIFT = `import Foundation
import React

/// React Native bridge to the auto-log App Group store. Mirrors
/// Money2TimeWidgetModule.swift.
///
/// Generated by plugins/withMoney2TimeAutoLog.js — edit the plugin, not this file.
@objc(Money2TimeAutoLog)
class Money2TimeAutoLog: NSObject {
  @objc
  static func requiresMainQueueSetup() -> Bool {
    false
  }

  @objc(writeCatalog:resolver:rejecter:)
  func writeCatalog(
    _ json: String,
    resolver resolve: RCTPromiseResolveBlock,
    rejecter reject: RCTPromiseRejectBlock
  ) {
    guard let defaults = AutoLogStore.defaults else {
      reject("autolog_app_group_unavailable", "Money2Time App Group is unavailable.", nil)
      return
    }

    defaults.set(json, forKey: AutoLogStore.catalogKey)
    defaults.synchronize()
    resolve(nil)
  }

  @objc(readPending:rejecter:)
  func readPending(
    _ resolve: RCTPromiseResolveBlock,
    rejecter reject: RCTPromiseRejectBlock
  ) {
    guard let defaults = AutoLogStore.defaults else {
      reject("autolog_app_group_unavailable", "Money2Time App Group is unavailable.", nil)
      return
    }

    resolve(defaults.string(forKey: AutoLogStore.pendingKey))
  }

  @objc(clearPending:resolver:rejecter:)
  func clearPending(
    _ ids: [String],
    resolver resolve: RCTPromiseResolveBlock,
    rejecter reject: RCTPromiseRejectBlock
  ) {
    AutoLogStore.clearPending(ids: ids)
    resolve(nil)
  }

  #if DEBUG
  /// Queue a tap exactly as LogTransactionIntent would, for the dev-only test
  /// button. A simulator has neither NFC nor the Shortcuts app, so this is the
  /// only way to exercise the real queue-and-drain path there.
  ///
  /// It calls the same \`upsertProvisional\` the intent does, then settles the row
  /// so the drain posts it immediately rather than waiting out the
  /// category-prompt window.
  @objc(enqueueTestTap:merchant:card:resolver:rejecter:)
  func enqueueTestTap(
    _ amountRaw: String,
    merchant: String?,
    card: String?,
    resolver resolve: RCTPromiseResolveBlock,
    rejecter reject: RCTPromiseRejectBlock
  ) {
    let id = AutoLogStore.upsertProvisional(
      amountRaw: amountRaw,
      merchant: merchant,
      cardName: card,
      accountId: nil,
      categoryId: nil
    )
    AutoLogStore.finalize(id: id, categoryId: nil)
    resolve(id)
  }
  #endif
}
`;

const AUTO_LOG_MODULE_OBJC = `#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(Money2TimeAutoLog, NSObject)

RCT_EXTERN_METHOD(writeCatalog:(NSString *)json
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(readPending:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(clearPending:(NSArray *)ids
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

#if DEBUG
RCT_EXTERN_METHOD(enqueueTestTap:(NSString *)amountRaw
                  merchant:(NSString *)merchant
                  card:(NSString *)card
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
#endif

@end
`;

// ---------------------------------------------------------------------------
// Mods
// ---------------------------------------------------------------------------

function addIosAutoLogFiles(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const appRoot = path.join(cfg.modRequest.projectRoot, 'ios', IOS_APP_TARGET_NAME);

      writeFileIfChanged(path.join(appRoot, 'Money2TimeAutoLogStore.swift'), AUTO_LOG_STORE_SWIFT);
      writeFileIfChanged(
        path.join(appRoot, 'Money2TimeAutoLogEntities.swift'),
        AUTO_LOG_ENTITIES_SWIFT,
      );
      writeFileIfChanged(
        path.join(appRoot, 'Money2TimeLogTransactionIntent.swift'),
        LOG_TRANSACTION_INTENT_SWIFT,
      );
      writeFileIfChanged(
        path.join(appRoot, 'Money2TimeAddTransactionIntent.swift'),
        ADD_TRANSACTION_INTENT_SWIFT,
      );
      writeFileIfChanged(path.join(appRoot, 'Money2TimeAppShortcuts.swift'), APP_SHORTCUTS_SWIFT);
      writeFileIfChanged(
        path.join(appRoot, 'Money2TimeAutoLogModule.swift'),
        AUTO_LOG_MODULE_SWIFT,
      );
      writeFileIfChanged(path.join(appRoot, 'Money2TimeAutoLogModule.m'), AUTO_LOG_MODULE_OBJC);

      return cfg;
    },
  ]);
}

/**
 * The widget plugin already adds this group, but `app.config.ts` strips that
 * plugin from the dev variant — so auto-log has to add it itself or dev builds
 * lose the App Group entirely. Idempotent, so the two can overlap safely.
 */
function addIosAutoLogEntitlements(config) {
  return withEntitlementsPlist(config, (cfg) => {
    const groups = cfg.modResults['com.apple.security.application-groups'] ?? [];
    if (!groups.includes(APP_GROUP)) {
      cfg.modResults['com.apple.security.application-groups'] = [...groups, APP_GROUP];
    }
    return cfg;
  });
}

function ensureIosAutoLogSources(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appTarget = findNativeTargetByName(project, IOS_APP_TARGET_NAME);
    if (!appTarget) return cfg;

    const appGroupKey = getOrCreateGroup(project, IOS_APP_TARGET_NAME, IOS_APP_TARGET_NAME);

    for (const source of SWIFT_SOURCES) {
      ensureSourceFile(project, `${IOS_APP_TARGET_NAME}/${source}`, appTarget.uuid, appGroupKey);
    }
    ensureSourceFile(
      project,
      `${IOS_APP_TARGET_NAME}/Money2TimeAutoLogModule.m`,
      appTarget.uuid,
      appGroupKey,
    );

    return cfg;
  });
}

module.exports = function withMoney2TimeAutoLog(config) {
  config = addIosAutoLogEntitlements(config);
  // Dangerous mods run before xcodeproj mods, so the files exist by the time
  // the project references them.
  config = addIosAutoLogFiles(config);
  config = ensureIosAutoLogSources(config);
  return config;
};
