import { LOG_NOTIFICATION_INTENT_NAME } from '~/constants/autoLogIntents';
import { parseIosPendingAlertsJson } from '~/features/autoLog/lib/captureQueue';

// The Log Notification action is Swift generated by the plugin; the app reads
// its queue in TypeScript. Shortcuts shows the Swift title verbatim, and the
// queue is decoded by field name, so both are pinned here.
const plugin = require('../../plugins/withMoney2TimeAutoLog.js') as {
  LOG_PAYMENT_ALERT_INTENT_SWIFT: string;
  AUTO_LOG_STORE_SWIFT: string;
  PENDING_ALERTS_KEY: string;
};

describe('Log Notification (withMoney2TimeAutoLog)', () => {
  const swift = plugin.LOG_PAYMENT_ALERT_INTENT_SWIFT;

  it('is titled as Settings and the tutorials name it', () => {
    expect(swift).toContain(
      `static var title: LocalizedStringResource = "${LOG_NOTIFICATION_INTENT_NAME}"`,
    );
  });

  it('keeps the struct name that existing shortcuts are bound to', () => {
    // Renaming the struct would orphan the action in every saved automation;
    // only the title changed when it became Log Notification.
    expect(swift).toContain('struct LogPaymentAlertIntent: AppIntent {');
  });

  it('never opens the app or posts anything', () => {
    expect(swift).toContain('static var openAppWhenRun: Bool = false');
    expect(swift).not.toContain('UNUserNotificationCenter');
  });

  it('does not request an app name when logging a notification', () => {
    expect(swift).not.toContain('@Parameter(title: "From")');
    expect(swift).not.toContain('\\.$source');
    expect(swift).toContain('source: nil');
    expect(swift).toContain('\\.$account');
  });

  it('queues what the app reads', () => {
    // The Swift PendingAlert encodes these property names as JSON keys.
    const queued = JSON.stringify([
      {
        id: 'A1',
        createdAt: '2026-10-04T08:00:00.000Z',
        source: 'Maybank',
        title: 'Card transaction',
        subtitle: null,
        message: 'RM12.30 spent at KFC with card ending 1234.',
        accountId: 'acc-1',
        categoryId: null,
      },
    ]);
    expect(parseIosPendingAlertsJson(queued)[0]).toMatchObject({
      id: 'A1',
      channel: 'ios_alert',
      sourceKey: 'maybank',
      sourceLabel: 'Maybank',
      body: 'RM12.30 spent at KFC with card ending 1234.',
      presetAccountId: 'acc-1',
    });
    const store = plugin.AUTO_LOG_STORE_SWIFT;
    const pendingAlert = store.slice(store.indexOf('struct PendingAlert'));
    for (const field of [
      'id: String',
      'createdAt: String',
      'source: String?',
      'title: String?',
      'subtitle: String?',
      'message: String',
      'accountId: String?',
      'categoryId: String?',
    ]) {
      expect(pendingAlert).toContain(`var ${field}`);
    }
    expect(store).toContain(`static let pendingAlertsKey = "${plugin.PENDING_ALERTS_KEY}"`);
  });
});
