import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, '..');

function removeConflictingAndroidLauncherPngs(resDir) {
  if (!fs.existsSync(resDir)) {
    return 0;
  }

  const conflictingFiles = new Set([
    'ic_launcher.png',
    'ic_launcher_foreground.png',
    'ic_launcher_monochrome.png',
  ]);

  let removedCount = 0;

  for (const entry of fs.readdirSync(resDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || !entry.name.startsWith('mipmap-')) {
      continue;
    }

    const mipmapDir = path.join(resDir, entry.name);
    for (const fileName of fs.readdirSync(mipmapDir)) {
      if (!conflictingFiles.has(fileName)) {
        continue;
      }

      fs.rmSync(path.join(mipmapDir, fileName), { force: true });
      removedCount += 1;
    }
  }

  return removedCount;
}

// The iOS app icon is no longer copied in from assets/ios/. It now has light,
// dark and tinted appearances (app.json's `ios.icon`), which only prebuild knows
// how to write into AppIcon.appiconset's Contents.json — overwriting that with a
// flat copy of the legacy PNG set would drop the dark and tinted faces on the
// floor. Alternate icons are generated by expo-alternate-app-icons the same way.
console.log('Skipped iOS sync: Expo manages the app icon appearances from app.json');

const androidTarget = path.join(projectRoot, 'android', 'app', 'src', 'main', 'res');

if (fs.existsSync(path.dirname(androidTarget))) {
  const removedCount = removeConflictingAndroidLauncherPngs(androidTarget);
  if (removedCount > 0) {
    console.log(`Removed ${removedCount} conflicting Android launcher PNGs from native res/mipmap`);
  }

  console.log('Skipped Android sync: Expo manages native launcher icons from app.json');
} else {
  console.log('Skipped Android sync: android project not found (run expo prebuild)');
}
