const fr = {
  food: [
    // General meal terms
    'repas',
    'déjeuner',
    'dîner',
    'petit-déjeuner',
    'petit déjeuner',
    'goûter',
    'grignotage',
    'collation',
    'casse-croûte',
    'en-cas',
    'encas',
    'resto',
    'restau',
    'boîte',
    'brasserie',
    'bistro',
    'bistrot',
    'bouchon',
    'auberge',
    'guinguette',
    'estaminet',
    'taverne',
    'cabaret',
    'buffet froid',
    'plateau repas',
    'menu du jour',
    'plat du jour',
    'formule',
    'formule déjeuner',
    'entrée',
    'plat principal',
    'dessert',
    'apéro',
    'apéritif',
    'digestif',
    'digestif',
    'boisson',
    'boissons',
    'limonade',
    'orangina',
    'perrier',
    'evian',
    'badoit',
    'vittel',
    'volvic',
    'schweppes',
    'coca',
    'coca-cola',
    'fanta',
    'sprite',
    // Boulangerie / viennoiserie
    'boulangerie',
    'viennoiserie',
    'pain au chocolat',
    'pain au lait',
    'pain de mie',
    'pain complet',
    'baguette tradition',
    'ficelle',
    'boule de pain',
    'brioche',
    'chausson aux pommes',
    'tarte aux fraises',
    'tarte tatin',
    'éclair',
    'millefeuille',
    'mille-feuille',
    'Paris-Brest',
    'religieuse',
    'chouquette',
    'chouquettes',
    'financier',
    'madeleine',
    'madeleines',
    'cannelé',
    'cannelés',
    'kouign-amann',
    'galette bretonne',
    'galette des rois',
    'frangipane',
    'tarte au citron',
    'tarte normande',
    'clafoutis',
    'far breton',
    'crème brûlée',
    'île flottante',
    'profiteroles',
    'macaron',
    'macarons',
    'opéra',
    'charlotte',
    'bûche de Noël',
    'crêpe',
    'crêpes',
    'galette',
    'galettes',
    // Patisseries & confiseries
    'pâtisserie',
    'confiserie',
    'chocolaterie',
    'bonbon',
    'bonbons',
    'caramel',
    'nougat',
    'calisson',
    'berlingot',
    'praline',
    'pralines',
    'réglisse',
    'guimauve',
    "sucre d'orge",
    // Cheese & deli
    'fromagerie',
    'charcuterie',
    'jambon',
    'saucisson',
    'pâté',
    'rillettes',
    'terrine',
    'foie gras',
    'camembert',
    'brie',
    'comté',
    'roquefort',
    'chèvre',
    'emmental',
    'gruyère',
    'raclette',
    'reblochon',
    'munster',
    'livarot',
    "pont-l'évêque",
    'beaufort',
    'abondance',
    'mimolette',
    "fourme d'ambert",
    'saint-nectaire',
    'ossau-iraty',
    // Traditional dishes
    'quiche lorraine',
    'quiche',
    'croque-monsieur',
    'croque-madame',
    'croque monsieur',
    'croque madame',
    'omelette',
    "soupe à l'oignon",
    'bouillabaisse',
    'cassoulet',
    'pot-au-feu',
    'pot au feu',
    'blanquette de veau',
    'bœuf bourguignon',
    'coq au vin',
    'gratin dauphinois',
    'ratatouille',
    'tapenade',
    'aïoli',
    'pissaladière',
    'socca',
    'tartiflette',
    'fondue savoyarde',
    'raclette',
    'choucroute',
    'flammenküche',
    'tarte flambée',
    'baeckeoffe',
    'brandade',
    'daube provençale',
    'bouillabaisse',
    'moules frites',
    'steak frites',
    'andouillette',
    'bavette',
    'entrecôte',
    'tournedos',
    'magret de canard',
    'confit de canard',
    'foie de veau',
    'rognons',
    'ris de veau',
    'cervelle',
    'tête de veau',
    'boudin noir',
    'boudin blanc',
    'merguez',
    'chipolata',
    'saucisse de Toulouse',
    'knack',
    'knacki',
    'fricassée',
    "navarin d'agneau",
    "gigot d'agneau",
    'rôti',
    'côtelette',
    'travers de porc',
    'côte de porc',
    'jarret',
    'palette',
    'potée',
    'garbure',
    // Seafood
    'moules',
    'huîtres',
    'crevettes',
    'langoustines',
    'homard',
    'tourteau',
    'palourdes',
    'bulots',
    'bigorneaux',
    'coquilles saint-jacques',
    'saint-jacques',
    'sardines grillées',
    'sole',
    'turbot',
    'bar',
    'dorade',
    'loup de mer',
    'daurade',
    'merlan',
    'lieu',
    'cabillaud',
    'thon',
    'saumon',
    'truite',
    'hareng',
    'maquereau',
    'rouget',
    'rougets',
    // Drinks
    'café allongé',
    'café noisette',
    'noisette',
    'café au lait',
    'café crème',
    'café serré',
    'ristretto',
    'thé nature',
    'thé vert',
    'thé noir',
    'infusion',
    'tisane',
    'verveine',
    'camomille',
    "menthe à l'eau",
    'diabolo',
    'diabolo menthe',
    'diabolo fraise',
    'monaco',
    'picon bière',
    'pastis',
    'ricard',
    'kir',
    'kir royal',
    'cidre',
    'bière pression',
    'demi',
    'pinte',
    'verre de vin',
    'vin rouge',
    'vin blanc',
    'vin rosé',
    'champagne',
    'prosecco',
    'crémant',
    'muscat',
    'sancerre',
    'bordeaux',
    'bourgogne',
    'côtes du rhône',
    'beaujolais',
    'alsace',
    'corbières',
    'minervois',
    'entre-deux-mers',
    'graves',
    'médoc',
    'saint-émilion',
    'pomerol',
    'chablis',
    'pouilly-fuissé',
    'meursault',
    'gevrey-chambertin',
    'côte de nuits',
    'côte de beaune',
    // Fast food France-specific
    'quick',
    'brioche dorée',
    'briochedorée',
    'paul',
    'paul boulangerie',
    'le pain quotidien',
    'eugène',
    'eugène restaurant',
    "flam's",
    'hippopotamus',
    'courtepaille',
    'buffalo grill',
    'léon de bruxelles',
    'mezzo di pasta',
    'speed rabbit pizza',
    "domino's",
    "mcdonald's france",
    'macdo',
    'mcdo',
    'kfc france',
    'five guys paris',
    'burger king france',
    'big fernand',
    'blend',
    'blend burger',
    "o'tacos",
    'tacos avenue',
    'pitaya',
    'pitaya thaï',
    'sushi shop',
    'eat sushi',
    'sushi dailymonop',
    "monop'daily",
    'monop daily',
    'jour',
    'exki',
    'cojean',
    "lina's",
    'pomme de pain',
    "baguet'in",
    'boulangerie paul',
    'eric kayser',
    'kayser',
    'poilâne',
    'poilane',
    'gontran cherrier',
    // Delivery France
    'deliveroo',
    'just eat',
    'uber eats france',
    'stuart',
    'frichti',
    'epicery',
    'yopmiam',
    'nestor',
    'le moulin de la vierge',
    // Sweets / ice cream
    'glace',
    'glaces',
    'sorbet',
    'gelato',
    'berthillon',
    'amorino',
    'häagen-dazs paris',
    'sundae',
    'coupe glacée',
    // Misc
    'ticket restaurant',
    'ticket-restaurant',
    'chèque-déjeuner',
    'chèque déjeuner',
    'edenred',
    'sodexo',
    'swile',
    'up déjeuner',
    'lunchr',
    'luncheon voucher',
    "restaurant d'entreprise",
    'cantine',
    'self',
    'self-service',
    // === France/FR merchants ===
    'starbucks',
    'starbucks france',
    'prêt à manger',
    'subway',
    'pizza hut',
    'la mie câline',
    'marie blachère',
    'planet sushi',
    'del arte',
    'uber eats',
  ],
  groceries: [
    // General
    'courses',
    'course',
    'provisions',
    'commissions',
    'épicerie',
    'epicerie',
    'épicerie fine',
    'grande surface',
    'supérette',
    'superette',
    'supermarché',
    'hypermarché',
    'hypermarche',
    'supermarche',
    'marché',
    'marche',
    'marché couvert',
    'marché de plein air',
    'primeur',
    'primeurs',
    'maraîcher',
    'maraicher',
    'boucher',
    'boucherie',
    'poissonnier',
    'poissonnerie',
    'charcutier',
    'fromagerie',
    'caviste',
    // France supermarket brands
    'carrefour',
    'carrefour market',
    'carrefour city',
    'carrefour express',
    'carrefour contact',
    'carrefour bio',
    'carrefour drive',
    'lidl france',
    'monoprix',
    "monop'",
    'monop',
    'intermarché',
    'intermarche',
    'super u',
    'hyper u',
    'u express',
    'utile',
    'franprix',
    'picard',
    'picard surgelés',
    'picard surgeles',
    "bio c' bon",
    'biocbon',
    'naturalia',
    'biocoop',
    'bio coop',
    'la vie claire',
    'vivien paille',
    'grand frais',
    'fresh market',
    'auchan',
    'auchan hypermarché',
    'auchan drive',
    'simply market',
    'simply',
    'leclerc',
    'e.leclerc',
    'leclerc drive',
    'leclerc bio',
    'geant casino',
    'géant casino',
    'casino',
    'casino supermarchés',
    'casino supermarches',
    'leaderprice',
    'leader price',
    'spar',
    'vival',
    'coccinelle',
    'shopi',
    'marché u',
    'netto',
    'penny',
    'match',
    'cora',
    'bi1',
    'thiriet',
    // Convenience / drive
    'monoprix en ligne',
    'auchan.fr',
    'leclerc.fr',
    'chronodrive',
    'ooshop',
    'leclercbio',
    'drive picard',
    'fresh',
    'fraiches envies',
    'la belle vie',
    'greenweez',
    'kazidomi',
    'cagette',
    // Household / drugstore purchased at grocery
    'lessive',
    'produit ménager',
    'produits ménagers',
    'liquide vaisselle',
    'éponge',
    'serpillière',
    'aspirateur',
    'papier toilette',
    'sopalin',
    'essuie-tout',
    'sac poubelle',
    'film alimentaire',
    'papier aluminium',
    'boite de conserve',
    'surgelés',
    'surgeles',
    'yaourt',
    'yaourts',
    'fromage blanc',
    'quark',
    'beurre',
    'crème fraîche',
    'crème fraiche',
    'lait entier',
    'lait demi-écrémé',
    'lait écrémé',
    'jus de fruits',
    "jus d'orange",
    'eau plate',
    'eau gazeuse',
    'eau minérale',
    'charcuterie',
    'jambon blanc',
    'jambon cru',
    'farine',
    'riz',
    'pâtes',
    'pates',
    'lentilles',
    'haricots',
    'pois chiches',
    "huile d'olive",
    'huile de tournesol',
    'vinaigre',
    'moutarde',
    'ketchup',
    'mayonnaise',
    'confiture',
    'miel',
    'pâte à tartiner',
    'nutella',
    'céréales',
    'muesli',
    'granola',
    'biscuits',
    'gâteau',
    'gateaux',
    'chips',
    'crackers',
    'eau de source',
    'soda',
    'limonade',
    'orangeade',
    'bière',
    'vin de table',
    'alcool',
    'spiritueux',
    'apéro',
    'apéritif',
    // Produce specific
    'pommes de terre',
    'carottes',
    'courgettes',
    'tomates',
    'poireaux',
    'oignons',
    'ail',
    'échalotes',
    'champignons',
    'salade',
    'laitue',
    'épinards',
    'brocoli',
    'chou-fleur',
    'haricots verts',
    'petits pois',
    'asperges',
    'radis',
    'poivrons',
    'aubergine',
    'courgette',
    'concombre',
    'fenouil',
    'céleri',
    'betterave',
    'navets',
    'pomme',
    'poire',
    'banane',
    'orange',
    'clémentine',
    'mandarine',
    'citron',
    'pêche',
    'abricot',
    'cerise',
    'fraise',
    'fraises',
    'framboise',
    'framboises',
    'myrtilles',
    'raisin',
    'melon',
    'pastèque',
    'kiwi',
    'ananas',
    'mangue',
    'avocat',
    // === France/FR merchants ===
    'delhaize',
    'colruyt',
    'migros',
    'coop suisse',
    'denner',
    'aldi suisse',
    'lidl suisse',
    'manor food',
    'provigo',
    'iga quebec',
    'metro quebec',
    'maxi quebec',
  ],
  transport: [
    // Public transit
    'ratp',
    'sncf',
    'navigo',
    'navigo mensuel',
    'navigo semaine',
    'passe navigo',
    'carte navigo',
    'vélib',
    'velib',
    'villo',
    'vcub',
    'bicloo',
    'nextbike',
    'bird',
    'lime trottinette',
    'dott',
    'tier',
    'pony',
    'revel moto',
    'ouigo',
    'ouigo train',
    'tgv',
    'tgv inouï',
    'tgv inoui',
    'intercités',
    'intercites',
    'ter',
    'transilien',
    'rer',
    'rer a',
    'rer b',
    'rer c',
    'rer d',
    'rer e',
    'métro parisien',
    'metro paris',
    'métro',
    'metro',
    'tramway',
    'tram',
    'bus ratp',
    'noctilien',
    'orlybus',
    'orlyval',
    'roissy bus',
    'cdgval',
    'le bus direct',
    'car postal',
    'flixbus france',
    'blablacar',
    'bla bla car',
    'blablabus',
    'covoiturage',
    'covoiturage.fr',
    'klaxit',
    'comuto',
    'idvroom',
    'mobicoop',
    'ouibus',
    'eurostar',
    'thalys',
    'izy',
    'lyria',
    'elipsos',
    'intercity',
    'transdev',
    'keolis',
    // Rideshare / taxi France
    'g7',
    'taxi g7',
    'alpha taxis',
    'taxis bleus',
    'le cab',
    'heetch',
    'kapten',
    'free now',
    'freenow',
    'marcel',
    'chauffeur privé',
    'vtc',
    // Fuel / energy France
    'total',
    'total energies',
    'totalenergies',
    'esso france',
    'bp france',
    'q8',
    'api',
    'intermarché station',
    'leclerc station',
    'carrefour station',
    'sp95',
    'sp98',
    'gazole',
    'e10',
    'e85',
    'ethanol',
    'gnv',
    'biogaz',
    'recharge électrique',
    'borne de recharge',
    'superchargeur',
    'ionity',
    'engie drive',
    'lidl drive',
    'freshmile',
    'powerdot',
    'izivia',
    'recharge ev',
    'charge rapide',
    // Parking France
    'vinci park',
    'vincipark',
    'indigo park',
    'effia',
    'parkings paris',
    'parking payant',
    'parcmètre',
    'pv',
    'procès-verbal',
    'forfait post-stationnement',
    'fps',
    'fourrière',
    'ticket de stationnement',
    'zone bleue',
    // Car maintenance France
    'contrôle technique',
    'controle technique',
    "crit'air",
    'vignette',
    'carte grise',
    "certificat d'immatriculation",
    'assurance auto',
    "prime d'assurance",
    'AXA auto',
    'MAIF',
    'MACIF',
    'MAAF',
    'GMF',
    'Covéa',
    'Groupama',
    'Direct Assurance',
    'Amaguiz',
    'autolib',
    'citiz',
    'communauto',
    'modulauto',
    'renault zoe',
    'peugeot e-208',
    'location voiture',
    'europcar',
    'sixt france',
    'avis france',
    'hertz france',
    'ada location',
    'ada',
    'budget france',
    'rent a car',
    'interrent',
    // Road terms
    'autoroute',
    'péage',
    'télépéage',
    'badge',
    'liber-t',
    'sanef',
    'vinci autoroutes',
    'cofiroute',
    'sapn',
    'escota',
    'aprr',
    'atmb',
    'via michelin',
    'A1',
    'A6',
    'A7',
    'A10',
    'A13',
    'rocade',
    'boulevard périphérique',
    'périphérique',
    'francilienne',
    // Train Paris extras
    'sncf connect',
    'oui.sncf',
    'trainline',
    'loco2',
    'captain train',
    'inoui',
    'carte avantage',
    'carte liberté',
    'abonnement sncf',
    // Airports France
    'aéroport cdg',
    'aéroport charles de gaulle',
    'aéroport orly',
    'aéroport de paris',
    'aéroport nice',
    'aéroport lyon',
    'aéroport marseille',
    'airport cdg',
    'airport orly',
    'navette aéroport',
    'taxi aéroport',
    // Airlines France
    'air france',
    'transavia',
    'volotea',
    'corsair',
    'french bee',
    'corsavia',
    'jet2',
    'ryanair',
    'easyjet',
    'vueling',
    'iberia',
    'tap air',
    'tap portugal',
    // === France/FR merchants ===
    'stib',
    'sncb',
    'cff',
    'sbb',
    'tpg',
    'stm',
    'via rail',
    'uber',
    'lyft',
    'tamoil',
  ],
  housing: [
    // General
    'loyer',
    'charges locatives',
    'charges de copropriété',
    'charges',
    'syndic',
    'syndicat de copropriété',
    'assemblée générale',
    'fonds de travaux',
    'travaux',
    'ravalement',
    'ravalement de façade',
    'rénovation',
    'isolation',
    'double vitrage',
    'chauffage central',
    'chauffage collectif',
    'chauffage individuel',
    'chaudière',
    'chauffe-eau',
    'contrat de location',
    'bail',
    'état des lieux',
    'dépôt de garantie',
    'caution',
    'agence immobilière',
    'agence',
    "honoraires d'agence",
    "frais d'agence",
    'notaire',
    'frais de notaire',
    'prêt immobilier',
    'crédit immobilier',
    'hypothèque',
    'remboursement de prêt',
    'mensualité de prêt',
    'PTZ',
    'action logement',
    'CAF logement',
    'APL',
    'aide au logement',
    'taxe foncière',
    "taxe d'habitation",
    // Real estate platforms France
    'seloger',
    'leboncoin immobilier',
    'pap',
    'logic-immo',
    'bien ici',
    'bienici',
    'orpi',
    'century 21',
    'ERA immobilier',
    'foncia',
    'nexity',
    'bouygues immobilier',
    'kaufman',
    'vinci immobilier',
    // Home equipment / maintenance
    'plombier',
    'serrurier',
    'électricien',
    'chauffagiste',
    'carreleur',
    'peintre',
    'maçon',
    'menuisier',
    'charpentier',
    'vitrier',
    'couvreur',
    'jardinier',
    'femme de ménage',
    'femme de chambre',
    'homme toutes mains',
    'aide ménagère',
    'ménage',
    'nettoyage',
    'devis',
    'facture travaux',
    'leroy merlin',
    'leroymerlin',
    'castorama',
    'bricomarché',
    'bricorama',
    'brico dépôt',
    'point p',
    'saint-maclou',
    'tollens',
    'peindre',
    // Furniture / appliances
    'meubles',
    'mobilier',
    'ikea',
    'maisons du monde',
    'alinéa',
    'fly',
    'conforama',
    'but',
    'gifi',
    'centrakor',
    'action',
    'normal',
    'babou',
    "la foir'fouille",
    'electroménager',
    'lave-linge',
    'lave-vaisselle',
    'réfrigérateur',
    'congélateur',
    'four',
    'micro-ondes',
    'hotte',
    'plaque de cuisson',
    // Insurance (home)
    'assurance habitation',
    'assurance logement',
    'assurance multirisque',
    'mrh',
    'assurances habitation',
    'maif habitation',
    'macif habitation',
    'groupama habitation',
    'axa habitation',
    // Miscellaneous
    'déménagement',
    'déménageurs',
    'prestataire déménagement',
    'monte-meuble',
    'garde-meuble',
    'self-stockage',
    'box',
    'location box',
  ],
  bills: [
    // Energy
    'edf',
    'engie',
    'engie particuliers',
    'total direct énergie',
    'total energie',
    'totalenergies particuliers',
    'ilek',
    'ekwateur',
    'planète oui',
    'ekwateur',
    'leclerc énergie',
    'enercoop',
    'mint énergie',
    'ohm énergie',
    'primeo énergie',
    'vattenfall',
    'veolia énergie',
    'veolia',
    'veolia eau',
    'saur',
    'lyonnaise des eaux',
    'eau de paris',
    'sedif',
    'gironde eau',
    'nantes métropole eau',
    'metropole nice',
    'eau du grand lyon',
    // Telecom
    'orange',
    'orange telecom',
    'sfr',
    'sfr red',
    'red by sfr',
    'bouygues',
    'bouygues telecom',
    'free',
    'free mobile',
    'free telecom',
    'iliad',
    'sosh',
    'b&you',
    'prixtel',
    'syma mobile',
    'la poste mobile',
    'auchan telecom',
    'lebara mobile',
    'lycamobile',
    'coriolis',
    'euro information telecom',
    'nrj mobile',
    'youprice',
    'virgin mobile',
    'virgin mobile france',
    'joe mobile',
    // TV / streaming France
    'canal+',
    'canal plus',
    'canalplus',
    'canalsat',
    'mycanal',
    'my canal',
    'orange tv',
    'sfr tv',
    'free tv',
    'bouygues tv',
    'bbox tv',
    'freebox',
    'livebox',
    'bbox',
    'neufbox',
    'arte',
    'molotov',
    'salto',
    'filmo',
    'mubi',
    'disneyplus',
    'disney+',
    'disney plus',
    'amazon prime',
    'prime video',
    'netflix',
    'spotify france',
    'deezer',
    'tidal france',
    'apple music',
    'fnac music',
    // Internet providers France
    'free adsl',
    'free fibre',
    'sfr fibre',
    'orange fibre',
    'bouygues fibre',
    'numéricable',
    'numericable',
    'sfr câble',
    'sfr cable',
    // Insurance (non-housing)
    'mutuelle',
    'mutuelle santé',
    'assurance vie',
    'assurance décès',
    'prevoyance',
    'prévoyance',
    'ag2r',
    'malakoff humanis',
    'apicil',
    'harmonie mutuelle',
    'mgen',
    'mfp',
    'mnh',
    'cnp assurances',
    'groupama',
    'covea',
    'covéa',
    'GMF',
    'maaf',
    'maif',
    'macif',
    'axa',
    'allianz',
    'axa banque',
    'credit agricole assurances',
    'predica',
    'pacifica',
    // Misc regular bills
    'abonnement',
    'prélèvement',
    'prel',
    'facture',
    'cotisation',
    'adhésion',
    'redevance',
    'redevance audiovisuelle',
    'contribution audiovisuelle',
    'taxe audiovisuelle',
    'amende',
    'amende forfaitaire',
    'trésor public',
    'impôts',
    'impots',
    'dgfip',
    'centre des finances publiques',
    'urssaf',
    'rsi',
    'caisse retraite',
    'cnav',
    'agirc arrco',
    'agirc-arrco',
    'msa',
    // Cloud / SaaS subscriptions (French context)
    'adobe france',
    'microsoft 365',
    'office 365',
    'google workspace',
    'dropbox',
    'icloud',
    'google storage',
    'notion',
    'figma',
    'canva',
    'mailchimp',
    'wordpress',
    'ovh',
    'gandi',
    'online.net',
    'infomaniak',
    'ionos',
    '1&1 ionos',
    // Gym / regular services (here as bills)
    'abonnement salle',
    'abonnement sport',
    'abonnement cinéma',
    'ugc illimité',
    'mk2 illimité',
    'pathé gaumont',
    'le pass',
    // === France/FR merchants ===
    'proximus',
    'telenet',
    'voo',
    'swisscom',
    'sunrise',
    'salt',
    'videotron',
    'hydro-québec',
  ],
  healthcare: [
    // General
    'santé',
    'sante',
    'médecin',
    'medecin',
    'docteur',
    'Dr',
    'consultation',
    'consultation médicale',
    'ordonnance',
    'prescription',
    'médicament',
    'medicament',
    'pharmacie',
    'pharmacien',
    'officine',
    'parapharmacie',
    'infirmier',
    'infirmière',
    'infirmière libérale',
    'IDEL',
    'kinésithérapeute',
    'kiné',
    'kine',
    'ostéopathe',
    'osteopathe',
    'chiropracteur',
    'opticien',
    'opticien lunetier',
    'audioprothésiste',
    'audioprothesiste',
    'audio',
    'prothèse dentaire',
    'dentiste',
    'orthodontiste',
    'orthodontie',
    'sage-femme',
    'gynécologue',
    'gyneco',
    'cardiologue',
    'dermatologue',
    'dermato',
    'pédiatre',
    'pediatre',
    'psychiatre',
    'psychologue',
    'psychothérapeute',
    'psychotherapeute',
    'thérapeute',
    'therapeute',
    'séance',
    'seance',
    'rhumatologue',
    'gastro-entérologue',
    'gastro',
    'urologue',
    'pneumologue',
    'ORL',
    'oto-rhino-laryngologue',
    'neurologue',
    'endocrinologue',
    'ophtalmologue',
    'ophtalmo',
    'radiologue',
    'radiologie',
    'scanner',
    'IRM',
    'radio',
    'radiographie',
    'échographie',
    'echographie',
    'bilan sanguin',
    'prise de sang',
    "laboratoire d'analyses",
    'labo',
    'clinique',
    'hôpital',
    'hopital',
    'CHU',
    'CHR',
    'EHPAD',
    'urgences',
    'garde de nuit',
    // Social security / mutuelle
    'sécurité sociale',
    'secu',
    'sécu',
    'cpam',
    'caisse primaire',
    'carte vitale',
    'remboursement sécu',
    'remboursement sécurité sociale',
    'tiers payant',
    'médecin traitant',
    'médecin référent',
    'ALD',
    'affection longue durée',
    'cotisation mutuelle',
    'mutuelle santé',
    // Teleconsult
    'doctolib',
    'médecin direct',
    'medecin direct',
    'livi',
    'deuxième avis',
    'kry',
    'qare',
    'teleconsultation',
    'téléconsultation',
    'medaviz',
    'hellocare',
    // Optics
    'lunettes',
    'montures',
    'verres correcteurs',
    'lentilles de contact',
    'lentilles',
    'opticien krys',
    'afflelou',
    'alain afflelou',
    'grand optical',
    'grandoptical',
    'optical center',
    'opticien center',
    'atol',
    'noémie',
    'noemie',
    'jimmy fairly',
    'sensee',
    'lunettes pour tous',
    "générale d'optique",
    'generale optique',
    // Pharmacy France
    'doliprane',
    'paracétamol',
    'ibuprofène',
    'ibuprofen',
    'aspegic',
    'efferalgan',
    'dafalgan',
    'nurofen',
    'voltaren',
    'antalgique',
    'antibiotique',
    'vaccin',
    'vaccins',
    'vitamine',
    'vitamines',
    'complément alimentaire',
    'pansement',
    'bande',
    'sparadrap',
    'dépistage',
    'bilan',
    'bilan santé',
    'bilan biologique',
    'bilan cardiovasculaire',
    // Dental
    'détartrage',
    'soin dentaire',
    'obturation',
    'couronne dentaire',
    'implant dentaire',
    'bridge dentaire',
    'gouttière',
    'gouttière dentaire',
    'consultation dentaire',
    // Mental health
    'psychanalyse',
    'psychanalyste',
    'analyse',
    'thérapie',
    'therapie',
    'EMDR',
    'TCC',
    'thérapie comportementale',
    // === France/FR merchants ===
    'multipharma',
    'amavita',
    'jean coutu',
    'pharmaprix',
    'uniprix',
  ],
  shopping: [
    // Electronics
    'fnac',
    'darty',
    'boulanger',
    'ldlc',
    'materiel.net',
    'rue du commerce',
    'amazon france',
    'cdiscount',
    'pixmania',
    'grosbill',
    'electro dépôt',
    'electro depot',
    'sono centre',
    // Home improvement
    'leroy merlin',
    'castorama',
    'bricomarché',
    'brico dépôt',
    'bricorama',
    'point p',
    'manomano',
    // Fashion
    'zara',
    'h&m',
    'uniqlo',
    'mango',
    'sézane',
    'sezane',
    'rouje',
    'ba&sh',
    'bash',
    'sandro',
    'maje',
    'claudie pierlot',
    'isabel marant',
    'A.P.C',
    'agnès b.',
    'agnes b',
    'des petits hauts',
    'jacquemus',
    'ami paris',
    'lacoste',
    'longchamp',
    'vanessa bruno',
    'gerard darel',
    'gérard darel',
    'berenice',
    'bérènice',
    'morgan',
    'cache cache',
    'pimkie',
    'promod',
    'kiabi',
    'jules',
    'celio',
    'brice',
    'armand thiery',
    'devred',
    'bexley',
    'minelli',
    'eram',
    'André',
    'andre',
    'bobbies',
    'jonak',
    'text 6',
    'text6',
    // Kids / toys
    'galeries lafayette',
    'galeries lafayette maison',
    'printemps',
    'le bon marché',
    'bon marche',
    'bhv',
    "bazar de l'hôtel de ville",
    'champs elysées shopping',
    'la vallée village',
    'marques avenue',
    'one nation',
    'bab2',
    'forum des halles',
    'les 4 temps',
    'oxybul',
    'picwic',
    'toys r us',
    'joué club',
    'king jouet',
    'la grande récré',
    'janod',
    'haba',
    'vilac',
    // Sports
    'décathlon',
    'decathlon',
    'go sport',
    'intersport',
    'sport 2000',
    'quechua',
    'kalenji',
    'domyos',
    'kipsta',
    'wedze',
    'nabaiji',
    // Drugstore / beauty
    'pharmacie',
    'parapharmacie',
    'yves rocher',
    "l'occitane",
    'loccitane',
    'sephora',
    'marionnaud',
    'nocibé',
    'nocibe',
    'flormar',
    'nyx',
    'bourjois',
    'garnier',
    "l'oréal",
    'loreal',
    'vichy',
    'la roche-posay',
    'avène',
    'avene',
    'uriage',
    'nuxe',
    'caudalie',
    'clarins',
    'lancôme',
    'lancome',
    'chanel beauté',
    'dior beauté',
    'biotherm',
    // Jewellery / accessories
    "histoire d'or",
    'maty',
    'cluse',
    'fossil',
    'daniel wellington',
    'marc by marc jacobs',
    'longines',
    'movado',
    'bijoux',
    'bijouterie',
    'horlogerie',
    // Office / stationery
    'bureau vallée',
    'bureau vallee',
    'eureka papeterie',
    'cultura',
    'nature et découvertes',
    'nature decouvertes',
    'fnac librairie',
    'gibert joseph',
    'decitre',
    'leclerc librairie',
    // Second-hand / flea market
    'vinted',
    'leboncoin',
    'videdressing',
    'vestiaire collective',
    'depop',
    'emmaüs',
    'emmaus',
    'la croix-rouge',
    'la croix rouge',
    'troc.com',
    'cash express',
    'easy cash',
    // Misc retail
    'action',
    'normal',
    'primark',
    'gifi',
    'centrakor',
    'noz',
    'stokomani',
    "la foir'fouille",
    'tati',
    'b&m',
    // Online marketplace
    'amazon',
    'cdiscount',
    'auchan.fr',
    'fnac.com',
    'darty.com',
    'vente privée',
    'veepee',
    'showroomprive',
    'showroomprivé',
    'bazarchic',
    'brands fashion',
    'sarenza',
    'zalando',
    'asos',
    'spartoo',
    'la redoute',
    'redoute',
    '3 suisses',
    'pixum',
    'made in design',
    'monsieur meuble',
    'topachat',
    // === France/FR merchants ===
    'inno',
    'manor',
    'globus',
    'simons',
    'canadian tire',
    'renaud-bray',
  ],
  entertainment: [
    // Cinema
    'cinéma',
    'cinema',
    'film',
    'films',
    'séance cinéma',
    'séance de cinéma',
    'cgr',
    'ugc',
    'pathé',
    'pathe',
    'gaumont',
    'mk2',
    'grand rex',
    'le grand rex',
    'kinépolis',
    'kinepolis',
    'ciné cité',
    'ciné',
    'cine',
    'ciné club',
    'cinémathèque',
    'cinematheque',
    'imax',
    '3D',
    'dolby',
    'pop corn',
    'popcorn',
    // Theatre / shows
    'théâtre',
    'theatre',
    'comédie',
    'comedie',
    'comédie musicale',
    'comedie musicale',
    'opéra',
    'opera',
    'ballet',
    'danse',
    'spectacle',
    'spectacle vivant',
    'one man show',
    'stand-up',
    'standup',
    'café-théâtre',
    'café theatre',
    'cabaret',
    'music-hall',
    'music hall',
    'revue',
    'comédie française',
    'comedie francaise',
    'comédie de paris',
    'folies bergère',
    'lido',
    'moulin rouge',
    'crazy horse',
    'olympia',
    'bataclan',
    'zenith',
    'zénith',
    'accor arena',
    'accor hotel arena',
    'grande halle de la villette',
    'la défense arena',
    'palais des sports',
    'salle de concert',
    'salles de spectacle',
    // Music / concerts
    'concert',
    'concerts',
    'festival',
    'rock en seine',
    'la route du rock',
    'vieilles charrues',
    'solidays',
    'eurockeennes',
    'eurockéennes',
    'francofolies',
    'printemps de bourges',
    'festival jazz',
    'hellfest',
    'tag',
    'we love green',
    'main square',
    'download',
    'lollapalooza paris',
    'billeterie',
    'billet',
    'billets',
    'entrée',
    'entrées',
    'place',
    'places de concert',
    'carnet de dix',
    'ticketmaster',
    'fnac spectacles',
    'france billet',
    'digitick',
    'weezevent',
    'mapticket',
    'seetickets',
    // Museums / culture
    'musée',
    'musee',
    'musée du louvre',
    'louvre',
    "musée d'orsay",
    'orsay',
    'centre pompidou',
    'pompidou',
    "musée de l'orangerie",
    'palais de tokyo',
    'musée rodin',
    'musée picasso',
    "musée national d'art moderne",
    'mnam',
    'cité des sciences',
    'planétarium',
    'planetarium',
    'muséum',
    'museum',
    'galerie',
    'expo',
    'exposition',
    'vernissage',
    'visite guidée',
    'audioguide',
    'château',
    'château de versailles',
    'versailles',
    'château de fontainebleau',
    'château de vaux-le-vicomte',
    'mont saint-michel',
    'tour eiffel',
    'arc de triomphe',
    'catacombes',
    'sainte-chapelle',
    'notre-dame',
    'patrimoine',
    // Escape games / activities
    'escape game',
    'escape room',
    'laser game',
    'paintball',
    'karting',
    'accrobranche',
    'bowlzone',
    'bowling',
    'billard',
    'fléchettes',
    'badminton loisir',
    'padel',
    'jeux vidéo',
    'jeux video',
    'gaming',
    'arcade',
    'casino',
    'paris hippique',
    'paris sportif',
    'loto',
    'loterie',
    'grattage',
    'Française des jeux',
    'FDJ',
    'PMU',
    // Books / media
    'livre',
    'livres',
    'librairie',
    'bouquiniste',
    'bdphileas',
    'album',
    'bande dessinée',
    'BD',
    'comics',
    'magazine',
    'presse',
    'kiosque',
    'hebdomadaire',
    'mensuel',
    'abonnement presse',
    'le monde',
    'le figaro',
    'libération',
    'le parisien',
    "l'express",
    'le point',
    "l'obs",
    'courrier international',
    "l'humanité",
    'médiapart',
    'podcast',
    // === France/FR merchants ===
    'cineplex',
    'guzzo',
    'utopia cinema',
    'starticket',
  ],
  education: [
    // General
    'école',
    'ecole',
    'collège',
    'college',
    'lycée',
    'lycee',
    'université',
    'universite',
    'fac',
    'faculté',
    'faculte',
    'grande école',
    'grande ecole',
    'classes préparatoires',
    'prépa',
    'BTS',
    'DUT',
    'licence',
    'master',
    'doctorat',
    'thèse',
    'these',
    'mémoire',
    'memoire',
    // Fees & admin
    'frais de scolarité',
    'frais scolarite',
    "droits d'inscription",
    'inscription',
    'cotisation étudiante',
    'contribution vie étudiante',
    'CVEC',
    'frais de dossier',
    'dossier admission',
    'concours',
    'préparation concours',
    // Private tutoring / training
    'cours particuliers',
    'soutien scolaire',
    'répétiteur',
    'repetiteur',
    'précepteur',
    'autoécole',
    'auto-école',
    'auto ecole',
    'permis de conduire',
    'code de la route',
    'code',
    'conduite accompagnée',
    'AAC',
    'conduite supervisée',
    // Online platforms
    'formation',
    'formation professionnelle',
    'formation continue',
    'bilan de compétences',
    'VAE',
    'certification',
    'e-learning',
    'MOOC',
    'openclassrooms',
    'coursera',
    'udemy',
    'skillshare',
    'linkedin learning',
    'datacamp',
    'codecademy',
    'khan academy',
    'brilliant',
    'duolingo',
    'babbel',
    'lingoda',
    'cned',
    // School supplies
    'fournitures scolaires',
    'fournitures',
    'cartable',
    'cahier',
    'cahiers',
    'trousse',
    'stylo',
    'stylos',
    'règle',
    'compas',
    'calculatrice',
    'classeur',
    'protège-cahier',
    'ramette de papier',
    'imprimante',
    'encre',
    'cartouche',
    'cartouches',
    'manuel scolaire',
    'manuel',
    'livre scolaire',
    'livres scolaires',
    // Language schools
    'école de langues',
    'cours de langue',
    "cours d'anglais",
    'cours de français',
    "cours d'espagnol",
    "cours d'allemand",
    'cours de chinois',
    'cours de japonais',
    'cours de FLE',
    'FLE',
    'Institut français',
    'Alliance française',
    'Goethe Institut',
    'Instituto Cervantes',
    // Music / art school
    'conservatoire',
    'cours de musique',
    'cours de piano',
    'cours de guitare',
    'cours de violon',
    'cours de batterie',
    'cours de chant',
    'cours de danse',
    'cours de dessin',
    'cours de peinture',
    'atelier',
    // School canteen / activities
    'cantine',
    'demi-pension',
    'internat',
    'périscolaire',
    'activité extra-scolaire',
    'sortie scolaire',
    'voyage scolaire',
    'classe verte',
    'classe de mer',
    'classe de ski',
    'frais de voyage scolaire',
  ],
  pets: [
    // General
    'animal de compagnie',
    'animaux',
    'vétérinaire',
    'vétérinaire',
    'véto',
    'veto',
    'clinique vétérinaire',
    'clinique veterinaire',
    'consultation vétérinaire',
    'vaccin animal',
    'identification',
    'tatouage',
    'puce électronique',
    'puce electronique',
    'registre national',
    'LOOF',
    'SCC',
    // Food & care
    'nourriture pour chat',
    'nourriture pour chien',
    'croquettes',
    'pâtée',
    'patee',
    'aliment pour animaux',
    'litière',
    'litiere',
    'arbre à chat',
    'griffoir',
    'cage',
    'aquarium',
    'terrarium',
    'laisse',
    'collier',
    'harnais',
    'jouet pour chat',
    'jouet pour chien',
    'balle',
    'friandise animal',
    'récompense animaux',
    // Grooming & services
    'toiletteur',
    'toilettage',
    'bain chien',
    'tonte',
    'pet sitting',
    'petsitting',
    "garde d'animaux",
    'garderie animaux',
    'pension animaux',
    'pension chien',
    'pension chat',
    'dressage',
    'éducateur canin',
    'comportementaliste',
    'comportementaliste animal',
    // France brands (pet)
    'animalis',
    'jardiland animaux',
    'gamm vert',
    'maxi zoo',
    'maxizoo',
    'tom et nana',
    'whiskas',
    'friskies',
    'purina',
    'royal canin',
    'hills science',
    'advance',
    'bravecto',
    'frontline',
    'milbemax',
    // Insurance
    'assurance animaux',
    'assurance chien',
    'assurance chat',
    'assurance NAC',
    // === France/FR merchants ===
    'tom&co',
    'qualipet',
    'mondou',
  ],
  travel: [
    // Accommodation
    'hôtel',
    'hotel',
    'hébergement',
    'hebergement',
    'nuitée',
    'nuitee',
    'auberge de jeunesse',
    'gîte',
    'gite',
    "chambre d'hôtes",
    'chambre d hotes',
    'maison de vacances',
    'location vacances',
    'villa vacances',
    'camping',
    'camping car',
    'mobil-home',
    'airbnb',
    'abritel',
    'homelidays',
    'booking.com',
    'booking',
    'expedia',
    'hotels.com',
    'trivago',
    'kayak',
    'leboncoin vacances',
    'amoma',
    'lastminute',
    'last minute',
    'promovacances',
    'tui',
    'thomas cook',
    'fram',
    'club med',
    'club méditerranée',
    'club mediterranee',
    'belambra',
    'PVF',
    'village vacances',
    'village club',
    'VVF',
    'Les Arcs',
    'Courchevel',
    "Val d'Isère",
    'Méribel',
    'Tignes',
    'Flaine',
    'Serre Chevalier',
    'Les Deux Alpes',
    'Montgenèvre',
    // Tours / excursions
    'séjour',
    'sejour',
    'voyage',
    'voyager',
    'circuit',
    'croisière',
    'croisiere',
    'excursion',
    'transfert',
    'navette',
    'guide touristique',
    'visite',
    'visite touristique',
    'tour opérateur',
    'agence de voyage',
    // Luggage / insurance
    'assurance voyage',
    'assistance voyage',
    'rapatriement',
    'bagage',
    'bagages',
    'supplément bagage',
    'valise',
    // Ferries / trains abroad
    'ferry',
    'traversée',
    'crosschannel',
    'brittany ferries',
    'dfds',
    'p&o',
    'stena',
    'eurostar',
    'thalys',
    'interrail',
    'eurail',
    'trenitalia',
    'renfe',
    'deutsche bahn',
    'flixbus international',
    // Health / visa
    'visa',
    'passeport',
    'assurance multirisque voyage',
    'pcr test voyage',
    'test covid voyage',
    // Currency
    'bureau de change',
    'change devise',
    'devise étrangère',
    'change euros',
    'taux de change',
    // === France/FR merchants ===
    'accor',
    'ibis',
    'novotel',
    'sofitel',
    'fairmont',
  ],
  fitness: [
    // Gyms / sports clubs
    'salle de sport',
    'salle de fitness',
    'salle de gym',
    'gymnase',
    'fitness',
    'musculation',
    'cours collectif',
    'cours de sport',
    'abonnement sport',
    'abonnement salle',
    'basic-fit',
    'basic fit',
    'neoness',
    "l'appart fitness",
    'l appart fitness',
    'moving',
    'moving sport',
    'keepcool',
    'keep cool',
    'fitness park',
    'fitnesspark',
    'urban gym',
    'club med gym',
    'club med sport',
    'reebok club',
    'all in one',
    'gofit',
    'fit one',
    'fitness first',
    'palestra',
    'orange bleue',
    'dynamos',
    'club vital',
    'vital',
    'sporting club',
    'cercle sportif',
    // Sports activities
    'cours de yoga',
    'yoga',
    'pilates',
    'cours de pilates',
    'stretching',
    'crossfit',
    'cross-training',
    'hiit',
    'zumba',
    'cours de zumba',
    'boxe',
    'boxe anglaise',
    'kickboxing',
    'muay thai',
    'judo',
    'jujitsu',
    'aïkido',
    'aikido',
    'karaté',
    'karate',
    'taekwondo',
    'escrime',
    'arts martiaux',
    'natation',
    'piscine',
    'aquagym',
    'aqua bike',
    'cours de natation',
    'tennis',
    'cours de tennis',
    'squash',
    'badminton',
    'padel tennis',
    'padel',
    'foot en salle',
    'football',
    'rugby',
    'basket',
    'handball',
    'volley',
    'climbing',
    'escalade',
    'bloc',
    "salle d'escalade",
    'vélo',
    'velo',
    'cyclisme',
    'spinning',
    'indoor cycling',
    'course à pied',
    'running',
    'trail',
    'marathon',
    'triathlon',
    'ski',
    'ski alpin',
    'ski de fond',
    'ski nordique',
    'snowboard',
    'randonnée',
    'randonnee',
    'trekking',
    'escalade',
    'voile',
    'voile',
    'planche à voile',
    'surf',
    'kayak',
    'canoe',
    'plongée',
    'plongee',
    'parachutisme',
    'parapente',
    // Equipment
    'équipement sportif',
    'tenue de sport',
    'chaussures de sport',
    'baskets',
    'running shoes',
    'raquette',
    'vélo de route',
    'velo de route',
    'velo de montagne',
    'VTT',
    // Nutrition / supplements
    'whey',
    'protéine',
    'proteine',
    'créatine',
    'creatine',
    'bcaa',
    'compléments sportifs',
    'complements sportifs',
    'sport nutrition',
    'myprotein',
    'optimum nutrition',
    'bulk',
    'nutri & co',
    // PT / coaching
    'coach sportif',
    'coach personnel',
    'personal trainer',
    'entraîneur',
    'entraineur',
    'séance de coaching',
    'coaching sportif',
    'bilan sportif',
    // Wellness
    'spa',
    'hammam',
    'sauna',
    'bain nordique',
    'massage',
    'massage sportif',
    'cryothérapie',
    'cryotherapie',
    'pressothérapie',
    'pressotherapie',
    'infrarouge',
    'réflex',
    'réflexologie',
    'soin du corps',
    'bien-être',
    'bien etre',
    // === France/FR merchants ===
    'nautilus plus',
    'econofitness',
    'energie fitness',
  ],
  gifts: [
    // General
    'cadeau',
    'cadeaux',
    "cadeau d'anniversaire",
    'cadeau de mariage',
    'cadeau de naissance',
    'cadeau de Noël',
    'cadeau noël',
    'cadeau noels',
    'cadeau fête',
    'paquet cadeau',
    'emballage cadeau',
    'liste de naissance',
    'liste de mariage',
    'faire-part',
    'carte de vœux',
    'carte de voeux',
    'carte cadeau',
    'bon cadeau',
    'chèque cadeau',
    // Events
    'anniversaire',
    "fête d'anniversaire",
    'fête',
    'fetes',
    'noël',
    'noel',
    'pâques',
    'paques',
    'étrennes',
    'etrennes',
    'fête des mères',
    'fête des pères',
    'saint-valentin',
    'valentin',
    'baptême',
    'bapteme',
    'communion',
    'confirmation',
    'mariage',
    'PACS',
    'retraite',
    'départ en retraite',
    'pot de départ',
    'pot d arrivee',
    'pot de bienvenue',
    'crémaillère',
    'cremaillere',
    'pendaison de crémaillère',
    // Donations
    'don',
    'dons',
    'donation',
    'donner',
    'charité',
    'charite',
    'association',
    'association caritative',
    'fondation',
    'ONG',
    'croix rouge',
    'médecins sans frontières',
    'msf',
    'restos du cœur',
    'banque alimentaire',
    'secours catholique',
    'secours populaire',
    'action contre la faim',
    'WWF',
    'greenpeace',
    'amnesty international',
    'UNICEF',
    'emmaüs',
    'emmaus',
    // Specific gifts / stores
    'fleuriste',
    'fleurs',
    'bouquet',
    'roses',
    'parfum',
    'coffret beauté',
    'coffret cadeau',
    'gastronomie',
    'coffret gastronomique',
    'coffret vin',
    'champagne cadeau',
    'chèque sport',
    'chèque lire',
    'fnac chèque cadeau',
    'chèque cado',
    'kadobon',
    'wonderbox',
    'smartbox',
    'dakotabox',
    'coffret experience',
  ],
  salary: [
    // General
    'salaire',
    'paie',
    'paye',
    'fiche de paie',
    'fiche de paye',
    'bulletin de salaire',
    'bulletin de paie',
    'virement salaire',
    'virement mensuel',
    'virement de salaire',
    'versement de salaire',
    'versement',
    'prime',
    'primes',
    "prime de fin d'année",
    'prime annuelle',
    'prime de performance',
    'bonus',
    'acompte',
    'acompte sur salaire',
    'avance sur salaire',
    'salaire net',
    'salaire brut',
    'salaire mensuel',
    'salaire annuel',
    'rémunération',
    'remuneration',
    // Specific income types
    'SMIC',
    'smic',
    'salaire minimum',
    '13ème mois',
    '13e mois',
    'intéressement',
    'interessement',
    'participation',
    'épargne salariale',
    'epargne salariale',
    'PEE',
    'PERCO',
    'PERCO entreprise',
    'RTT',
    'indemnité de congés payés',
    'congés payés',
    'ICP',
    'indemnité de fin de contrat',
    'solde de tout compte',
    'préavis',
    'preavis',
    'indemnité de licenciement',
    'heures supplémentaires',
    'heures sup',
    'frais professionnels',
    'remboursement frais',
    'note de frais',
    'frais kilomètriques',
    'IKV',
    'indemnités kilométriques',
    // Freelance / independent
    'honoraires',
    'mission',
    'prestation',
    'facture client',
    'facture émise',
    'freelance',
    'auto-entrepreneur',
    'auto entrepreneur',
    'micro-entrepreneur',
    'microentrepreneur',
    'indépendant',
    'independant',
    'travailleur indépendant',
    'portage salarial',
    'SASU',
    'EURL',
    'dividendes',
    'rémunération de gérant',
    // Benefits / welfare
    'allocation',
    'allocations',
    'RSA',
    'ARE',
    'chômage',
    'chomage',
    'indemnité chômage',
    'pôle emploi',
    'pole emploi',
    'CAF',
    'allocations familiales',
    'APL',
    'aide au logement',
    'AAH',
    'pension alimentaire',
    'pension de retraite',
    'retraite',
    'pension vieillesse',
    // Student / scholarship
    'bourse étudiant',
    'bourse étudiante',
    'bourse',
    'bourse CROUS',
    'CROUS',
    'stage',
    'gratification de stage',
    'alternance',
    'contrat apprentissage',
    'apprentissage',
    'revenu alternance',
  ],
  investment: [
    // General
    'investissement',
    'investissements',
    'épargne',
    'epargne',
    'placement',
    'placements',
    'action',
    'actions',
    'bourse',
    'dividende',
    'dividendes',
    'coupon',
    'intérêt',
    'interets',
    'plus-value',
    'moins-value',
    // Account types
    'PEA',
    'PEA-PME',
    'compte-titres',
    'compte titres',
    'assurance vie',
    "contrat d'assurance vie",
    'PER',
    'plan épargne retraite',
    'plan epargne retraite',
    'PEE',
    'plan épargne entreprise',
    'PERCO',
    'livret A',
    'LDDS',
    'livret de développement durable',
    'LEP',
    'livret épargne populaire',
    'livret jeune',
    'CEL',
    'PEL',
    'plan épargne logement',
    'livret',
    'livret bancaire',
    // Real estate investment
    'investissement locatif',
    'SCPI',
    'société civile de placement immobilier',
    'OPCI',
    'SIIC',
    'foncière',
    // Crypto / alternatives
    'crypto',
    'cryptomonnaie',
    'bitcoin',
    'ethereum',
    'binance',
    'kraken',
    'coinbase',
    'bitpanda',
    'staking',
    'NFT',
    'DeFi',
    'finance décentralisée',
    // Brokers France
    'degiro',
    'boursorama',
    'fortuneo',
    'bforbank',
    'binck',
    'saxo banque',
    'trade republic',
    'etoro',
    'interactive brokers',
    'lynx',
    'revolut trading',
    'n26 bourse',
    'bourse direct',
    'yomoni',
    'marie quantier',
    'nalo',
    'linxea',
    'spirica',
    'suravenir',
    // Funds / products
    'ETF',
    'FCP',
    'SICAV',
    'OPCVM',
    'tracker',
    'fonds euros',
    'unité de compte',
    'arbitrage',
    'versement libre',
    'versement programmé',
    // Banks (French)
    'BNP Paribas',
    'BNP',
    'Société Générale',
    'Crédit Agricole',
    'LCL',
    'Crédit Mutuel',
    'CIC',
    'Banque Populaire',
    "Caisse d'Epargne",
    'Caisse d Epargne',
    'La Banque Postale',
    'ING Direct',
    'Boursorama Banque',
    'Hello Bank',
    'Monabanq',
    'Ma French Bank',
    'Orange Bank',
    'Nickel',
    'Lydia',
    'N26',
    'Revolut',
    'Bunq',
    'Qonto',
    'Shine',
    'Memo Bank',
    'Bankin',
  ],
  refund: [
    // General
    'remboursement',
    'remboursé',
    'rembours',
    'rembourse',
    'avoir',
    'avoirs',
    'crédit',
    'credits',
    "crédit d'impôt",
    'credit impot',
    'retour',
    'retours',
    'retour produit',
    'retour article',
    'annulation',
    'rétractation',
    'retractation',
    'droit de rétractation',
    // Commerce
    'bon de retour',
    'bon de remboursement',
    'échange',
    'exchange',
    'reprise',
    'crédit commercial',
    'dédommagement',
    'dedommagement',
    'geste commercial',
    // Insurance
    'remboursement assurance',
    'remboursement mutuelle',
    'remboursement sécu',
    'remboursement sécurité sociale',
    'remboursement médicament',
    'remboursement médecin',
    'remboursement soins',
    'remboursement frais médicaux',
    'sinistre',
    'indemnisation',
    'indemnité',
    // Tax refund
    'remboursement impôts',
    'remboursement fiscal',
    'trop-perçu',
    'trop perçu',
    'restitution',
    'remboursement TVA',
    // Travel / flight
    'remboursement billet',
    'avoir billet',
    'remboursement vol',
    'indemnisation vol',
    'indemnisation retard',
    'indemnité vol annulé',
    'EU261',
    'règlement européen',
    // Misc
    'caution remboursée',
    'dépôt remboursé',
    'réservation annulée',
    'réservation annulée remboursée',
    'trop facturé',
    'erreur de facturation',
    'correction',
    'note de crédit',
  ],
};

export default fr;
