const vi = {
  food: [
    'ăn',
    'ăn uống',
    'bữa trưa',
    'bữa tối',
    'bữa sáng',
    'cơm',
    'cơm tấm',
    'bún bò',
    'bún riêu',
    'hủ tiếu',
    'phở bò',
    'phở gà',
    'mì quảng',
    'gỏi cuốn',
    'chả giò',
    'nem rán',
    'lẩu',
    'nướng',
    'cháo',
    'xôi',
    'bánh cuốn',
    'bánh xèo',
    'bánh khọt',
    'cơm bình dân',
    'cơm trưa',
    'trà sữa',
    'cà phê sữa đá',
    'cà phê phin',
    'sinh tố',
    'nước mía',
    'chè',
    'grabfood',
    'baemin',
    'shopeefood',
    'be food',
    'kfc',
    'lotteria',
    'pizza hut',
    'jollibee',
    'phúc long',
    'highlands coffee',
    'the coffee house',
    'trung nguyên',
    'quán ăn',
    'đặt đồ ăn',
    'giao đồ ăn',
    'cafe',
    'cà phê',
    'trà',
    'nước ngọt',
    'bia',
    'nhậu',
    'buffet',
    // === Vietnam merchants ===
    'gofood',
    "mcdonald's",
    'burger king',
    "domino's pizza",
    "pizza 4p's",
    'starbucks',
    'texas chicken',
    'popeyes',
    'gong cha',
    'koi thé',
    'tocotoco',
    'phê la',
    'katinat',
    'cộng cà phê',
    "al fresco's",
    'baskin robbins',
    "swensen's",
    'the pizza company',
  ],
  groceries: [
    'siêu thị',
    'chợ',
    'chợ truyền thống',
    'rau',
    'thịt',
    'cá',
    'trứng',
    'gạo',
    'co.opmart',
    'co.opxtra',
    'vinmart',
    'winmart',
    'bigc',
    'big c',
    'go! vietnam',
    'lotte mart',
    'aeon mall',
    'bách hoá xanh',
    'bach hoa xanh',
    'vinmart+',
    'tạp hoá',
    'cửa hàng tiện lợi',
    'circle k',
    'gs25',
    'familymart',
    'ministop',
    'rau củ',
    'trái cây',
    'hoa quả',
    'đồ ăn',
    'thực phẩm',
    'gia vị',
    'dầu ăn',
    'nước mắm',
    'mua rau',
    'mua thịt',
    // === Vietnam merchants ===
    'mm mega market',
    'satrafoods',
    'emart',
    'annam gourmet market',
    'kingfoodmart',
  ],
  transport: [
    'xe buýt',
    'xe ôm',
    'grab bike',
    'grab car',
    'be car',
    'gojek',
    'taxi',
    'taxi mai linh',
    'taxi vinasun',
    'tàu điện',
    'tàu metro',
    'metro',
    'xăng',
    'đổ xăng',
    'gửi xe',
    'phí gửi xe',
    'thu phí',
    'trạm thu phí',
    'vé tàu',
    'vé xe khách',
    'xe khách',
    'xe máy',
    'ô tô',
    'grab',
    'be',
    'xăng dầu',
    'sửa xe',
    'bảo dưỡng xe',
    'phí đường',
    'cầu đường',
    'bến xe',
    'ga tàu',
    'vé máy bay nội địa',
    // === Vietnam merchants ===
    'xanh sm',
    'petrolimex',
    'pvoil',
    'vetc',
    'vinasun',
    'mai linh',
  ],
  housing: [
    'tiền nhà',
    'thuê nhà',
    'tiền thuê',
    'phí quản lý',
    'phí chung cư',
    'phí dịch vụ',
    'sửa nhà',
    'nội thất',
    'đồ gia dụng',
    'thuê phòng',
    'ký túc xá',
    'điện nước',
    'mua nhà',
    'vay nhà',
    'thế chấp',
    'tiền cọc',
    'đặt cọc',
    'hợp đồng thuê',
  ],
  bills: [
    'điện',
    'tiền điện',
    'nước',
    'tiền nước',
    'internet',
    'điện thoại',
    'viettel',
    'mobifone',
    'vinaphone',
    'vietnamobile',
    'vnpt',
    'fpt telecom',
    'fpt',
    'sctv',
    'vtvcab',
    'nạp điện thoại',
    'nạp tiền',
    'hoá đơn',
    'bill',
    'truyền hình cáp',
    'netflix',
    'spotify',
    'youtube premium',
    'phí dịch vụ',
    'bảo hiểm nhân thọ',
    'bảo hiểm xe máy',
    'bảo hiểm ô tô',
    'thuế',
    'phí',
    'đóng tiền',
    'chuyển tiền',
    // === Vietnam merchants ===
    'vieon',
    'fpt play',
    'evn',
    'sawaco',
  ],
  healthcare: [
    'bác sĩ',
    'bệnh viện',
    'phòng khám',
    'thuốc',
    'hiệu thuốc',
    'long châu',
    'pharmacity',
    'an khang',
    'nha sĩ',
    'bảo hiểm y tế',
    'khám bệnh',
    'khám sức khoẻ',
    'xét nghiệm',
    'siêu âm',
    'chụp x-quang',
    'nha khoa',
    'mắt kính',
    'kính mắt',
    'thuốc tây',
    'vitamin',
    'thực phẩm chức năng',
    'bệnh viện tư',
    'bệnh viện công',
    'cấp cứu',
    'tiêm phòng',
    'vaccine',
    // === Vietnam merchants ===
    'vinmec',
    'hoàn mỹ',
    'medlatec',
    'jio health',
  ],
  shopping: [
    'mua sắm',
    'quần áo',
    'giày dép',
    'shopee',
    'lazada',
    'tiki',
    'sendo',
    'thời trang',
    'uniqlo',
    'h&m',
    'zara',
    'canifa',
    "biti's",
    "biti's hunter",
    'adidas vn',
    'nike vn',
    'túi xách',
    'phụ kiện',
    'trang sức',
    'đồng hồ',
    'mỹ phẩm',
    'son môi',
    'sữa rửa mặt',
    'kem dưỡng',
    'nước hoa',
    'guardian',
    'watsons',
    'hasaki',
    'thế giới di động',
    'fpt shop',
    'điện máy xanh',
    'điện thoại',
    'laptop',
    'tai nghe',
    // === Vietnam merchants ===
    'cellphones',
    'nguyễn kim',
    'con cưng',
    'điện máy chợ lớn',
    'pico plaza',
  ],
  entertainment: [
    'phim',
    'rạp phim',
    'cgv',
    'lotte cinema',
    'bhd star',
    'karaoke',
    'nhà hàng',
    'bar',
    'pub',
    'vui chơi',
    'giải trí',
    'game',
    'billiards',
    'bida',
    'bowling',
    'escape room',
    'sở thú',
    'công viên',
    'hội chợ',
    'concert',
    'show',
    'sự kiện',
    'vé sự kiện',
    'lễ hội',
    // === Vietnam merchants ===
    'galaxy cinema',
    'beta cinemas',
    'dcine',
  ],
  education: [
    'trường',
    'học phí',
    'đại học',
    'luyện thi',
    'gia sư',
    'trung tâm ngoại ngữ',
    'tiếng Anh',
    'ielts',
    'toeic',
    'toefl',
    'học online',
    'khoá học',
    'sách giáo khoa',
    'sách',
    'văn phòng phẩm',
    'học vẽ',
    'học nhạc',
    'học đàn',
    'lớp học thêm',
    'học lái xe',
    'bằng lái',
    'udemy',
    'coursera',
    'duolingo',
    'trường mầm non',
    'trường tiểu học',
  ],
  pets: [
    'thú cưng',
    'chó',
    'mèo',
    'cá cảnh',
    'chim cảnh',
    'thức ăn chó',
    'thức ăn mèo',
    'thú y',
    'bác sĩ thú y',
    'tiêm phòng chó mèo',
    'xén lông',
    'tắm chó',
    'cửa hàng thú cưng',
    'pet shop',
    'lồng chim',
    'bể cá',
    'phụ kiện thú cưng',
    // === Vietnam merchants ===
    'pet mart',
    'paddy pet shop',
    'vipet',
  ],
  travel: [
    'vé máy bay',
    'vietnam airlines',
    'vietjet',
    'bamboo airways',
    'vietravel',
    'khách sạn',
    'resort',
    'homestay',
    'booking',
    'agoda',
    'airbnb',
    'du lịch',
    'tour',
    'visa',
    'hộ chiếu',
    'hành lý',
    'balo du lịch',
    'vali',
    'đặt phòng',
    'vé tàu hoả',
    'tàu hoả',
    'xe đi tỉnh',
    'du lịch nước ngoài',
    'passport',
    'đổi tiền ngoại tệ',
    // === Vietnam merchants ===
    'traveloka',
    'mytour',
    'ivivu',
    'luxstay',
  ],
  fitness: [
    'phòng gym',
    'gym',
    'yoga',
    'zumba',
    'thể dục',
    'thể thao',
    'bơi lội',
    'hồ bơi',
    'bóng đá',
    'cầu lông',
    'tennis',
    'bóng rổ',
    'chạy bộ',
    'thành viên gym',
    'hội viên',
    'california fitness',
    'giày thể thao',
    'dụng cụ thể thao',
    'protein',
    'whey',
    'supplement',
    // === Vietnam merchants ===
    'elite fitness',
    'citygym',
    'fit24',
  ],
  gifts: [
    'quà',
    'quà tặng',
    'quà sinh nhật',
    'quà cưới',
    'phong bì',
    'mừng cưới',
    'mừng thọ',
    'quà Tết',
    'quà Giáng Sinh',
    'quà valentine',
    'hoa',
    'bánh sinh nhật',
    'thiệp',
    'voucher tặng',
    'đồ chơi trẻ em',
    'mừng tân gia',
    'từ thiện',
    'ủng hộ',
    'quyên góp',
  ],
  salary: [
    'lương',
    'tiền lương',
    'thưởng',
    'thu nhập',
    'freelancer',
    'chuyển khoản',
    'nhận lương',
    'lương tháng',
    'thưởng tháng 13',
    'thưởng tết',
    'hoa hồng',
    'commission',
    'trợ cấp',
    'phụ cấp',
    'overtime',
    'làm thêm giờ',
    'thu nhập thụ động',
    'cho thuê',
    'tiền cộng tác',
    'doanh thu',
    'tiền bán',
  ],
  investment: [
    'đầu tư',
    'cổ phiếu',
    'chứng khoán',
    'vps securities',
    'ssi',
    'vnsc',
    'finhay',
    'momo invest',
    'quỹ',
    'quỹ đầu tư',
    'vàng',
    'mua vàng',
    'sjc',
    'bất động sản',
    'tiết kiệm',
    'gửi tiết kiệm',
    'lãi suất',
    'crypto',
    'bitcoin',
    'ethereum',
    'binance',
    'tiền điện tử',
    'ngoại tệ',
    'forex',
    'cổ tức',
    'lợi nhuận',
  ],
  refund: [
    'hoàn tiền',
    'refund',
    'cashback',
    'hoàn lại',
    'trả hàng',
    'đổi hàng',
    'bồi thường',
    'hoàn phí',
    'hoàn cọc',
    'nhận lại tiền',
    'shopee hoàn',
    'lazada hoàn',
    'tiki hoàn',
    'khiếu nại',
    'bảo hành',
    'đổi trả',
  ],
};

export default vi;
