import { NativeModules, Platform } from 'react-native';

/**
 * Bridge to the ActivityKit live-earnings activity (see
 * `Money2TimeLiveActivityModule.swift`, generated by
 * `plugins/withMoney2TimeWidgets.js`).
 *
 * Live Activities are iOS-only and need no Apple approval: the app just
 * declares `NSSupportsLiveActivities`. What it cannot do is repaint on its
 * own. ActivityKit only redraws the card when something pushes an update, so
 * everything time-derived on the card (the elapsed clock, the progress bar) is
 * rendered by the system from the start/end dates, and the money figure has to
 * be sent to it.
 *
 * Three things send it, in descending order of how often they get to run:
 *
 *  - the **live-earnings Worker**, once a minute for the life of the session.
 *    This is the only one that works while the phone is locked and the app is
 *    suspended, which is to say the only one that makes the figure *tick*. It
 *    needs a push token, which is why the activity is requested with
 *    `pushType: .token` and why `pushToken` comes back on every read.
 *  - the app itself, on every foreground transition, so the card is right the
 *    instant the user looks at it even if a push was missed.
 *  - the card's own refresh button, a `LiveActivityIntent` run in the app's
 *    process.
 */

export interface LiveActivityStatus {
  /** The OS can run Live Activities at all. */
  supported: boolean;
  /** The user has not switched them off for Money2Time in iOS Settings. */
  enabled: boolean;
}

export interface LiveActivitySession {
  id: string;
  /** Epoch ms. */
  startedAt: number;
  /** Epoch ms. */
  endsAt: number;
  /** The rate the session was started at, carried through the activity. */
  hourlyRate: number;
  earnedText: string;
  /**
   * The APNs address of this card, hex-encoded, once ActivityKit has minted
   * one. Absent when the token has not arrived yet or the OS declined to issue
   * one - the session still runs, it just cannot be pushed to, so the amount
   * falls back to only moving when the app is in the foreground.
   */
  pushToken?: string;
}

export interface LiveActivityStartPayload {
  startedAt: number;
  endsAt: number;
  hourlyRate: number;
  /** All copy is localized in JS: the extension has no i18n catalog. */
  earnedText: string;
  /** The same amount unformatted, for the digit-roll animation. */
  earned: number;
  /** The app's theme colour as 0xRRGGBB, light and dark variants. */
  accentLightHex: number;
  accentDarkHex: number;
  titleText: string;
  rateText: string;
  endsText: string;
  /** "RM180.00": what the whole session is worth if it runs to the end. */
  totalText: string;
  /** Accessibility label for the card's refresh button. */
  refreshText: string;
}

interface NativeLiveActivityModule {
  getStatus?: () => Promise<LiveActivityStatus>;
  getPushToStartToken?: () => Promise<string | null>;
  getCurrent?: () => Promise<LiveActivitySession | null>;
  start?: (payload: LiveActivityStartPayload) => Promise<LiveActivitySession>;
  update?: (payload: { earnedText: string; earned: number }) => Promise<boolean>;
  end?: () => Promise<void>;
}

const nativeLiveActivityModule = NativeModules.Money2TimeLiveActivity as
  | NativeLiveActivityModule
  | undefined;

/**
 * False on Android, on web, and on an iOS build made before the Live Activity
 * target existed, so callers can hide the feature rather than fail on tap.
 */
export const isLiveActivityAvailable =
  Platform.OS === 'ios' && typeof nativeLiveActivityModule?.start === 'function';

export async function getLiveActivityStatus(): Promise<LiveActivityStatus> {
  if (!isLiveActivityAvailable) return { supported: false, enabled: false };
  try {
    return (await nativeLiveActivityModule?.getStatus?.()) ?? { supported: false, enabled: false };
  } catch {
    return { supported: false, enabled: false };
  }
}

/**
 * The device's push-to-start token, or null when a shift cannot be started
 * without the app.
 *
 * This is a different token from the one on a session: it addresses the
 * activity **type** on this device rather than a card, it outlives every card
 * started from it, and it is the only thing that can raise a Live Activity
 * while the app is not running - which is what makes the auto-start schedule
 * an auto-start rather than a reminder to tap.
 *
 * Null is an ordinary answer, not a failure: it means iOS below 17.2, Live
 * Activities switched off for Money2Time, or a token that has not been minted
 * yet (it arrives asynchronously, like a session's). Callers fall back to the
 * local notification instead.
 */
export async function getLiveActivityPushToStartToken(): Promise<string | null> {
  if (!isLiveActivityAvailable) return null;
  try {
    return (await nativeLiveActivityModule?.getPushToStartToken?.()) ?? null;
  } catch {
    return null;
  }
}

export async function getCurrentLiveActivity(): Promise<LiveActivitySession | null> {
  if (!isLiveActivityAvailable) return null;
  try {
    return (await nativeLiveActivityModule?.getCurrent?.()) ?? null;
  } catch {
    return null;
  }
}

export async function startLiveActivity(
  payload: LiveActivityStartPayload,
): Promise<LiveActivitySession> {
  if (!nativeLiveActivityModule?.start) {
    throw new Error('Live Activities are not available on this device.');
  }
  return nativeLiveActivityModule.start(payload);
}

/**
 * `true` when the running activity took the new figures, `false` when
 * ActivityKit says there is no activity left to update (the user swiped it
 * away), and `null` when the call itself failed and we simply cannot tell.
 *
 * The three cases have to stay distinct: the caller clears its session on
 * `false`, and folding an error into that would make a transient failure look
 * like the user dismissing a card that is still sitting on their Lock Screen.
 */
export async function updateLiveActivity(
  earnedText: string,
  earned: number,
): Promise<boolean | null> {
  if (!isLiveActivityAvailable) return null;
  try {
    return (await nativeLiveActivityModule?.update?.({ earnedText, earned })) ?? null;
  } catch {
    return null;
  }
}

export async function endLiveActivity(): Promise<void> {
  if (!isLiveActivityAvailable) return;
  try {
    await nativeLiveActivityModule?.end?.();
  } catch {
    // Ending is best-effort: iOS reaps the activity on its own timer anyway.
  }
}
