const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/**
 * Android payment alerts: a NotificationListenerService that copies the text of
 * payment notifications from the banking and wallet apps the user picked into
 * the app's files directory, where the JS drain (PaymentAlertSync) parses and
 * queues them for user review. Design: "Notification review" in the repository README.
 *
 * What the listener does, and deliberately does not do:
 *
 * - **It reads only the apps the user chose.** `config.json`, written by the
 *   JS side, lists them; everything else is dropped in memory. With no config
 *   (or capture off) nothing is kept. The one other thing it notes is which
 *   apps post notifications at all (package and label, never content), so the
 *   setup screen can offer "Recently active" apps.
 * - **It does no parsing and logs nothing.** It writes raw text, one file per
 *   alert, `<millis>-<uuid>.json` written as `.part` and renamed, so a file the
 *   drain can see is always complete and the folder listing is the queue
 *   (features/autoLog/lib/captureQueue.ts reads it). Parsing, binding,
 *   categories and de-duplication live in TypeScript, where they are tested.
 * - **It never starts JS.** The drain runs the next time the app is open; when
 *   it already is, the module emits `Money2TimePaymentCaptureQueued` so the
 *   payment appears at once.
 * - **The setup screen's test alert** is money2time's own notification tagged
 *   `m2t-payment-alert-test`; it is captured with `"test": true` and only ever
 *   previewed.
 *
 * Play policy: notification access needs the prominent disclosure the setup
 * screen shows before sending the user to the system toggle, and a Play
 * Console declaration. Sideloaded builds on Android 13+ get "restricted
 * settings"; the setup screen explains the workaround.
 *
 * Package visibility: the suggested apps are declared in a `<queries>` block
 * built from features/autoLog/lib/paymentApps.ts, so the picker can show the
 * installed ones without QUERY_ALL_PACKAGES.
 */

const PACKAGE_PATH = 'com/nelsongan/money2time';
const CAPTURE_PACKAGE = 'com.nelsongan.money2time.paymentcapture';
const SERVICE_NAME = '.paymentcapture.PaymentCaptureListener';
/** Must match PAYMENT_CAPTURES_DIR in features/autoLog/lib/captureQueue.ts. */
const PAYMENT_CAPTURES_DIR = 'payment-captures';
/** Must match PAYMENT_CAPTURE_TEST_TAG in features/autoLog/lib/captureQueue.ts. */
const PAYMENT_CAPTURE_TEST_TAG = 'm2t-payment-alert-test';
/** Must match CAPTURE_QUEUED_EVENT in services/paymentCapture.ts. */
const CAPTURE_QUEUED_EVENT = 'Money2TimePaymentCaptureQueued';
/** Must match the NativeModules name in services/paymentCapture.ts. */
const MODULE_NAME = 'Money2TimePaymentCapture';
/** Source of the suggested apps; the plugin reads their package ids from it. */
const PAYMENT_APPS_SOURCE = 'features/autoLog/lib/paymentApps.ts';

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfChanged(filePath, contents) {
  ensureDir(path.dirname(filePath));
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf8') === contents) return;
  fs.writeFileSync(filePath, contents);
}

/**
 * Package ids of the suggested payment apps. Read out of the TypeScript catalog
 * rather than duplicated, so adding an app there is the whole job; a test
 * checks this matches PAYMENT_APPS.
 */
function paymentAppPackages(projectRoot) {
  const source = fs.readFileSync(path.join(projectRoot, PAYMENT_APPS_SOURCE), 'utf8');
  const packages = new Set();
  for (const match of source.matchAll(/\bpackage:\s*'([A-Za-z0-9_.]+)'/g)) {
    packages.add(match[1]);
  }
  return [...packages].sort();
}

const STORE_SOURCE = `package ${CAPTURE_PACKAGE}

import android.app.Notification
import android.content.Context
import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.graphics.Canvas
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Parcelable
import android.service.notification.StatusBarNotification
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.util.UUID
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * Generated by plugins/withMoney2TimePaymentCapture.js. Do not edit by hand.
 *
 * Everything the listener and the module share, all in
 * filesDir/${PAYMENT_CAPTURES_DIR} (features/autoLog/lib/captureQueue.ts reads it):
 * one <millis>-<uuid>.json per captured alert, config.json (written by JS),
 * status.json (listener health) and seen-apps.json (which apps post
 * notifications: package and label only). All work runs on one background
 * thread, so the files never see two writers from this side.
 */
internal object PaymentCaptureStore {
  const val TAG = "Money2TimePaymentCapture"
  const val TEST_TAG = "${PAYMENT_CAPTURE_TEST_TAG}"
  private const val DIR = "${PAYMENT_CAPTURES_DIR}"
  private const val CONFIG_FILE = "config.json"
  private const val STATUS_FILE = "status.json"
  private const val SEEN_FILE = "seen-apps.json"
  private const val ICON_DIR = "payment-capture-icons"
  private const val SHELL_PACKAGE = "com.android.shell"
  /** Raw text kept per field; a payment alert is a sentence or two. */
  private const val MAX_TEXT = 2000
  private const val MAX_LINES = 10
  private const val MAX_MESSAGES = 3
  /** Captures waiting for the app beyond this many lose their oldest. */
  private const val MAX_QUEUE = 1000
  private const val MAX_SEEN = 40
  private const val MINUTE = 60_000L
  private const val DAY = 24 * 60 * MINUTE

  val executor: ExecutorService = Executors.newSingleThreadExecutor()

  fun dir(context: Context): File {
    val dir = File(context.filesDir, DIR)
    if (!dir.exists()) dir.mkdirs()
    return dir
  }

  // --- config.json ----------------------------------------------------------

  data class Config(
    val enabled: Boolean,
    val optedOut: Boolean,
    val packages: Set<String>,
    val allowShell: Boolean,
    val testTag: String,
  )

  private val OFF = Config(false, false, emptySet(), false, TEST_TAG)
  private var config: Config? = null
  private var configModified = Long.MIN_VALUE
  private var configLength = -1L
  private var configReadAt = 0L

  /** Re-read when the file changes, and at least every half minute. */
  fun config(context: Context): Config {
    val file = File(dir(context), CONFIG_FILE)
    val exists = file.exists()
    val modified = if (exists) file.lastModified() else 0L
    val length = if (exists) file.length() else 0L
    val now = System.currentTimeMillis()
    val cached = config
    if (cached != null && modified == configModified && length == configLength && now - configReadAt < 30_000L) {
      return cached
    }
    // No file: capture nothing. An unreadable one (caught mid-write) keeps the last good read.
    val next = if (!exists) OFF else parseConfig(file) ?: cached ?: OFF
    config = next
    configModified = modified
    configLength = length
    configReadAt = now
    return next
  }

  private fun parseConfig(file: File): Config? =
    try {
      val json = JSONObject(file.readText())
      val packages = HashSet<String>()
      json.optJSONArray("packages")?.let { list ->
        for (i in 0 until list.length()) {
          val name = list.optString(i)
          if (name.isNotBlank()) packages.add(name)
        }
      }
      Config(
        enabled = json.optBoolean("enabled", false),
        optedOut = json.optBoolean("optedOut", false),
        packages = packages,
        allowShell = json.optBoolean("allowShell", false),
        testTag = json.optString("testTag", TEST_TAG).ifBlank { TEST_TAG },
      )
    } catch (error: Exception) {
      null
    }

  // --- status.json ----------------------------------------------------------

  private var statusLoaded = false
  private var connected = false
  private var connectedAt = 0L
  private var lastNotificationAt = 0L
  private var lastCaptureAt = 0L
  private var statusWrittenAt = 0L

  private fun loadStatus(context: Context) {
    if (statusLoaded) return
    statusLoaded = true
    try {
      val file = File(dir(context), STATUS_FILE)
      if (!file.exists()) return
      val json = JSONObject(file.readText())
      connectedAt = json.optLong("connectedAt", 0L)
      lastNotificationAt = json.optLong("lastNotificationAt", 0L)
      lastCaptureAt = json.optLong("lastCaptureAt", 0L)
    } catch (error: Exception) {
      // A fresh status is fine.
    }
  }

  private fun writeStatus(context: Context) {
    val json = JSONObject()
      .put("v", 1)
      .put("connected", connected)
      .put("connectedAt", connectedAt)
      .put("lastNotificationAt", lastNotificationAt)
      .put("lastCaptureAt", lastCaptureAt)
    writeAtomically(File(dir(context), STATUS_FILE), json.toString())
    statusWrittenAt = System.currentTimeMillis()
  }

  fun noteConnected(context: Context, isConnected: Boolean) {
    loadStatus(context)
    connected = isConnected
    if (isConnected) connectedAt = System.currentTimeMillis()
    writeStatus(context)
  }

  private fun noteNotification(context: Context, at: Long) {
    loadStatus(context)
    lastNotificationAt = at
    // Every notification on the phone passes through here; health only needs "recently".
    if (at - statusWrittenAt > 5 * MINUTE) writeStatus(context)
  }

  private fun noteCapture(context: Context, at: Long) {
    loadStatus(context)
    lastNotificationAt = maxOf(lastNotificationAt, at)
    lastCaptureAt = at
    writeStatus(context)
  }

  // --- seen-apps.json -------------------------------------------------------

  private class SeenApp(val pkg: String, var label: String, var lastSeenAt: Long, var count: Int)

  private var seen: LinkedHashMap<String, SeenApp>? = null
  private var seenWrittenAt = 0L

  private fun loadSeen(context: Context): LinkedHashMap<String, SeenApp> {
    seen?.let { return it }
    val map = LinkedHashMap<String, SeenApp>()
    try {
      val file = File(dir(context), SEEN_FILE)
      if (file.exists()) {
        val list = JSONArray(file.readText())
        for (i in 0 until list.length()) {
          val row = list.optJSONObject(i) ?: continue
          val pkg = row.optString("package")
          if (pkg.isBlank()) continue
          map[pkg] = SeenApp(pkg, row.optString("label", pkg), row.optLong("lastSeenAt", 0L), row.optInt("count", 0))
        }
      }
    } catch (error: Exception) {
      // Start over.
    }
    seen = map
    return map
  }

  private fun noteSeenApp(context: Context, pkg: String, appInfo: ApplicationInfo?, at: Long) {
    val map = loadSeen(context)
    val existing = map[pkg]
    if (existing != null) {
      existing.lastSeenAt = at
      existing.count += 1
      // Order is irrelevant on disk (JS sorts); a rewrite every half hour keeps it fresh.
      if (at - seenWrittenAt > 30 * MINUTE) writeSeen(context, map)
      return
    }
    map[pkg] = SeenApp(pkg, labelOf(context, pkg, appInfo) ?: pkg, at, 1)
    if (map.size > MAX_SEEN) {
      map.values.minByOrNull { it.lastSeenAt }?.let { map.remove(it.pkg) }
    }
    writeSeen(context, map)
    // Cache its icon now, while the notification carries the app's info.
    iconUri(context, pkg, appInfo)
  }

  private fun writeSeen(context: Context, map: Map<String, SeenApp>) {
    val list = JSONArray()
    map.values.forEach { app ->
      list.put(
        JSONObject()
          .put("package", app.pkg)
          .put("label", app.label)
          .put("lastSeenAt", app.lastSeenAt)
          .put("count", app.count),
      )
    }
    writeAtomically(File(dir(context), SEEN_FILE), list.toString())
    seenWrittenAt = System.currentTimeMillis()
  }

  fun seenLabel(context: Context, pkg: String): String? = loadSeen(context)[pkg]?.label

  fun clearSeen(context: Context) {
    seen = LinkedHashMap()
    File(dir(context), SEEN_FILE).delete()
  }

  // --- app info -------------------------------------------------------------

  /**
   * The posting app's info. Notifications built with Notification.Builder
   * carry it, which works without package visibility; otherwise ask the
   * package manager, which only answers for declared or visible packages.
   */
  @Suppress("DEPRECATION")
  private fun applicationInfoOf(context: Context, notification: Notification, pkg: String): ApplicationInfo? {
    val fromExtras =
      try {
        if (Build.VERSION.SDK_INT >= 33) {
          notification.extras?.getParcelable("android.appInfo", ApplicationInfo::class.java)
        } else {
          notification.extras?.getParcelable("android.appInfo") as? ApplicationInfo
        }
      } catch (error: Exception) {
        null
      }
    if (fromExtras != null && fromExtras.packageName == pkg) return fromExtras
    return visibleApplicationInfo(context, pkg)
  }

  fun visibleApplicationInfo(context: Context, pkg: String): ApplicationInfo? =
    try {
      context.packageManager.getApplicationInfo(pkg, 0)
    } catch (error: PackageManager.NameNotFoundException) {
      null
    } catch (error: Exception) {
      null
    }

  fun labelOf(context: Context, pkg: String, appInfo: ApplicationInfo?): String? {
    val info = appInfo ?: visibleApplicationInfo(context, pkg) ?: return null
    return try {
      info.loadLabel(context.packageManager).toString().trim().takeIf { it.isNotEmpty() }
    } catch (error: Exception) {
      null
    }
  }

  /** A file:// URI of the app's icon as a small PNG, cached for a week. */
  fun iconUri(context: Context, pkg: String, appInfo: ApplicationInfo?): String? {
    val dir = File(context.cacheDir, ICON_DIR)
    if (!dir.exists()) dir.mkdirs()
    val file = File(dir, "$pkg.png")
    val cached = if (file.exists()) Uri.fromFile(file).toString() else null
    if (cached != null && System.currentTimeMillis() - file.lastModified() < 7 * DAY) return cached
    val info = appInfo ?: visibleApplicationInfo(context, pkg) ?: return cached
    return try {
      val drawable = info.loadIcon(context.packageManager)
      val size = 96
      val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888)
      drawable.setBounds(0, 0, size, size)
      drawable.draw(Canvas(bitmap))
      val part = File(dir, "$pkg.png.part")
      FileOutputStream(part).use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
      bitmap.recycle()
      if (!part.renameTo(file)) part.delete()
      Uri.fromFile(file).toString()
    } catch (error: Exception) {
      cached
    }
  }

  // --- captures -------------------------------------------------------------

  /** Last content seen per notification key, so a silent re-post is not a second alert. */
  private val recent =
    object : LinkedHashMap<String, Pair<Int, Long>>(64, 0.75f, true) {
      override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, Pair<Int, Long>>?): Boolean = size > 100
    }

  fun handlePosted(context: Context, sbn: StatusBarNotification, at: Long) {
    try {
      val config = config(context)
      if (config.optedOut) return
      noteNotification(context, at)
      val pkg = sbn.packageName ?: return
      val notification = sbn.notification ?: return
      val own = pkg == context.packageName
      val appInfo = if (own) null else applicationInfoOf(context, notification, pkg)
      if (!own) noteSeenApp(context, pkg, appInfo, at)
      if (!config.enabled) return

      val isTest = own && sbn.tag == config.testTag
      val accepted = isTest || pkg in config.packages || (config.allowShell && pkg == SHELL_PACKAGE)
      if (!accepted) return
      // A group summary repeats its children; an ongoing one is a status, not an alert.
      if (!isTest && (notification.flags and Notification.FLAG_GROUP_SUMMARY) != 0) return
      if (sbn.isOngoing) return

      val label = if (own) null else labelOf(context, pkg, appInfo)
      val capture = captureJson(sbn, notification, label, isTest) ?: return
      if (isRepeat(sbn.key, capture, at)) return
      if (writeCapture(context, capture, at)) {
        remember(sbn.key, capture, at)
        noteCapture(context, at)
        PaymentCaptureModule.emitCaptureQueued()
      }
    } catch (error: Exception) {
      Log.w(TAG, "Could not capture a notification", error)
    }
  }

  /** The setup test without a notification: money2time's own notifications are blocked. */
  fun writeDirectTest(context: Context, title: String, body: String) {
    try {
      val at = System.currentTimeMillis()
      val capture = JSONObject()
        .put("v", 1)
        .put("package", context.packageName)
        .put("postedAt", at)
        .put("title", title.take(MAX_TEXT))
        .put("text", body.take(MAX_TEXT))
        .put("test", true)
      if (writeCapture(context, capture, at)) PaymentCaptureModule.emitCaptureQueued()
    } catch (error: Exception) {
      Log.w(TAG, "Could not queue the test alert", error)
    }
  }

  private fun text(value: CharSequence?): String? {
    val trimmed = value?.toString()?.trim() ?: return null
    return if (trimmed.isEmpty()) null else trimmed.take(MAX_TEXT)
  }

  @Suppress("DEPRECATION")
  private fun messagesOf(extras: Bundle): List<String> {
    val raw: Array<out Parcelable>? =
      try {
        if (Build.VERSION.SDK_INT >= 33) {
          extras.getParcelableArray(Notification.EXTRA_MESSAGES, Parcelable::class.java)
        } else {
          extras.getParcelableArray(Notification.EXTRA_MESSAGES)
        }
      } catch (error: Exception) {
        null
      }
    if (raw == null) return emptyList()
    return raw.mapNotNull { item -> (item as? Bundle)?.getCharSequence("text")?.let { text(it) } }.takeLast(MAX_MESSAGES)
  }

  private fun captureJson(
    sbn: StatusBarNotification,
    notification: Notification,
    appLabel: String?,
    isTest: Boolean,
  ): JSONObject? {
    val extras = notification.extras ?: return null
    val title = text(extras.getCharSequence(Notification.EXTRA_TITLE))
      ?: text(extras.getCharSequence(Notification.EXTRA_TITLE_BIG))
    val body = text(extras.getCharSequence(Notification.EXTRA_TEXT))
    val bigText = text(extras.getCharSequence(Notification.EXTRA_BIG_TEXT))
    val lines = extras.getCharSequenceArray(Notification.EXTRA_TEXT_LINES)
      ?.mapNotNull { text(it) }
      ?.takeLast(MAX_LINES)
      ?: emptyList()
    val messages = messagesOf(extras)
    if (body == null && bigText == null && lines.isEmpty() && messages.isEmpty()) return null

    val json = JSONObject()
      .put("v", 1)
      .put("package", sbn.packageName)
      .put("postedAt", sbn.postTime)
      .put("key", sbn.key)
    appLabel?.let { json.put("appLabel", it) }
    title?.let { json.put("title", it) }
    body?.let { json.put("text", it) }
    bigText?.let { json.put("bigText", it) }
    text(extras.getCharSequence(Notification.EXTRA_SUB_TEXT))?.let { json.put("subText", it) }
    text(extras.getCharSequence(Notification.EXTRA_SUMMARY_TEXT))?.let { json.put("summaryText", it) }
    text(extras.getCharSequence(Notification.EXTRA_INFO_TEXT))?.let { json.put("infoText", it) }
    if (lines.isNotEmpty()) json.put("lines", JSONArray(lines))
    if (messages.isNotEmpty()) {
      val list = JSONArray()
      messages.forEach { list.put(JSONObject().put("text", it)) }
      json.put("messages", list)
    }
    if (isTest) json.put("test", true)
    return json
  }

  private fun fingerprintOf(capture: JSONObject): Int = listOf("title", "text", "bigText", "lines", "messages")
      .joinToString("|") { capture.opt(it)?.toString() ?: "" }
      .hashCode()

  private fun isRepeat(key: String, capture: JSONObject, at: Long): Boolean {
    val previous = recent[key]
    return previous != null && previous.first == fingerprintOf(capture) && at - previous.second < 2 * MINUTE
  }

  private fun remember(key: String, capture: JSONObject, at: Long) {
    recent[key] = Pair(fingerprintOf(capture), at)
  }

  private fun writeCapture(context: Context, capture: JSONObject, at: Long): Boolean {
    val dir = dir(context)
    trimQueue(dir)
    val name = "$at-" + UUID.randomUUID().toString() + ".json"
    val part = File(dir, "$name.part")
    return try {
      part.writeText(capture.toString())
      if (part.renameTo(File(dir, name))) {
        true
      } else {
        part.delete()
        false
      }
    } catch (error: Exception) {
      part.delete()
      false
    }
  }

  /** An app left closed for months must not fill the disk; the oldest alerts go first. */
  private fun trimQueue(dir: File) {
    val captures = dir.listFiles { file -> CAPTURE_NAME.matches(file.name) } ?: return
    if (captures.size < MAX_QUEUE) return
    captures.sortedBy { it.name.substringBefore('-').toLongOrNull() ?: 0L }
      .take(captures.size - MAX_QUEUE + 1)
      .forEach { it.delete() }
  }

  private val CAPTURE_NAME = Regex("^\\\\d{10,}-[A-Za-z0-9-]+\\\\.json$")

  private fun writeAtomically(file: File, contents: String) {
    try {
      val part = File(file.parentFile, file.name + ".part")
      part.writeText(contents)
      if (!part.renameTo(file)) {
        file.delete()
        if (!part.renameTo(file)) part.delete()
      }
    } catch (error: Exception) {
      Log.w(TAG, "Could not write " + file.name, error)
    }
  }
}
`;

const LISTENER_SOURCE = `package ${CAPTURE_PACKAGE}

import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import java.lang.ref.WeakReference

/**
 * Generated by plugins/withMoney2TimePaymentCapture.js. Do not edit by hand.
 *
 * Bound by Android once the user turns on notification access for
 * money2time. Each posted notification is handed to PaymentCaptureStore on its
 * background thread, which keeps only alerts from the apps the user chose.
 */
class PaymentCaptureListener : NotificationListenerService() {
  override fun onListenerConnected() {
    super.onListenerConnected()
    instance = WeakReference(this)
    val context = applicationContext
    PaymentCaptureStore.executor.execute {
      PaymentCaptureStore.noteConnected(context, true)
      // Turned off in the app after being used: Android rebinds every enabled
      // listener after a reboot, so step aside again.
      if (PaymentCaptureStore.config(context).optedOut) {
        try {
          requestUnbind()
        } catch (error: Exception) {
          // Already unbinding.
        }
      }
    }
  }

  override fun onListenerDisconnected() {
    super.onListenerDisconnected()
    if (instance?.get() === this) instance = null
    val context = applicationContext
    PaymentCaptureStore.executor.execute { PaymentCaptureStore.noteConnected(context, false) }
  }

  override fun onNotificationPosted(sbn: StatusBarNotification?) {
    val posted = sbn ?: return
    val context = applicationContext
    val at = System.currentTimeMillis()
    PaymentCaptureStore.executor.execute { PaymentCaptureStore.handlePosted(context, posted, at) }
  }

  companion object {
    @Volatile
    internal var instance: WeakReference<PaymentCaptureListener>? = null

    /** Bound in this process right now (status.json can be stale after a crash). */
    fun isConnected(): Boolean = instance?.get() != null
  }
}
`;

const MODULE_SOURCE = `package ${CAPTURE_PACKAGE}

import android.Manifest
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.ActivityNotFoundException
import android.content.ComponentName
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.provider.Settings
import android.service.notification.NotificationListenerService
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.ReadableArray
import java.lang.ref.WeakReference

/**
 * Generated by plugins/withMoney2TimePaymentCapture.js. Do not edit by hand.
 *
 * The JS side of payment alerts on Android (services/paymentCapture.ts):
 * notification-access state and settings, rebinding a dropped listener, the
 * setup screen's test alert, and app labels and icons for the app picker. The
 * captures themselves are files, read by JS directly.
 */
class PaymentCaptureModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
  init {
    contextRef = WeakReference(reactContext)
  }

  override fun getName(): String = "${MODULE_NAME}"

  private fun listenerComponent() = ComponentName(reactApplicationContext, PaymentCaptureListener::class.java)

  @ReactMethod
  fun getAccessState(promise: Promise) {
    val context = reactApplicationContext
    val granted = NotificationManagerCompat.getEnabledListenerPackages(context).contains(context.packageName)
    val state = Arguments.createMap()
    state.putBoolean("granted", granted)
    state.putBoolean("connected", granted && PaymentCaptureListener.isConnected())
    promise.resolve(state)
  }

  /** The listener's own page where the OS has one (Android 11+), else the list. */
  @ReactMethod
  fun openAccessSettings(promise: Promise) {
    val context = reactApplicationContext
    val intents = ArrayList<Intent>()
    if (Build.VERSION.SDK_INT >= 30) {
      intents.add(
        Intent(Settings.ACTION_NOTIFICATION_LISTENER_DETAIL_SETTINGS)
          .putExtra(Settings.EXTRA_NOTIFICATION_LISTENER_COMPONENT_NAME, listenerComponent().flattenToString()),
      )
    }
    intents.add(Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS))
    val activity = context.currentActivity
    for (intent in intents) {
      try {
        if (activity != null) {
          activity.startActivity(intent)
        } else {
          context.startActivity(intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
        }
        promise.resolve(null)
        return
      } catch (error: ActivityNotFoundException) {
        // Some builds drop the detail page; try the list.
      } catch (error: SecurityException) {
        // Same.
      }
    }
    promise.reject("unavailable", "No notification access settings on this device")
  }

  @ReactMethod
  fun requestRebind(promise: Promise) {
    try {
      NotificationListenerService.requestRebind(listenerComponent())
      promise.resolve(null)
    } catch (error: Exception) {
      promise.reject("rebind_failed", error)
    }
  }

  @ReactMethod
  fun requestUnbind(promise: Promise) {
    try {
      PaymentCaptureListener.instance?.get()?.requestUnbind()
      PaymentCaptureStore.executor.execute { PaymentCaptureStore.clearSeen(reactApplicationContext) }
      promise.resolve(null)
    } catch (error: Exception) {
      promise.reject("unbind_failed", error)
    }
  }

  /**
   * A real notification the listener captures like a bank's, tagged so it is
   * only previewed. Without permission to post, the test is queued directly so
   * the preview still runs.
   */
  @ReactMethod
  fun postTestAlert(title: String, body: String, channelName: String, promise: Promise) {
    val context = reactApplicationContext
    val manager = NotificationManagerCompat.from(context)
    val mayPost =
      manager.areNotificationsEnabled() &&
        (Build.VERSION.SDK_INT < 33 ||
          ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) ==
            PackageManager.PERMISSION_GRANTED)
    if (!mayPost) {
      PaymentCaptureStore.executor.execute { PaymentCaptureStore.writeDirectTest(context, title, body) }
      promise.resolve("direct")
      return
    }
    try {
      if (Build.VERSION.SDK_INT >= 26) {
        val channel = NotificationChannel(TEST_CHANNEL, channelName, NotificationManager.IMPORTANCE_DEFAULT)
        context.getSystemService(NotificationManager::class.java)?.createNotificationChannel(channel)
      }
      val notification = NotificationCompat.Builder(context, TEST_CHANNEL)
        .setSmallIcon(context.applicationInfo.icon)
        .setContentTitle(title)
        .setContentText(body)
        .setStyle(NotificationCompat.BigTextStyle().bigText(body))
        .setAutoCancel(true)
        .setTimeoutAfter(TEST_TIMEOUT_MS)
        .build()
      manager.notify(PaymentCaptureStore.TEST_TAG, TEST_ID, notification)
      // Gone again once captured, so it never lingers in the shade.
      Handler(Looper.getMainLooper()).postDelayed({
        try {
          manager.cancel(PaymentCaptureStore.TEST_TAG, TEST_ID)
        } catch (error: Exception) {
          // Already gone.
        }
      }, TEST_VISIBLE_MS)
      promise.resolve("posted")
    } catch (error: SecurityException) {
      PaymentCaptureStore.executor.execute { PaymentCaptureStore.writeDirectTest(context, title, body) }
      promise.resolve("direct")
    } catch (error: Exception) {
      promise.reject("post_failed", error)
    }
  }

  /**
   * Labels and icons for the picker: installed packages the app may see (the
   * declared payment apps), and apps the listener saw notifying, whose icon it
   * cached at the time. Packages it knows nothing about are left out.
   */
  @ReactMethod
  fun getAppInfo(packages: ReadableArray, promise: Promise) {
    val context = reactApplicationContext
    val names = (0 until packages.size()).mapNotNull { packages.getString(it) }
    PaymentCaptureStore.executor.execute {
      try {
        val result = Arguments.createArray()
        for (pkg in names) {
          val info = PaymentCaptureStore.visibleApplicationInfo(context, pkg)
          val icon = PaymentCaptureStore.iconUri(context, pkg, info)
          if (info == null && icon == null) continue
          val label = PaymentCaptureStore.labelOf(context, pkg, info) ?: PaymentCaptureStore.seenLabel(context, pkg) ?: pkg
          val row = Arguments.createMap()
          row.putString("package", pkg)
          row.putString("label", label)
          if (icon != null) row.putString("iconUri", icon) else row.putNull("iconUri")
          result.pushMap(row)
        }
        promise.resolve(result)
      } catch (error: Exception) {
        promise.reject("app_info_failed", error)
      }
    }
  }

  companion object {
    private const val TEST_CHANNEL = "money2time_payment_alert_test"
    private const val TEST_ID = 4242
    private const val TEST_VISIBLE_MS = 6_000L
    private const val TEST_TIMEOUT_MS = 30_000L

    @Volatile
    private var contextRef: WeakReference<ReactApplicationContext>? = null

    /** Tell a running app a capture is waiting; harmless when none is. */
    fun emitCaptureQueued() {
      val context = contextRef?.get() ?: return
      try {
        if (context.hasActiveReactInstance()) context.emitDeviceEvent("${CAPTURE_QUEUED_EVENT}", null)
      } catch (error: Exception) {
        // The app picks it up on its next foreground.
      }
    }
  }
}
`;

const PACKAGE_SOURCE = `package ${CAPTURE_PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Generated by plugins/withMoney2TimePaymentCapture.js. Do not edit by hand. */
class PaymentCapturePackage : ReactPackage {
  @Deprecated("Matches the interface; the widget package registers the same way.")
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(PaymentCaptureModule(reactContext))

  override fun createViewManagers(
    reactContext: ReactApplicationContext,
  ): List<ViewManager<in Nothing, in Nothing>> = emptyList()
}
`;

function patchMainApplication(androidRoot) {
  const filePath = path.join(androidRoot, 'app/src/main/java', PACKAGE_PATH, 'MainApplication.kt');
  if (!fs.existsSync(filePath)) {
    throw new Error(
      'withMoney2TimePaymentCapture: expected MainApplication.kt to register the module.',
    );
  }
  let source = fs.readFileSync(filePath, 'utf8');
  if (source.includes('PaymentCapturePackage')) return;
  source = source.replace(
    /package com\.nelsongan\.money2time\n/,
    `package com.nelsongan.money2time\n\nimport ${CAPTURE_PACKAGE}.PaymentCapturePackage\n`,
  );
  const patched = source.replace(
    /(PackageList\(this\)\.packages\s*)/,
    '$1\n          .also { packages -> packages.add(PaymentCapturePackage()) }',
  );
  if (patched === source) {
    throw new Error(
      'withMoney2TimePaymentCapture: could not find PackageList in MainApplication.kt.',
    );
  }
  fs.writeFileSync(filePath, patched);
}

function withPaymentCaptureSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const sourceRoot = path.join(
        androidRoot,
        'app/src/main/java',
        PACKAGE_PATH,
        'paymentcapture',
      );
      writeFileIfChanged(path.join(sourceRoot, 'PaymentCaptureStore.kt'), STORE_SOURCE);
      writeFileIfChanged(path.join(sourceRoot, 'PaymentCaptureListener.kt'), LISTENER_SOURCE);
      writeFileIfChanged(path.join(sourceRoot, 'PaymentCaptureModule.kt'), MODULE_SOURCE);
      writeFileIfChanged(path.join(sourceRoot, 'PaymentCapturePackage.kt'), PACKAGE_SOURCE);
      patchMainApplication(androidRoot);
      return cfg;
    },
  ]);
}

function withPaymentCaptureManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.service = (app.service ?? []).filter(
      (service) => service.$?.['android:name'] !== SERVICE_NAME,
    );
    app.service.push({
      $: {
        'android:name': SERVICE_NAME,
        'android:exported': 'true',
        'android:permission': 'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE',
      },
      'intent-filter': [
        {
          action: [
            { $: { 'android:name': 'android.service.notification.NotificationListenerService' } },
          ],
        },
      ],
      'meta-data': [
        // Android 12+ lets the user narrow what a listener receives; ongoing
        // notifications (media, navigation, downloads) are never alerts.
        {
          $: {
            'android:name': 'android.service.notification.default_filter_types',
            'android:value': 'conversations|alerting|silent',
          },
        },
        {
          $: {
            'android:name': 'android.service.notification.disabled_filter_types',
            'android:value': 'ongoing',
          },
        },
      ],
    });

    // Suggested apps, so the picker can tell which are installed.
    const packages = paymentAppPackages(cfg.modRequest.projectRoot);
    const ours = new Set(packages);
    manifest.queries = (manifest.queries ?? [])
      .map((query) => ({
        ...query,
        package: (query.package ?? []).filter((entry) => !ours.has(entry.$?.['android:name'])),
      }))
      .filter((query) =>
        Object.keys(query).some((key) => key !== 'package' || query.package.length > 0),
      );
    manifest.queries.push({
      package: packages.map((name) => ({ $: { 'android:name': name } })),
    });
    return cfg;
  });
}

module.exports = function withMoney2TimePaymentCapture(config) {
  config = withPaymentCaptureManifest(config);
  config = withPaymentCaptureSources(config);
  return config;
};

module.exports.PAYMENT_CAPTURES_DIR = PAYMENT_CAPTURES_DIR;
module.exports.PAYMENT_CAPTURE_TEST_TAG = PAYMENT_CAPTURE_TEST_TAG;
module.exports.CAPTURE_QUEUED_EVENT = CAPTURE_QUEUED_EVENT;
module.exports.MODULE_NAME = MODULE_NAME;
module.exports.paymentAppPackages = paymentAppPackages;
