const da = {
  food: [
    // General meal terms
    'mad',
    'frokost',
    'middag',
    'morgenmad',
    'aftensmad',
    'brunch',
    'mellemmåltid',
    'snack',
    'snacks',
    'restaurant',
    'restauranter',
    'café',
    'kaffebar',
    'spisested',
    'takeaway',
    'take away',
    'levering',
    'afhentningsmad',
    // Danish dishes & food culture
    'kaffe',
    'smørrebrød',
    'flæskesteg',
    'æbleskiver',
    'leverpostej',
    'rugbrød',
    'wienerbrød',
    'remoulade',
    'hot dog',
    'pølsevogn',
    'pølse',
    'rød pølse',
    'koldskål',
    'øllebrød',
    'stegt flæsk',
    'frikadeller',
    'biksemad',
    'medisterpølse',
    'boller i karry',
    'hakkebøf',
    'tarteletter',
    'lagkage',
    'kanelsnegl',
    'tebirkes',
    'rundstykker',
    'franskbrød',
    'cremehorn',
    'hindbærsnitte',
    'drømmekage',
    'romkugle',
    // Drinks
    'øl',
    'vin',
    'kaffe latte',
    'cappuccino',
    'americano',
    'espresso',
    'te',
    'juice',
    'sodavand',
    // Food delivery platforms (DK)
    'wolt',
    'foodora',
    'just eat',
    'just eat dk',
    'hungry.dk',
    // Brands & chains (DK)
    'sunset boulevard',
    "sticks'n'sushi",
    'sticks n sushi',
    'joe and the juice',
    'joe & the juice',
    'baresso',
    'baresso coffee',
    '7-eleven dk',
    'netto dk',
    'føtex',
    'lagkagehuset',
    'reinh van hauen',
    "o'learys",
    'wok inn',
    'karma sushi',
    'sushida',
  ],
  groceries: [
    // General terms
    'dagligvarer',
    'indkøb',
    'supermarked',
    'dagligvarebutik',
    'grønt',
    'frugt',
    'kød',
    'fisk',
    'brød',
    'mælk',
    'mejeriprodukter',
    'æg',
    'smør',
    'ost',
    'yoghurt',
    'pålæg',
    'konserves',
    'frostvarer',
    'kolonial',
    // Danish supermarket chains
    'netto',
    'føtex',
    'bilka',
    'rema 1000',
    'rema',
    'aldi',
    'lidl',
    'meny',
    'superbrugsen',
    'kvickly',
    'fakta',
    'coop',
    'irma',
    'spar dk',
    "dagli'brugsen",
    'brugsen',
    'løvbjerg',
    'fleggaard',
    'inco',
    'jem og fix',
  ],
  transport: [
    // General terms
    'tog',
    's-tog',
    'letbane',
    'taxa',
    'parkering',
    'benzin',
    'diesel',
    'brændstof',
    'p-afgift',
    'bomring',
    // Transit systems & brands
    'rejsekort',
    'dsb',
    'arriva dk',
    'arriva',
    'midttrafik',
    'movia',
    'sydtrafik',
    'fynbus',
    'ntrafik',
    'bornholmertrafikken',
    // Ride-hailing (DK)
    'bolt dk',
    'uber dk',
    'dantaxi',
    'taxa 4x35',
    '4x35',
    // Ferries & bridges
    'øresundsbro',
    'storebælt',
    'storebæltsforbindelsen',
    'mols-linien',
    'scandlines',
    'bornholmerfærgen',
    // Train types
    'ic3',
    'intercity',
    'regional tog',
    // Airlines (DK)
    'sas',
    'scandinavian airlines',
    'norwegian dk',
    // Fuel stations (DK)
    'circle k',
    'ok benzin',
    'q8',
    'uno-x',
    'ingo',
    // EV charging
    'ladestation',
    'clever',
    'clever ladestation',
  ],
  housing: [
    // General terms
    'husleje',
    'leje',
    'boliglån',
    'realkreditlån',
    'realkredit',
    'andelsbolig',
    'ejendomsskat',
    'grundskyld',
    'fællesudgifter',
    'fællesomkostninger',
    'vedligeholdelse',
    'vedligehold',
    'istandsættelse',
    'renovering',
    'lejlighed',
    'villa',
    'rækkehus',
    'kollegium',
    'fremleje',
    'depositum',
    // Property & management
    'grundejerforening',
    'ejerforening',
    'boligforening',
    'andelsforening',
    'ejendomsadministrator',
    'dab',
    'boligselskab',
    // Home services
    'vvs',
    'elektriker',
    'tømrer',
    'murer',
    'maler',
    'håndværker',
    'skorstensfejning',
    'vinduespolering',
    'rengøringsservice',
    'haveservice',
    'snerydning',
    // Insurance
    'husforsikring',
    'indboforsikring',
    'ejerskifteforsikring',
  ],
  bills: [
    // General
    'elregning',
    'strøm',
    'vandregning',
    'fjernvarme',
    'varme',
    'gasregning',
    'mobilabonnement',
    'abonnement',
    'forsikring',
    'regning',
    // Utilities (DK)
    'ørsted',
    'radius elnet',
    'hofor',
    'nordvand',
    'norlys',
    'ewii',
    'cerius',
    'nrgi',
    'seas-nve',
    'n1',
    'verdo',
    'energi fyn',
    // Telco (DK)
    'yousee',
    'tdc',
    'telenor dk',
    'telia dk',
    '3 danmark',
    '3dk',
    'cbb mobil',
    'telmore',
    'lebara dk',
    'oister',
    'lycamobile dk',
    'callme',
    // TV / streaming (DK)
    'tv 2',
    'tv2',
    'tv3',
    'viaplay dk',
    'viaplay',
    'tv 2 play',
    'tv2 play',
    // Insurance companies (DK)
    'tryg',
    'codan',
    'if forsikring',
    'topdanmark',
    'alm brand',
    'alm. brand',
    'gjensidige',
    'lb forsikring',
  ],
  healthcare: [
    // General
    'læge',
    'hospital',
    'apotek',
    'medicin',
    'recept',
    'lægebesøg',
    'konsultation',
    'tandlæge',
    'optiker',
    'sygesikring',
    'sygedagpenge',
    'behandling',
    'terapi',
    'psykolog',
    'fysioterapeut',
    'kiropraktor',
    'akupunktur',
    'vagtlæge',
    'skadestue',
    'ambulance',
    'blodprøve',
    'scanning',
    'operation',
    // Danish specific
    'regioner',
    'region',
    'sundhedskort',
    'sundhedsforsikring',
    'kritisk sygdomsforsikring',
    // Pharmacy brands
    'apoteket dk',
    'boots apotek',
    'docmorris',
    // Vision
    'synoptik',
    'louis nielsen',
    'pearle',
    // Dental
    'tandklinik',
    'tandplejer',
    // Mental health
    'psykiater',
    'psykiatri',
  ],
  shopping: [
    // General
    'butik',
    'netbutik',
    'webshop',
    'tøj',
    'sko',
    'elektronik',
    'boligindretning',
    'møbler',
    'gavekort',
    'onlineshopping',
    // Major retailers (DK)
    'ikea dk',
    'elgiganten',
    'power dk',
    'magasin du nord',
    'magasin',
    'illum',
    'storcenter',
    'fields',
    'fisketorvet',
    'city 2',
    // Fashion (DK / Scandinavian)
    'vero moda',
    'jack & jones',
    'only',
    'name it',
    'selected',
    'selected femme',
    'selected homme',
    'bestseller',
    'lindbergh',
    'second female',
    'ichi',
    'pieces',
    'noisy may',
    'vila',
    // Beauty / personal care
    'matas',
    'normal dk',
    'flying tiger',
    'søstrene grene',
    'sinnerup',
    'bolia',
    // Electronics
    'komplett dk',
    'proshop dk',
  ],
  entertainment: [
    // General
    'biograf',
    'teater',
    'koncert',
    'museum',
    'udstilling',
    'festival',
    'forlystelsespark',
    'fodbold',
    'håndbold',
    'kamp',
    'spillehallen',
    'escape room',
    'bowling',
    'karting',
    'paintball',
    // Cinema brands (DK)
    'palads',
    'cinemaxx',
    'nordisk film biografer',
    'cinemaxx dk',
    'empire biograferne',
    // Cultural venues
    'tivoli',
    'bakken',
    'nationalmuseet',
    'statens museum for kunst',
    'smk',
    'louisiana',
    'aros',
    'den gamle by',
    'experimentarium',
    // Music / events
    'royal arena',
    'det kongelige teater',
    'vega',
    'store vega',
    'musikhuset aarhus',
    'odeon odense',
  ],
  education: [
    // General
    'skole',
    'skoleudgifter',
    'universitet',
    'uddannelse',
    'kursus',
    'pensum',
    'studiebøger',
    'undervisning',
    'lektiehjælp',
    'privatundervisning',
    'studiematerialer',
    'eksamensgebyr',
    'studieafgift',
    'studielån',
    // Danish specific
    'su',
    'statens uddannelsesstøtte',
    'uddannelsesstøtte',
    'gymnasiet',
    'hf',
    'erhvervsskole',
    'eux',
    'htx',
    'stx',
    'hhx',
    'vuc',
    'cphbusiness',
    'university college',
  ],
  pets: [
    // General
    'kæledyr',
    'hund',
    'kat',
    'fugl',
    'kanin',
    'dyrlæge',
    'dyreklinik',
    'dyrehandler',
    'hundefoder',
    'kattesand',
    'hundetræning',
    'hundepasning',
    'kattepasning',
    'dyreinternat',
    'hundepension',
    'grooming',
    'pelspleje',
    'halsbånd',
    'hundesnor',
    'ormekur',
    'vaccination',
    'chipning',
    'dyreforsikring',
    // Pet store brands (DK)
    'fressnapf',
    'zooplus',
    'musti',
    'musti og mirri',
    'petworld',
    'zoobio',
  ],
  travel: [
    // General
    'rejse',
    'ferie',
    'flyrejse',
    'flyticket',
    'overnatning',
    'hostel',
    'sommerhus',
    'campingplads',
    'camping',
    'billeje',
    'biludlejning',
    'rejseforsikring',
    'bagage',
    'kuffert',
    'visum',
    'rejsebureau',
    'pakkerejse',
    // Danish / Nordic travel brands
    'spies',
    'tjæreborg',
    'ving dk',
    'apollo',
    'bravo tours',
    'sunshine holidays',
    // Booking platforms
    'momondo',
    'rejseplanen',
    // Ferry operators
    'dfds',
    'color line',
    'fjord line',
    'stena line dk',
    // Accommodation
    'danland',
    'novasol',
    'dansommer',
  ],
  fitness: [
    // General
    'fitnesscenter',
    'gym',
    'træning',
    'holdtræning',
    'personlig træner',
    'crossfit',
    'yoga',
    'pilates',
    'svømning',
    'svømmehallen',
    'løb',
    'spinning',
    'sportsklubb',
    'idrætsforening',
    'boldklub',
    'tennis',
    'padel',
    'badminton',
    'squash',
    // Gym chains (DK)
    'fitness world',
    'fitnessworld',
    'sats dk',
    'sats',
    'elixia dk',
    'loop fitness',
    // Sports equipment
    'sportsmaster',
    'intersport dk',
    'intersport',
    'xxl sport',
    'xxl',
    'decathlon dk',
    'sport24',
    'løberen',
    'sportigan',
  ],
  gifts: [
    // General
    'gave',
    'gaver',
    'donation',
    'donationer',
    'bidrag',
    'blomster',
    'buket',
    'konfirmation',
    'bryllup',
    'fødselsdagsgave',
    'julegave',
    'julegaver',
    'velgørenhed',
    'indsamling',
    // Danish charity
    'røde kors',
    'unicef dk',
    'læger uden grænser dk',
    'folkekirkens nødhjælp',
    'red barnet',
    'kræftens bekæmpelse',
    'hjerteforeningen',
    'danmission',
    // Gift & flowers
    'gavekort',
    'blomsterhandler',
    'interflora dk',
  ],
  salary: [
    // General
    'løn',
    'månedlig løn',
    'lønudbetaling',
    'overarbejde',
    'bonus',
    'udbetaling',
    'honorar',
    'konsulenthonorar',
    'freelanceindtægt',
    'dagpenge',
    'barselsdagpenge',
    'feriepenge',
    'feriegodtgørelse',
    'efterløn',
    'folkepension',
    'tjenestemandspension',
    // Payment platforms (DK)
    'mobilepay betaling',
    'mobilepay',
    'lønoverførsel',
    'bankoverførsel',
  ],
  investment: [
    // General
    'investering',
    'aktier',
    'obligationer',
    'investeringsfond',
    'etf',
    'depot',
    'kurtage',
    'udbytte',
    'renteindtægt',
    'kapitalgevinst',
    'kryptovaluta',
    'crowdfunding',
    // Danish investment platforms / banks
    'nordnet dk',
    'nordnet',
    'saxo bank',
    'saxoinvestor',
    'sparinvest',
    'maj invest',
    // Pension
    'pensionsindbetaling',
    'pfa pension',
    'danica pension',
    'nordea liv og pension',
    'ap pension',
    'velliv',
    'sampension',
    'pfa',
    'atp',
    'atp livslang pension',
  ],
  refund: [
    // General
    'tilbagebetaling',
    'tilbagebetalt',
    'refundering',
    'refunderet',
    'refusion',
    'kreditering',
    'kreditnota',
    'cashback',
    'tilbageføring',
    'tilbageført',
    'godtgørelse',
    'kompensation',
    'erstatning',
    // Shopping returns
    'returnering',
    'retur',
    'returvare',
    'bytte',
    'returpenge',
    // Insurance / healthcare refund
    'sygesikringsgodtgørelse',
    'forsikringserstatning',
    'forsikringsudbetaling',
    'skadeserstatning',
    // Tax
    'overskydende skat',
    'skatteoverskud',
    'skat tilbage',
    'årsopgørelse',
    // Travel refund
    'aflyst fly',
    'flykompensation',
    'forsinkelse kompensation',
    'rejseforsikring udbetaling',
    // MobilePay
    'tilbagebetaling mobilepay',
    'mobilepay tilbage',
  ],
};

export default da;
