const es = {
  food: [
    'comida',
    'comidas',
    'almuerzo',
    'almuerzos',
    'cena',
    'cenas',
    'desayuno',
    'merienda',
    'bocadillo',
    'bocadillos',
    'tapas',
    'tapa',
    'pincho',
    'pinchos',
    'ración',
    'menú',
    'menú del día',
    'plato del día',
    'comida a domicilio',
    'para llevar',
    'a domicilio',
    'paella',
    'tortilla',
    'tortilla española',
    'gazpacho',
    'salmorejo',
    'cocido',
    'fabada',
    'puchero',
    'caldo',
    'potaje',
    'croquetas',
    'jamón',
    'jamón serrano',
    'jamón ibérico',
    'chorizo',
    'morcilla',
    'lomo',
    'butifarra',
    'empanada',
    'empanadas',
    'pulpo',
    'pulpo a la gallega',
    'boquerones',
    'calamares',
    'gambas',
    'gambas al ajillo',
    'patatas bravas',
    'pan con tomate',
    'churros',
    'porras',
    'migas',
    'pisto',
    'arroz con leche',
    'flan',
    'crema catalana',
    'buñuelos',
    'torrijas',
    'turrón',
    'polvorón',
    'mantecado',
    'tacos',
    'taco',
    'quesadilla',
    'quesadillas',
    'burrito',
    'burritos',
    'enchiladas',
    'tamales',
    'tostadas',
    'sopes',
    'tlayuda',
    'pozole',
    'menudo',
    'birria',
    'carnitas',
    'barbacoa',
    'chilaquiles',
    'huevos rancheros',
    'molletes',
    'torta',
    'tortas',
    'gorditas',
    'cemita',
    'pambazo',
    'arepas',
    'arepa',
    'bandeja paisa',
    'sancocho',
    'ajiaco',
    'lechona',
    'mondongo',
    'lomo saltado',
    'ceviche',
    'tiradito',
    'anticuchos',
    'causa',
    'pollo a la brasa',
    'arroz con pollo',
    'asado',
    'choripán',
    'medialunas',
    'milanesa',
    'locro',
    'alfajor',
    'alfajores',
    'mate',
    'ropa vieja',
    'picadillo',
    'congri',
    'plátanos fritos',
    'tequeños',
    'hallacas',
    'pabellón criollo',
    'café con leche',
    'cortado',
    'carajillo',
    'clara',
    'cerveza',
    'caña',
    'vermut',
    'tinto',
    'tinto de verano',
    'sangría',
    'sidra',
    'horchata',
    'agua fresca',
    'aguas frescas',
    'licuado',
    'licuados',
    'jugo',
    'jugos',
    'chicha',
    'chicha morada',
    'refresco',
    'refrescos',
    'gaseosa',
    'gaseosas',
    'limonada',
    'tamarindo',
    'jamaica',
    'tepache',
    'pulque',
    'michelada',
    'clericot',
    'fernet',
    'pisco',
    'pisco sour',
    'tequila',
    'mezcal',
    'ron',
    'cuba libre',
    'daiquirí',
    'mojito',
    'guarapo',
    'agua de panela',
    'restaurante',
    'restorán',
    'resto',
    'mesón',
    'tasca',
    'bodegón',
    'asador',
    'parrilla',
    'parrillada',
    'marisquería',
    'chiringuito',
    'cantina',
    'fonda',
    'comedor',
    'lonchería',
    'taquería',
    'cevichería',
    'pollería',
    'picantería',
    'chifería',
    'tamalería',
    'tortillería',
    'panadería',
    'pastelería',
    'confitería',
    'heladería',
    'gelatería',
    'nevería',
    'paleta',
    'paletas',
    'frutería',
    'jugería',
    'cafetería',
    'bar',
    'bodega',
    'telepizza',
    'dominos',
    'vips',
    'rodilla',
    'pans and company',
    'bocatta',
    'goiko grill',
    'goiko',
    'honest greens',
    'pollo campero',
    'bembos',
    'pardos chicken',
    'chinawok',
    'la lucha',
    'crepes y waffles',
    'el corral',
    'frisby',
    'madam tusan',
    'sanguchería',
  ],
  groceries: [
    'supermercado',
    'supermercados',
    'mercado',
    'mercados',
    'mercadillo',
    'tienda',
    'tiendas',
    'colmado',
    'bodega',
    'abarrotes',
    'almacén',
    'almacenes',
    'ultramarinos',
    'despensa',
    'verdulería',
    'carnicería',
    'pescadería',
    'charcutería',
    'lácteos',
    'panadería',
    'mercadona',
    'carrefour',
    'lidl',
    'aldi',
    'dia',
    'eroski',
    'el corte inglés',
    'alcampo',
    'hipercor',
    'consum',
    'ahorramas',
    'condis',
    'caprabo',
    'bonpreu',
    'esclat',
    'gadis',
    'spar',
    'supercor',
    'simply',
    'makro',
    'walmart',
    'chedraui',
    'soriana',
    'bodega aurrera',
    'la comer',
    'city market',
    'superama',
    'tianguis',
    'exito',
    'carulla',
    'jumbo',
    'metro',
    'd1',
    'ara',
    'olímpica',
    'disco',
    'vea',
    'coto',
    'walmart',
    'changomas',
    'día',
    'lider',
    'líder',
    'unimarc',
    'santa isabel',
    'tottus',
    'wong',
    'plaza vea',
    'vivanda',
    'mass',
    'economax',
    'supermaxi',
    'megamaxi',
    'aki',
    'tía',
    'superselectos',
    'econo',
    'selectos',
    'frutas',
    'verduras',
    'hortalizas',
    'legumbres',
    'carne',
    'carnes',
    'pollo',
    'pescado',
    'marisco',
    'mariscos',
    'huevos',
    'leche',
    'queso',
    'yogur',
    'yogurt',
    'mantequilla',
    'pan',
    'harina',
    'arroz',
    'pasta',
    'fideos',
    'aceite',
    'sal',
    'azúcar',
    'condimentos',
    'especias',
    'conservas',
    'enlatados',
    'embutidos',
    'jabón',
    'detergente',
    'limpieza',
    'higiene',
    'pañales',
    'hacer la compra',
    'la compra',
    'las compras',
    'mandado',
    'ir al mercado',
    'ir al súper',
  ],
  transport: [
    'transporte',
    'traslado',
    'traslados',
    'pasaje',
    'pasajes',
    'billete',
    'billetes',
    'boleto',
    'boletos',
    'cuota',
    'abono',
    'abono transporte',
    'tarjeta transporte',
    'recarga',
    'metro',
    'subte',
    'subterráneo',
    'metropolitano',
    'autobús',
    'autobus',
    'autobuses',
    'bus',
    'buses',
    'colectivo',
    'colectivos',
    'micro',
    'micros',
    'microbús',
    'metrobús',
    'transmilenio',
    'mio',
    'megabus',
    'tranvía',
    'tren',
    'trenes',
    'cercanías',
    'renfe',
    'rodalies',
    'feve',
    'ave',
    'alvia',
    'ferrocarril',
    'ruta',
    'rutas',
    'línea',
    'taxi',
    'taxis',
    'taxista',
    'radiotaxi',
    'remis',
    'remise',
    'remises',
    'cabify',
    'indrive',
    'didi',
    'beat',
    'picap',
    'kwik',
    'yango',
    'tapsi',
    'fastoy',
    'taxibeat',
    'easy taxi',
    'gasolina',
    'gasoil',
    'diésel',
    'diesel',
    'nafta',
    'bencina',
    'combustible',
    'carburante',
    'surtidor',
    'gasolinera',
    'estación de servicio',
    'bencinera',
    'bomba de gasolina',
    'ypf',
    'repsol',
    'cepsa',
    'galp',
    'pemex',
    'copec',
    'primax',
    'oxxo gas',
    'estacionamiento',
    'estacionamientos',
    'aparcamiento',
    'parquímetro',
    'parquear',
    'parqueo',
    'cochera',
    'garaje',
    'autopista',
    'peaje',
    'peajes',
    'caseta',
    'casetas',
    'telepeaje',
    'via t',
    'viat',
    'tag',
    'telepass',
    'taller mecánico',
    'taller',
    'mecánico',
    'itv',
    'revisión técnica',
    'grúa',
    'remolque',
    'seguro de coche',
    'seguro auto',
    'seguro vehicular',
    'moto',
    'motos',
    'motocicleta',
    'scooter',
    'patinete',
    'bicicleta',
    'bicis',
    'bici',
    'ecobici',
    'bicing',
    'sevici',
    'valenbisi',
    'bicimad',
    'ferry',
    'ferri',
    'barco',
    'lancha',
    'barca',
    'avión',
    'vuelo',
    'vuelos',
    'aerolínea',
    'iberia',
    'vueling',
    'air europa',
    'volotea',
    'ryanair',
    'aeromexico',
    'avianca',
    'latam',
    'copa',
    'vivaaerobus',
    'volaris',
    'skyairline',
    'jetsmart',
    'camión',
    'pesero',
    'combis',
    'ómnibus',
    'omnibus',
    'locomoción',
    'flota',
    'flotas',
  ],
  housing: [
    'alquiler',
    'alquilar',
    'alquileres',
    'arriendo',
    'arrendamiento',
    'renta',
    'rentar',
    'hipoteca',
    'hipotecas',
    'préstamo hipotecario',
    'letra',
    'cuota hipoteca',
    'comunidad',
    'cuota comunidad',
    'gastos comunidad',
    'ibi',
    'impuesto de bienes inmuebles',
    'derrama',
    'derramas',
    'fondo de reserva',
    'condominio',
    'administración',
    'cuota de administración',
    'expensas',
    'expensas comunes',
    'reparación',
    'reparaciones',
    'fontanería',
    'fontanero',
    'plomería',
    'plomero',
    'electricista',
    'albañil',
    'carpintero',
    'pintor',
    'pintura',
    'limpieza del hogar',
    'servicio doméstico',
    'empleada del hogar',
    'mucama',
    'niñera',
    'canguro',
    'portero',
    'mueble',
    'muebles',
    'electrodoméstico',
    'electrodomésticos',
    'lavadora',
    'lavarropa',
    'nevera',
    'refrigerador',
    'heladera',
    'microondas',
    'horno',
    'lavavajillas',
    'cocina',
    'estufa',
    'calentador',
    'calefacción',
    'aire acondicionado',
    'ventilador',
    'colchón',
    'sofá',
    'sillón',
    'armario',
    'ropero',
    'placares',
    'placard',
    'agua',
    'gas',
    'luz',
    'electricidad',
    'basura',
    'recogida de basura',
  ],
  bills: [
    'factura',
    'facturas',
    'recibo',
    'recibos',
    'pago',
    'pagos',
    'servicio',
    'servicios',
    'suscripción',
    'suscripciones',
    'cuota',
    'cuotas',
    'mensualidad',
    'mensualidades',
    'domiciliación',
    'cargo',
    'cargos',
    'suministros',
    'suministro',
    'luz',
    'electricidad',
    'endesa',
    'iberdrola',
    'naturgy',
    'repsol energía',
    'enel',
    'edp',
    'cfe',
    'comisión federal de electricidad',
    'epm',
    'codensa',
    'luz del sur',
    'edelnor',
    'enel perú',
    'chilelectra',
    'edesur',
    'edenor',
    'eden',
    'edelap',
    'ande',
    'ete',
    'agua y gas',
    'gas natural fenosa',
    'metrogas',
    'canal de isabel ii',
    'agbar',
    'aigues de barcelona',
    'emasa',
    'aqualia',
    'aguas del valle',
    'sedapal',
    'aguas andinas',
    'movistar',
    'vodafone',
    'orange',
    'yoigo',
    'jazztel',
    'masmovil',
    'pepephone',
    'simyo',
    'amena',
    'lowi',
    'digi',
    'fibra óptica',
    'adsl',
    'internet en casa',
    'claro',
    'telmex',
    'telcel',
    'entel',
    'personal',
    'wom',
    'bitel',
    'virgin mobile',
    'nextel',
    'movilnet',
    'digitel',
    'cantv',
    'tigo',
    'une',
    'etb',
    'emcali',
    'antel',
    'disney plus',
    'disney+',
    'hbo max',
    'max',
    'prime video',
    'amazon prime',
    'paramount plus',
    'apple tv',
    'apple tv+',
    'apple one',
    'spotify',
    'deezer',
    'tidal',
    'youtube premium',
    'crunchyroll',
    'mubi',
    'filmin',
    'movistar plus',
    'movistar+',
    'canal plus',
    'canal+',
    'sky',
    'izzi',
    'axtel',
    'megacable',
    'claro tv',
    'cable',
    'tv cable',
    'cablevisión',
    'telecentro',
    'fibertel',
    'arnet',
    'speedy',
    'seguro',
    'seguros',
    'póliza',
    'poliza',
    'aseguradora',
    'mapfre',
    'axa',
    'allianz',
    'generali',
    'zurich',
    'caser',
    'mutua madrileña',
    'sanitas',
    'adeslas',
    'asisa',
    'línea directa',
    'verti',
    'qualitas',
    'basura',
    'limpieza viaria',
    'tasa municipal',
    'impuesto',
    'impuestos',
    'isr',
    'iva',
    'cuota autónomo',
    'autónomo',
    'seguridad social',
  ],
  healthcare: [
    'médico',
    'medico',
    'médica',
    'doctora',
    'doctor',
    'consulta',
    'consultas',
    'consulta médica',
    'visita médica',
    'cita médica',
    'cita',
    'citas',
    'urgencias',
    'emergencia',
    'emergencias',
    'clínica',
    'clinica',
    'hospital',
    'hospitales',
    'sanatorio',
    'centro de salud',
    'ambulatorio',
    'policlínico',
    'centro médico',
    'farmacia',
    'farmacias',
    'farmacéutico',
    'farmaceutico',
    'medicamento',
    'medicamentos',
    'medicina',
    'medicinas',
    'pastillas',
    'pastilla',
    'tabletas',
    'tableta',
    'cápsulas',
    'jarabe',
    'jarabes',
    'inyección',
    'inyecciones',
    'suero',
    'vitaminas',
    'suplemento',
    'anticonceptivos',
    'farmacias guadalajara',
    'farmacias similares',
    'farmacias del ahorro',
    'inkafarma',
    'mifarma',
    'farmacenter',
    'farmatodo',
    'locatel',
    'cruz verde',
    'ahumada',
    'salcobrand',
    'fasa',
    'fybeca',
    'drogueria',
    'dentista',
    'dental',
    'ortodoncia',
    'odontólogo',
    'odontología',
    'oftalmólogo',
    'óptica',
    'optica',
    'gafas',
    'lentillas',
    'lentes de contacto',
    'anteojos',
    'audífono',
    'fisioterapia',
    'fisioterapeuta',
    'kinesiólogo',
    'terapeuta',
    'terapia',
    'psicólogo',
    'psicologo',
    'psicóloga',
    'psiquiatra',
    'salud mental',
    'nutricionista',
    'dermatólogo',
    'pediatra',
    'ginecólogo',
    'laboratorio',
    'análisis de sangre',
    'analítica',
    'radiografía',
    'ecografía',
    'resonancia',
    'tomografía',
    'seguro médico',
    'seguro de salud',
    'plan de salud',
    'adeslas',
    'sanitas',
    'asisa',
    'fonasa',
    'isapre',
    'essalud',
    'imss',
    'issste',
    'vacuna',
    'vacunas',
    'vacunación',
    'chequeo médico',
    'revisión médica',
    'copago',
  ],
  shopping: [
    'compras',
    'comprar',
    'tienda',
    'tiendas',
    'centro comercial',
    'centros comerciales',
    'mall',
    'malls',
    'galería',
    'galería comercial',
    'el corte inglés',
    'corte inglés',
    'primark',
    'zara',
    'mango',
    'bershka',
    'stradivarius',
    'pull and bear',
    'pull&bear',
    'massimo dutti',
    'oysho',
    "women's secret",
    'springfield',
    'cortefiel',
    'lefties',
    'custo barcelona',
    'desigual',
    'camper',
    'tous',
    'carolina herrera',
    'loewe',
    'hackett',
    'scalpers',
    'tendam',
    'falabella',
    'ripley',
    'paris',
    'sodimac',
    'liverpool',
    'palacio de hierro',
    'suburbia',
    'sears mexico',
    'coppel',
    'elektra',
    'exito',
    'mercado libre',
    'mercadolibre',
    'mlm',
    'mla',
    'mlc',
    'olx',
    'linio',
    'shein',
    'aliexpress',
    'pccomponentes',
    'mediamarkt',
    'fnac',
    'worten',
    'amazon españa',
    'ropa',
    'ropas',
    'calzado',
    'zapatos',
    'zapatería',
    'zapatilla',
    'zapatillas',
    'tenis',
    'deportivas',
    'sandalias',
    'botas',
    'bolso',
    'bolsos',
    'cartera',
    'carteras',
    'joyería',
    'joyerías',
    'joya',
    'joyas',
    'bisutería',
    'relojería',
    'reloj',
    'relojes',
    'electrónica',
    'móvil',
    'movil',
    'celular',
    'smartphone',
    'tablet',
    'ordenador',
    'portátil',
    'laptop',
    'computadora',
    'televisión',
    'television',
    'tele',
    'auriculares',
    'cargador',
    'ferretería',
    'herramientas',
    'decoración',
    'jardín',
    'bricolaje',
    'leroy merlin',
    'aki',
    'bauhaus',
    'hornbach',
    'brico depot',
    'easy',
    'homecenter',
    'artesanía',
    'artículo',
    'artículos',
    'producto',
    'productos',
    'regalo',
    'regalos',
    'temporada',
    'rebaja',
    'rebajas',
    'oferta',
    'ofertas',
    'descuento',
    'descuentos',
    'liquidación',
    'chollos',
    'ganga',
    'gangas',
  ],
  entertainment: [
    'cine',
    'cines',
    'cinema',
    'cineplex',
    'kinépolis',
    'kinepolis',
    'yelmo',
    'yelmo cines',
    'cinesa',
    'cinépolis',
    'cinemex',
    'cinemark',
    'hoyts',
    'cinecolombia',
    'cineplanet',
    'película',
    'pelicula',
    'películas',
    'función',
    'funcion',
    'entrada de cine',
    'palomitas',
    'teatro',
    'teatros',
    'obra de teatro',
    'concierto',
    'conciertos',
    'festival',
    'festivales',
    'música en vivo',
    'recital',
    'recitales',
    'ópera',
    'opera',
    'ballet',
    'danza',
    'show',
    'shows',
    'espectáculo',
    'espectaculos',
    'comedia',
    'stand up',
    'monólogo',
    'circo',
    'entrada',
    'entradas',
    'localidad',
    'localidades',
    'ticketmaster',
    'taquilla',
    'palco',
    'butaca',
    'estadio',
    'estadios',
    'partido',
    'partidos',
    'fútbol',
    'futbol',
    'baloncesto',
    'básquet',
    'béisbol',
    'toros',
    'corrida',
    'plaza de toros',
    'videojuego',
    'videojuegos',
    'consola',
    'playstation',
    'xbox',
    'nintendo',
    'steam',
    'psn',
    'game pass',
    'bar',
    'bares',
    'discoteca',
    'discotecas',
    'boliche',
    'antro',
    'club nocturno',
    'club',
    'karaoke',
    'salsa',
    'bachata',
    'peña',
    'taberna',
    'pub',
    'pubs',
    'terraza',
    'terrazas',
    'copa',
    'copas',
    'marcha',
    'fiesta',
    'museo',
    'museos',
    'exposición',
    'exposicion',
    'galería de arte',
    'zoo',
    'zoológico',
    'acuario',
    'parque temático',
    'parque de atracciones',
    'libro',
    'libros',
    'librería',
    'revista',
    'revistas',
    'periódico',
    'periodico',
  ],
  education: [
    'educación',
    'estudios',
    'colegio',
    'colegios',
    'escuela',
    'escuelas',
    'instituto',
    'institutos',
    'liceo',
    'prepa',
    'preparatoria',
    'bachillerato',
    'universidad',
    'universidades',
    'unam',
    'itesm',
    'tec de monterrey',
    'ibero',
    'uanl',
    'uab',
    'uc',
    'unal',
    'udea',
    'javeriana',
    'andes',
    'uniandes',
    'cayetano heredia',
    'pucp',
    'utec',
    'icesi',
    'pontificia universidad',
    'uba',
    'unc',
    'unlp',
    'udec',
    'uch',
    'puc',
    'usach',
    'matrícula',
    'matricula',
    'inscripción',
    'mensualidad escolar',
    'pensión escolar',
    'aranceles',
    'arancel',
    'cuota escolar',
    'colegiatura',
    'colegiaturas',
    'curso',
    'cursos',
    'clases',
    'clase',
    'taller',
    'talleres',
    'capacitación',
    'formación',
    'máster',
    'master',
    'posgrado',
    'postgrado',
    'diplomado',
    'doctorado',
    'especialización',
    'tutor',
    'tutorías',
    'academía',
    'academia',
    'clases particulares',
    'refuerzo',
    'inglés',
    'idiomas',
    'idioma',
    'clases de idiomas',
    'escuela de idiomas',
    'duolingo',
    'babbel',
    'rosetta stone',
    'udemy',
    'coursera',
    'edx',
    'platzi',
    'domestika',
    'skillshare',
    'linkedin learning',
    'khan academy',
    'masterclass',
    'libros de texto',
    'útiles escolares',
    'material escolar',
    'cuaderno',
    'cuadernos',
    'lápices',
    'mochila',
    'uniforme',
    'uniformes',
    'examen',
    'exámenes',
    'certificación',
    'certificacion',
    'título',
    'titulo',
    'certificado',
  ],
  pets: [
    'mascota',
    'mascotas',
    'veterinario',
    'veterinaria',
    'vet',
    'veterinarios',
    'consulta veterinaria',
    'clinica veterinaria',
    'hospital veterinario',
    'comida de mascota',
    'comida para mascotas',
    'pienso',
    'piensos',
    'croquetas para perro',
    'croquetas para gato',
    'comida para perros',
    'comida para gatos',
    'peluquería canina',
    'baño de perro',
    'baño y corte',
    'peluquería de mascotas',
    'estética canina',
    'grooming',
    'kiwoko',
    'pet center',
    'petco',
    'petsmart',
    'vacuna mascota',
    'antiparasitario',
    'antipulgas',
    'desparasitación',
    'microchip',
    'esterilización',
    'operación vet',
    'collar',
    'correa',
    'arnés',
    'cama para perro',
    'cama para gato',
    'jaula',
    'terrario',
    'arenero',
    'arena para gatos',
    'guardería canina',
    'residencia canina',
    'hotel para mascotas',
    'perrería',
    'pensión para mascotas',
    'paseador',
    'paseo de perros',
    'cuidador de mascotas',
  ],
  travel: [
    'viaje',
    'viajes',
    'vacaciones',
    'escapada',
    'turismo',
    'excursión',
    'excursion',
    'excursiones',
    'aventura',
    'hotel',
    'hoteles',
    'hostal',
    'hostales',
    'hostel',
    'alojamiento',
    'pensión',
    'pension',
    'residencial',
    'apartahotel',
    'airbnb',
    'booking',
    'booking.com',
    'trivago',
    'hotels.com',
    'expedia',
    'agoda',
    'spa hotel',
    'resort',
    'posada',
    'mesón',
    'parador',
    'hacienda',
    'ecolodge',
    'cabaña',
    'cabañas',
    'casa rural',
    'camping',
    'billete de avión',
    'vuelo',
    'vuelos',
    'ticket de avión',
    'pasaje aéreo',
    'aeropuerto',
    'aeropuertos',
    'tasas de aeropuerto',
    'maleta',
    'equipaje',
    'renta de auto',
    'alquiler de auto',
    'alquiler de coche',
    'renta de carro',
    'rent a car',
    'hertz',
    'avis',
    'europcar',
    'sixt',
    'enterprise',
    'national',
    'dollar',
    'budget',
    'thrifty',
    'localiza',
    'movida',
    'tour',
    'tours',
    'guía turístico',
    'visita guiada',
    'entrada turística',
    'barco turístico',
    'crucero',
    'cruceros',
    'paquete vacacional',
    'paquete turístico',
    'agencia de viajes',
    'viajes el corte inglés',
    'viajes barceló',
    'barcelo',
    'iberojet',
    'tui',
    'thomas cook',
    'melia',
    'meliá',
    'nh hoteles',
    'riu',
    'viva',
    'palladium',
    'cambio de divisas',
    'cambio de moneda',
    'casa de cambio',
    'divisas',
    'tipo de cambio',
    'seguro de viaje',
  ],
  fitness: [
    'gimnasio',
    'gimnasios',
    'gym',
    'gyms',
    'fitness',
    'cuota del gimnasio',
    'mensualidad gimnasio',
    'matrícula gimnasio',
    'suscripción fitness',
    'decathlon',
    'basic fit',
    'mcfit',
    'fitness first',
    'lifestyle',
    'altafit',
    'o2 centro wellness',
    'bodybell',
    'eurofitness',
    'virgin active',
    'synergym',
    'anytime fitness',
    'smartfit',
    'bodytech',
    'hard rock gym',
    'sports world',
    'american fitness',
    'sportlife',
    'natación',
    'natacion',
    'pilates',
    'yoga',
    'crossfit',
    'spinning',
    'boxeo',
    'artes marciales',
    'karate',
    'judo',
    'taekwondo',
    'kickboxing',
    'muay thai',
    'escalada',
    'tenis',
    'pádel',
    'padel',
    'squash',
    'golf',
    'ciclismo',
    'atletismo',
    'running',
    'carrera popular',
    'maratón',
    'maraton',
    'media maratón',
    'triatlón',
    'ropa deportiva',
    'zapatillas de deporte',
    'zapatillas running',
    'zapatillas de correr',
    'decathlon compra',
    'intersport',
    'sprinter',
    'footlocker',
    'joma',
    'kelme',
    'spa',
    'masaje',
    'masajes',
    'quiromasaje',
    'fisioterapia',
    'osteopatía',
    'personal trainer',
    'entrenador personal',
    'entrenamiento',
    'clases de fitness',
    'clases de aeróbic',
    'aeróbic',
    'zumba',
    'bodypump',
  ],
  gifts: [
    'regalo',
    'regalos',
    'obsequio',
    'obsequios',
    'detalle',
    'detalles',
    'presente',
    'presentes',
    'sorpresa',
    'sorpresas',
    'gift card',
    'tarjeta regalo',
    'tarjeta de regalo',
    'bono regalo',
    'cumpleaños',
    'cumple',
    'navidad',
    'nochebuena',
    'año nuevo',
    'reyes',
    'día de reyes',
    'santos',
    'onomástica',
    'día del padre',
    'día de la madre',
    'san valentín',
    'aniversario',
    'boda',
    'bodas',
    'bautizo',
    'bautismo',
    'primera comunión',
    'comunión',
    'confirmación',
    'quinceañera',
    'quince años',
    'graduation',
    'graduación',
    'graduacion',
    'donación',
    'donaciones',
    'donativo',
    'donativos',
    'caridad',
    'obra social',
    'organización benéfica',
    'ong',
    'cáritas',
    'caritas',
    'cruz roja',
    'médicos sin fronteras',
    'teletón',
    'teleton',
    'unicef',
    'aldeas infantiles',
    'fundación',
    'flores',
    'florería',
    'florista',
    'ramo de flores',
    'ramo',
    'chocolates',
    'bombones',
    'cesta regalo',
  ],
  salary: [
    'sueldo',
    'sueldos',
    'salario',
    'salarios',
    'nómina',
    'nomina',
    'paga',
    'pagos',
    'pago de nómina',
    'mensualidad sueldo',
    'quincena',
    'quincenas',
    'quincena laboral',
    'liquidación',
    'finiquito',
    'prestaciones',
    'aguinaldo',
    'gratificación',
    'gratificaciones',
    'bono',
    'bonos',
    'bono anual',
    'plus',
    'pluses',
    'complemento',
    'complementos',
    'dieta',
    'dietas',
    'gastos de viaje',
    'kilometraje',
    'horas extras',
    'horas extraordinarias',
    'vacaciones pagadas',
    'comisión',
    'comisiones',
    'honorarios',
    'honorario',
    'remuneración',
    'remuneraciones',
    'ingreso laboral',
    'ingresos laborales',
    'factura emitida',
    'cobro',
    'cobros',
    'pago de cliente',
    'ingresos freelance',
    'ingresos autónomo',
    'autónomo',
    'autonomo',
    'cuenta propia',
    'trabajo independiente',
    'independiente',
    'recibo de honorarios',
    'cfdi',
    'ingreso',
    'ingresos',
    'renta',
    'alquiler cobrado',
    'arrendamiento ingreso',
    'pensión',
    'pensiones',
    'jubilación',
    'prestación por desempleo',
    'subsidio',
    'beca',
    'becas',
    'ingreso extra',
    'trabajo extra',
    'changas',
    'chamba',
    'chambas',
    'pololos',
  ],
  investment: [
    'inversión',
    'inversion',
    'inversiones',
    'invertir',
    'rendimiento',
    'rendimientos',
    'rentabilidad',
    'retorno',
    'acciones',
    'accion',
    'bolsa',
    'bolsa de valores',
    'mercado de valores',
    'bmv',
    'bvc',
    'santiago exchange',
    'renta variable',
    'fondo de inversión',
    'fondo de inversion',
    'fondos de inversión',
    'etf',
    'índice',
    'renta fija',
    'bono',
    'bonos',
    'deuda',
    'obligaciones',
    'ahorro',
    'ahorros',
    'cuenta de ahorro',
    'plazo fijo',
    'plazos fijos',
    'depósito a plazo',
    'deposito a plazo',
    'depósito fijo',
    'cdt',
    'cetes',
    'udibonos',
    'afore',
    'afores',
    'pensión privada',
    'plan de pensiones',
    'plan de jubilación',
    'fondos de pensión',
    'inmueble',
    'inmuebles',
    'bien inmueble',
    'compra de inmueble',
    'propiedad',
    'propiedades',
    'criptomoneda',
    'criptomonedas',
    'bitcoin',
    'ethereum',
    'cripto',
    'exchange cripto',
    'degiro',
    'trading212',
    'etoro',
    'scalable capital',
    'inbestme',
    'indexa capital',
    'myinvestor',
    'broker',
    'bróker',
    'actinver',
    'gbm',
    'gbm+',
    'dividendo',
    'dividendos',
    'utilidades',
    'utilidad',
    'reparto de utilidades',
    'ptu',
  ],
  refund: [
    'reembolso',
    'reembolsos',
    'devolución',
    'devoluciones',
    'devolver',
    'devuelto',
    'reintegro',
    'reintegros',
    'reintegración',
    'retorno',
    'nota de crédito',
    'abono',
    'abonos',
    'reclamación',
    'reclamaciones',
    'reclamar',
    'reclamado',
    'cargo revertido',
    'cargo devuelto',
    'cancelación',
    'cancelaciones',
    'contracargo',
    'contracargos',
    'chargeback',
    'reverso',
    'reversos',
    'anulación',
    'anulaciones',
    'producto devuelto',
    'artículo devuelto',
    'cambio de producto',
    'vale de cambio',
    'vale descuento',
    'cashback',
    'recompensa',
    'recompensas',
    'puntos canjeados',
    'puntos redimidos',
    'redención de puntos',
    'canje',
    'canjes',
    'millas',
    'devolución de iva',
    'devolución iva',
    'desgravación',
    'deducción fiscal',
    'devolución hacienda',
    'hacienda devolución',
    'sat devolución',
    'indemnización',
    'indemnizaciones',
    'cobro de seguro',
    'pago de seguro',
    'reembolso médico',
    'reembolso de vuelo',
    'cancelación de vuelo',
    'reembolso de hotel',
    'cancelación de hotel',
    'reembolso de reserva',
  ],
};

export default es;
