const fil = {
  food: [
    'kain',
    'almusal',
    'tanghalian',
    'hapunan',
    'merienda',
    'kanin',
    'adobo',
    'sinigang',
    'kare-kare',
    'lechon',
    'crispy pata',
    'sisig',
    'tocino',
    'longganisa',
    'daing',
    'tapa',
    'tapsilog',
    'silog',
    'tosilog',
    'bangsilog',
    'chosilog',
    'adsilog',
    'pork chop',
    'dinuguan',
    'kinilaw',
    'bulalo',
    'nilaga',
    'arroz caldo',
    'lugaw',
    'champorado',
    'turon',
    'halo-halo',
    'leche flan',
    'buko juice',
    'calamansi juice',
    'gulaman',
    'pancit',
    'lumpia',
    'menudo',
    'kaldereta',
    'afritada',
    'pinakbet',
    'paksiw',
    'binagoongan',
    'sopas',
    'tinola',
    'monggo',
    'ginataan',
    'bibingka',
    'puto',
    'kutsinta',
    'biko',
    'suman',
    'palitaw',
    'mais con yelo',
    'balut',
    'kwek-kwek',
    'isaw',
    'fishball',
    'squidball',
    'kikiam',
    'taho',
    'sago',
    'carinderia',
    'karinderya',
    'ihaw-ihaw',
    'lechon manok',
    'grabfood',
    'foodpanda',
    'jollibee',
    'chowking',
    'mang inasal',
    'goldilocks',
    'red ribbon',
    "max's restaurant",
    'greenwich',
    "andok's",
    'bon chon',
    'savory',
    "shakey's",
    'kenny rogers',
    'yellow cab',
    "bo's coffee",
    'figaro',
    'coffee project',
    'mcdo',
  ],
  groceries: [
    'palengke',
    'talipapa',
    'tindahan',
    'sari-sari store',
    'sari-sari',
    'tingi',
    'bilhin',
    'sm supermarket',
    'puregold',
    'robinsons supermarket',
    'metro supermarket',
    'shopwise',
    's&r',
    "rustan's supermarket",
    'mercury drug',
    'watsons ph',
    'true value',
    'ace hardware ph',
    'allday supermarket',
    'landers',
    'landmark supermarket',
    'walter mart',
    'savemore',
    'bigas',
    'gulay',
    'isda',
    'karne',
    'manok',
    'baboy',
    'itlog',
    'gatas',
    'tinapay',
    'asukal',
    'asin',
    'mantika',
    'toyo',
    'suka',
    'patis',
    'bagoong',
    'sardinas',
    'corned beef',
    'lucky me',
    'skyflakes',
    'rebisco',
  ],
  transport: [
    'jeepney',
    'jeep',
    'e-jeep',
    'e-jeepney',
    'pedicab',
    'tricycle',
    'trike',
    'lrt',
    'mrt',
    'mrt manila',
    'pnr',
    'uv express',
    'fx',
    'p2p bus',
    'grab ph',
    'grab car',
    'angkas',
    'move it',
    'tnvs',
    'bayad fare',
    'pamasahe',
    'beep card',
    'rfid',
    'autosweep',
    'easytrip',
    'slex',
    'nlex',
    'cavitex',
    'skyway',
    'star toll',
    'toll fee',
    'benzina',
    'gasolina',
    'diesel',
    'petron',
    'shell ph',
    'caltex ph',
    'phoenix fuel',
    'seaoil',
    'unioil',
    'bus',
    'taxi',
    'parking',
    'kotse',
    'sasakyan',
    'lrt1',
    'lrt2',
    'mrt3',
  ],
  housing: [
    'upa',
    'renta',
    'arkila',
    'bahay',
    'apartment',
    'condo',
    'condominium',
    'boarding house',
    'dorm',
    'dormitoryo',
    'bedspace',
    'amortization',
    'mortgage',
    'pagibig',
    'pag-ibig',
    'hdmf',
    'association dues',
    'hoa dues',
    'condo dues',
    'maintenance fee',
    'repair',
    'ayos bahay',
    'karpintero',
    'plomero',
    'electrician',
    'kasambahay',
    'katulong',
    'yaya',
    'subdivision',
    'townhouse',
  ],
  bills: [
    'meralco',
    'manila water',
    'maynilad',
    'pldt',
    'globe telecom',
    'globe',
    'smart communications',
    'smart',
    'dito telecommunity',
    'dito',
    'converge',
    'sky cable',
    'cignal',
    'gsat',
    'sun cellular',
    'electric bill',
    'kuryente',
    'ilaw',
    'tubig',
    'water bill',
    'internet bill',
    'wifi bill',
    'cable bill',
    'phone bill',
    'load',
    'bayad center',
    'gcash bayad',
    'maya bills',
    'ecpay',
    'singil',
    'bayarin',
    'postpaid',
    'prepaid',
    'subscription',
    'netflix ph',
    'spotify ph',
    'landline',
    'broadband',
  ],
  healthcare: [
    'duktor',
    'doktor',
    'ospital',
    'botika',
    'gamot',
    'lunas',
    'mercury drug',
    'rose pharmacy',
    'tgp pharmacy',
    'the generics pharmacy',
    'watsons ph',
    "st. luke's",
    'makati medical',
    'manila doctors',
    'philhealth',
    'malasakit',
    'hmo',
    'medicard',
    'maxicare',
    'intellicare',
    'laboratory',
    'lab test',
    'xray',
    'x-ray',
    'ultrasound',
    'blood test',
    'vaccine',
    'bakuna',
    'vitamins',
    'bitamina',
    'ospital bill',
    'dental',
    'ngipin',
    'optometrist',
    'eyeglass',
    'physical therapy',
    'klinik',
  ],
  shopping: [
    'sm mall',
    'ayala mall',
    'robinsons mall',
    'sm department store',
    'landmark',
    'rustans',
    'divisoria',
    'tiangge',
    'ukay-ukay',
    'ukay',
    'shopee ph',
    'shopee',
    'lazada ph',
    'lazada',
    'zalora ph',
    'zalora',
    'carousell ph',
    'carousell',
    'facebook marketplace',
    'pamimili',
    'pabili',
    'damit',
    'sapatos',
    'bag',
    'accessories',
    'alahas',
    'jewelry',
    'tshirt',
    'polo',
    'pantalon',
    'shorts',
    'dress',
    'skirt',
    'mall',
    'bazaar',
    'online shopping',
    'cod',
    'cash on delivery',
    'shein',
    'bench',
    'penshoppe',
    'sm store',
  ],
  entertainment: [
    'sinehan',
    'sine',
    'pelikula',
    'sm cinema',
    'ayala cinemas',
    'robinsons cinemas',
    'videoke',
    'karaoke',
    'ktvbox',
    'ktv',
    'birthday party',
    'kaarawan',
    'fiesta',
    'pistang bayan',
    'perya',
    'game',
    'laro',
    'bowling',
    'billiards',
    'darts',
    'netflix',
    'youtube premium',
    'disney plus',
    'concert',
    'show',
    'event',
    'gig',
    'bar',
    'inuman',
    'gimik',
    'videogame',
    'playstation',
    'xbox',
    'amusement park',
    'enchanted kingdom',
    'star city',
    'swimming pool',
    'resort',
    'water park',
  ],
  education: [
    'eskwela',
    'paaralan',
    'kolehiyo',
    'unibersidad',
    'pamantasan',
    'matrikula',
    'tuition fee',
    'tuition',
    'enrollment',
    'deped',
    'ched',
    'tesda',
    'state university',
    'school supplies',
    'school bag',
    'school uniform',
    'libro',
    'books',
    'notebook',
    'ballpen',
    'papel',
    'online class',
    'review center',
    'tutorial',
    'allowance',
    'baon',
    'graduation',
    'diploma',
    'certificate',
    'seminar',
    'training',
  ],
  pets: [
    'alagang hayop',
    'alaga',
    'aso',
    'pusa',
    'ibon',
    'isda',
    'pet food',
    'dog food',
    'cat food',
    'veterinarian',
    'vet',
    'vet clinic',
    'beterinaryo',
    'grooming',
    'dog grooming',
    'pet shop',
    'vaccine ng aso',
    'anti-rabies',
    'deworming',
    'pet supplies',
    'leash',
    'cage',
    'aquarium',
  ],
  travel: [
    'byahe',
    'biyahe',
    'bakasyon',
    'bakation',
    'lipad',
    'eroplano',
    'airplane',
    'paliparan',
    'airport',
    'naia',
    'cebu pacific',
    'philippine airlines',
    'pal',
    'airasia ph',
    '2go',
    'hotel',
    'resort',
    'inn',
    'hostel',
    'airbnb ph',
    'boracay',
    'palawan',
    'el nido',
    'coron',
    'bohol',
    'siargao',
    'batangas',
    'tagaytay',
    'baguio',
    'sagada',
    'davao',
    'cebu',
    'pasalubong',
    'souvenir',
    'tour package',
    'tour guide',
    'van hire',
    'ferry',
    'banka',
    'boat',
    'ship',
    'bus terminal',
    'victory liner',
    'visa',
    'passport',
    'travel insurance',
  ],
  fitness: [
    'gym',
    'fitness center',
    'anytime fitness ph',
    "gold's gym ph",
    'membership',
    'gym fee',
    'monthly gym',
    'ehersisyo',
    'jogging',
    'running',
    'cycling',
    'yoga',
    'zumba',
    'aerobics',
    'crossfit',
    'protein powder',
    'supplements',
    'sports',
    'basketball',
    'volleyball',
    'badminton',
    'swimming',
    'sports wear',
    'rubber shoes',
    'sneakers',
    'court rental',
    'pool fee',
    'personal trainer',
  ],
  gifts: [
    'regalo',
    'handog',
    'padala',
    'bigay',
    'birthday gift',
    'kaarawan',
    'pasko',
    'christmas gift',
    'money gift',
    'aguinaldo',
    'christmas bonus',
    'wedding gift',
    'kasal',
    'baby shower',
    'christening',
    'binyag',
    'valentines',
    'motherday',
    'fatherday',
    'anniversary',
    'pasalubong',
    'oleh-oleh',
    'souvenir',
    'flowers',
    'bulaklak',
    'cake',
    'torta',
    'charity',
    'donation',
    'abuloy',
    'ambag',
    'libing',
    'ninong',
    'ninang',
    'baptism',
  ],
  salary: [
    'sahod',
    'sweldo',
    'suweldo',
    'pasok',
    'kita',
    'bonus',
    'overtime',
    'ot pay',
    'gcash transfer',
    'bank transfer',
    'payroll',
    'semi-monthly',
    'monthly salary',
    'thirteenth month',
    '13th month',
    'performance bonus',
    'allowance',
    'transportation allowance',
    'meal allowance',
    'commission',
    'incentive',
    'profit sharing',
    'freelance',
    'remittance',
    'padala',
    'sss benefit',
    'philhealth benefit',
  ],
  investment: [
    'pamumuhunan',
    'investment',
    'pondo',
    'stock market',
    'stocks',
    'pse',
    'colfinancial',
    'mutual fund',
    'uitf',
    'vul',
    'real estate',
    'lupa',
    'pagibig mp2',
    'pag-ibig mp2',
    'gcash invest money',
    'maya invest',
    'cryptocurrency',
    'crypto',
    'bitcoin',
    'peso cost averaging',
    'time deposit',
    'savings',
    'ipon',
    'alkansya',
    'bonds',
    'retail treasury',
    'insurance',
    'life insurance',
    'bdo investment',
    'bpi investment',
  ],
  refund: [
    'refund',
    'ibalik',
    'palitan',
    'cashback',
    'cash back',
    'ibabalik',
    'ibinalik',
    'bawi',
    'return',
    'exchange',
    'replacement',
    'shopee refund',
    'lazada refund',
    'gcash refund',
    'na-cancel',
    'nabawi',
    'overpayment',
    'sukli',
    'reimbursement',
    'reimburse',
    'liquidation',
    'disputed charge',
    'chargeback',
  ],
};

export default fil;
