const hi = {
  food: [
    'खाना',
    'खाना-पीना',
    'दोपहर का खाना',
    'रात का खाना',
    'सुबह का नाश्ता',
    'नाश्ता',
    'दाल',
    'चावल',
    'रोटी',
    'सब्जी',
    'दाल-चावल',
    'राजमा-चावल',
    'छोले-भटूरे',
    'समोसा',
    'पोहा',
    'उपमा',
    'इडली',
    'डोसा',
    'वड़ा पाव',
    'पाव भाजी',
    'बिरयानी',
    'कबाब',
    'तंदूरी',
    'लस्सी',
    'चाय',
    'मसाला चाय',
    'दूध',
    'khana',
    'chai',
    'biryani',
    'samosa',
    'nashta',
    'roti',
    'sabzi',
    'dal',
    'chawal',
    'lassi',
    'dosa',
    'idli',
    'kabab',
    'Zomato',
    'Swiggy',
    "Domino's",
    'Pizza Hut',
    "McDonald's",
    'KFC',
    "Haldiram's",
    'Barbeque Nation',
    'Saravana Bhavan',
  ],
  groceries: [
    'किराने',
    'किराना',
    'सब्जी',
    'दूध',
    'अनाज',
    'आटा',
    'चीनी',
    'तेल',
    'सब्जी मंडी',
    'राशन',
    'kirana',
    'sabzi',
    'atta',
    'tel',
    'cheeni',
    'sabzi mandi',
    'Big Bazaar',
    'Reliance Fresh',
    'DMart',
    'D-Mart',
    'BigBasket',
    'Zepto',
    'Blinkit',
    'JioMart',
    "Spencer's",
    'More Supermarket',
  ],
  transport: [
    'बस',
    'ट्रेन',
    'मेट्रो',
    'ऑटो',
    'ऑटोरिक्शा',
    'रिक्शा',
    'टैक्सी',
    'ओला',
    'रैपिडो',
    'पेट्रोल',
    'डीजल',
    'पार्किंग',
    'टोल',
    'रेलवे',
    'bus',
    'train',
    'metro',
    'auto',
    'rickshaw',
    'taxi',
    'Ola',
    'Rapido',
    'petrol',
    'diesel',
    'parking',
    'toll',
    'IRCTC',
    'Indian Railways',
    'DMRC',
    'Mumbai Local',
    'Uber',
  ],
  housing: [
    'किराया',
    'मकान',
    'घर',
    'मेंटेनेंस',
    'मकान मालिक',
    'हाउस रेंट',
    'रेंट',
    'फ्लैट',
    'kiraya',
    'makan',
    'ghar',
    'rent',
    'maintenance',
    'society',
    'flat',
    'PG',
    'NoBroker',
    'MagicBricks',
    '99acres',
  ],
  bills: [
    'बिजली',
    'पानी',
    'गैस',
    'इंटरनेट',
    'मोबाइल',
    'डीटीएच',
    'bijli',
    'bijli bill',
    'paani bill',
    'gas bill',
    'mobile bill',
    'Jio',
    'Airtel',
    'Vi',
    'Vodafone',
    'BSNL',
    'DTH',
    'Tata Play',
    'Dish TV',
    'Sun Direct',
    'recharge',
  ],
  healthcare: [
    'डॉक्टर',
    'अस्पताल',
    'दवाई',
    'दवा',
    'क्लीनिक',
    'इलाज',
    'doctor',
    'hospital',
    'dawai',
    'dawa',
    'clinic',
    'Apollo',
    'Fortis',
    'Max Hospital',
    'Practo',
    'PharmEasy',
    '1mg',
    'NetMeds',
  ],
  shopping: [
    'कपड़े',
    'सोने की दुकान',
    'खरीदारी',
    'kapde',
    'kharidari',
    'shopping',
    'Flipkart',
    'Amazon India',
    'Meesho',
    'Snapdeal',
    'Myntra',
    'Ajio',
    'Reliance Digital',
    'Croma',
    'Lifestyle',
    'Pantaloons',
    'Nykaa',
  ],
  entertainment: [
    'सिनेमा',
    'फिल्म',
    'क्रिकेट',
    'मेला',
    'त्यौहार',
    'पार्टी',
    'cinema',
    'movie',
    'cricket',
    'mela',
    'PVR',
    'INOX',
    'BookMyShow',
    'IPL',
    'Hotstar',
    'Disney+ Hotstar',
    'SonyLIV',
    'Zee5',
    'JioCinema',
  ],
  education: [
    'स्कूल',
    'कॉलेज',
    'ट्यूशन',
    'कोचिंग',
    'फ़ीस',
    'पढ़ाई',
    'किताब',
    'school',
    'college',
    'tuition',
    'coaching',
    'fees',
    "BYJU'S",
    'Unacademy',
    'Vedantu',
    'Coursera',
    'udemy',
  ],
  pets: [
    'पालतू जानवर',
    'कुत्ता',
    'बिल्ली',
    'पशु चिकित्सक',
    'paltu janwar',
    'kutta',
    'billi',
    'vet',
    'pet food',
    'pet shop',
  ],
  travel: [
    'यात्रा',
    'सफर',
    'होटल',
    'फ्लाइट',
    'हवाई जहाज',
    'टिकट',
    'yatra',
    'safar',
    'hotel',
    'flight',
    'ticket',
    'MakeMyTrip',
    'Goibibo',
    'Cleartrip',
    'EaseMyTrip',
    'Airbnb',
    'OYO',
    'IndiGo',
    'Air India',
    'SpiceJet',
  ],
  fitness: [
    'जिम',
    'व्यायाम',
    'योग',
    'खेल',
    'gym',
    'yoga',
    'exercise',
    'Cult.fit',
    'Cultfit',
    'HealthifyMe',
  ],
  gifts: [
    'उपहार',
    'तोहफा',
    'गिफ्ट',
    'जन्मदिन का उपहार',
    'uphar',
    'tohfa',
    'gift',
    'Amazon gift card',
    'Flipkart gift card',
  ],
  salary: [
    'सैलरी',
    'तनख्वाह',
    'वेतन',
    'पगार',
    'बोनस',
    'इनकम',
    'कमाई',
    'salary',
    'tankhwah',
    'bonus',
    'income',
    'stipend',
    'freelance payment',
  ],
  investment: [
    'निवेश',
    'बचत',
    'शेयर',
    'म्यूचुअल फंड',
    'एफडी',
    'एसआईपी',
    'बीमा',
    'nivesh',
    'bachat',
    'share',
    'mutual fund',
    'FD',
    'SIP',
    'bima',
    'Zerodha',
    'Groww',
    'Upstox',
    'Angel One',
    'LIC',
    'PPF',
    'NPS',
  ],
  refund: ['रिफंड', 'वापसी', 'वापस', 'कैशबैक', 'पैसे वापस', 'refund', 'wapsi', 'cashback'],
};

export default hi;
