const id = {
  food: [
    'makan siang',
    'makan malam',
    'sarapan pagi',
    'makan pagi',
    'camilan',
    'jajanan',
    'cemilan',
    'bubur ayam',
    'bubur sumsum',
    'mie ayam',
    'mie goreng',
    'mie rebus',
    'bakso',
    'bakso kuah',
    'soto ayam',
    'soto betawi',
    'soto lamongan',
    'rawon',
    'opor ayam',
    'gado-gado',
    'gado gado',
    'ketoprak',
    'nasi uduk',
    'nasi liwet',
    'nasi tumpeng',
    'nasi kuning',
    'nasi bakar',
    'nasi rames',
    'pecel lele',
    'pecel',
    'ayam geprek',
    'ayam bakar',
    'ayam kremes',
    'tahu goreng',
    'tempe goreng',
    'tahu tempe',
    'gorengan',
    'batagor',
    'siomay',
    'pempek',
    'tekwan',
    'klepon',
    'martabak',
    'martabak manis',
    'martabak telur',
    'terang bulan',
    'es teh',
    'es jeruk',
    'es campur',
    'es dawet',
    'es cendol',
    'wedang jahe',
    'jamu',
    'kopi tubruk',
    'kopi susu',
    'susu segar',
    'indomie goreng',
    'indomie rebus',
    'mie instant',
    'mie instan',
    'seblak',
    'cilok',
    'cireng',
    'cimol',
    'cuanki',
    'lotek',
    'karedok',
    'sate padang',
    'sate madura',
    'nasi panas',
    'lalapan',
    'oseng-oseng',
    'tumis',
    'sop buntut',
    'sop iga',
    'gulai kambing',
    'tongseng',
    'mangut',
    'tengkleng',
    'nasi penyet',
    'bebek goreng',
    'bebek betutu',
    'ikan gurame',
    'kepiting',
    'cumi goreng',
    'babi guling',
    'nasi jinggo',
    'lawar',
    'sate lilit',
    'rujak',
    'rujak cingur',
    'kolak',
    'kolak pisang',
    'getuk',
    'onde-onde',
    'lemper',
    'nagasari',
    'dadar gulung',
    'serabi',
    'lupis',
    'cenil',
    'wajik',
    'kue lapis',
    'bika ambon',
    'wingko babat',
    'lontong sayur',
    'lontong cap gomeh',
    'nasi jagung',
    'bubur kacang hijau',
    'bubur ketan hitam',
    'kolak ubi',
    'gofood',
    'go-food',
    'shopeefood',
    'shopee food',
    'grabfood',
    'grab food',
    'hokben',
    'hoka-hoka bento',
    "d'cost",
    'dcost',
    'solaria',
    'es teler 77',
    'bakso boedjangan',
    'sate khas senayan',
    'janji jiwa',
    'kopi kenangan',
    'fore coffee',
    'kopi lain hati',
    'excelso',
    'anomali coffee',
    'filosofi kopi',
    'mie gacoan',
    'geprek bensu',
    'ayam geprek bensu',
    'rocket chicken',
    'richeese factory',
    'warteg',
    'warung nasi',
    'warung makan',
    'dapur solo',
    'bumbu desa',
    'cfc',
    'california fried chicken',
    'pizza hut delivery',
    'phd pizza',
    'domino indonesia',
    'jco donuts',
    'krispy kreme indonesia',
    'breadlife',
    'bread life',
    'roti o',
    'rotiboy indonesia',
    'a&w indonesia',
    'mcdonald indonesia',
    'kfc indonesia',
    'burger king indonesia',
    'popeyes indonesia',
    'starbucks indonesia',
  ],
  groceries: [
    'indomaret',
    'alfamart',
    'alfamidi',
    'circle k indonesia',
    'giant indonesia',
    'transmart',
    'hypermart',
    'lotte mart',
    'lottemart',
    'superindo',
    'super indo',
    'farmers market',
    'ranch market',
    'kem chicks',
    'kemchicks',
    'grand lucky',
    'lion super indo',
    'toserba yogya',
    'pasar tradisional',
    'pasar modern',
    'pasar swalayan',
    'tukang sayur',
    'tukang buah',
    'toko sembako',
    'sembako',
    'warung sembako',
    'minimarket',
    'swalayan',
    'belanja bulanan',
    'belanja harian',
    'belanja mingguan',
    'bahan makanan',
    'kebutuhan dapur',
    'sayuran segar',
    'buah segar',
    'beras 5kg',
    'beras 10kg',
    'minyak goreng',
    'minyak sayur',
    'kecap manis',
    'kecap asin',
    'saus sambal',
    'bumbu masak',
    'bumbu racik',
    'royco',
    'masako',
    'indofood',
    'abc kecap',
    'bango kecap',
    'sasa',
    'kokita',
    'teh botol sosro',
    'sosro',
    'ultra milk',
    'indomilk',
    'bear brand',
    'dancow',
    'frisian flag',
    'sunlight sabun',
    'mama lime',
    'rinso',
    'so klin',
    'soklin',
    'bayclin',
    'wipol',
    'kapal api',
    'torabika',
    'nescafe indonesia',
    'indocafe',
    'chitato',
    'piattos',
    'potabee',
    'taro snack',
    'wafer tango',
    'beng beng',
    'silverqueen',
    'kopiko',
    'relaxa',
    'gerry chocolatos',
    'energen',
  ],
  transport: [
    'ojek online',
    'gocar',
    'go car',
    'grabcar indonesia',
    'bluebird',
    'blue bird taxi',
    'taksi bluebird',
    'taksi express',
    'jaklingko',
    'transjakarta',
    'trans jakarta',
    'busway',
    'commuter line',
    'krl commuter',
    'krl jabodetabek',
    'mrt jakarta',
    'lrt jabodebek',
    'lrt jakarta',
    'angkot',
    'angkutan kota',
    'mikrolet',
    'metromini',
    'damri',
    'bus antar kota',
    'travel antar kota',
    'maxim indonesia',
    'indriver indonesia',
    'ojol',
    'goride',
    'go-ride',
    'grabmotor',
    'grab motor',
    'beli bensin',
    'isi bensin',
    'isi bahan bakar',
    'pertamina',
    'spbu pertamina',
    'shell indonesia',
    'bensin pertalite',
    'bensin pertamax',
    'pertalite',
    'pertamax',
    'pertamax turbo',
    'bio solar',
    'solar subsidi',
    'bayar parkir',
    'parkir motor',
    'parkir mobil',
    'jalan tol',
    'bayar tol',
    'e-toll',
    'etoll',
    'kartu e-toll',
    'kartu tol',
    'emoney mandiri',
    'e-money mandiri',
    'brizzi bri',
    'flazz bca',
    'tapcash bni',
    'jakcard',
    'bengkel',
    'servis motor',
    'servis mobil',
    'ganti oli',
    'cuci motor',
    'cuci mobil',
    'tambal ban',
    'ganti ban',
    'asuransi kendaraan',
    'pajak kendaraan',
    'samsat',
    'tilang',
    'denda tilang',
    'derek mobil',
    'kereta api',
    'tiket kereta',
    'tiket krl',
    'tiket pesawat domestik',
    'lion air',
    'citilink',
    'batik air',
    'sriwijaya air',
    'garuda indonesia',
    'pelni',
    'kapal pelni',
    'feri',
    'tiket feri',
  ],
  housing: [
    'sewa kos',
    'kos-kosan',
    'kos kosan',
    'sewa kontrakan',
    'kontrakan',
    'kontrak rumah',
    'sewa apartemen',
    'sewa rumah',
    'bayar kos',
    'bayar kontrakan',
    'uang kos',
    'biaya kos',
    'ipl',
    'iuran pengelolaan lingkungan',
    'biaya maintenance',
    'biaya service charge',
    'service charge',
    'listrik pln',
    'token listrik',
    'bayar listrik',
    'renovasi rumah',
    'perbaikan rumah',
    'bangun rumah',
    'cicilan rumah',
    'kpr',
    'kredit pemilikan rumah',
    'dp rumah',
    'uang muka',
    'biaya notaris',
    'akta jual beli',
    'ppn bphtb',
    'bphtb',
    'uang keamanan',
    'iuran rt',
    'iuran rw',
    'iuran warga',
    'biaya kebersihan',
    'biaya keamanan',
    'tukang bangunan',
    'tukang cat',
    'tukang kayu',
    'material bangunan',
    'cat tembok',
    'keramik',
    'genteng',
    'semen',
    'kontraktor',
    'beli perabot',
    'furniture',
    'lemari',
    'kasur',
    'springbed',
    'sofa',
    'meja makan',
    'kursi makan',
    'kulkas',
    'mesin cuci',
    'dispenser',
    'ac',
    'kipas angin',
  ],
  bills: [
    'pln',
    'bayar pln',
    'tagihan pln',
    'listrik prabayar',
    'token listrik pln',
    'pdam',
    'tagihan pdam',
    'bayar air',
    'bayar pdam',
    'gas elpiji',
    'gas lpg',
    'beli gas',
    'tabung gas',
    'isi ulang gas',
    'indihome',
    'indi home',
    'telkom indihome',
    'myindihome',
    'telkomsel',
    'xl axiata',
    'xl postpaid',
    'indosat ooredoo',
    'indosat im3',
    'im3',
    'smartfren',
    'tri indonesia',
    'telkom indonesia',
    'firstmedia',
    'first media',
    'mnc vision',
    'biznet',
    'myrepublic',
    'oxygen id',
    'iconnet',
    'icon net',
    'bayar wifi',
    'tagihan wifi',
    'internet rumah',
    'paket internet',
    'pulsa',
    'beli pulsa',
    'isi pulsa',
    'paket data',
    'kuota internet',
    'beli kuota',
    'langganan bulanan',
    'biaya admin',
    'biaya bulanan',
    'iuran bulanan',
    'cicilan bulanan',
    'bpjs',
    'bpjs kesehatan',
    'bpjs ketenagakerjaan',
    'jkn',
    'jamsostek',
    'pph',
    'ppn',
    'pajak',
    'pajak bumi bangunan',
    'pbb',
    'npwp',
    'vidio',
    'vidio premium',
    'rcti plus',
    'vision plus',
    'mola tv',
    'maxstream',
    'langit musik',
    'joox',
    'resso',
    'spotify indonesia',
    'viu indonesia',
    'wetv indonesia',
    'genflix',
    'catchplay',
    'cgv cinemas member',
  ],
  healthcare: [
    'dokter umum',
    'dokter spesialis',
    'dokter anak',
    'dokter gigi',
    'dokter kandungan',
    'bidan',
    'perawat',
    'puskesmas',
    'klinik pratama',
    'klinik utama',
    'rsud',
    'rs swasta',
    'rawat inap',
    'rawat jalan',
    'ugd',
    'igd',
    'apotek',
    'apotik',
    'kimia farma',
    'k24',
    'century healthcare',
    'guardian indonesia',
    'watsons indonesia',
    'generik',
    'obat generik',
    'obat resep',
    'obat bebas',
    'vitamin c',
    'multivitamin',
    'suplemen kesehatan',
    'herbal',
    'jamu tradisional',
    'bpjs faskes',
    'bpjs rs',
    'bpjs klaim',
    'klaim bpjs',
    'kartu bpjs',
    'iuran bpjs',
    'bayar bpjs',
    'asuransi kesehatan',
    'asuransi jiwa',
    'premi asuransi',
    'biaya rumah sakit',
    'biaya dokter',
    'biaya operasi',
    'biaya persalinan',
    'biaya melahirkan',
    'usg',
    'rontgen',
    'cek darah',
    'laboratorium',
    'lab klinik',
    'prodia',
    'pramita',
    'parahita',
    'bio medika',
    'vaksin covid',
    'vaksin flu',
    'imunisasi',
    'posyandu',
    'khitan',
    'sunat',
    'fisioterapi',
    'terapi',
    'akupunktur',
    'pijat kesehatan',
    'pijat refleksi',
    'urut tradisional',
    'minyak kayu putih',
    'koyo',
    'hansaplast',
    'betadine',
    'tolak angin',
    'antangin',
    'bodrex',
    'paracetamol',
    'ibuprofen',
    'amoxicillin',
    'obat batuk woods',
    'komix',
  ],
  shopping: [
    'tokopedia',
    'bukalapak',
    'blibli',
    'zalora indonesia',
    'jd id',
    'jd.id',
    'tiktok shop',
    'tiktokshop',
    'shopee indonesia',
    'lazada indonesia',
    'bhineka',
    'bhinneka',
    'jakartanotebook',
    'ibox indonesia',
    'matahari department store',
    'matahari dept store',
    'ramayana',
    'ace hardware indonesia',
    'ikea indonesia',
    'electronic city',
    'erafone',
    'brand official store',
    'official store',
    'baju batik',
    'kemeja batik',
    'batik',
    'kain batik',
    'daster',
    'gamis',
    'mukena',
    'sajadah',
    'peci',
    'sarung',
    'celana kain',
    'sepatu lokal',
    'sendal jepit',
    'crocs indonesia',
    'converse indonesia',
    'planet surf',
    'the executive',
    'nevada',
    'connexion',
    'sport station',
    'sports station',
    'world of sports',
    'league',
    'mills indonesia',
    'specs sport',
    'ortuseight',
    'ninja xfast',
    'wardah',
    'emina',
    'make over',
    'purbasari',
    'sariayu',
    'pixy',
    'caring colours',
    'viva cosmetics',
    'marina',
    'citra',
    'mustika ratu',
    'natur',
    'herborist',
    'biore indonesia',
    'ponds indonesia',
    'fair lovely',
    'glow lovely',
    'garnier indonesia',
    'loreal indonesia',
    'pantene indonesia',
    'clear shampoo',
    'sunsilk indonesia',
    'lifebuoy indonesia',
    'dove indonesia',
    'vaseline indonesia',
    'nivea indonesia',
    'grand indonesia',
    'mall grand indonesia',
    'plaza indonesia',
    'pacific place',
    'kota kasablanka',
    'pondok indah mall',
    'central park mall',
    'taman anggrek',
    'emporium pluit',
    'pluit village',
    'mall of indonesia',
    'mal kelapa gading',
    'transmart mall',
    'ramayana mall',
    'lippo mall',
    'cito surabaya',
    'galaxy mall surabaya',
    'pakuwon mall',
    'tunjungan plaza',
    'ciputra world',
    'paris van java',
    'trans studio mall',
    'mantos manado',
  ],
  entertainment: [
    'xxi',
    '21 cineplex',
    'cgv indonesia',
    'cinemaxx indonesia',
    'flix cinema',
    'bioskop',
    'nonton bioskop',
    'nonton film',
    'tiket bioskop',
    'layar lebar',
    'timezone',
    'fun world',
    'kidzoona',
    'amazone',
    'wahana bermain',
    'taman bermain',
    'dufan',
    'dunia fantasi',
    'ancol',
    'taman impian jaya ancol',
    'tmii',
    'taman mini indonesia indah',
    'kebun binatang',
    'ragunan',
    'batu secret zoo',
    'jatim park',
    'kidzania',
    'waterboom',
    'waterpark',
    'trans studio bandung',
    'trans studio makassar',
    'karaoke family',
    'nav karaoke',
    'inul vizta',
    'happy puppy',
    'karaoke happy puppy',
    'mobile legends indonesia',
    'pubg mobile indonesia',
    'free fire indonesia',
    'garena',
    'garena free fire',
    'top up diamond',
    'diamond ml',
    'diamond ff',
    'top up game',
    'beli diamond',
    'beli uc',
    'top up uc',
    'google play indonesia',
    'app store indonesia',
    'vidio',
    'rcti plus',
    'sctv streaming',
    'mola tv bola',
    'tiket.com konser',
    'bertiket',
    'loket.com',
    'eventbrite indonesia',
  ],
  education: [
    'ruangguru',
    'ruang guru',
    'zenius',
    'quipper indonesia',
    'sekolahmu',
    'pahamify',
    'cakap',
    'bimbingan belajar',
    'bimbel',
    'les privat',
    'les bahasa inggris',
    'les piano',
    'les gitar',
    'les matematika',
    'spp',
    'bayar spp',
    'uang gedung',
    'uang sekolah',
    'uang kuliah',
    'biaya kuliah',
    'ukt',
    'sks',
    'wisuda',
    'toga',
    'univ indonesia',
    'ui depok',
    'itb bandung',
    'ugm yogyakarta',
    'its surabaya',
    'ipb bogor',
    'undip',
    'unair',
    'binus',
    'binus university',
    'telkom university',
    'gunadarma',
    'petra christian university',
    'unika atma jaya',
    'studi independent',
    'kampus merdeka',
    'beasiswa',
    'beasiswa lpdp',
    'seleksi masuk',
    'sbmptn',
    'snmptn',
    'try out',
    'tryout',
    'ujian nasional',
    'un sekolah',
    'ppdb',
    'buku pelajaran',
    'buku teks',
    'buku paket',
    'lks',
    'alat tulis',
    'atk',
    'seragam sekolah',
    'baju seragam',
    'tas sekolah',
    'sepatu sekolah',
    'ekskul',
    'ekstrakurikuler',
    'kursus bahasa',
    'english course',
    'lembaga kursus',
    'lkp',
    'pelatihan kerja',
    'blk',
    'sertifikasi kompetensi',
    'sertifikat',
    'ijazah',
    'skripsi',
    'thesis',
    'tesis',
  ],
  pets: [
    'hewan peliharaan',
    'pakan hewan',
    'pakan kucing',
    'pakan anjing',
    'makanan kucing',
    'makanan anjing',
    'petshop',
    'pet shop indonesia',
    'grooming kucing',
    'grooming anjing',
    'kandang kucing',
    'kandang anjing',
    'pasir kucing',
    'obat kutu',
    'vaksin kucing',
    'vaksin anjing',
    'steril kucing',
    'kastrasi',
    'dokter hewan',
    'klinik hewan',
    'rumah sakit hewan',
    'rsg hewan',
    'penitipan hewan',
    'penitipan kucing',
    'penitipan anjing',
    'akuarium',
    'ikan hias',
    'pakan ikan',
    'hamster',
    'kelinci',
    'burung',
    'kandang burung',
    'pakan burung',
    'sangkar burung',
  ],
  travel: [
    'traveloka',
    'tiket.com',
    'tiketcom',
    'pegipegi',
    'pegi pegi',
    'trivago indonesia',
    'agoda indonesia',
    'booking indonesia',
    'oyo indonesia',
    'bali',
    'lombok',
    'yogyakarta',
    'jogja',
    'malang',
    'surabaya',
    'bandung',
    'jakarta',
    'semarang',
    'makassar',
    'manado',
    'medan',
    'palembang',
    'balikpapan',
    'labuan bajo',
    'flores',
    'raja ampat',
    'wakatobi',
    'bunaken',
    'kawah ijen',
    'gunung bromo',
    'bromo',
    'gunung rinjani',
    'rinjani',
    'danau toba',
    'toba',
    'pantai kuta',
    'pantai legian',
    'seminyak',
    'ubud',
    'nusa dua',
    'sanur',
    'gili trawangan',
    'gili',
    'nusa penida',
    'tanah lot',
    'uluwatu',
    'borobudur',
    'prambanan',
    'malioboro',
    'parangtritis',
    'perjalanan dinas',
    'jalan-jalan',
    'liburan',
    'wisata',
    'pariwisata',
    'paket wisata',
    'paket tour',
    'tour operator',
    'agen perjalanan',
    'agen wisata',
    'tiket masuk',
    'tiket wahana',
    'sewa motor bali',
    'sewa mobil',
    'rental mobil',
    'rental motor',
    'penginapan',
    'villa',
    'guest house',
    'losmen',
    'bungalow',
    'resort bali',
    'hotel bintang',
    'budget hotel',
    'hotel murah',
    'paspor',
    'visa indonesia',
    'asuransi perjalanan',
    'travel insurance',
    'tiket domestik',
    'tiket internasional',
    'check in bagasi',
    'bagasi tambahan',
    'biaya bagasi',
    'umrah',
    'haji',
    'ziarah',
    'biro perjalanan haji',
    'ongkos naik haji',
    'onh',
    'biaya umrah',
    'manasik',
  ],
  fitness: [
    'gym indonesia',
    'fitness center',
    'fit hub',
    'fithub',
    'gold gym indonesia',
    'anytime fitness indonesia',
    'celebrity fitness indonesia',
    'fitness first indonesia',
    'f45 indonesia',
    'crossfit indonesia',
    'muay thai indonesia',
    'kickboxing',
    'tinju',
    'pencak silat',
    'silat',
    'karate',
    'taekwondo',
    'renang',
    'kolam renang',
    'yoga indonesia',
    'pilates indonesia',
    'zumba indonesia',
    'aerobik',
    'senam',
    'senam pagi',
    'jogging',
    'lari pagi',
    'lari sore',
    'bersepeda',
    'sepeda statis',
    'treadmill',
    'dumbbell',
    'barbel',
    'protein shake',
    'suplemen gym',
    'whey protein indonesia',
    'optimum nutrition',
    'isopure',
    'suplemen fitnes',
    'bca protein',
    'l-glutamine',
    'creatine monohydrate',
    'olahraga',
    'futsal',
    'basket',
    'voli',
    'bulu tangkis',
    'badminton',
    'tenis',
    'tenis meja',
    'ping pong',
    'golf indonesia',
    'sepatu olahraga',
    'baju olahraga',
    'celana olahraga',
    'tas gym',
  ],
  gifts: [
    'hadiah ulang tahun',
    'kado ulang tahun',
    'kado',
    'kado pernikahan',
    'hadiah pernikahan',
    'bingkisan',
    'hampers lebaran',
    'hampers natal',
    'parcel lebaran',
    'parcel natal',
    'parcel',
    'buket bunga',
    'buket',
    'kartu ucapan',
    'voucher belanja',
    'infak',
    'sedekah',
    'zakat fitrah',
    'zakat maal',
    'zakat profesi',
    'wakaf',
    'donasi panti asuhan',
    'donasi masjid',
    'bayar masjid',
    'sumbangan masjid',
    'kolekte',
    'amplop gereja',
    'persembahan',
    'uang tip',
    'lebaran',
    'hari raya idul fitri',
    'idul fitri',
    'idul adha',
    'tunjangan hari raya',
    'thr',
    'angpao lebaran',
    'duit jajan',
    'uang saku',
    'santunan',
    'santunan anak yatim',
    'bantuan sosial',
    'bansos',
    'pkh',
    'baznas',
    'yayasan',
    'yayasan sosial',
    'donor darah',
  ],
  salary: [
    'gaji pokok',
    'gaji bersih',
    'gaji kotor',
    'take home pay',
    'thp',
    'pendapatan bulanan',
    'transfer gaji',
    'masuk gaji',
    'terima gaji',
    'honor',
    'honorarium',
    'uang jasa',
    'jasa konsultan',
    'fee konsultan',
    'proyek',
    'bayaran proyek',
    'upah harian',
    'upah mingguan',
    'upah borongan',
    'kerja sampingan',
    'penghasilan sampingan',
    'usaha sampingan',
    'jualan online',
    'jualan',
    'hasil jualan',
    'omzet',
    'profit',
    'keuntungan usaha',
    'royalti',
    'pph 21',
    'pajak penghasilan',
    'bpjs tk',
    'jaminan pensiun',
    'jp bpjs',
    'uang pensiun',
    'dana pensiun',
    'tunjangan jabatan',
    'tunjangan kemahalan',
    'tunjangan anak',
    'tunjangan istri',
    'tunjangan makan',
    'tunjangan transportasi',
    'tunjangan perumahan',
    'tunjangan komunikasi',
    'tunjangan kesehatan',
    'tunjangan kinerja',
    'insentif kinerja',
    'bonus akhir tahun',
    'bonus lebaran',
    'bonus kinerja',
    'uang lembur',
    'uang makan',
    'uang bensin',
    'uang representasi',
    'dana operasional',
    'reimbursement kerja',
    'transfer dari klien',
    'bayar dari klien',
    'konten kreator',
    'adsense',
    'google adsense',
    'youtube monetisasi',
    'affiliate',
    'komisi affiliate',
    'dropship',
    'reseller',
    'endorsement',
    'sponsored post',
    'iklan',
    'pendapatan iklan',
  ],
  investment: [
    'bibit',
    'bibit invest',
    'bareksa',
    'ipot',
    'indo premier',
    'indo premier sekuritas',
    'bni sekuritas',
    'mandiri sekuritas',
    'bri danareksa',
    'panin sekuritas',
    'trimegah sekuritas',
    'philip sekuritas',
    'mirae asset',
    'mirae sekuritas',
    'sucor sekuritas',
    'kisi sekuritas',
    'stockbit',
    'ajaib',
    'ajaib sekuritas',
    'pintu crypto',
    'pintu',
    'idx',
    'bursa efek indonesia',
    'bei',
    'ihsg',
    'reksa dana',
    'reksadana',
    'reksa dana pasar uang',
    'reksa dana saham',
    'reksa dana campuran',
    'reksa dana pendapatan tetap',
    'obligasi',
    'obligasi pemerintah',
    'sbr',
    'st',
    'sr',
    'sukuk ritel',
    'sbn',
    'deposito',
    'deposito bank',
    'tabungan berjangka',
    'tabungan emas',
    'emas antam',
    'antam',
    'logam mulia',
    'beli emas',
    'investasi emas',
    'pegadaian emas',
    'pegadaian',
    'perak',
    'properti invest',
    'reit',
    'dire',
    'crowdfunding',
    'crowdfunding properti',
    'p2p lending',
    'pinjaman p2p',
    'fintech lending',
    'nabung saham',
    'nabung rutin',
    'setoran modal',
    'modal usaha',
    'tambah modal',
    'investasi bisnis',
    'asuransi jiwa syariah',
    'takaful indonesia',
    'prudential indonesia',
    'allianz indonesia',
    'aia indonesia',
    'manulife indonesia',
    'sunlife indonesia',
    'premi unit link',
    'unit link',
    'tabungan pendidikan',
    'dana darurat',
    'investasi crypto',
    'bitcoin indonesia',
    'indodax',
    'tokocrypto',
    'triv',
  ],
  refund: [
    'pengembalian uang',
    'pengembalian dana',
    'uang kembali',
    'kembalian',
    'sisa uang',
    'refund shopee',
    'refund tokopedia',
    'refund traveloka',
    'refund tiket',
    'refund pesanan',
    'refund order',
    'batalkan pesanan',
    'batal order',
    'pengembalian barang',
    'retur barang',
    'klaim asuransi',
    'klaim jaminan',
    'dana kembali',
    'uang balik',
    'transfer balik',
    'reimbursement kantor',
    'reimbursement biaya',
    'klaim reimburse',
    'lebih bayar',
    'kelebihan bayar',
    'refund pln',
    'refund telkom',
    'refund bpjs',
    'ganti rugi',
    'kompensasi delay',
    'kompensasi penerbangan',
    'cashback shopee',
    'cashback tokopedia',
    'cashback ovo',
    'cashback dana',
    'cashback gopay',
    'voucher cashback',
    'poin reward',
    'reward points',
    'tukar poin',
    'redeem poin',
    'poin ovo',
    'gopay coins',
    'shopee coins',
    'bonus cashback',
    'promo cashback',
    'koin',
    'poin ditukarkan',
  ],
};

export default id;
