const it = {
  food: [
    'pranzo',
    'cena',
    'colazione',
    'merenda',
    'spuntino',
    'aperitivo',
    'spritz',
    'trattoria',
    'osteria',
    'pizzeria',
    'gelateria',
    'rosticceria',
    'friggitoria',
    'paninoteca',
    'braceria',
    'taverna',
    'bar',
    'caffè',
    'caffe',
    'cornetto',
    'brioche',
    'cappuccino italiano',
    'macchiato',
    'caffè macchiato',
    'caffè corretto',
    'orzo',
    'gelato',
    'panino',
    'panini',
    'focaccia',
    'arancino',
    'arancina',
    'supplì',
    'tramezzino',
    'bruschetta',
    'crostino',
    'aperol spritz',
    'amaro',
    'digestivo',
    'prosecco',
    'negroni',
    'caffetteria',
    'pasticceria',
    'lasagne',
    'carbonara',
    'amatriciana',
    'cacio e pepe',
    'gricia',
    'saltimbocca',
    'gnocchi',
    'risotto',
    'ossobuco',
    'cotoletta',
    'bistecca fiorentina',
    'porchetta',
    'lampredotto',
    'ribollita',
    'panzanella',
    'pappa al pomodoro',
    'tiramisù',
    'panna cotta',
    'cannoli',
    'granita',
    'granita siciliana',
    'autogrill',
    'chef express',
    'roadhouse',
    'old wild west',
    'wagamama it',
    'kebabbaro',
    'piadina',
    'piadineria',
    'just eat',
    'deliveroo',
    'glovo',
    'uber eats italia',
    'foodora',
    'street food',
    'sagra',
    'fiera del cibo',
  ],
  groceries: [
    'esselunga',
    'conad',
    'coop italia',
    'coop',
    'eurospin',
    'pam',
    'pam panorama',
    'despar',
    'famila',
    'iper',
    'simply',
    'sisa',
    'sigma',
    'bennet',
    'auchan',
    'il gigante',
    'basko',
    'finiper',
    'spesa',
    'supermercato',
    'ipermercato',
    'discount',
    'mercato',
    'mercato rionale',
    'fruttivendolo',
    'macelleria',
    'panificio',
    'salumeria',
    'pescheria',
    'norcineria',
    'gastronomia',
    'bottega',
    'drogheria',
    'alimentari',
    'negozio alimentare',
    'penny market',
    'penny',
    'maxì',
    'md',
    'md discount',
    'aldi italia',
    'lidl italia',
    'carrefour express',
    'carrefour market',
    'carrefour bio',
    'interspar',
    'pane',
    'latte',
    'uova',
    'verdura',
    'frutta',
    'olio extravergine',
    'olio di oliva',
    'pasta secca',
    'riso',
    'conserve',
    'pelati',
    'farina',
    'zucchero',
    'sale',
    'formaggio',
    'affettati',
    'salumi',
    'prosciutto',
    'mortadella',
    'spesa settimanale',
    'spesa mensile',
    'fare la spesa',
    'lista della spesa',
  ],
  transport: [
    'trenitalia',
    'frecciarossa',
    'frecciargento',
    'frecciabianca',
    'intercity',
    'regionale',
    'italo',
    'italo treno',
    'trenord',
    'ferrovie dello stato',
    'fs',
    'rfi',
    'atm',
    'atm milano',
    'atac',
    'atac roma',
    'anm',
    'anm napoli',
    'actv',
    'actv venezia',
    'amt genova',
    'gtt torino',
    'tper bologna',
    'biglietto',
    'abbonamento',
    'abbonamento mensile',
    'tessera',
    'ticket bus',
    'autobus',
    'tram',
    'metropolitana',
    'metro',
    'linea metro',
    'vaporetto',
    'autostrada',
    'casello',
    'pedaggio',
    'pedaggi',
    'telepass',
    'viacard',
    'bollo auto',
    'tassa automobilistica',
    'revisione',
    'collaudo',
    'benzina',
    'gasolio',
    'gpl',
    'metano auto',
    'rifornimento',
    'carburante',
    'area service',
    'parcheggio',
    'parchimetro',
    'strisce blu',
    'zona ztl',
    'ztl',
    'multa',
    'ncc',
    'noleggio con conducente',
    'blablacar',
    'enjoy',
    'share now',
    'citybee',
    'free2move',
    'car sharing',
    'carsharing',
    'monopattino',
    'ita airways',
    'ita',
    'ryanair',
    'easyjet',
    'volotea',
    'wizz air',
    'flixbus italia',
    'busitalia',
    'baltour',
    'bici',
    'bikemi',
    'bike sharing',
  ],
  housing: [
    'affitto',
    'canone',
    'canone di affitto',
    'locazione',
    'inquilino',
    'locatario',
    'locatore',
    'padrone di casa',
    'proprietario',
    'agenzia immobiliare',
    'caparra',
    'deposito cauzionale',
    'cauzione',
    'contratto di affitto',
    'spese condominiali',
    'condominio',
    'amministratore',
    'tasi',
    'imu',
    'tari',
    'mutuo',
    'rata del mutuo',
    'rogito',
    'notaio',
    'spese notarili',
    'manutenzione',
    'riparazione',
    'idraulico',
    'elettricista',
    'caldaia',
    'boiler',
    'termoidraulico',
    'imbianchino',
    'verniciatura',
    'ristrutturazione',
    'lavori in casa',
    'pulizia',
    'pulizie domestiche',
    'colf',
    'badante',
    'portiere',
    'mobili',
    'arredamento',
    'divano',
    'letto',
    'armadio',
    'lavatrice',
    'lavastoviglie',
    'frigorifero',
    'cucina',
    'piano cottura',
    'forno',
    'microonde',
    'condizionatore',
    'climatizzatore',
    'immobiliare.it',
    'idealista',
    'casa.it',
    'subito casa',
    'wikicasa',
  ],
  bills: [
    'enel',
    'enel energia',
    'eni gas',
    'eni gas e luce',
    'a2a',
    'a2a energia',
    'acea',
    'acea energia',
    'edison',
    'iren',
    'hera',
    'italgas',
    'snam',
    'acquedotto',
    'bolletta',
    'bolletta luce',
    'bolletta gas',
    'bolletta acqua',
    'luce',
    'utenze',
    'fornitura',
    'lettura contatore',
    'consumo energia',
    'riscaldamento',
    'teleriscaldamento',
    'tim',
    'tim italia',
    'vodafone italia',
    'wind',
    'wind tre',
    'iliad',
    'iliad italia',
    'fastweb',
    'tiscali',
    'fibra ottica',
    'adsl',
    'sim',
    'ricarica telefonica',
    'sky italia',
    'sky',
    'dazn',
    'mediaset premium',
    'mediaset infinity',
    'infinity tv',
    'raiplay',
    'timvision',
    'nowtv',
    'now tv',
    'tassa rifiuti',
    'tassa smaltimento',
  ],
  healthcare: [
    'medico',
    'medico di base',
    'medico di famiglia',
    'ospedale',
    'pronto soccorso',
    'farmacia',
    'medicinale',
    'medicinali',
    'farmaco',
    'farmaci',
    'visita medica',
    'visita specialistica',
    'dentista',
    'studio dentistico',
    'fisioterapista',
    'fisioterapia',
    'ottico',
    'occhiali da vista',
    'lenti a contatto',
    'lenti',
    'ricetta',
    'ricetta medica',
    'mutuabilità',
    'mutua',
    'ssn',
    'servizio sanitario nazionale',
    'asl',
    'cup',
    'impegnativa',
    'ticket sanitario',
    'ticket',
    'guardia medica',
    'pediatra',
    'ginecologo',
    'cardiologo',
    'oncologo',
    'ortopedico',
    'dermatologo',
    'psicologo',
    'psichiatra',
    'logopedista',
    'ambulatorio',
    'poliambulatorio',
    'laboratorio analisi',
    'esame del sangue',
    'ecografia',
    'radiografia',
    'tac',
    'risonanza',
    'risonanza magnetica',
    'vaccino',
    'vaccinazione',
    'farmacia di turno',
    'erboristeria',
    'assicurazione sanitaria',
    'polizza salute',
    'fondo sanitario',
    'lloyds farmacia',
    'farmacia comunale',
  ],
  shopping: [
    'la rinascente',
    'rinascente',
    'ovs',
    'ovs industry',
    'piazza italia',
    'upim',
    'coin',
    'coin stores',
    'intimissimi',
    'calzedonia',
    'tezenis',
    'carpisa',
    'bata italia',
    'mondadori',
    'feltrinelli',
    'euronics',
    'mediaworld',
    'unieuro',
    'trony',
    'expert',
    'max mara',
    'benetton',
    'sisley',
    'replay',
    'liu jo',
    'diesel',
    'fila',
    'kappa',
    'breil',
    'guess italy',
    'brandy melville',
    'pollini',
    'geox',
    'superga',
    'tods',
    'hogan',
    'subito',
    'subito.it',
    'vinted',
    'depop',
    'kiko',
    'kiko milano',
    'wycon',
    'sephora italia',
    'bricoman',
    'brico',
    'castorama',
    'leroy merlin',
    'obi',
    'bricocenter',
    'centro commerciale',
    'galleria',
    'outlet',
    'mcarthurglen',
    'serravalle outlet',
    'fidenza village',
    'vale village',
    'scalo milano',
  ],
  entertainment: [
    'cinema',
    'multisala',
    'teatro',
    'concerto',
    'museo',
    'mostra',
    'parco divertimenti',
    'parco acquatico',
    'discoteca',
    'locale notturno',
    'pub',
    'birreria',
    'piscina',
    'palestra',
    'karting',
    'uci cinemas',
    'uci',
    'the space cinema',
    'the space',
    'odeon',
    'amazon prime video it',
    'apple tv plus italia',
    'sky show',
    'sky sport',
    'sky calcio',
    'dazn italia',
    'superenalotto',
    'lotto',
    'gratta e vinci',
    '10 e lotto',
    'win for life',
    'sisal',
    'lottomatica',
    'ticketone',
    'ticket one',
    'vivaticket',
    'dice',
    'eventim',
    'eventim italia',
  ],
  education: [
    'scuola',
    'scuola elementare',
    'scuola media',
    'scuola superiore',
    'liceo',
    'istituto tecnico',
    'istituto professionale',
    'università',
    'ateneo',
    'politecnico',
    'facoltà',
    'corso di laurea',
    'retta scolastica',
    'retta universitaria',
    'tasse universitarie',
    'iscrizione università',
    'tassa di iscrizione',
    'edisu',
    'dsu',
    'borsa di studio',
    'lezioni private',
    'ripetizioni',
    'maestro privato',
    'tutor',
    'corso',
    'corso online',
    'master',
    'master universitario',
    'mba',
    'dottorato',
    'specializzazione',
    'libri scolastici',
    'libri universitari',
    'manuale',
    'libreria',
    'cartoleria',
    'cancelleria',
    'quaderni',
    'diario',
    'zaino',
    'astuccio',
    'skuola.net',
    'studenti.it',
    'brainly',
    'zanichelli',
    'hoepli',
    'cils',
    'celi',
    'plida',
    'b1',
    'b2',
    'c1',
    'c2',
  ],
  pets: [
    'animale domestico',
    'animali domestici',
    'veterinario',
    'clinica veterinaria',
    'ambulatorio veterinario',
    'toelettatura',
    'toelettatore',
    'pensione per cani',
    'cane',
    'gatto',
    'cucciolo',
    'gattino',
    'crocchette',
    'bocconcini',
    'mangiatoia',
    'pettorina',
    'guinzaglio',
    'cuccia',
    'trasportino',
    'arcaplanet',
    'isola dei tesori',
    'zooplus',
    'zoo',
    'zoostore',
    'animalia',
    'baloo',
    'microchip',
    'vaccini cane',
    'vaccini gatto',
    'sverminazione',
    'antiparassitario',
  ],
  travel: [
    'vacanza',
    'vacanze',
    'gita',
    'viaggio',
    'soggiorno',
    'ferie',
    'week end',
    'albergo',
    'locanda',
    'bed and breakfast',
    'b&b',
    'agriturismo',
    'villaggio turistico',
    'campeggio',
    'ostello',
    'affittacamere',
    'casa vacanze',
    'venere.com',
    'trivago',
    'volagratis',
    'lastminute.com',
    'edreams',
    'bravofly',
    'gotogate',
    'viaggi del ventaglio',
    'alpitour',
    'turisanda',
    'neckermann',
    'passaporto',
    'patente internazionale',
    'visto',
    'assicurazione viaggio',
    'check-in online',
    'bagaglio',
    'bagaglio a mano',
    'bagaglio in stiva',
    'eccesso bagaglio',
    'traghetto',
    'moby',
    'tirrenia',
    'grimaldi lines',
    'gnv',
    'corsica ferries',
    'blu ferries',
    'snav',
    'maggiore rent',
    'maggiore',
    'locauto',
    'europcar',
    'goldcar',
    'aci blueteam',
  ],
  fitness: [
    'virgin active',
    'virgin active italia',
    'mcfit',
    'technogym',
    'palestra',
    'centro sportivo',
    'piscina comunale',
    'vasca',
    'nuoto',
    'corso nuoto',
    'atletica',
    'corsa',
    'camminata',
    'ciclismo',
    'bicicletta',
    'calcio',
    'calcetto',
    'tennis',
    'padel',
    'padel club',
    'squash',
    'basket',
    'pallavolo',
    'volley',
    'rugby',
    'pugilato',
    'boxe',
    'arti marziali',
    'judo',
    'karate',
    'taekwondo',
    'personal trainer',
    'allenatore personale',
    'abbonamento palestra',
    'tessera sportiva',
    'csi',
    'uisp',
    'aics',
    'acsi',
    'fidal',
    'figc',
    'abbonamento annuale',
  ],
  gifts: [
    'regalo',
    'regali',
    'compleanno',
    'festa',
    'matrimonio',
    'nozze',
    'nascita',
    'battesimo',
    'prima comunione',
    'cresima',
    'laurea',
    'anniversario',
    'onomastico',
    'natale',
    'capodanno',
    'pasqua',
    'epifania',
    'befana',
    'festa della mamma',
    'festa del papà',
    'san valentino',
    'mance',
    'mancia',
    'donazione',
    'beneficenza',
    'caritas',
    'croce rossa italiana',
    'croce rossa',
    'medici senza frontiere',
    'wwf italia',
    'amnesty international',
    'save the children italia',
    'telethon',
    'cinque per mille',
    'cinque x mille',
    'offerta',
    'elemosina',
    'chiesa',
    'parrocchia',
    'voucher regalo',
    'buono regalo',
    'fiori',
    'bouquet',
    'fiorista',
    'cesta',
    'cesto natalizio',
    'panettone regalo',
    'colomba regalo',
  ],
  salary: [
    'stipendio',
    'salario',
    'busta paga',
    'cedolino',
    'cedolino paga',
    'netto',
    'lordo',
    'tredicesima',
    'quattordicesima',
    'tfr',
    'liquidazione',
    'trattamento di fine rapporto',
    'bonus',
    'premi',
    'premio di produzione',
    'indennità',
    'diaria',
    'rimborso spese',
    'nota spese',
    'cassa integrazione',
    'cig',
    'naspi',
    'pensione',
    'reddito di cittadinanza',
    'rdc',
    'assegno familiare',
    'assegno unico',
    'agenzia delle entrate',
    'irpef',
    'inps',
    'contributi',
    'contributi previdenziali',
    'bonifico stipendio',
    'accredito stipendio',
    'accredito',
    'lavoro dipendente',
    'lavoro autonomo',
    'partita iva',
    'freelance',
    'consulenza',
    'onorario',
    'provvigione',
    'commissioni',
    'f24',
    'modello f24',
    'dichiarazione dei redditi',
    '730',
    'modello 730',
    'cud',
    'certificazione unica',
  ],
  investment: [
    'investimento',
    'rendimento',
    'dividendo',
    'cedola',
    'interesse',
    'obbligazione',
    'btp',
    'bot',
    'cct',
    'buono del tesoro',
    'titolo di stato',
    'borsa',
    'borsa italiana',
    'piazza affari',
    'ftse mib',
    'azioni',
    'azione',
    'fondo comune',
    'fondo comune di investimento',
    'sicav',
    'etf',
    'pac',
    'piano di accumulo',
    'risparmio',
    'conto deposito',
    'gestione patrimoniale',
    'consulente finanziario',
    'fineco',
    'finecobank',
    'directa',
    'directa sim',
    'mediolanum',
    'banca mediolanum',
    'azimut',
    'anima',
    'poste italiane',
    'buoni fruttiferi postali',
    'poste',
    'bnl',
    'unicredit',
    'intesa sanpaolo',
    'banca sella',
    'iwbank',
    'banca generali',
    'generali investimenti',
    'assicurazione vita',
    'polizza vita',
    'polizza unit linked',
    'polizza index linked',
    'fondo pensione',
    'piano individuale pensionistico',
    'pip',
    'previdenza complementare',
    'conio',
    'bitpanda',
    'coinbase italia',
    'binance',
    'kraken',
    'ledger',
  ],
  refund: [
    'rimborso',
    'rimborsi',
    'restituzione',
    'accredito',
    'storno',
    'nota di credito',
    'reso',
    'cambio merce',
    'reso merce',
    'annullamento',
    'cancellazione',
    'recesso',
    'diritto di recesso',
    'recupero',
    'risarcimento',
    'risarcimento danni',
    'indennizzo',
    'rimborso ticket',
    'rimborso spese mediche',
    'rimborso viaggio',
    'rimborso volo',
    'rimborso treno',
    'rimborso biglietto',
    'rimborso tasse',
    'rimborso irpef',
    'conguaglio',
    'conguaglio irpef',
    'credito fiscale',
    'credito di imposta',
    'cashback stato',
    'cashback italia',
    'superbonus',
    'ecobonus',
    'bonus casa',
    'detrazione',
    'rimborso assicurazione',
    'sinistro',
    'liquidazione sinistro',
  ],
};

export default it;
