const ms = {
  food: [
    'big bang burger',
    'big bang',
    'ayam gepuk',
    'gepuk',
    'nasi ayam hainan',
    'chicken chop',
    'snappy tomato',
    'fatburger malaysia',
    'jollibee malaysia',
    'popeyes malaysia',
    'mcd mccafe',
    'mccafe',
    'starbucks malaysia',
    'kopi ais tarik',
    'kopi tarik panas',
    'teh c peng',
    'teh o ais limau',
    'air bandung',
    'air laici',
    'air longan',
    'jus kedondong',
    'jus belimbing',
    'buah naga',
    'jambu batu',
    'jambu air',
    'salak',
    'durian kampung',
    'durian d24',
    'durian sultan',
    'durian frozen',
    'durian crepe',
    'durian puff',
    'durian ice cream',
    'cendol durian',
    'waffle durian',
    'durian cake',
    'durian pancake',
    'bak chor mee',
    'bah kut teh',
    'wonton soup',
    'char kuey',
    'hokkien char',
    'wan tan',
    'dim sum malaysia',
    'yam basket',
    'yong tau fu',
    'hakka mee',
    'economy rice',
    'economy noodle',
    'nasi campur cina',
    'deliveroo malaysia',
    'deliveroo',
    'lalamove food',
    'koodoo',
    'bungkusit rider',
    'viral food',
    'hawker food',
    'street food',
    'makan best',
    'tempat makan',
    'kedai nasi',
    'kedai kopi',
    'gerai tepi jalan',
    'food truck kl',
    'night market food',
    'bazaar ramadan',
    'bazaar',
    'bazar ramadan',
    'bazar',
    'juadah berbuka',
    'berbuka puasa',
    'sahur',
    'makan sahur',
    'kuih raya',
    'biskut raya',
    'kuih muih',
    'mee bandung muar',
    'mee bandung',
    'nasi ambang',
    'nasi minyak',
    'nasi tomato',
    'sup torpedo',
    'sup gearbox',
    'sup hameed',
    'nasik lemak',
    'nasik goreng',
    'kolo mee',
    'sarawak laksa',
    'mee jawa sabah',
    'hinava',
    'ambuyat',
    'tuak',
    'pak li kopitiam',
    'family kopitiam',
    'kim kopitiam',
    'restoran bersih',
    'gerai makan',
    // === Malaysia merchants ===
    'mamak',
    'kopitiam',
    'kedai makan',
    'grabfood',
    'foodpanda',
    'shopeefood',
    'kfc malaysia',
    'mcdonalds malaysia',
    'pizza hut malaysia',
    "domino's pizza malaysia",
    'subway malaysia',
    "nando's malaysia",
  ],
  groceries: [
    'lotus extra',
    'lotus hipermarket',
    'jaya grocer pavilion',
    'aeon wellness',
    'aeon maxvalu prime',
    'kedai rakyat 1malaysia',
    'kedai rakyat',
    'kr1m',
    'pasar komuniti',
    'pasar tani jpm',
    'setiapagi',
    'pasaraya ansar',
    'mydin express',
    'mydin mall',
    'pakej beras',
    'pakej minyak',
    'gula perang',
    'gula melaka',
    'tepung jagung',
    'tepung ubi',
    'roti gardenia',
    'susu bear brand',
    'susu HL',
    'susu uht',
    'yogurt vitagen',
    'vitagen',
    'yakult',
    '100plus',
    '100 plus',
    'isotonic',
    'revive',
    'spritzer',
    'cactus water',
    'air cactus',
    'air mineral',
    'evian malaysia',
    'fm milk',
    'frisomel',
    'dumex',
    'enfamil',
    'similac',
    'enfagrow',
    'pediasure',
    'belachan',
    'udang kering',
    'santan uht',
    'ayam brand',
    'kagome',
    'heinz malaysia',
    'maggi perencah',
    'rempah instant',
    'beras cap rambutan',
    'beras faiza',
    'beras jasmine',
    'beras siam',
    'beras wangi',
    'happy fresh',
    'happyfresh',
    'grab mart',
    'grabmart',
    'jaya grocer online',
    'shopee mart',
    'lazada mart',
    'mydin online',
    'tesco online',
    'lotus online',
    'aeon online',
    'cold chain',
    'frozen food delivery',
    'borong',
    'beli borong',
    'kilang',
    'direct kilang',
    'kedai borong',
    'nilai borong',
    'pasar malam beli',
    'morning market',
    'pasar pagi borong',
    'pencuci lantai',
    'sabun mandi',
    'sabun tangan',
    'pewangi',
    'pewangi kain',
    'softlan',
    'dynamo',
    'breeze',
    'attack detergent',
    'wash & go',
    'rejoice',
    'pantene malaysia',
    'head shoulders',
    'gatsby',
    'gatsby hair',
    'brylcreem',
    'axe brand',
    'minyak angin',
    'bio oil',
    'nivea malaysia',
    // === Malaysia merchants ===
    "lotus's",
    'giant hypermarket',
    'mydin',
    'jaya grocer',
    '99 speedmart',
    'kk mart',
    'econsave',
    'nsk trade city',
    'village grocer',
    "ben's independent grocer",
  ],
  transport: [
    'mrt putrajaya line',
    'laluan putrajaya',
    'mrt sungai buloh putrajaya',
    'mrt kwasa damansara',
    'mrt kwasa sentral',
    'mrt cyberjaya utara',
    'mrt cyberjaya city',
    'mrt putrajaya sentral',
    'mrt serdang raya selatan',
    'mrt serdang raya utara',
    'mrt salak selatan',
    'mrt bandar tun hussein onn',
    'mrt bukit dukung',
    'tada malaysia',
    'tada',
    'ola electric',
    'ola',
    'mula car',
    'mula',
    'grab hitch',
    'grab premium',
    'grab premium x',
    'grab6',
    'grabexec',
    'grab exec',
    'grab van',
    'grab pets',
    'grab minibus',
    'lalamove',
    'lalamove malaysia',
    'pickupp',
    'pick upp',
    'delyva',
    'borzo',
    'rider express',
    'ev innio',
    'ev plaza',
    'evolt',
    'gentari',
    'gentari ev',
    'petronas ev',
    'petronas gentari',
    'shell recharge',
    'shell ev',
    'tnb ev charging',
    'chargev',
    'myev',
    'my ev',
    'evhub',
    'ev hub',
    'voltaiq',
    'juice ev',
    'greenlane ev',
    'dc fast charging',
    'ac charging',
    'home charger',
    'byd ev',
    'proton e.mas',
    'proton emas',
    'perodua ev',
    'myvi ev',
    'suke highway',
    'suke',
    'dash highway',
    'dash',
    'ekve',
    'ekve highway',
    'skim highway timur laut',
    'shtl',
    'west coast expressway',
    'wce',
    'penang second bridge',
    'jambatan kedua',
    'sabah expressway',
    'sarawak expressway',
    'proton x70',
    'proton x50',
    'proton s70',
    'perodua alza',
    'perodua ativa',
    'perodua bezza',
    'myvi',
    'insurans kenderaan',
    'puspakom',
    'jpj renew',
    'roadtax renew',
    'road tax renew',
    'renew road tax',
    'renew roadtax',
    'roadtax digital',
    'skim tenang',
    'motor insurance',
    'motor insurans',
    'potong kereta',
    'scrap car',
    'hire purchase',
    'ansuran kereta',
    'bayar kereta',
    'konsortium bas ekspres',
    'starmart express kl',
    'kesatuan',
    'bas muafakat johor',
    'rcv bus',
    'bas one way',
    'ets tiket',
    'park by phone malaysia',
    'ipay88 parking',
    'presto parking',
    'parking waze',
    'smart selangor',
    'smartselangor',
    // === Malaysia merchants ===
    'grab',
    'grabcar',
    'rapidkl',
    'mrt',
    'lrt',
    'touch n go',
    'tng',
    'petronas',
    'shell malaysia',
    'petron malaysia',
    'bhpetrol',
    'caltex malaysia',
    'smarttag',
    'airasia',
    'malaysia airlines',
    'firefly airlines',
  ],
  housing: [
    'sewa rumah pprt',
    'pprt',
    'pr1ma',
    'prima rumah',
    'rumah mampu milik',
    'rumah mesra rakyat',
    'rumah selangorku',
    'selangorku',
    'rumah wilayah',
    'rumah idaman',
    'spnb',
    'kwsp rumah',
    'pengeluaran kwsp',
    'pengeluaran epf',
    'kwsp akaun 2',
    'spaapp',
    'spa application',
    'strata title',
    'geran individu',
    'geran hakmilik',
    'sijil hakmilik',
    'master title',
    'pajakan tanah',
    'ptptn semula',
    'pinjaman bank rumah',
    'margin pinjaman',
    'downpayment rumah',
    'down payment rumah',
    'bayaran pendahuluan',
    'solicitor fee',
    'guaman rumah',
    'peguam hartanah',
    'spa fee',
    'loan agreement fee',
    'stamping fee',
    'insurance mrta',
    'mrta',
    'mlta',
    'fire insurance rumah',
    'houseowner insurance',
    'householder insurance',
    'sinking fund condo',
    'quit rent malay',
    'cukai tanah negeri',
    'kontraktor renovation',
    'renovation cost',
    'kos renovation',
    'renovation package',
    'id design',
    'interior design malaysia',
    'kitchen cabinet',
    'kabinet dapur',
    'wardrobe built in',
    'almari bina',
    'grill rumah',
    'pintu grill',
    'pintu security',
    'cctv rumah',
    'alarm rumah',
    'system alarm',
    'solar panel rumah',
    'suria solar',
    'jom solar',
    'bil syabas',
    'bil air selangor',
    'air selangor online',
    'tnb bill',
    'tnb myelectric',
    'mytnb',
    'my tnb',
    'tnb online',
    'gas petronas',
    'gas ngv',
    'bill gas',
    'gas cylinder',
    'tangki gas',
  ],
  bills: [
    'yes 5g home',
    'unifi home',
    'unifi 30mbps',
    'unifi 100mbps',
    'unifi 300mbps',
    'unifi 800mbps',
    'time 100mbps',
    'time 600mbps',
    'time 1gbps',
    'maxis 5g',
    'celcom 5g',
    'digi 5g',
    'onexox black',
    'onexox true 5g',
    'yoodo 5g',
    'altel',
    'cliq',
    'cliq mobile',
    'c1 mobile',
    'allo broadband',
    'allo',
    'jom apply',
    'pakej unifi',
    'pakej maxis',
    'pakej time',
    'billplz',
    'bill plz',
    'ipay88',
    'fpx payment',
    'fpx',
    'duitnow',
    'duit now',
    'duitnow qr',
    'boost wallet',
    'boost app',
    'boost pay',
    'boost cashback',
    'tng ewallet',
    'tng wallet',
    'touch n go ewallet',
    'tng digital',
    'grab pay',
    'grabpay',
    'grabpay wallet',
    'shopee pay',
    'shopeepay',
    'lazada wallet',
    'lazpay',
    'maybank qr',
    'maybank2u',
    'maybank pay',
    'cimb octo',
    'octo pay',
    'rhb now',
    'hong leong connect',
    'hlb connect',
    'public bank qr',
    'affin pay',
    'ambank fpx',
    'tabung haji online',
    'astro go',
    'astro on demand',
    'astro box office',
    'unifi tv',
    'unifi play',
    'mewatch',
    'vidio',
    'starz play',
    'dimsum entertainment',
    'dimsum',
    'sooka',
    'sooka tv',
    'apple tv malaysia',
    'tiktok live',
    'topup boost',
    'topup tng',
    'topup grabpay',
    'topup shopeepay',
    'isi boost',
    'isi tng',
    'reload boost',
    'reload tng',
    'cas wallet',
    'ewallet',
    'e-wallet',
    'dompet digital',
    // === Malaysia merchants ===
    'maxis',
    'celcom',
    'digi',
    'celcomdigi',
    'u mobile',
    'unifi',
    'yes 4g',
    'tnb',
    'syabas',
    'air selangor',
    'astro',
  ],
  healthcare: [
    'kpj damansara',
    'kpj klang',
    'kpj seremban',
    'kpj johor',
    'kpj penang',
    'kpj ipoh',
    'kpj ampang puteri',
    'kpj selangor',
    'kpj tawakkal',
    'hospital tawakkal',
    'pantai cheras',
    'pantai klang',
    'pantai ayer keroh',
    'pantai indah',
    'pantai bangsar',
    'columbia asia cheras',
    'columbia asia bukit rimau',
    'columbia asia nusajaya',
    'columbia asia miri',
    'gleneagles medini',
    'gleneagles penang',
    'sime darby medical',
    'sime darby subang',
    'ara damansara medical',
    'sjmc subang',
    'mahkota specialist',
    'manipal hospital malaysia',
    'manipal',
    'nsh national specialist',
    'ara specialist',
    'vista specialist',
    'sunway velocity medical',
    'sunway specialist',
    'hospital pakar',
    'klinik pakar',
    'caring pharmacy online',
    'big pharmacy online',
    'alpro online',
    'guardian online',
    'watsons online',
    'farmasi al-zahra',
    'farmasi caring',
    'farmasi big',
    'farmasi ansar',
    'farmasi mydin',
    'mysejahtera',
    'my sejahtera',
    'vaksin mysejahtera',
    'digital health',
    'rekod kesihatan',
    'health record digital',
    'doktor pakar bedah',
    'doktor pakar kardiologi',
    'doktor pakar ortopedik',
    'doktor pakar pediatrik',
    'doktor pakar neurologi',
    'doktor pakar onkologi',
    'doktor pakar mata',
    'ujian covid',
    'pcr test',
    'antigen test',
    'rtk antigen',
    'swab test',
    'booster dose',
    'dos penggalak',
    'vaksin covid',
    'vaksin flu',
    'vaksin influenza',
    'imunisasi',
    'program imunisasi',
    'skrin kanser',
    'mammogram malaysia',
    'pap smear',
    'colonoscopy malaysia',
    'pakej kesihatan',
    'pakej medical',
    'medical checkup package',
    'health screening package',
    'health screening',
    'skim peduli kesihatan',
    'kad kesihatan',
    'kaunselor',
    'kaunseling',
    'psikologi',
    'psikiatri',
    'mental wellness',
    'sinseh',
    'kedai ubat cina',
    'kedai sinseh',
    'ubat tradisional',
    'ubat herba',
    'klinik tradisional',
    'urut tradisional',
    'urut melayu',
    'rawatan tradisional',
    'jamu',
    'air jamu',
    'habbatus sauda',
    'blackseed',
    'spirulina',
    'herbalife',
    'shaklee',
    'lampe berger',
    'forever living',
    'noni',
    'minyak zaitun',
    'cabut gigi',
    'tampal gigi',
    'implan gigi',
    'gigi palsu',
    'behel gigi',
    'pendakap gigi',
    'pemutihan gigi',
    'scaling gigi',
    'rawatan gigi',
    'ortodontik',
    'crown gigi',
    'veneer gigi',
    // === Malaysia merchants ===
    'watsons',
    'guardian',
    'caring pharmacy',
    'big pharmacy',
    'alpro pharmacy',
  ],
  shopping: [
    'shopee live',
    'shopee coins',
    'lazada voucher',
    'shopee voucher',
    'shopee sale',
    'lazada sale',
    '11.11 shopee',
    '12.12 shopee',
    'shopee birthday sale',
    'lazada birthday sale',
    'shopee flash sale',
    'lazada flash sale',
    'tiktok shop malaysia',
    'tiktok shop',
    'facebook marketplace malaysia',
    'carousell malaysia',
    'mudah.my',
    'lelong my',
    'lelong',
    'lowyat forum',
    'lowyat buy sell',
    'pavilion bukit jalil',
    'pavilion bj',
    'mitsui outlet park',
    'mitsui outlet',
    'genting premium outlet',
    'premium outlet genting',
    'johor premium outlet',
    'jpo',
    'design village outlet mall',
    'design village',
    'mytown shopping',
    'dc mall',
    'jalan masjid india',
    'masjid india',
    'petaling street',
    'chow kit',
    'pudu sentral',
    'nilai 3',
    'nilai3',
    'focus point',
    'focus point optical',
    'eyes plus',
    'malaya optical',
    'optical 88',
    'switch apple reseller',
    'istudio',
    'i-studio',
    'machines malaysia',
    'apple premium reseller',
    'samsung malaysia',
    'samsung store',
    'huawei store malaysia',
    'xiaomi malaysia',
    'mi store',
    'oneplus malaysia',
    'realme malaysia',
    'oppo malaysia',
    'vivo malaysia',
    'infinix malaysia',
    'techno malaysia',
    'baju batik cotton',
    'kain pelikat',
    'kain sarung',
    'kain batik cotton',
    'kain ela',
    'baju sulam',
    'kurung moden',
    'jubah labuh',
    'skirt labuh',
    'inner pakaian',
    'inner tudung',
    'bawal premium',
    'bawal ironless',
    'shawl',
    'pashmina',
    'selendang',
    'scarf',
    'aksesori',
    'stokin',
    'tali pinggang',
    'cermin mata frame',
    'frame cermin mata',
    'ace hardware malaysia',
    'habitat malaysia',
    'mr diy malaysia',
    'simplysiti',
    'd program',
    'wardah malaysia',
    'purbasari',
    'luxcrime',
    'safi malaysia',
    'cosmoderm',
    'bioessence malaysia',
    'olay malaysia',
    'cetaphil malaysia',
    'hada labo',
    'senka',
    'skii malaysia',
    'lancome malaysia',
    'estee lauder malaysia',
    'mac malaysia',
    'clinique malaysia',
    'benefit malaysia',
    // === Malaysia merchants ===
    'parkson',
    'harvey norman',
    'senheng',
    'senq',
    'courts malaysia',
    'uniqlo malaysia',
    'padini',
    'brands outlet',
    'shopee',
    'lazada',
    'zalora',
    'eco-shop',
  ],
  entertainment: [
    'tgv cinemas',
    'gsc cinemas',
    'mbo cinemas',
    'lotus five star cinemas',
    'big cinema',
    'big cinemas',
    'aurum theatre kl',
    'cinema online malaysia',
    'tiket filem',
    'wayang malam',
    'wayang 3d',
    'tiket 3d',
    'imax malaysia',
    'astro go premium',
    'unifi tv premier',
    'viu premium',
    'wetv premium',
    'iqiyi premium',
    'disney+ hotstar',
    'hotstar malaysia',
    'apple one',
    'youtube premium malaysia',
    'spotify premium malaysia',
    'joox premium',
    'joox',
    'steam malaysia',
    'garena',
    'garena free fire',
    'garena top up',
    'pubg mobile malaysia',
    'mobile legends malaysia',
    'ml diamond',
    'ml top up',
    'free fire diamond',
    'genshin impact malaysia',
    'honkai star rail',
    'call of duty mobile',
    'arena of valor',
    'point blank',
    'ragnarok mobile',
    'ragnarok malaysia',
    'league of legends malaysia',
    'dota2 malaysia',
    'valorant malaysia',
    'roblox',
    'minecraft malaysia',
    'game top up',
    'topup game',
    'voucher game',
    'steam wallet',
    'google play credit',
    'apple app store credit',
    'gplay',
    'good vibes festival',
    'good vibes',
    'escape penang',
    'escape theme park',
    'skytrex shah alam',
    'skytrex adventure',
    'mines wonderland',
    'wet world',
    'waterpark malaysia',
    'berjaya times square theme park',
    'times square theme park',
    'i-city',
    'icity',
    'legoland malaysia',
    'legoland',
    'hello kitty town',
    'thomas town',
    'indoor playground',
    'kidzsports',
    'kidzania kl',
    'kidzania',
    'stadium merdeka',
    'bukit jalil',
    'stadium bukit jalil',
    'stadium nasional',
    'liga super malaysia',
    'liga malaysia',
    'bola sepak malaysia',
    'tiket bola',
    'badminton malaysia open',
    'thomas cup',
    'uber cup',
    'piala thomas',
    'piala uber',
    'sukma',
    'sukan malaysia',
    // === Malaysia merchants ===
    'netflix',
    'netflix malaysia',
    'viu',
    'iqiyi',
    'wetv',
    'sunway lagoon',
    'zoo negara',
  ],
  education: [
    'ump universiti malaysia pahang',
    'ump',
    'unimas',
    'universiti malaysia sarawak',
    'ums universiti malaysia sabah',
    'ums',
    'unimap',
    'universiti malaysia perlis',
    'umt',
    'universiti malaysia terengganu',
    'upm universiti putra',
    'utem',
    'universiti teknikal malaysia melaka',
    'uitm kampus',
    'politeknik',
    'komuniti kolej',
    'kolej komuniti',
    'kppk',
    'ucsi',
    'ucsi university',
    'raffles college',
    'sae institute',
    'mahsa university',
    'manipal international university',
    'widad university',
    'perdana university',
    'aimst university',
    'masterskill',
    'metropolitan college',
    'kolej metropolitan',
    'brickfields asia college',
    'brickfields',
    'city university malaysia',
    'city university college',
    'ptptn belajar',
    'ptptn payment',
    'bayar ptptn',
    'ansuran ptptn',
    'ptptn loan',
    'ptptn monthly',
    'yuran matrikulasi',
    'matrikulasi',
    'foundation program',
    'pra universiti',
    'tingkatan 6',
    'form 6',
    'a level malaysia',
    'o level malaysia',
    'igcse',
    'igcse malaysia',
    'spm tuisyen',
    'tuisyen spm',
    'kelas tambahan spm',
    'bestari kid',
    'pra sekolah',
    'kindie',
    'taska',
    'taska berdaftar',
    'taska kerajaan',
    'daycare',
    'child care',
    'babysitter',
    'pengasuh',
    'sijil kemahiran malaysia',
    'skm',
    'ciast',
    'hrdc',
    'hrdf',
    'hrdf kursus',
    'train the trainer',
    'kursus hrdf',
    'kursus bersertifikat',
    'kursus online free',
    'coursera malaysia',
    'udemy malaysia',
    'certificate course',
    'professional certificate',
    'akreditasi',
    'lembaga jurutera',
    'board of engineers',
    'mpm',
    'majlis peperiksaan malaysia',
    'pendaftaran exam',
    'kad pengenalan murid',
    'borang sekolah',
    'pendaftaran sekolah',
    'daftar sekolah',
    'yuran pdp',
    'yuran sukan',
    'yuran kokurikulum',
    'buku aktiviti',
    'buku cerita',
    'ensiklopedia',
    'komputer laptop sekolah',
    'laptop student',
    'ipad student',
    'wifi sekolah',
  ],
  pets: [
    'pet world malaysia',
    'paws n tails',
    'pet zone malaysia',
    'happy pets malaysia',
    'pet avenue',
    'happy tails',
    'my pets paradise',
    'paws station',
    'pawsome',
    'klinik haiwan kerajaan',
    'klinik veterinar',
    'hospital haiwan',
    'jpv',
    'jabatan perkhidmatan veterinar',
    'lesen anjing',
    'lesen kucing',
    'permit haiwan',
    'microchip haiwan',
    'tatoo haiwan',
    'royal canin malaysia',
    'hills prescription malaysia',
    'science diet malaysia',
    'orijen malaysia',
    'taste wild malaysia',
    'proplan',
    'pro plan malaysia',
    'nutro malaysia',
    'pedigree malaysia',
    'whiskas malaysia',
    'kit kat cat food',
    'friskies malaysia',
    'grooming haiwan',
    'mandikan anjing',
    'mandikan kucing',
    'potong kuku haiwan',
    'hotel haiwan',
    'penginapan haiwan',
    'pet boarding malaysia',
    'pet hotel',
    'daycare anjing',
    'latihan anjing',
    'pet sitter malaysia',
    'makanan haiwan',
    'makanan anjing',
    'makanan kucing',
    'anjing',
    'kucing',
    'burung',
    'arnab',
    'arnab peliharaan',
    'hamster',
    'ikan hiasan',
    'kolam ikan',
    'ikan koi',
    'sangkar burung',
    'pasir kucing',
    'ubat cacing',
    'rawatan kutu',
    'ubat kutu',
    'pelet arnab',
    'makanan burung',
    'benih burung',
    // === Malaysia merchants ===
    'pet lovers centre',
    'petsmore',
    "nature's farm malaysia",
  ],
  travel: [
    'pakej all in',
    'pakej honeymoon',
    'pakej bajet',
    'pakej jimat',
    'pakej tiket flight',
    'flight kl singapore',
    'flight kl penang',
    'flight kl kk',
    'flight domestic',
    'flight antarabangsa',
    'tiket kapal terbang',
    'bayar tiket',
    'insurans perjalanan',
    'travel insurance malaysia',
    'etiqa travel',
    'aia travel',
    'allianz travel',
    'tokio marine travel',
    'resort world sentosa',
    'batam',
    'bintan',
    'patong beach',
    'phi phi island',
    'phi phi',
    'hatyai',
    'hat yai',
    'padang besar',
    'kanchanaburi',
    'chiang mai',
    'chiang rai',
    'yangon',
    'mandalay',
    'nha trang',
    'da nang',
    'hue vietnam',
    'hoi an',
    'phu quoc',
    'bali canggu',
    'bali seminyak',
    'bali ubud',
    'yogyakarta',
    'borobudur',
    'bandung',
    'surabaya',
    'makasar',
    'brunei darussalam',
    'bandar seri begawan',
    'cambodia phnom penh',
    'siem reap',
    'angkor wat',
    'sri lanka',
    'maldives',
    'nepal',
    'istanbul',
    'jeddah',
    'riyadh',
    'abu dhabi',
    'muscat',
    'cairo',
    'capsule hotel',
    'backpacker hostel',
    'rumah rehat kerajaan',
    'resort pulau',
    'chalet beach',
    'camping',
    'glamping',
    'riverside resort',
    'hill resort',
    'duit forex',
    'tukar duit',
    'money changer',
    'kaunter pertukaran wang',
    'rm ke dollar',
    'rm to usd',
    'airasia big loyalty',
    'enrich miles',
    'enrich malaysia airlines',
    'kris flyer',
    'bigpay',
    'big pay',
    'travel debit card',
    'westernunion',
    'wise transfer',
    'remittance',
    // === Malaysia merchants ===
    'agoda',
    'booking.com',
    'traveloka',
    'airbnb malaysia',
    'tune hotels',
    'oyo malaysia',
  ],
  fitness: [
    'planet fitness malaysia',
    'kfit malaysia',
    'kfit',
    'nexus fitness',
    'altitude gym',
    'urbanathletics',
    'r fitness',
    'sportsplanet',
    'sports planet',
    'starling fitness',
    'power gym',
    'hardwork gym',
    'one boxing',
    'training lab',
    'kompleks sukan',
    'pusat sukan',
    'stadium mini',
    'gelanggang badminton',
    'gelanggang squash',
    'squash court',
    'badminton court',
    'padel court',
    'padel malaysia',
    'futsal court',
    'gelanggang futsal',
    'bowling malaysia',
    'rock climbing malaysia',
    'batu mendaki',
    'panjat tebing',
    'archery malaysia',
    'panahan',
    'horse riding',
    'berkuda',
    'wakeboard',
    'water ski',
    'langganan gym',
    'bayar gym',
    'fee gym',
    'yuran gym',
    'ahli gym',
    'card gym',
    'pas gym',
    'latihan kekuatan',
    'angkat berat',
    'bina badan',
    'binaan badan',
    'bodybuilding',
    'supplement malaysia',
    'whey protein malaysia',
    'optimum nutrition',
    'myprotein malaysia',
    'nl nutrition',
    'nl pro',
    'health lane supplement',
    'dymatize',
    'muscletech malaysia',
    'creatine monohydrate',
    'mass gainer',
    'fat burner',
    'multivitamin sukan',
    'zinc malaysia',
    'magnesium supplement',
    'omega 3 malaysia',
    // === Malaysia merchants ===
    'fitness first malaysia',
    'celebrity fitness',
    'anytime fitness malaysia',
    'gym',
  ],
  gifts: [
    'bagi hadiah',
    'belanja kawan',
    'belanja makan',
    'traktir makan',
    'traktir',
    'open house',
    'rumah terbuka',
    'majlis aqiqah',
    'aqiqah',
    'cukur jambul',
    'marhaban',
    'selamatan',
    'majlis kesyukuran',
    'kesyukuran',
    'hadiah bayi baru',
    'baby gift',
    'baby shower',
    'buaian',
    'bunga telur',
    'telur pelangi',
    'hantaran',
    'mas kahwin',
    'mahar',
    'akad nikah',
    'nikah',
    'resepsi',
    'persandingan',
    'bersanding',
    'makan malam kahwin',
    'hadiah graduation',
    'konvokesyen',
    'konvo',
    'hadiah konvo',
    'duit salam',
    'sampul raya',
    'sampul hijau',
    'sampul cny',
    'token reward',
    'cash token',
    'hamper raya',
    'hamper cny',
    'hamper krismas',
    'khairat kematian',
    'tabung kebajikan',
    'tabung surau',
    'wakaf',
    'amal jariah',
    'jariah',
    'nazar',
    'fidyah',
    'kaffarah',
  ],
  salary: [
    'caruman kwsp',
    'caruman epf',
    'kwsp bulanan',
    'epf bulanan',
    'kwsp akaun 1',
    'kwsp akaun 3',
    'kwsp akaun tiga',
    'pengeluaran kwsp akaun 2',
    'pengeluaran kwsp 50',
    'i-sinar',
    'i-lestari',
    'i-citra',
    'pengeluaran perumahan kwsp',
    'caruman socso',
    'caruman perkeso',
    'skim bencana pekerjaan',
    'skim kecacatan',
    'faedah perkeso',
    'pcb potongan',
    'potongan pcb',
    'pcb monthly',
    'cukai pendapatan bulanan',
    'borang be',
    'borang b',
    'borang e',
    'e-filing lhdn',
    'lhdn refund',
    'cukai refund lhdn',
    'bayar cukai pendapatan',
    'lhdn payment',
    'lhdn bayar',
    'gaji pokok asas',
    'gaji minimum',
    'minimum wage',
    'upah minimum',
    'gaji penuh',
    'gaji akhir bulan',
    'gaji tengah bulan',
    'transfer gaji',
    'masuk bank gaji',
    'slip gaji digital',
    'e-slip gaji',
    'pencen kerajaan',
    'pencen tentera',
    'pencen polis',
    'lebihan kerja',
    'lembur',
    'ot rate',
    'rate ot',
    'double pay',
    'bayaran ganda',
    'elaun kehadiran',
    'elaun pakaian',
    'elaun telefon',
    'elaun petrol',
    'elaun khas',
    'elaun hujung minggu',
    'elaun cuti',
    'ganjaran cuti',
    'bonus khas',
    'bonus prestasi',
    'bonus akhir tahun',
    'ex gratia',
    'golden handshake',
    'retrenchment benefit',
    'vsss',
    'vss',
    'pendapatan sampingan',
    'pendapatan aktif',
    'pendapatan pasif',
    'pendapatan sewaan',
    'sewa bulanan',
    'sewa kedai',
    'yuran profesional',
    'fee guaman',
    'fee konsultasi',
    'honorarium',
    'upah harian',
    'upah mingguan',
    'bayaran kontrak',
  ],
  investment: [
    'akaun kwsp',
    'kwsp simpanan',
    'dividen kwsp',
    'dividen epf',
    'kwsp tahunan',
    'kwsp withdrawal',
    'amanah saham bumiputera',
    'asb loan',
    'pinjaman asb',
    'amanah saham wawasan',
    'amanah saham malaysia',
    'asb dividend',
    'tabung haji saving',
    'th dividend',
    'bursa trade',
    'contra trade',
    'short sell',
    'warran saham',
    'call warrant',
    'put warrant',
    'etf malaysia',
    'tradeplus etf',
    'principal etf',
    'fbm klci etf',
    'versa cash',
    'versa invest',
    'stashaway simple',
    'stashaway portfolio',
    'wahed invest malaysia',
    'bimb securities',
    'kenanga',
    'kenanga futures',
    'affin hwang',
    'rhb invest',
    'cimb invest',
    'maybank invest',
    'hong leong invest',
    'am invest',
    'uob asset',
    'emas beli',
    'emas jual',
    'pelaburan emas',
    'emas bank',
    'emas muamalat',
    'emas maybank',
    'emas cimb',
    'ar-rahnu',
    'ar rahnu',
    'gadai emas',
    'pajak gadai',
    'penggadaian',
    'public gold',
    'publicgold',
    'pgold',
    'poh kong gold',
    'habib jewels',
    'luxe jewels',
    'perak bar',
    'silver perak',
    'luno malaysia',
    'luno',
    'tokenize malaysia',
    'tokenize',
    'sinegy',
    'crypto malaysia',
    'bitcoin malaysia',
    'ethereum malaysia',
    'defi malaysia',
    'funding societies',
    'alixco',
    'kapital boost',
    'ethis malaysia',
    'agrobank invest',
    'reit malaysia',
    'sunreit',
    'pavilion reit',
    'igbreit',
    'klccp',
    'axis reit',
    'hektar reit',
    'pelaburan hartanah',
    'crowdfunding hartanah',
    'equity crowdfunding',
    'takaful keluarga',
    'takaful am',
    'takaful malaysia',
    'takaful ikhlas',
    'takaful premier',
    'aia takaful',
    'prudential bsn takaful',
    'zurich takaful',
    'syarikat takaful',
    'premium takaful',
    'caruman takaful',
    'polisi takaful',
  ],
  refund: [
    'refund shopee',
    'refund lazada',
    'refund tiktok shop',
    'refund mudah',
    'refund carousell',
    'pulang wang shopee',
    'pulang wang lazada',
    'seller refund',
    'buyer refund',
    'refund proses',
    'refund dalam proses',
    'refund berjaya',
    'status refund',
    'semak refund',
    'refund boost',
    'refund tng',
    'refund grabpay',
    'refund shopeepay',
    'balik kredit',
    'kredit kembali',
    'ewallet refund',
    'cashback kredit',
    'tuntutan kemalangan',
    'tuntutan kecurian',
    'tuntutan kebakaran',
    'tuntutan banjir',
    'tuntutan motor',
    'tuntutan kereta',
    'tuntutan medikan',
    'tuntutan hospital',
    'tuntutan kematian',
    'klaim insurans',
    'klaim takaful',
    'panel claim',
    'workshop panel',
    'workshop claim',
    'refund lhdn',
    'cukai balik',
    'bayaran balik cukai',
    'borang be refund',
    'e-refund lhdn',
    'refund tiket kapal terbang',
    'refund airasia',
    'refund malaysia airlines',
    'refund hotel',
    'refund agoda',
    'refund traveloka',
    'refund booking.com',
    'refund grab',
    'gst refund tourist',
    'bayaran balik deposit',
    'deposit kembali',
    'deposit dikembalikan',
    'wang cagaran',
    'cagaran kembali',
    'duit pendahuluan balik',
    'over payment',
    'lebih bayar',
    'bayaran berlebihan',
    'guna points',
    'redeem points',
    'tukar points',
    'cashback kredit masuk',
    'kredit cashback',
    'reward redeem',
    'myrewards',
    'points maybank',
    'treats points',
    'enrich redeem',
    'big points redeem',
    'shopee coins redeem',
    'lazada coins',
    'tng cashback dapat',
  ],
};

export default ms;
