const nb = {
  food: [
    'mat',
    'lunsj',
    'middag',
    'frokost',
    'kaffe',
    'kaffebar',
    'smørbrød',
    'brunost',
    'pinnekjøtt',
    'fårikål',
    'rømmegrøt',
    'lefse',
    'krumkake',
    'vafler',
    'pizza',
    'kebab',
    'wolt',
    'foodora',
    'uber eats',
    'mcdonalds',
    'burger king',
    'subway',
    'peppes pizza',
    'dolly dimple',
    'deli de luca',
    'narvesen',
    '7-eleven',
    'mix kiosk',
    'baker hansen',
    'kaffebrenneriet',
    'stockfleths',
    'starbucks',
    'restaurant',
    'kafé',
    'takeaway',
    'spisested',
    'gatekjøkken',
    'bakeri',
    'konditori',
  ],
  groceries: [
    'matbutikk',
    'dagligvare',
    'dagligvarer',
    'rema 1000',
    'rema',
    'kiwi',
    'meny',
    'ica',
    'extra',
    'coop prix',
    'coop',
    'spar',
    'joker',
    'eurospar',
    'nærbutikken',
    'grønnsaker',
    'frukt',
    'kjøtt',
    'fisk',
    'brød',
    'melk',
    'meieri',
    'matvarer',
    'handel',
    'kolonial',
    'oda',
    'egg',
    'ost',
    'smør',
    'yoghurt',
    'juice',
    'brus',
    'rengjøring',
    'vaskemiddel',
  ],
  transport: [
    'buss',
    'trikk',
    't-bane',
    'tbane',
    'metro',
    'ruter',
    'kolumbus',
    'skyss',
    'atb',
    'vy',
    'vy tog',
    'vy express',
    'taxi',
    'drosje',
    'bolt',
    'uber',
    'oslo taxi',
    'drivstoff',
    'bensin',
    'diesel',
    'parkering',
    'parkeringshus',
    'bomring',
    'bompenger',
    'autopass',
    'entur',
    'mobilbillett',
    'månedskort',
    'periodebillett',
    'togbillett',
    'flybuss',
    'hurtigbåt',
    'ferje',
    'bysykkel',
    'sparkesykkel',
    'shell',
    'circle k',
    'st1',
    'esso',
    'uno-x',
    'bilverksted',
    'eu-kontroll',
    'dekk',
  ],
  housing: [
    'husleie',
    'leie',
    'boliglån',
    'renter',
    'avdrag',
    'felleskostnader',
    'fellesutgifter',
    'borettslag',
    'sameie',
    'kommunale avgifter',
    'renovasjon',
    'eiendomsskatt',
    'innboforsikring',
    'boligforsikring',
    'møbler',
    'interiør',
    'oppussing',
    'vedlikehold',
    'håndverker',
    'rørlegger',
    'elektriker',
    'maler',
    'tømrer',
  ],
  bills: [
    'strøm',
    'strømregning',
    'elektrisk',
    'hafslund',
    'tibber',
    'fortum',
    'lyse',
    'vann',
    'vannregning',
    'fjernvarme',
    'bredbånd',
    'internett',
    'mobilabonnement',
    'mobilregning',
    'telenor',
    'telia',
    'ice',
    'onecall',
    'chili mobil',
    'canal digital',
    'viaplay',
    'tv 2 play',
    'nrk',
    'forsikring',
    'gjensidige',
    'if forsikring',
    'fremtind',
    'tryg',
    'storebrand',
    'dnb',
    'netflix',
    'spotify',
    'abonnement',
    'regning',
    'faktura',
  ],
  healthcare: [
    'lege',
    'legetime',
    'fastlege',
    'sykehus',
    'legevakt',
    'apotek',
    'legemidler',
    'apotek 1',
    'vitusapotek',
    'boots apotek',
    'medisin',
    'resept',
    'tannlege',
    'optiker',
    'brillesenter',
    'specsavers',
    'synsam',
    'helsetrygd',
    'egenandel',
    'nav',
    'fysioterapi',
    'kiropraktor',
    'psykolog',
    'helsekost',
    'vitaminer',
    'helseforsikring',
  ],
  shopping: [
    'butikk',
    'nettbutikk',
    'handel',
    'ikea',
    'elkjøp',
    'power',
    'netonnet',
    'komplett',
    'g-sport',
    'xxl',
    'h&m',
    'cubus',
    'lindex',
    'dressmann',
    'bik bok',
    'nelly',
    'zalando',
    'finn.no',
    'finn',
    'stadium',
    'intersport',
    'zara',
    'mango',
    'boozt',
    'uniqlo',
    'clas ohlson',
    'biltema',
    'maxbo',
    'byggmakker',
    'jernia',
    'europris',
  ],
  entertainment: [
    'kino',
    'kinobesøk',
    'teater',
    'konsert',
    'museum',
    'sf kino',
    'odeon kino',
    'viaplay',
    'netflix',
    'hbo',
    'amazon prime',
    'spotify',
    'tidal',
    'youtube',
    'twitch',
    'playstation',
    'xbox',
    'steam',
    'nintendo',
    'spill',
    'bowling',
    'biljard',
    'escape room',
    'paintball',
    'festival',
    'arrangement',
    'bilett',
  ],
  education: [
    'skole',
    'skolegang',
    'universitet',
    'høyskole',
    'fagskole',
    'kurs',
    'opplæring',
    'studiestøtte',
    'lånekassen',
    'pensum',
    'skolemateriell',
    'bøker',
    'lærebøker',
    'studiekosten',
    'semesteravgift',
    'workshop',
    'webinar',
    'nettkurs',
    'udemy',
    'coursera',
    'sfo',
    'barnehage',
    'fritidsklubb',
  ],
  pets: [
    'dyr',
    'kjæledyr',
    'hund',
    'katt',
    'veterinær',
    'dyreklinikk',
    'hundemat',
    'kattemat',
    'dyremat',
    'hundesalong',
    'dyrepass',
    'hundepensjonat',
    'dyrebutikk',
    'petshop',
    'dyreforsikring',
    'merking',
    'vaksinasjon',
    'hundeavgift',
    'hundekurs',
  ],
  travel: [
    'ferie',
    'reise',
    'fly',
    'flyreise',
    'flybillett',
    'sas',
    'norwegian air',
    'wizz air',
    'wideroe',
    'hotel',
    'hotell',
    'airbnb',
    'booking.com',
    'expedia',
    'trivago',
    'hurtigruten',
    'cruise',
    'charter',
    'ving',
    'apollo',
    'tui',
    'reiseforsikring',
    'pasport',
    'visum',
    'bagasje',
    'leiebil',
    'hertz',
    'avis',
    'reisebyra',
    'reisebyrå',
    'valuta',
  ],
  fitness: [
    'treningssenter',
    'treningsstudio',
    'trening',
    'gym',
    'sats',
    'evo fitness',
    'fresh fitness',
    '3t',
    'spinning',
    'yoga',
    'pilates',
    'crossfit',
    'løping',
    'sykling',
    'svømming',
    'ski',
    'snowboard',
    'langrenn',
    'fotball',
    'håndball',
    'tennis',
    'squash',
    'klatring',
    'kampsport',
    'dans',
    'gruppetrening',
    'personlig trener',
    'treningsutstyr',
    'protein',
    'kosttilskudd',
  ],
  gifts: [
    'gave',
    'gaver',
    'presang',
    'blomster',
    'interflora',
    'jubileum',
    'bursdag',
    'bryllup',
    'konfirmasjon',
    'dåp',
    'jul',
    'julekort',
    'gavekort',
    'pakke',
    'innpakning',
    'charity',
    'donasjon',
    'innsamling',
  ],
  salary: [
    'lønn',
    'lønning',
    'månedslønn',
    'timelønn',
    'overtid',
    'bonus',
    'utbetaling',
    'honorar',
    'vipps',
    'inntekt',
    'arbeidsinntekt',
    'feriepenger',
    'pensjon',
    'trygd',
    'dagpenger',
    'sykepenger',
    'nav utbetaling',
    'freelance',
    'konsulenthonorar',
    'provisjon',
  ],
  investment: [
    'investering',
    'aksjer',
    'fond',
    'obligasjoner',
    'krypto',
    'bitcoin',
    'ether',
    'dnb',
    'nordnet',
    'sbanken',
    'sparebank',
    'sparing',
    'sparekonto',
    'bsu',
    'ips',
    'aksjesparekonto',
    'ask',
    'utbytte',
    'avkastning',
    'renter',
    'oslo børs',
    'etf',
    'indeksfond',
    'aksjefond',
    'pensjonssparing',
  ],
  refund: [
    'tilbakebetaling',
    'refusjon',
    'kreditering',
    'cashback',
    'tilbakeføring',
    'kompensasjon',
    'erstatning',
    'reklamasjon',
    'returvare',
    'retur',
    'godtgjørelse',
    'utlegg',
    'utleggsrefusjon',
    'reiseregning',
    'skatteoppgjør',
    'skatterefusjon',
  ],
};

export default nb;
