const nl = {
  food: [
    'eten',
    'lunch',
    'diner',
    'ontbijt',
    'snack',
    'café',
    'kroeg',
    'eetcafé',
    'broodje',
    'koffie',
    'stamppot',
    'erwtensoep',
    'bitterballen',
    'kroket',
    'stroopwafel',
    'patatje',
    'frietje',
    'haring',
    'thuisbezorgd',
    'uber eats',
    'just eat',
    'new york pizza',
    'spare rib express',
    'bagels & beans',
    'la place',
    'restaurant',
    'takeaway',
    'bezorging',
    'maaltijd',
    'hapje',
    'drankje',
    'borrel',
    // === Netherlands/BE merchants ===
    'deliveroo',
    "mcdonald's",
    'mcdonalds',
    'burger king',
    'kfc',
    'febo',
    'mora',
    'subway',
    "domino's pizza",
    'pizza hut',
    'bakkerij',
    'broodjeszaak',
    'snackbar',
    'cafetaria',
    'ijssalon',
    'starbucks',
    'coffeecompany',
  ],
  groceries: [
    'supermarkt',
    'albert heijn',
    'ah',
    'jumbo',
    'lidl',
    'aldi',
    'plus supermarkt',
    'coop',
    'dirk',
    'jan linders',
    'boni',
    'spar',
    'picnic',
    'bezorgboodschappen',
    'buurtsuper',
    'bakker',
    'slager',
    'groenteboer',
    'markt',
    'weekmarkt',
    'biologisch',
    'boodschappen',
    // === Netherlands/BE merchants ===
    'colruyt',
    'delhaize',
    'carrefour',
    'okay',
  ],
  transport: [
    'trein',
    'tram',
    'bus',
    'metro',
    'fiets',
    'ov-chipkaart',
    'ov chipkaart',
    'ns',
    'gvb',
    'htm',
    'ret',
    'connexxion',
    'arriva',
    'keolis',
    'taxi',
    'uber',
    'bolt',
    'snorfiets',
    'brommer',
    'parkeren',
    'parkeergarage',
    'benzine',
    'diesel',
    'tankstation',
    'shell',
    'bp',
    'esso',
    'tango',
    'tinq',
    'openbaar vervoer',
    'reiskosten',
    'p+r',
    'veer',
    'tolweg',
    // === Netherlands/BE merchants ===
    'klm',
    'transavia',
    'total',
    'avia',
    'gulf',
    'octa+',
    'free now',
  ],
  housing: [
    'huur',
    'hypotheek',
    'servicekosten',
    'vve',
    'onderhoud',
    'reparatie',
    'woningcorporatie',
    'woningbouwvereniging',
    'appartement',
    'woning',
    'huurder',
    'verhuurder',
    'woninginrichting',
    'meubels',
  ],
  bills: [
    'energie',
    'gas',
    'water',
    'internet',
    'telefoon',
    'eneco',
    'vattenfall',
    'nuon',
    'essent',
    'greenchoice',
    't-mobile',
    'vodafone',
    'kpn',
    'telfort',
    'tele2',
    'ziggo',
    'xs4all',
    'upc',
    'netflix',
    'abonnement',
    'rekening',
    'factuur',
    'verzekering',
    'belasting',
    'gemeentebelasting',
    'automatische incasso',
    // === Netherlands/BE merchants ===
    'odido',
    'proximus',
    'telenet',
    'base',
    'engie',
    'luminus',
  ],
  healthcare: [
    'dokter',
    'huisarts',
    'apotheek',
    'medicijnen',
    'ziekenhuis',
    'tandarts',
    'oogarts',
    'fysiotherapeut',
    'zorgverzekering',
    'eigen risico',
    'verloskundige',
    'etos',
    'da drogist',
    'drogist',
    'zorg',
    'specialist',
    'GGZ',
    'psycholoog',
    // === Netherlands/BE merchants ===
    'kruidvat',
    'mediq apotheek',
    'trekpleister',
  ],
  shopping: [
    'winkel',
    'webshop',
    'bol.com',
    'coolblue',
    'amazon',
    'zalando',
    'ikea',
    'mediamarkt',
    'bcc',
    'h&m',
    'primark',
    'zara',
    'hema',
    'action',
    'zeeman',
    'c&a',
    'kleding',
    'schoenen',
    'elektronica',
    'online bestelling',
    'wehkamp',
    'decathlon nl',
    // === Netherlands/BE merchants ===
    'bijenkorf',
    'blokker',
    'vinted',
    'marktplaats',
    'asos',
    'temu',
    'shein',
  ],
  entertainment: [
    'bioscoop',
    'theater',
    'concert',
    'museum',
    'pathé',
    'vue cinemas',
    'kinepolis',
    'pretpark',
    'efteling',
    'walibi',
    'festival',
    'voorstelling',
    'uitje',
    'bowling',
    'escape room',
    'dierentuin',
    'artis',
    'attractiepark',
    // === Netherlands/BE merchants ===
    'disney+',
    'videoland',
    'hbo max',
    'spotify',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
  ],
  education: [
    'school',
    'universiteit',
    'hbo',
    'wo',
    'bijles',
    'cursus',
    'studiekosten',
    'collegegeld',
    'duo',
    'studie',
    'opleiding',
    'training',
    'leermateriaal',
    'studieboeken',
    'tentamen',
    'examen',
    'mbo',
    'vmbo',
  ],
  pets: [
    'huisdier',
    'dierenarts',
    'dierenwinkel',
    'hond',
    'kat',
    'voer',
    'diervoeding',
    'dierbenodigdheden',
    'trimmen',
    'kennel',
    'dierenasiel',
    'huisdierenverzekering',
    // === Netherlands/BE merchants ===
    'pets place',
    'welkoop',
    'boerenbond',
  ],
  travel: [
    'vakantie',
    'reis',
    'vliegtuig',
    'hotel',
    'schiphol',
    'vliegticket',
    'vlucht',
    'booking.com',
    'airbnb',
    'corendon',
    'tui nl',
    'sunweb',
    'vliegvakantie',
    'cruise',
    'reisorganisatie',
    'paspoort',
    'visum',
    'buitenland',
    'citytrip',
    // === Netherlands/BE merchants ===
    'expedia',
    'ryanair',
    'easyjet',
    'hotels.com',
    'tripadvisor',
  ],
  fitness: [
    'sportschool',
    'gym',
    'fitness',
    'basic-fit',
    'fit for free',
    'sportabonnement',
    'sport',
    'zwembad',
    'tennis',
    'voetbal',
    'yoga',
    'pilates',
    'hardlopen',
    'fietsen',
    'sporten',
    'sportkleding',
    'sportschoenen',
    'intersport',
    'decathlon',
    // === Netherlands/BE merchants ===
    'sportcity',
    'clubsportive',
  ],
  gifts: [
    'cadeau',
    'cadeautje',
    'verjaardag',
    'verjaarsdagscadeau',
    'kerstcadeau',
    'sinterklaas',
    'bloemen',
    'bloemist',
    'chocolade',
    'wijn',
    'wenskaart',
    'cadeaubon',
    'cadeaukaart',
    'donatie',
  ],
  salary: [
    'salaris',
    'loon',
    'nettoloon',
    'salarisstrook',
    'bonus',
    'honorarium',
    'overboeking',
    'inkomen',
    'uitbetaling',
    'loonstrook',
    'netto salaris',
    'bruto salaris',
    'vakantiegeld',
    'dertiende maand',
    'vergoeding',
    'uitkering',
  ],
  investment: [
    'beleggen',
    'belegging',
    'aandelen',
    'obligaties',
    'fondsen',
    'etf',
    'degiro',
    'abn amro',
    'ing beleggen',
    'rabobank beleggen',
    'meesman',
    'brand new day',
    'pensioen',
    'lijfrente',
    'spaarrekening',
    'rente',
    'dividenden',
    'crypto',
    'bitcoin',
  ],
  refund: [
    'terugbetaling',
    'teruggave',
    'terugstorting',
    'cashback',
    'creditnota',
    'restitutie',
    'refund',
    'retour',
    'terugvordering',
    'belastingteruggave',
    'toeslagen',
    'huurtoeslag',
    'zorgtoeslag',
  ],
};

export default nl;
