const pl = {
  food: [
    // General meal terms
    'jedzenie',
    'obiad',
    'kolacja',
    'śniadanie',
    'przekąska',
    'przekąski',
    'drugie śniadanie',
    'podwieczorek',
    'jadłodajnia',
    'stołówka',
    'bufet',
    // Venue types
    'restauracja',
    'restauracje',
    'bar',
    'bistro',
    'bistrot',
    'bar mleczny',
    'pijalnia',
    'piwiarnia',
    'kawiarnia',
    'cukiernia',
    'lodziarnia',
    'piekarnia',
    'grill',
    'grill bar',
    // Drinks
    'kawa',
    'herbata',
    'kompot',
    'sok',
    'napój',
    'napoje',
    'piwo',
    'wino',
    'koktajl',
    'nalewka',
    'wódka',
    'piwo rzemieślnicze',
    'lemoniada',
    'woda mineralna',
    'sok owocowy',
    'smoothie',
    // Polish dishes
    'żurek',
    'bigos',
    'pierogi',
    'gołąbki',
    'kotlet schabowy',
    'żeberka',
    'barszcz',
    'flaki',
    'zapiekanka',
    'naleśniki',
    'pączek',
    'pączki',
    'drożdżówka',
    'drożdżówki',
    'oscypek',
    'kiełbasa',
    'kabanos',
    'kiełbaski',
    'golonka',
    'schab',
    'zupa',
    'rosół',
    'kapuśniak',
    'grochówka',
    'pomidorowa',
    'ogórkowa',
    'fasolowa',
    'kopytka',
    'kluski',
    'kluski śląskie',
    'uszka',
    'kotlet mielony',
    'zrazy',
    'placki ziemniaczane',
    'placki',
    'sałatka',
    'kanapka',
    'tost',
    'jajecznica',
    'jajka',
    'twaróg',
    'śmietana',
    'maślanka',
    'kefir',
    // Delivery services
    'pyszne.pl',
    'pyszne',
    'wolt',
    'glovo',
    // Polish/international chains
    'burger king pl',
    'kfc pl',
    'subway pl',
    'pizza hut pl',
    'telepizza',
    'sphinx',
    'bobby burger',
    'pijalnia wódki i piwa',
    'coffeeheaven',
    'green caffè nero',
    'green caffe nero',
    'tortilla',
    'stop cafe',
    'pijalnia czekolady',
    'blikle',
    'grycan',
    'mati',
    'nordcaffe',
  ],
  groceries: [
    // General
    'sklep',
    'supermarket',
    'hipermarket',
    'delikatesy',
    'warzywniak',
    'mięso',
    'nabiał',
    'warzywa',
    'owoce',
    'chleb',
    'masło',
    'ser',
    'mleko',
    'jajka',
    'mąka',
    'cukier',
    'sól',
    'olej',
    'ocet',
    'makaron',
    'ryż',
    'konserwy',
    'mrożonki',
    // Brands
    'biedronka',
    'lidl',
    'kaufland',
    'aldi',
    'żabka',
    'carrefour',
    'auchan',
    'tesco',
    'netto',
    'spar',
    'eurocash',
    'makro',
    'stokrotka',
    'polomarket',
    'topaz',
    'piotr i paweł',
    'e.leclerc',
    'leclerc',
    'intermarche',
    'intermarché',
    'dino',
    'dino polska',
    'selgros',
    'frisco',
    'frisco.pl',
  ],
  transport: [
    // General
    'autobus',
    'tramwaj',
    'metro',
    'pociąg',
    'taksówka',
    'taksówki',
    'bilet',
    'bilety',
    'bilet miesięczny',
    'komunikacja miejska',
    'transport publiczny',
    'paliwo',
    'benzyna',
    'diesel',
    'stacja paliw',
    'stacja benzynowa',
    'parking',
    'autostrada',
    // Brands & services
    'pkp',
    'pks',
    'ztm',
    'skm',
    'jakdojade',
    'blablacar',
    'bolt taxi',
    'free now',
    'itaxi',
    'orlen',
    'lotos',
    'circle k',
    'moya',
    'amic energy',
    'viatoll',
    'e-toll',
    'etoll',
    'mpk',
    'koleje mazowieckie',
    'koleje śląskie',
    'koleje dolnośląskie',
    'intercity',
    'pendolino',
    'polregio',
    'flixbus',
    'lux express',
    'lotnisko',
    'lot',
    'ryanair',
    'wizz air',
    'wizzair',
    'easyjet',
    'serwis samochodowy',
    'mechanik',
    'warsztat samochodowy',
    'ubezpieczenie oc',
    'ubezpieczenie ac',
    'przegląd techniczny',
    'myjnia samochodowa',
    'holowanie',
  ],
  housing: [
    // Polish-specific
    'czynsz',
    'wynajem',
    'najem',
    'mieszkanie',
    'kredyt hipoteczny',
    'hipoteka',
    'spółdzielnia',
    'wspólnota mieszkaniowa',
    'zarządca nieruchomości',
    'administracja',
    'opłata administracyjna',
    'fundusz remontowy',
    'media',
    'remont',
    'modernizacja',
    'ubezpieczenie mieszkania',
    'podatek od nieruchomości',
    'meble',
    'wyposażenie',
    'sprzęt agd',
    'agd',
    'lodówka',
    'pralka',
    'zmywarka',
    'piekarnik',
    'kuchenka',
    'odkurzacz',
    'klimatyzacja',
    'ogrzewanie',
    'ciepła woda',
    'otodom',
    'gratka',
    'morizon',
    'nieruchomości',
    'dom',
    'blok',
  ],
  bills: [
    // Utilities
    'prąd',
    'gaz',
    'woda',
    'internet',
    'telefon',
    'rachunek',
    'rachunki',
    'opłaty',
    'abonament',
    'subskrypcja',
    'abonament tv',
    'telewizja',
    'kablówka',
    // Utility brands
    'enea',
    'pge',
    'tauron',
    'energa',
    'innogy',
    'e.on',
    'eon',
    'pgnig',
    'polska spółka gazownictwa',
    'mwik',
    'mpwik',
    'mpec',
    // Telecom brands
    'orange',
    'polsat',
    'polsat cyfrowy',
    'upc',
    'play',
    't-mobile',
    'plus',
    'polkomtel',
    'cyfrowy polsat',
    'nc+',
    'canal+',
    // Streaming
    'netflix',
    'disney+',
    'disney plus',
    'hbo max',
    'spotify',
    'apple music',
    'youtube premium',
    'tvn player',
  ],
  healthcare: [
    // General
    'lekarz',
    'doktor',
    'szpital',
    'klinika',
    'apteka',
    'leki',
    'recepta',
    'wizyta',
    'badanie',
    'badania',
    'laboratorium',
    'stomatolog',
    'dentysta',
    'okulista',
    'okulary',
    'soczewki',
    'fizjoterapeuta',
    'rehabilitacja',
    'psychiatra',
    'psycholog',
    'psychoterapeuta',
    'prywatna opieka',
    'prywatna opieka zdrowotna',
    'nfz',
    'składka zdrowotna',
    'ubezpieczenie zdrowotne',
    'pogotowie',
    // Brands
    'apteka różana',
    'dbam o zdrowie',
    'doz apteka',
    'doz',
    'dr max',
    'melissa',
    'medicover',
    'lux med',
    'luxmed',
    'enel-med',
    'pzu zdrowie',
    'polmed',
    'centrum medyczne',
    'falck',
    'cefarm',
  ],
  shopping: [
    // General
    'sklep internetowy',
    'zakupy',
    'odzież',
    'ubrania',
    'buty',
    'obuwie',
    'elektronika',
    'sprzęt',
    'kosmetyki',
    'perfumy',
    'biżuteria',
    'akcesoria',
    // Polish/European brands
    'allegro',
    'olx',
    'zalando',
    'amazon',
    'empik',
    'media markt',
    'rtv euro agd',
    'euro agd',
    'saturn',
    'ikea',
    'reserved',
    'mohito',
    'house',
    'cropp',
    'ccc',
    'deichmann',
    'h&m',
    'zara',
    'stradivarius',
    'pull&bear',
    'bershka',
    'sinsay',
    'tk maxx',
    'pepco',
    'kik',
    'takko',
    'action',
    'jysk',
    'castorama',
    'obi',
    'leroy merlin',
    'bricomarche',
    'agata meble',
    'black red white',
    'brw',
    'neonet',
    'x-kom',
    'xkom',
    'komputronik',
    'mediaexpert',
    'media expert',
    'morele',
    'morele.net',
    'douglas',
    'hebe',
    'rossmann',
    'notino',
  ],
  entertainment: [
    // General
    'kino',
    'teatr',
    'koncert',
    'muzeum',
    'galeria',
    'park rozrywki',
    'escape room',
    'bowling',
    'kręgle',
    'klub',
    'dyskoteka',
    'pub',
    'impreza',
    'festiwal',
    'spektakl',
    'opera',
    'filharmonia',
    'cyrk',
    'zoo',
    'aquapark',
    'wesołe miasteczko',
    'laser tag',
    'karting',
    'gry wideo',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    // Brands
    'multikino',
    'cinema city',
    'helios',
    'imax',
    'bilety24',
    'ticketmaster',
    'eventim',
    'ebilet',
    'going',
    'biletomat',
  ],
  education: [
    // General
    'szkoła',
    'uczelnia',
    'studia',
    'korepetycje',
    'kurs',
    'szkolenie',
    'kurs językowy',
    'kurs online',
    'kurs zawodowy',
    'egzamin',
    'podręcznik',
    'podręczniki',
    'książki',
    'zeszyt',
    'materiały szkolne',
    'czesne',
    'opłata za studia',
    'internat',
    'akademik',
    // Brands
    'duolingo',
    'coursera',
    'udemy',
    'edx',
    'codecademy',
    'oxford',
    'cambridge',
    'pearson',
    'pwn',
    'nowa era',
    'wsip',
  ],
  pets: [
    // General
    'zwierzę',
    'zwierzęta',
    'pies',
    'kot',
    'karma',
    'karma dla psa',
    'karma dla kota',
    'weterynarz',
    'weterynaria',
    'klinika weterynaryjna',
    'lecznica dla zwierząt',
    'szczepienie',
    'szczepionka',
    'schronisko',
    'hodowla',
    'pielęgnacja zwierząt',
    'groomer',
    'toaleta dla psa',
    'obroża',
    'smycz',
    'klatka',
    'akwarium',
    'terrarium',
    'przysmaki',
    'zabawki dla psa',
    'żwirek',
    // Brands
    'zooplus',
    'kakadu',
    'animalia',
    'dolina noteci',
    'brit',
    'royal canin',
    'hills',
    'josera',
    'purina',
    'whiskas',
    'felix',
    'pedigree',
    'eukanuba',
  ],
  travel: [
    // General
    'podróż',
    'podróże',
    'wycieczka',
    'wakacje',
    'urlop',
    'hotel',
    'hostel',
    'pensjonat',
    'apartament wakacyjny',
    'willa',
    'kemping',
    'camping',
    'nocleg',
    'pobyt',
    'rezerwacja',
    'bilet lotniczy',
    'wiza',
    'ubezpieczenie podróżne',
    'wynajem samochodu',
    'transfer lotniskowy',
    'przewodnik',
    'zwiedzanie',
    // Brands
    'booking',
    'booking.com',
    'airbnb',
    'trivago',
    'skyscanner',
    'momondo',
    'kiwi.com',
    'itaka',
    'neckermann',
    'tui',
    'coral travel',
    'exim tours',
    'rainbow tours',
    'ecco holiday',
    'travelplanet',
    'travelist',
    'orbis',
    'accor',
    'marriott',
    'hilton',
    'ibis',
    'novotel',
    'holiday inn',
    'radisson',
  ],
  fitness: [
    // General
    'siłownia',
    'klub fitness',
    'basen',
    'pływalnia',
    'kort tenisowy',
    'squash',
    'joga',
    'yoga',
    'pilates',
    'crossfit',
    'bieganie',
    'rower',
    'trening',
    'trener personalny',
    'personal trainer',
    'treningi',
    'karnet',
    'karnet na siłownię',
    'abonament sportowy',
    'multisport',
    'ok system',
    'medicover sport',
    'odzież sportowa',
    'buty sportowe',
    'sprzęt sportowy',
    'hantle',
    'odżywki',
    'suplementy',
    'odżywka białkowa',
    'protein',
    'dieta',
    'dietetyk',
    // Brands
    'fitness world',
    'fitness platinium',
    'just gym',
    'cityfit',
    'mcfit',
    'planet fitness',
    'anytime fitness',
    'martes sport',
    'intersport',
    'decathlon',
    '4f',
    'reebok',
    'adidas',
    'nike',
    'under armour',
    'salomon',
  ],
  gifts: [
    // General
    'prezent',
    'prezenty',
    'upominek',
    'upominki',
    'darowizna',
    'datki',
    'karta podarunkowa',
    'voucher',
    'bon podarunkowy',
    'zbiórka',
    'zrzutka',
    'kwiaty',
    'bukiet',
    'urodziny',
    'imieniny',
    'ślub',
    'chrzciny',
    'komunia',
    'wesele',
    'rocznica',
    'święta',
    // Brands
    'zrzutka.pl',
    'poczta kwiatowa',
    'euroflorist',
    'interflora',
    'kwiaciarnia',
    'kwiaty.pl',
    'caritas',
    'wosp',
    'wielka orkiestra świątecznej pomocy',
  ],
  salary: [
    // General
    'wynagrodzenie',
    'pensja',
    'przelew',
    'premia',
    'zlecenie',
    'faktura',
    'honorarium',
    'wypłata',
    'zarobki',
    'dochód',
    'przychód',
    'przychody',
    'umowa o pracę',
    'umowa zlecenie',
    'umowa o dzieło',
    'b2b',
    'działalność gospodarcza',
    'samozatrudnienie',
    'dywidenda',
    'renta',
    'emerytura',
    'zasiłek',
    'stypendium',
    'praca dorywcza',
    'praca sezonowa',
    'freelance',
    'prowizja',
    'zaliczka',
  ],
  investment: [
    // General
    'inwestycja',
    'inwestycje',
    'giełda',
    'akcje',
    'obligacje',
    'fundusz',
    'etf',
    'kryptowaluta',
    'bitcoin',
    'ethereum',
    'krypto',
    'lokata',
    'konto oszczędnościowe',
    'oszczędności',
    'odsetki',
    'portfel inwestycyjny',
    'broker',
    'dom maklerski',
    // Brands
    'xtb',
    'bossa',
    'degiro',
    'etoro',
    'interactive brokers',
    'saxo bank',
    'revolut trading',
    'trading 212',
    'coinbase',
    'binance',
    'kraken',
    'bitstamp',
    'zonda',
    'bitbay',
    'ppe',
    'ike',
    'ikze',
    'pzu oszczędności',
    'allianz',
    'aviva',
    'nn invest',
    'skarbiec',
    'union investment',
  ],
  refund: [
    // General
    'zwrot',
    'zwroty',
    'reklamacja',
    'reklamacje',
    'cashback',
    'zwrot pieniędzy',
    'korekta',
    'nadpłata',
    'zwrot podatku',
    'pit zwrot',
    'zwrot nadpłaty',
    'zwrot towaru',
    'wymiana towaru',
    'zwrot vat',
    'refundacja',
    'odszkodowanie',
    'kompensata',
    'przelew zwrotny',
    'nota kredytowa',
    'storno',
    'cofnięcie płatności',
    'anulowanie zamówienia',
  ],
};

export default pl;
