const pt = {
  food: [
    'almoço',
    'jantar',
    'café da manhã',
    'café da tarde',
    'lanche',
    'marmita',
    'quentinha',
    'refeição',
    'comida',
    'comer',
    'bebida',
    'bebidas',
    'açaí',
    'açaí na tigela',
    'pão de queijo',
    'coxinha',
    'pastel',
    'pastelaria',
    'churrasco',
    'espetinho',
    'espeto',
    'feijoada',
    'brigadeiro',
    'pão de mel',
    'empada',
    'enroladinho',
    'caldo',
    'caldo de cana',
    'tapioca',
    'acarajé',
    'moqueca',
    'bauru',
    'frango assado',
    'frango frito',
    'costela',
    'picanha',
    'alcatra',
    'linguiça',
    'mortadela',
    'pernil',
    'torresmo',
    'arroz e feijão',
    'prato feito',
    'pf',
    'self service',
    'kilo',
    'por kilo',
    'por quilo',
    'quilo',
    'buffet livre',
    'rodízio',
    'churrascaria',
    'guaraná',
    'guaraná antarctica',
    'caipirinha',
    'cachaça',
    'pinga',
    'cerveja',
    'chope',
    'chopp',
    'suco',
    'vitamina',
    'água de coco',
    'limonada',
    'maracujá',
    'acerola',
    'cupuaçu',
    'graviola',
    'refrigerante',
    'refri',
    'cafézinho',
    'pingado',
    'nescau',
    "bob's",
    "habib's",
    'spoleto',
    'coco bambu',
    'madero',
    'giraffas',
    'outback br',
    'ragazzo',
    'boi na braza',
    'fogo de chão',
    'paris 6',
    'temakeria',
    'temaki',
    'comida japonesa',
    'japonês',
    'yakissoba',
    'gyoza',
    'hot dog',
    'cachorro quente',
    'churros',
    'bolo de pote',
    'bolo caseiro',
    'brigaderia',
    'sorveteria',
    'açaíteria',
    'padaria',
    'confeitaria',
    'bistrô',
    'boteco',
    'botequim',
    'barzinho',
    'lanchonete',
    'food truck',
    'feira gastronômica',
    'ifood',
    'rappi',
    'rappi food',
    'loggi',
    'james delivery',
    'aiqfome',
    'pedido online',
    'delivery br',
    // === Portugal/Brazil merchants ===
    "mcdonald's",
    'mcdonalds',
    'burger king',
    'kfc',
    'pizza hut',
    "domino's",
    'dominos pizza',
    'subway',
    'starbucks',
    'uber eats',
    'glovo',
    'china in box',
    'telepizza',
    'pastéis de belém',
    'nicola',
    'santini',
    'delta cafés',
    'a padaria portuguesa',
  ],
  groceries: [
    'pão de açúcar',
    'grupo pão de açúcar',
    'gpa',
    'carrefour brasil',
    'extra hipermercado',
    'extra supermercado',
    'mercado extra',
    'big hipermercado',
    'assaí',
    'assaí atacadista',
    'atacadão',
    'hiper bompreço',
    'bompreço',
    'mundial supermercados',
    'rede save',
    'dia supermercado',
    'dia%',
    'sonda supermercados',
    'enxuto',
    'savegnago',
    'condor supermercado',
    'muffato',
    'beal',
    'prezunic',
    'sendas',
    'guanabara',
    'carioca',
    'festval',
    'bistek',
    'hortifruti',
    'sacolão',
    'feira livre',
    'feira',
    'quitanda',
    'mercearia',
    'açougue',
    'peixaria',
    'laticínios',
    'frutaria',
    'verdureiro',
    'legumes',
    'hortaliças',
    'tempero',
    'ervas',
    'cheiro-verde',
    'cebolinha',
    'salsinha',
    'coentro',
    'banha',
    'carne seca',
    'nestlé',
    'sadia',
    'perdigão',
    'seara',
    'friboi',
    'aurora',
    'vigor',
    'itambé',
    'tirol',
    'leite condensado',
    'creme de leite',
    'achocolatado',
    'nescafé',
    'pilão',
    'melitta',
    'três corações',
    'café torrado',
    'café moído',
    'farinha de trigo',
    'farinha de mandioca',
    'farinha de milho',
    'fubá',
    'maizena',
    'feijão',
    'feijão carioca',
    'feijão preto',
    'óleo de soja',
    'azeite',
    'vinagre',
    'molho de pimenta',
    'molho shoyu',
    'ketchup',
    'maionese',
    'mostarda',
    'atacado',
    'compra no atacado',
    // === Portugal/Brazil merchants ===
    'continente',
    'pingo doce',
    'lidl',
    'auchan',
    'mercadona',
    'minipreço',
    'minipreco',
  ],
  transport: [
    '99',
    '99pop',
    '99taxi',
    'indrive br',
    'uber brasil',
    'cabify',
    'blablacar',
    'ônibus',
    'busão',
    'metrô',
    'metrô sp',
    'metrô rio',
    'cptm',
    'sptrans',
    'brt',
    'vlt',
    'trem',
    'trilho',
    'lotação',
    'van escolar',
    'bilhete único',
    'bilhete único mensal',
    'gasolina',
    'gasolina comum',
    'gasolina aditivada',
    'etanol',
    'álcool',
    'flex',
    'gnv',
    'diesel s10',
    'posto',
    'abastecimento',
    'tanque',
    'pedágio',
    'sem parar',
    'conectcar',
    'veloe',
    'move mais',
    'autopass',
    'via fácil',
    'rodovias',
    'autopista',
    'ecovias',
    'centrovias',
    'cart',
    'renovias',
    'sistema anhanguera bandeirantes',
    'anb',
    'via dutra',
    'via lagos',
    'estacionamento',
    'valet',
    'zona azul',
    'mototaxi',
    'motoboy',
    'motofrete',
    'revisão carro',
    'troca de óleo',
    'borracharia',
    'conserto carro',
    'seguro auto',
    'seguro carro',
    'dpvat',
    'ipva',
    'licenciamento',
    'multa de trânsito',
    'gol',
    'gol linhas aéreas',
    'latam brasil',
    'azul linhas aéreas',
    'azul',
    'passagem aérea',
    'passagem',
    'embarque',
    'despacho de bagagem',
    'rodoviária',
    'rodoviário',
    'passagem de ônibus',
    'viação garcia',
    'comfortbus',
    'buser',
    'catarinense',
    'itapemirim',
    'util',
    'penha',
    // === Portugal/Brazil merchants ===
    'uber',
    'via verde',
    'ipiranga',
    'shell',
    'petrobras',
    'galp',
    'prio',
    'tap portugal',
    'tap air portugal',
    'flixbus',
  ],
  housing: [
    'aluguel',
    'aluguel mensal',
    'mensalidade aluguel',
    'condomínio',
    'taxa condominial',
    'fundo de reserva',
    'iptu',
    'escritura',
    'financiamento imobiliário',
    'parcela financiamento',
    'prestação',
    'consórcio imóvel',
    'seguro residencial',
    'seguro fiança',
    'fiança',
    'caução',
    'reforma',
    'obra',
    'pedreiro',
    'pintor',
    'encanador',
    'eletricista',
    'marceneiro',
    'dedetização',
    'dedetizadora',
    'mudança',
    'frete de mudança',
    'república',
    'kitnet',
    'quitinete',
    'cobertura',
    'coworking',
    'casa',
    'apartamento',
    'zap imóveis',
    'viva real',
    'quinto andar',
    'boa moradia',
  ],
  bills: [
    'enel',
    'cemig',
    'light rj',
    'copel',
    'energisa',
    'celpe',
    'coelba',
    'coelce',
    'celg',
    'eletropaulo',
    'cpfl',
    'elektro',
    'equatorial',
    'conta de luz',
    'energia elétrica',
    'sabesp',
    'cedae',
    'sanepar',
    'cagece',
    'caesb',
    'casan',
    'embasa',
    'caema',
    'conta de água',
    'água e esgoto',
    'saneamento',
    'comgas',
    'gás natural',
    'gas br',
    'ultragaz',
    'liquigás',
    'supergasbras',
    'botijão',
    'botijão de gás',
    'gás de cozinha',
    'conta de gás',
    'claro',
    'tim',
    'vivo',
    'oi',
    'nextel',
    'net',
    'claro internet',
    'claro tv',
    'vivo fibra',
    'sky',
    'directv go',
    'plano mensal',
    'plano celular',
    'plano internet',
    'conta de telefone',
    'conta de celular',
    'internet fibra',
    'banda larga',
    'recarga de celular',
    'crédito celular',
    'globoplay',
    'dazn',
    'paramount plus br',
    'star plus',
    'telecine',
    'globo',
    'premiere',
    'sportv',
    'conta de condomínio',
    'boleto',
    'conta a pagar',
    // === Portugal/Brazil merchants ===
    'meo',
    'nos',
    'vodafone',
    'edp',
    'nowo',
  ],
  healthcare: [
    'plano de saúde',
    'plano médico',
    'convênio',
    'convênio médico',
    'consulta médica',
    'consulta particular',
    'pronto-socorro',
    'upa',
    'sus',
    'ubs',
    'posto de saúde',
    'clínica médica',
    'remédio',
    'remédios',
    'medicamento',
    'receita médica',
    'farmácia',
    'drogasil',
    'droga raia',
    'drogaraia',
    'pacheco',
    'ultrafarma',
    'farmácias pague menos',
    'pague menos',
    'dpsp',
    'farmacinha',
    'drogaria araujo',
    'farmácia popular',
    'dentista',
    'odontologia',
    'ortodontia',
    'aparelho dentário',
    'fisioterapia',
    'fisioterapeuta',
    'psicólogo',
    'psicologia',
    'psiquiatra',
    'terapia',
    'nutricionista',
    'fonoaudióloga',
    'exame',
    'exame de sangue',
    'raio x',
    'ultrassom',
    'ressonância',
    'tomografia',
    'mamografia',
    'colonoscopia',
    'vacina',
    'vacinação',
    'suplemento',
    'vitaminas',
    'farmácia de manipulação',
    'unimed',
    'amil',
    'bradesco saúde',
    'sulamerica saúde',
    'hapvida',
    'notredame',
    'intermédica',
    'omint',
    'copagamento',
    'coparticipação',
    // === Portugal/Brazil merchants ===
    'farmácias portuguesas',
    'wells',
  ],
  shopping: [
    'americanas',
    'americanas.com',
    'shoptime',
    'submarino',
    'mercado livre',
    'mercadolivre',
    'magalu',
    'magazine luiza',
    'casas bahia',
    'pontofrio',
    'madeira madeira',
    'leroy merlin br',
    'telhanorte',
    'c&a brasil',
    'renner',
    'riachuelo',
    'hering',
    'zara brasil',
    'centauro',
    'netshoes',
    'kabum',
    'ponto',
    'roupa',
    'roupas',
    'camiseta',
    'calça',
    'bermuda',
    'vestido',
    'blusa',
    'saia',
    'camisa',
    'terno',
    'sapato',
    'sandália',
    'tênis',
    'chinelo',
    'bolsa',
    'carteira',
    'relógio',
    'bijuteria',
    'joia',
    'joalheria',
    'boticário',
    'o boticário',
    'natura',
    'eudora',
    'avon',
    'beleza na web',
    'época cosméticos',
    'quem disse berenice',
    'cuidado pessoal',
    'cabelo',
    'cabeleireiro',
    'salão de beleza',
    'manicure',
    'barbearia',
    'depilação',
    'tok stok',
    'mobly',
    'etna',
    'havan',
    'shopee brasil',
    'ali express brasil',
    'shein brasil',
    'ferramentas',
    'material de construção',
    'shopping center',
    'shopping',
    'center norte',
    'morumbi shopping',
    'iguatemi',
    'eldorado shopping',
    'market place shopping',
    'jk iguatemi',
    'barra shopping',
    'rio sul',
    'pondok indah mall',
    // === Portugal/Brazil merchants ===
    'worten',
    'fnac',
    'el corte inglés',
    'el corte ingles',
    'decathlon',
    'sport zone',
    'ikea',
  ],
  entertainment: [
    'cinema',
    'cinema br',
    'cinemark brasil',
    'cinépolis',
    'kinoplex',
    'cinesystem',
    'ingresso.com',
    'ingresso',
    'show',
    'show ao vivo',
    'forró',
    'samba',
    'pagode',
    'sertanejo',
    'axé',
    'funk',
    'baile funk',
    'festa',
    'balada',
    'boate',
    'teatros',
    'espetáculo',
    'apresentação',
    'festival',
    'carnaval',
    'micareta',
    'festa junina',
    'arraial',
    'parque de diversões',
    'multishow',
    'telecine play',
    'looke',
    'mubi',
    'jogos',
    'jogar',
    'videogame',
    'jogo online',
    'loteria',
    'mega sena',
    'loto fácil',
    'timemania',
    'quina',
    'lotofácil',
    'barzinho',
    'choperia',
    'choperia',
    'cervejaria',
    'happy hour br',
    'petisco',
    'tira-gosto',
    // === Portugal/Brazil merchants ===
    'uci cinemas',
    'nos cinemas',
    'netflix',
    'disney+',
    'disney plus',
    'hbo max',
    'playstation store',
    'xbox live',
    'steam',
  ],
  education: [
    'escola',
    'escola particular',
    'escola pública',
    'colégio',
    'faculdade',
    'universidade',
    'cursinho',
    'cursinho pré-vestibular',
    'pré-vestibular',
    'mensalidade escolar',
    'mensalidade faculdade',
    'anuidade',
    'matrícula',
    'prouni',
    'fies',
    'enem',
    'vestibular',
    'concurso público',
    'concurso',
    'provas',
    'apostila',
    'hotmart',
    'eduzz',
    'kiwify',
    'alura',
    'digitalhouse',
    'rocketseat',
    'descomplica',
    'qconcursos',
    'gran cursos',
    'estratégia concursos',
    'alfacon',
    'wizard',
    'ccaa',
    'cultura inglesa',
    'fisk',
    'inglês',
    'espanhol',
    'material escolar',
    'caderno',
    'mochila',
    'estojo',
    'caneta',
    'lápis',
    'borracha',
    'régua',
    'compasso',
    'calculadora',
    'livro didático',
    'apostilas',
    'certificação',
    'graduação',
    'pós-graduação',
    'mestrado',
    'doutorado',
    'mba',
    'extensão',
  ],
  pets: [
    'animal de estimação',
    'bichinho',
    'pet shop',
    'ração',
    'ração para cachorro',
    'ração para gato',
    'veterinário',
    'clínica veterinária',
    'vacina animal',
    'consulta veterinária',
    'banho e tosa',
    'tosa',
    'petshop',
    'coleira',
    'cama pet',
    'brinquedo pet',
    'areia higiênica',
    'caixa de areia',
    'aquário',
    'gaiola',
    'petz',
    'petlove',
    'cobasi',
    'zee dog',
    'premium',
    'premier',
    'royal canin br',
    'hills br',
    'proplan',
    'pro plan',
    'golden',
    'whiskas br',
    'friskies br',
    // === Portugal/Brazil merchants ===
    'kiwoko',
  ],
  travel: [
    'decolar',
    'decolar.com',
    'submarino viagens',
    'viajanet',
    '123 milhas',
    '123milhas',
    'smiles',
    'tudoazul',
    'multiplus',
    'pousada',
    'hotel fazenda',
    'flat',
    'apart-hotel',
    'hostel',
    'camping',
    'resort br',
    'chalé',
    'casa de praia',
    'casa de temporada',
    'florianópolis',
    'floripa',
    'natal',
    'fortaleza',
    'recife',
    'salvador',
    'porto seguro',
    'maceió',
    'curitiba',
    'gramado',
    'canela',
    'foz do iguaçu',
    'bonito',
    'pantanal',
    'arraial do cabo',
    'búzios',
    'paraty',
    'ilha grande',
    'ilhabela',
    'viagem',
    'férias',
    'passagem',
    'voo',
    'check-in',
    'bagagem',
    'excesso de bagagem',
    'seguro viagem',
    'passeio',
    'excursão',
    'tour',
    'ingresso',
    'museu',
    'parque nacional',
    'ecoturismo',
    // === Portugal/Brazil merchants ===
    'booking.com',
    'airbnb',
    'pestana',
    'ryanair',
    'skyscanner',
  ],
  fitness: [
    'academia',
    'academia de ginástica',
    'mensalidade academia',
    'personal trainer',
    'treinador pessoal',
    'treino',
    'musculação',
    'aeróbica',
    'natação',
    'piscina',
    'judô',
    'capoeira',
    'funcional',
    'corrida',
    'hidroginástica',
    'dança',
    'ballet',
    'balé',
    'ginástica',
    'smartfit',
    'smart fit',
    'bluefit',
    'blue fit',
    'bodytech',
    'bio ritmo',
    'academia de ginástica',
    'total pass',
    'totalpass',
    'triton fitness',
    'whey protein',
    'albumina',
    'hipercalórico',
    'maltodextrina',
    'suplemento esportivo',
    'bcaa br',
    'glutamina',
    'growth',
    'growth supplements',
    // === Portugal/Brazil merchants ===
    'holmes place',
    'fitness hut',
  ],
  gifts: [
    'presente',
    'presentes',
    'aniversário',
    'casamento',
    'chá de bebê',
    'chá de panela',
    'chá de casa nova',
    'maternidade',
    'lista de casamento',
    'convite',
    'lembrancinha',
    'mimo',
    'brindes',
    'flores',
    'arranjo de flores',
    'buquê',
    'doação',
    'doações',
    'gorjeta',
    'gorjeta garçom',
    'contribuição',
    'dia das mães',
    'dia dos pais',
    'dia das crianças',
    'natal br',
    'páscoa',
    'dia dos namorados',
    'dia dos namorados br',
    'dia da mulher',
    'são joão',
    'festas',
    'quermesse',
    'igreja',
    'dízimo',
    'oferta',
    'templo',
    'caridade',
    'americanas presente',
    'cartão presente',
    'vale presente',
    'gifty',
    'cesta de café',
    'cesta básica',
  ],
  salary: [
    'salário',
    'pagamento',
    'renda',
    'rendimento',
    'rendimentos',
    'holerite',
    'contracheque',
    'folha de pagamento',
    'clt',
    'pj',
    'nota fiscal',
    'nf-e',
    'nfse',
    'nfs-e',
    'pró-labore',
    'distribuição de lucros',
    'participação nos lucros',
    'plr',
    'décimo terceiro',
    '13° salário',
    '13 salário',
    'adiantamento',
    'vale',
    'vale alimentação',
    'vale refeição',
    'vale transporte',
    'ajuda de custo',
    'auxílio',
    'auxílio home office',
    'pix',
    'transferência pix',
    'ted',
    'doc',
    'depósito',
    'crédito em conta',
    'freela',
    'freelancer',
    'prestação de serviços',
    'autonomo',
    'autônomo',
    'mei',
    'me',
    'eireli',
    'ltda',
    'bico',
    'renda extra',
    'renda variável',
    'inss',
    'fgts',
    'irpf',
    'imposto de renda',
    'declaração ir',
    'restituição ir',
    'seguro desemprego',
    'abono salarial',
    'pis',
    'pasep',
    'rescisão',
    'indenização',
    'verbas rescisórias',
  ],
  investment: [
    'investimento',
    'aplicação',
    'rendimento',
    'juros',
    'dividendos',
    'lucros',
    'ações',
    'bolsa de valores',
    'bovespa',
    'b3',
    'tesouro direto',
    'tesouro selic',
    'tesouro ipca',
    'tesouro prefixado',
    'cdb',
    'lci',
    'lca',
    'cri',
    'cra',
    'debêntures',
    'fundos imobiliários',
    'fii',
    'fundo de investimento',
    'fundo multimercado',
    'fundo de ações',
    'renda fixa',
    'renda variável',
    'previdência privada',
    'pgbl',
    'vgbl',
    'poupança',
    'criptomoeda',
    'bitcoin br',
    'crypto br',
    'nft',
    'ouro',
    'xp investimentos',
    'xp',
    'rico',
    'rico investimentos',
    'clear',
    'clear investimentos',
    'modal',
    'nuinvest',
    'nu invest',
    'inter invest',
    'banco inter',
    'c6 bank',
    'itaú corretora',
    'bradesco corretora',
    'bb broker',
    'btg pactual',
    'warren',
    'kinvo',
    'magnetis',
    'seguro de vida',
    'previdência',
    'aporte',
    'vencimento',
    'rentabilidade',
  ],
  refund: [
    'reembolso',
    'estorno',
    'devolução',
    'chargeback',
    'cashback br',
    'volta do dinheiro',
    'crédito de volta',
    'ressarcimento',
    'pedido de reembolso',
    'devolução de produto',
    'troca de produto',
    'cancelamento',
    'cancelar pedido',
    'nota de crédito',
    'restituição',
    'restituição do ir',
    'restituição de imposto',
    'crédito tributário',
    'devolução de tributo',
    'cashback nubank',
    'cashback inter',
    'pontos',
    'milhas',
    'smiles br',
    'tudoazul br',
    'livelo',
    'esfera',
    'meliuz',
    'méliuz',
    'ame digital',
    'ame cashback',
    'mercado pontos',
    'clube de vantagens',
    'fidelidade',
    'programa de fidelidade',
    'reembolso de despesas',
    'despesas reembolsáveis',
    'adiantamento para reembolso',
    'relatório de despesas',
  ],
};

export default pt;
