const sv = {
  food: [
    // General meal terms
    'mat',
    'lunch',
    'middag',
    'frukost',
    'fika',
    'mellanmål',
    'kvällsmat',
    'nattvard',
    'smörgås',
    'smörgåsar',
    'macka',
    'mackor',
    'räkmacka',
    // Swedish dishes
    'köttbullar',
    'husmanskost',
    'surströmming',
    'pickad sill',
    'inlagd sill',
    'gravlax',
    'gravad lax',
    'semla',
    'semlor',
    'kanelbulle',
    'kanelbullar',
    'kladdkaka',
    'prinsesstårta',
    'drottningkaka',
    'knäckebröd',
    'pyttipanna',
    'raggmunk',
    'blodpudding',
    'falukorv',
    'prinskorv',
    'leverpaté',
    'smörgåstårta',
    'ostbågar',
    'kroppkakor',
    'lutfisk',
    'janssons frestelse',
    'ärtsoppa',
    'pannkaka',
    'pannkakor',
    'våffla',
    'våfflor',
    'laxpudding',
    'palt',
    'pirog',
    'kåldolmar',
    'toast skagen',
    'brännvin',
    'snaps',
    'glögg',
    'KRAV mat',
    'kravmärkt',
    'ekologisk mat',
    // Café / fika culture
    'kafé',
    'café',
    'kök',
    'konditori',
    'bakelse',
    'fikabröd',
    'tårta',
    'lussekatt',
    'pepparkakor',
    'kardemummabulle',
    'chokladboll',
    'mazarin',
    'dammsugare',
    'biskvi',
    'wienerbröd',
    // Drinks
    'kaffe',
    'te',
    'latte',
    'cappuccino',
    'espresso',
    'americano',
    'flat white',
    'mjölk',
    'juice',
    'saft',
    'öl',
    'vin',
    'cider',
    'lättöl',
    'folköl',
    'läsk',
    'vatten',
    'mineralvatten',
    'energidryck',
    'smoothie',
    // Food delivery
    'foodora',
    'wolt',
    'uber eats se',
    'matleverans',
    'hemkörning',
    // Restaurant brands — Swedish
    'max hamburgare',
    'max burger',
    'sibylla',
    'frasses',
    'clock',
    'espresso house',
    "wayne's coffee",
    'waynes coffee',
    'pressbyrån',
    'pressbyran',
    'hesburger',
    '7-eleven se',
    // Restaurant brands — global (Swedish context)
    'mcdonalds',
    "mcdonald's",
    'burger king',
    'subway',
    'pizza hut',
    'dominos',
    'kfc',
    'nandos',
    "nando's",
    'five guys',
    'taco bar',
    'leos lekland',
    // Grocery / deli counter
    'charkuteri',
    'delikatessdisk',
    'saluhall',
    'östermalms saluhall',
    'hötorgshallen',
    // Bahasa context already in core; Swedish additions
    'restaurang',
    'matställe',
    'uteservering',
    'hämtmat',
    'take away',
    'baguette',
    'croissant',
    'frukostbuffé',
    'lunchbuffé',
    'dagens lunch',
    'dagens rätt',
  ],
  groceries: [
    // General
    'mataffär',
    'matbutik',
    'dagligvaror',
    'daglivs',
    'livsmedel',
    'livsmedelsbutik',
    'ekologisk',
    'eko',
    'kravmärkt',
    'närodlat',
    'frukt',
    'grönt',
    'grönsaker',
    'kött',
    'fisk',
    'bröd',
    'mejeri',
    'mejeriprodukter',
    'mjölk',
    'smör',
    'ost',
    'ägg',
    'yoghurt',
    'filmjölk',
    'fil',
    'grädde',
    'glass',
    'glass och godis',
    'godis',
    'snacks',
    'chips',
    'ris',
    'pasta',
    'nudlar',
    'mjöl',
    'socker',
    'salt',
    'olja',
    'kryddor',
    'konserver',
    'fryst',
    'frysmat',
    'charkuterivaror',
    'påläggsmat',
    'pålägg',
    // Brands — Swedish grocery chains
    'ica',
    'ica maxi',
    'ica supermarket',
    'ica nära',
    'ica kvantum',
    'ica torget',
    'coop',
    'coop extra',
    'coop forum',
    'hemköp',
    'willys',
    'lidl',
    'netto',
    'axfood',
    'citygross',
    'city gross',
    'tempo',
    'mathem',
    'matsmart',
    // Online grocery delivery
    'kolonial',
    'linas matkasse',
    'godare',
    'middagsfrid',
    // Global brands present in Sweden
    'tesco',
    'aldi',
    'amazon fresh',
  ],
  transport: [
    // General Swedish transit terms
    'buss',
    'tunnelbana',
    'tbana',
    't-bana',
    'spårvagn',
    'spårväg',
    'pendeltåg',
    'tåg',
    'taxi',
    'flyg',
    'flygbiljett',
    'kollektivtrafik',
    'biljeett',
    'biljett',
    'månadskort',
    'periodbiljett',
    'reskassa',
    'resekonto',
    'sl-kort',
    'sl kort',
    'trängselskatt',
    'congestion',
    'bensin',
    'diesel',
    'parkering',
    'parkeringsavgift',
    'parkeringsböter',
    'p-böter',
    'p-hus',
    'p-plats',
    'laddning',
    'laddstation',
    'elfordon',
    'elbil',
    'körkort',
    'fordonsskatt',
    'bilförsäkring',
    'bilservice',
    'däckbyte',
    'däck',
    'besiktning',
    'bilreparation',
    'verkstad',
    'vinterdäck',
    'sommardäck',
    // Swedish transit operators
    'sl',
    'stockholms lokaltrafik',
    'västtrafik',
    'skånetrafiken',
    'mälardalstrafik',
    'mtr express',
    'snälltåget',
    'vy tåg',
    'vy',
    'sj',
    'sj ab',
    'sj prio',
    'arlanda express',
    'arlandaexpress',
    'flixbus',
    'flygbussarna',
    'express',
    'swebus',
    // Taxi / rideshare in Sweden
    'uber se',
    'bolt sweden',
    'cabonline',
    'taxi stockholm',
    'taxi göteborg',
    'taxikurir',
    'mytaxi',
    'free now',
    // Fuel / petrol in Sweden
    'ok-q8',
    'okq8',
    'st1',
    'preem',
    'circle k',
    'ingo',
    'shell se',
    // Airlines operating in Sweden
    'sas',
    'scandinavian airlines',
    'norwegian',
    'ryanair se',
    'wizz air',
    'klm se',
    'lufthansa se',
    'british airways se',
    // Payment for transit
    'swish betalning transport',
    'månadsrabatt',
  ],
  housing: [
    // Swedish housing terms
    'hyra',
    'hyresrätt',
    'bostadsrätt',
    'avgift',
    'bostadsrättsavgift',
    'månadsavgift',
    'arrende',
    'villa',
    'radhus',
    'äganderätt',
    'bostadslån',
    'bolån',
    'amortering',
    'ränta bolån',
    'kontantinsats',
    'lagfart',
    'pantbrev',
    'fastighetsavgift',
    'fastighetsskatt',
    'tomträttsavgäld',
    'samfällighetsavgift',
    'brf avgift',
    'hyresvärd',
    'hyresgäst',
    'hyreskontrakt',
    'deposition',
    'handpenning',
    'flytt',
    'flyttstädning',
    'hemförsäkring',
    'villaförsäkring',
    'villa försäkring',
    'brandförsäkring',
    'underhåll',
    'reparation',
    'renovering',
    'ombyggnad',
    'el-installation',
    'vvs',
    'rörmokare',
    'elektriker',
    'snickare',
    'målare',
    'tapetsering',
    'golv',
    'kök renovering',
    'badrum renovering',
    'möbler',
    'vitvaror',
    'kylskåp',
    'tvättmaskin',
    'diskmaskin',
    'ugn',
    'spis',
    'mikrovågsugn',
    'fläkt',
    'ventilation',
    // Swedish housing platforms/services
    'hemnet',
    'booli',
    'blocket bostad',
    'riksbyggen',
    'hsb',
    'sabo',
    'stena fastigheter',
    'heimstaden',
    'willhem',
  ],
  bills: [
    // Swedish utility terms
    'el',
    'elkostnad',
    'elräkning',
    'elförbrukning',
    'elpris',
    'vatten',
    'vattenräkning',
    'fjärrvärme',
    'värmekostnad',
    'värme',
    'naturgas',
    'gasräkning',
    'bredband',
    'internet',
    'fiber',
    'mobilabonnemang',
    'telefonabonnemang',
    'abonnemang',
    'månadsavgift',
    'räkning',
    'faktura',
    'autogiro',
    'försäkring',
    'hemförsäkring',
    // Swedish energy providers
    'vattenfall',
    'fortum',
    'eon',
    'e.on',
    'tibber',
    'bixia',
    'telge energi',
    'gothnet',
    'skellefteå kraft',
    'jämtkraft',
    'borlänge energi',
    // Swedish telco
    'telia',
    'tele2',
    'telenor',
    'tre',
    '3 sverige',
    'comviq',
    'halebop',
    'hallon',
    'vimla',
    'lycamobile',
    'fello',
    'voi',
    // Swedish broadband
    'bredbandsbolaget',
    'bahnhof',
    'allente',
    'com hem',
    'comhem',
    'canal digital',
    // Streaming services (Swedish context)
    'viaplay',
    'c more',
    'svt play',
    'tv4 play',
    'discoveryplus',
    'discovery+',
    'nent',
    'tv3 play',
    'viafree',
    'filmnet',
    'sf anytime',
    'sfanytime',
    'nordic entertainer',
    'storytel',
    'nextory',
    'bookbeat',
    'spotify',
    'netflix',
    'hbo nordic',
    'paramount plus',
    'disney plus',
    'apple tv',
    // Municipal fees
    'sophämtning',
    'sophantering',
    'avfallsavgift',
    'renhållning',
    'va-avgift',
    'vatten och avlopp',
    'avlopp',
    'skorstensfejaravgift',
    'kommunal avgift',
  ],
  healthcare: [
    // Swedish healthcare terms
    'läkare',
    'läkarbesök',
    'sjukhus',
    'vårdcentral',
    'husläkare',
    'distriktsläkare',
    'specialist',
    'akutmottagning',
    'akuten',
    'operation',
    'sjukhusvård',
    'sjukvård',
    'vård',
    'sjukdom',
    'sjukskrivning',
    'rehabilitering',
    'sjukgymnast',
    'fysioterapeut',
    'psykolog',
    'psykoterapeut',
    'kurator',
    'undersökning',
    'blodprov',
    'röntgen',
    'ultraljud',
    'vaccination',
    'vaccin',
    'hörapparat',
    'glasögon',
    'linser',
    'tandläkare',
    'tandvård',
    'ortoped',
    'optiker',
    'syntest',
    // Swedish healthcare fees / insurance
    'patientavgift',
    'vårdavgift',
    'besöksavgift',
    'egenavgift',
    'frikort',
    'högkostnadsskydd',
    'förskrivning',
    'recept',
    'sjukkassan',
    'försäkringskassan',
    'fk',
    'sjukpenning',
    'sjukersättning',
    'privat sjukvård',
    'privat sjukvårdsförsäkring',
    // Swedish pharmacies
    'apotek',
    'apoteket',
    'apoteksgruppen',
    'apotek hjärtat',
    'apotek hjartat',
    'kronans apotek',
    'kronans droghandel',
    'lloyds apotek',
    'läkemedel',
    'medicin',
    'receptfritt',
    'värktabletter',
    'antibiotiika',
    'antibiotika',
    'hostmedicin',
    'näsdroppar',
    'ögondroppar',
    'salva',
    'plåster',
    'bandage',
    'första hjälpen',
    'vitaminer',
    'kosttillskott',
  ],
  shopping: [
    // Swedish general shopping
    'butik',
    'affär',
    'köpcenter',
    'galleria',
    'näthandel',
    'nätköp',
    'onlineköp',
    'e-handel',
    'beställning',
    'kläder',
    'skor',
    'väska',
    'accessoarer',
    'smycken',
    'klocka',
    'elektronik',
    'dator',
    'mobil',
    'tablet',
    // Swedish retail brands
    'ikea',
    'ikea se',
    'elgiganten',
    'netonnet',
    'net on net',
    'mediamarkt',
    'media markt',
    'webhallen',
    'komplett',
    'komplett se',
    'dustin',
    'clasohlson',
    'clas ohlson',
    'biltema',
    'jula',
    'jysk',
    'stadium',
    'intersport',
    'team sportia',
    'outnorth',
    'naturkompaniet',
    'haglöfs',
    'fjällräven',
    'fjallraven',
    'peak performance',
    'hm',
    'h&m',
    'lindex',
    'kappahl',
    'åhlens',
    'ahlens',
    'weekday',
    'arket',
    'cos',
    'monki',
    'filippa k',
    'acne studios',
    'tiger of sweden',
    'gant',
    'odd molly',
    'nk',
    'nordiska kompaniet',
    'kicks',
    'lyko',
    'mq',
    'cubus',
    'dressmann',
    'nelly',
    'nelly.com',
    'bubbleroom',
    'kidsbrandstore',
    'babyshop',
    'hemtex',
    'cervera',
    'royal design',
    'designtorget',
    // Global brands in Swedish context
    'zalando',
    'amazon se',
    'boozt',
    'booztlet',
    'johnells',
    'brothers',
    'jack and jones',
    'only',
    'vero moda',
    'zara',
    'uniqlo se',
    'primark se',
  ],
  entertainment: [
    // Swedish entertainment
    'bio',
    'biobiljett',
    'filmstaden',
    'sf bio',
    'biografen',
    'teater',
    'teaterbesök',
    'opera',
    'konserthus',
    'konsert',
    'museum',
    'utställning',
    'nöjespark',
    'leos lekland',
    'gröna lund',
    'liseberg',
    'furuvik',
    'skansen',
    'djurpark',
    'kolmårdens djurpark',
    'kolmården',
    'furuviksparken',
    'aqua park',
    'badland',
    'bowling',
    'bowlinghall',
    'spel',
    'spelkväll',
    'escape room',
    'paintball',
    'laserquest',
    'laser',
    'minigolf',
    'golf',
    'restaurang kvällskul',
    'nattklubbb',
    'nattklubb',
    'bar',
    'pub',
    'nöjesfält',
    'evenemang',
    'event',
    'festival',
    'musikfestival',
    'sommarnöje',
    'cirkus',
    'varieté',
    'stand-up',
    'stand up',
    'comedy',
    'karaoke',
    'spelautomat',
    'kasino',
    'lotteri',
    'bingo',
    // Streaming / digital (Swedish context)
    'storytel',
    'nextory',
    'spotify',
    'viaplay',
    'c more',
    'svt play',
    'tv4 play',
    // Gaming
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    'spelkonsol',
    'datorspel',
    'mobilspel',
  ],
  education: [
    // Swedish education terms
    'skola',
    'skolan',
    'gymnasiet',
    'gymnasium',
    'grundskola',
    'förskola',
    'dagis',
    'fritids',
    'fritidsklubb',
    'universitet',
    'högskola',
    'folkhögskola',
    'yrkeshögskola',
    'komvux',
    'vuxenutbildning',
    'sfi',
    'svenska för invandrare',
    'kurs',
    'kurslitteratur',
    'lärobok',
    'böcker',
    'studielån',
    'csn',
    'studiestöd',
    'studiemedel',
    'bidrag csn',
    'terminsavgift',
    'skolavgift',
    'kursavgift',
    'studieplan',
    'distansutbildning',
    'nätbaserad utbildning',
    'online kurs',
    'e-learning',
    'coursera',
    'udemy',
    'certifikat',
    'examen',
    'diplomkurs',
    'praktik',
    'stipendium',
    'skolbok',
    'miniräknare',
    'skrivmateriel',
    'papper',
    'pennor',
    'ryggsäck',
    'skolmat',
    'matsedel',
    'skolavgifter',
    // Swedish education institutions
    'ki',
    'karolinska',
    'kth',
    'su',
    'stockholms universitet',
    'uu',
    'uppsala universitet',
    'gu',
    'göteborgs universitet',
    'lu',
    'lunds universitet',
    'chalmers',
    'linköpings universitet',
    'liu',
    'umeå universitet',
    'umu',
    'örebro universitet',
  ],
  pets: [
    // Swedish pet terms
    'husdjur',
    'hund',
    'katt',
    'hundfoder',
    'kattfoder',
    'djurfoder',
    'foder',
    'veterinär',
    'veterinärklinik',
    'djurklinik',
    'djursjukhus',
    'djurförsäkring',
    'hundförsäkring',
    'kattförsäkring',
    'veterinärbesök',
    'vaccination djur',
    'chip husdjur',
    'chipning',
    'öronmärkning',
    'löplina',
    'koppel',
    'halsband',
    'hundkorg',
    'kattsäng',
    'klösträd',
    'kattlåda',
    'kattgrus',
    'djuraffär',
    'zoobutik',
    'zoohandel',
    'dog park',
    'hundpark',
    'hundtrim',
    'grooming',
    'hundpensionat',
    'kattpassning',
    'djurpassning',
    'hundskola',
    'djurleksaker',
    // Swedish pet store brands
    'djurmagazinet',
    'granngården',
    'agria',
    'agria djurförsäkring',
    'folksam djur',
    'if djurförsäkring',
  ],
  travel: [
    // Swedish travel terms
    'resa',
    'resor',
    'semesterresa',
    'semester',
    'utlandsresa',
    'utomlands',
    'paketresa',
    'sällskapsresa',
    'kryssning',
    'biljett',
    'flygbiljett',
    'tågbiljett',
    'busskort',
    'färja',
    'passagerarfärja',
    'hotell',
    'hotellrum',
    'hotellbokning',
    'övernattning',
    'vandrarhem',
    'airbnb',
    'camping',
    'campingplats',
    'stuga',
    'cottege',
    'stuguthyrning',
    'fjällstuga',
    'skidresa',
    'skidresort',
    'skidliftkort',
    'skipass',
    'liftkort',
    'charterresa',
    'charter',
    'solresort',
    'solsemester',
    'sightseeeing',
    'sightseeing',
    'guidetur',
    'dagstur',
    'utflykt',
    'reseförsäkring',
    'visum',
    'pass',
    'respass',
    'transfer',
    'flygplats',
    'arlanda',
    'landvetter',
    'bromma',
    'sturup',
    'kiruna flygplats',
    'valutaväxling',
    'valuta',
    'växelkurs',
    // Swedish travel booking platforms
    'ving',
    'apollo',
    'tui',
    'fritidsresor',
    'tickets.se',
    'tripwell',
    'sj prio',
    'sj',
    'booking.com se',
    'expedia se',
    'hotels.com se',
    'tripadvisor',
    'klarna resor',
    // Hotels in Sweden
    'scandic',
    'scandic hotels',
    'radisson',
    'elite hotels',
    'clarion',
    'quality hotel',
    'best western se',
    'nordic choice',
    'strawberry hotels',
    'nordic hotels',
    'city hotel',
  ],
  fitness: [
    // Swedish fitness terms
    'gym',
    'träning',
    'träna',
    'träningskort',
    'gymkort',
    'gymmedlemskap',
    'gymavgift',
    'fitness',
    'workout',
    'styrketräning',
    'konditionsträning',
    'löpning',
    'cykling',
    'spinning',
    'yoga',
    'pilates',
    'aerobics',
    'zumba',
    'crossfit',
    'crossfit klass',
    'löparskor',
    'träningsskor',
    'träningskläder',
    'gymkläder',
    'sportutrustning',
    'träningsutrustning',
    'hantel',
    'skivstång',
    'proteinpulver',
    'kosttillskott',
    'kreatin',
    'simning',
    'simkort',
    'simsällskap',
    'simhall',
    'badhus',
    'badhusavgift',
    'friidrott',
    'fotboll',
    'tennis',
    'squash',
    'padel',
    'padelbana',
    'innebandy',
    'hockey',
    'ishockeyträning',
    'ridning',
    'ridskola',
    'ridtur',
    // Swedish gym chains
    'sats',
    'sats fitness',
    'nordic wellness',
    'friskis och svettis',
    'friskis & svettis',
    'actic',
    'evo fitness',
    'bodycontact',
    'fitness24seven',
    '24 seven fitness',
    'pure gym se',
    'my gym',
    'formtech',
    'friskvård',
    'friskvårdsbidrag',
    'friskvårdsersättning',
  ],
  gifts: [
    // Swedish gift terms
    'present',
    'gåva',
    'julklapp',
    'julklappar',
    'födelsedag',
    'födelsdagspresent',
    'namnsdag',
    'bröllop',
    'bröllopsgåva',
    'student',
    'studentpresent',
    'konfirmation',
    'dopgåva',
    'blomma',
    'blommor',
    'blomsteraffär',
    'blomsterhandlare',
    'choklad',
    'pralin',
    'chokladask',
    'presentkort',
    'presentkortt',
    'välkomstpresent',
    'minnesgåva',
    'sorgeblommor',
    'krans',
    'kondoleans',
    'välgörenhet',
    'donation',
    'insamling',
    'välgörenhetsorganisation',
    'swisha till',
    'kollekt',
    'rädda barnen',
    'unicef',
    'röda korset',
    'frälsningsarmen',
    'cancerfonden',
    'hjärtfonden',
    'WWF',
    'naturskyddsföreningen',
    'doctors without borders',
    'läkare utan gränser',
    // Gift wrapping / cards
    'presentpapper',
    'presentinslagning',
    'gratulationskort',
    'kort',
    'vykortt',
    'vykort',
  ],
  salary: [
    // Swedish salary / income terms
    'lön',
    'lönebetalning',
    'månadslön',
    'timlön',
    'veckolön',
    'dagslön',
    'övertid',
    'övertidslön',
    'bonus',
    'utbetalning',
    'löneutbetalning',
    'arvode',
    'honorar',
    'konsultarvode',
    'frilanskonsult',
    'frilansarvode',
    'uppdragsersättning',
    'projektarvode',
    'sjuklön',
    'föräldrapenning',
    'foraldrapenning',
    'vab',
    'VAB',
    'barnbidrag',
    'bostadsbidrag',
    'aktivitetsstöd',
    'a-kassa',
    'akassa',
    'försörjningsstöd',
    'studiebidrag',
    'rot-avdrag',
    'rut-avdrag',
    'skatteåterbäring',
    'skatteåterbärring',
    'skatteverket',
    'swish lön',
    'bg lön',
    'bankgiro lön',
    // Payroll providers
    'visma',
    'hogia',
    'agilon',
    'fortnox lön',
  ],
  investment: [
    // Swedish investment terms
    'aktier',
    'aktie',
    'aktieinvestering',
    'aktiefond',
    'fond',
    'fonder',
    'fondandelar',
    'räntefond',
    'indexfond',
    'ETF',
    'etf',
    'obligation',
    'obligationer',
    'sparande',
    'spara',
    'sparkonto',
    'ISK',
    'isk konto',
    'investeringssparkonto',
    'kapitalförsäkring',
    'KF',
    'pension',
    'pensionssparande',
    'tjänstepension',
    'IPS',
    'PPM',
    'premiepension',
    'AP-fond',
    'kryptovaluta',
    'bitcoin',
    'krypto',
    'investering',
    'kapital',
    'avkastning',
    'utdelning',
    'direktavkastning',
    'portfölj',
    'courtagefri',
    'courtage',
    'fondavgift',
    'förvaltningsavgift',
    // Swedish brokers and investment platforms
    'avanza',
    'nordnet',
    'swedbank aktier',
    'handelsbanken fond',
    'seb invest',
    'länsförsäkringar bank',
    'skandia',
    'folksam',
    'sjunde ap-fonden',
    'lysa',
    'opti',
    'nordea invest',
    'carnegie fonder',
    'spiltan fonder',
    'simplivity',
    'savr',
    'etoro se',
    'degiro se',
    'saxo bank se',
    'robinhood se',
    'klarna invest',
    'stabelo',
    'hoist finance',
  ],
  refund: [
    // Swedish refund terms
    'återbetalning',
    'återbetalas',
    'återbetald',
    'tillbaka pengarna',
    'pengarna tillbaka',
    'återköp',
    'returnera',
    'returnerat',
    'returnering',
    'lämna tillbaka',
    'bytesrätt',
    'reklamation',
    'reklamera',
    'reklamerat',
    'garanti',
    'garantiärende',
    'cashback',
    'rabatt',
    'rabattkod',
    'kompensation',
    'ersättning',
    'gottgörelse',
    'kreditnota',
    'kreditfaktura',
    'avbeställning',
    'avbokning',
    'avbokningsersättning',
    'avbeställningsersättning',
    'annullering',
    'avbrutna',
    'inställt',
    'inställd resa',
    'skatteåterbäring',
    'överskjutande skatt',
    'återbäring',
    'bonusåterbäring',
    'lojalitetspoäng',
    'trohetsbonus',
    'poäng inlösning',
    'coop-återbäring',
    'ica-återbäring',
    'hemköp-poäng',
    'feldebiterat',
    'felaktigt debiterat',
    'dubbeldebiterat',
    'rättelse',
    'korrigering',
    'kreditering',
    'swish tillbaka',
    'övertrasseringsersättning',
  ],
};

export default sv;
