const tr = {
  food: [
    'yemek',
    'öğle yemeği',
    'akşam yemeği',
    'kahvaltı',
    'atıştırmalık',
    'lokanta',
    'kebap',
    'döner',
    'lahmacun',
    'pide',
    'mantı',
    'köfte',
    'börek',
    'simit',
    'poğaça',
    'baklava',
    'künefe',
    'çay',
    'kahve',
    'türk kahvesi',
    'ayran',
    'çorba',
    'rakı',
    'meyhane',
    'yemeksepeti',
    'getir',
    'trendyol yemek',
    'burger king',
    'kfc',
    'kahve dünyası',
    'simit sarayı',
    'fast food',
    'sokak yemeği',
    'tabldot',
    'öğün',
    'kahvehane',
    'pastane',
    'tatlı',
    'dürüm',
    'şiş',
    'adana',
    'urfa',
    'iskender',
    'patlıcan',
    'hummus',
    'meze',
    'izgara',
  ],
  groceries: [
    'market',
    'süpermarket',
    'migros',
    'bim',
    'a101',
    'şok',
    'carrefoursa',
    'metro',
    'kipa',
    'makromarket',
    'hakmar',
    'onur market',
    'pazar',
    'semt pazarı',
    'manav',
    'kasap',
    'bakkal',
    'fırın',
    'esnaf',
    'gıda',
    'market alışverişi',
    'ekmek',
    'süt',
    'meyve',
    'sebze',
    'et',
    'tavuk',
    'balık',
    'peynir',
    'yoğurt',
    'yumurta',
    'zeytin',
    'zeytinyağı',
    'un',
    'şeker',
    'tuz',
    'makarna',
    'pirinç',
    'temizlik ürünü',
  ],
  transport: [
    'otobüs',
    'metro',
    'metrobüs',
    'tramvay',
    'dolmuş',
    'taksi',
    'minibüs',
    'tren',
    'tcdd',
    'marmaray',
    'başkentray',
    'istanbul kart',
    'ankara kart',
    'kentkart',
    'hgs',
    'ogs',
    'kgs',
    'yakıt',
    'benzin',
    'motorin',
    'park ücreti',
    'otopark',
    'opet',
    'petrol ofisi',
    'shell',
    'bp',
    'total',
    'uçak',
    'thy',
    'türk hava yolları',
    'pegasus',
    'anadolujet',
    'sunexpress',
    'uber',
    'bitaksi',
    'marti',
    'toplu taşıma',
    'vapur',
    'feribot',
    'otoyol',
    'araç kiralama',
    'tamirhane',
    'lastik',
    'servis',
    'muayene',
  ],
  housing: [
    'kira',
    'ev kirası',
    'aidat',
    'site aidatı',
    'yönetim',
    'emlak',
    'konut',
    'daire',
    'apartman',
    'taşınma',
    'nakliyat',
    'mobilya',
    'dekorasyon',
    'tadilat',
    'boya',
    'badana',
    'tesisatçı',
    'elektrikçi',
    'tamirci',
    'depozito',
    'ipotek',
    'konut kredisi',
    'ev kredisi',
  ],
  bills: [
    'elektrik',
    'su',
    'doğalgaz',
    'internet',
    'telefon',
    'fatura',
    'tedaş',
    'botaş',
    'türk telekom',
    'turkcell',
    'vodafone',
    'türksat',
    'd-smart',
    'abonelik',
    'sigorta',
    'kasko',
    'trafik sigortası',
    'sağlık sigortası',
    'vergi',
    'belediye vergisi',
    'emlak vergisi',
    'netflix',
    'spotify',
    'youtube premium',
    'disney+',
    'exxen',
    'gain tv',
    'blutv',
    'tabii',
    'dijital platform',
  ],
  healthcare: [
    'doktor',
    'hastane',
    'eczane',
    'ilaç',
    'poliklinik',
    'sağlık',
    'sgk',
    'muayene',
    'diş doktoru',
    'diş hekimi',
    'göz doktoru',
    'gözlük',
    'acıbadem',
    'medical park',
    'medicana',
    'özel hastane',
    'devlet hastanesi',
    'aile hekimi',
    'psikolog',
    'psikiyatrist',
    'fizyoterapi',
    'ameliyat',
    'tahlil',
    'röntgen',
    'mri',
    'ultrason',
    'reçete',
    'vitamin',
    'medikal malzeme',
  ],
  shopping: [
    'alışveriş',
    'mağaza',
    'trendyol',
    'hepsiburada',
    'n11',
    'gittigidiyor',
    'amazon',
    'ikea',
    'mediamarkt',
    'teknosa',
    'arçelik',
    'vestel',
    'zara',
    'h&m',
    'lcwaikiki',
    'defacto',
    'koton',
    'mavi',
    'ipekyol',
    'beymen',
    'vakko',
    'boyner',
    'yargıcı',
    'english home',
    'karaca',
    'kigili',
    'adidas tr',
    'nike tr',
    'flo',
    'elektronik',
    'telefon',
    'bilgisayar',
    'tablet',
  ],
  entertainment: [
    'sinema',
    'tiyatro',
    'konser',
    'müze',
    'lunapark',
    'eğlence',
    'oyun',
    'oyun salonu',
    'bowling',
    'bilardo',
    'kaçış odası',
    'akvaryum',
    'hayvanat bahçesi',
    'tema parkı',
    'aquapark',
    'bilet',
    'gece kulübü',
    'bar',
    'pub',
    'nargile',
    'karaoke',
    'avm',
    'oyun konsolu',
    'steam',
    'playstation',
    'xbox',
  ],
  education: [
    'okul',
    'üniversite',
    'dershane',
    'özel ders',
    'kurs',
    'sınav',
    'meb',
    'burs',
    'harç',
    'kayıt ücreti',
    'kitap',
    'ders kitabı',
    'kırtasiye',
    'online kurs',
    'udemy',
    'coursera',
    'İngilizce kursu',
    'yabancı dil',
    'ösym',
    'yks',
    'kpss',
    'toefl',
    'ielts',
    'dil okulu',
    'okul forması',
  ],
  pets: [
    'evcil hayvan',
    'köpek',
    'kedi',
    'kuş',
    'balık',
    'veteriner',
    'pet shop',
    'mama',
    'köpek maması',
    'kedi maması',
    'pet market',
    'tasma',
    'kafes',
    'akvaryum malzeme',
    'tımar',
    'banyolama',
    'aşı',
    'hayvan hastanesi',
    'pet otel',
    'köpek eğitimi',
  ],
  travel: [
    'otel',
    'tatil',
    'seyahat',
    'uçak bileti',
    'thy',
    'pegasus',
    'vize',
    'pasaport',
    'hostel',
    'pansiyon',
    'booking',
    'trivago',
    'jolly',
    'tatilsepeti',
    'enuygun',
    'obilet',
    'etstur',
    'airbnb',
    'tur',
    'gezi',
    'turizm',
    'rehber',
    'karayolu',
    'otobüs bileti',
    'tren bileti',
    'feribot bileti',
    'araç kiralama tatil',
    'seyahat sigortası',
    'valiz',
  ],
  fitness: [
    'spor',
    'spor salonu',
    'gym',
    'fitness',
    'pilates',
    'yoga',
    'yüzme',
    'tenis',
    'basketbol',
    'futbol',
    'voleybol',
    'koşu',
    'bisiklet',
    'crossfit',
    'zumba',
    'aerobik',
    'dans kursu',
    'boks',
    'kickboks',
    'muay thai',
    'jiujitsu',
    'spor ürünleri',
    'spor giyim',
    'protein',
    'supplement',
    'personal trainer',
    'kişisel antrenör',
    'spor kulübü üyelik',
  ],
  gifts: [
    'hediye',
    'doğum günü hediyesi',
    'düğün hediyesi',
    'çiçek',
    'çiçekçi',
    'çikolata',
    'kutlama',
    'tebrik',
    'paket',
    'hediye paketi',
    'kurban',
    'bayram hediyesi',
    'nişan',
    'düğün',
    'baby shower',
    'yılbaşı hediyesi',
    'sevgililer günü',
    'anneler günü',
    'babalar günü',
    'mezuniyet hediyesi',
  ],
  salary: [
    'maaş',
    'ücret',
    'ödeme',
    'ikramiye',
    'transfer',
    'gelir',
    'bordro',
    'net maaş',
    'brüt maaş',
    'prim',
    'fazla mesai',
    'serbest çalışma',
    'freelance',
    'proje ücreti',
    'danışmanlık ücreti',
    'komisyon',
    'kira geliri',
    'emekli maaşı',
    'burs geliri',
  ],
  investment: [
    'yatırım',
    'borsa',
    'hisse',
    'hisse senedi',
    'bist',
    'borsa istanbul',
    'döviz',
    'euro',
    'dolar',
    'altın',
    'gram altın',
    'gümüş',
    'kripto',
    'bitcoin',
    'ethereum',
    'binance',
    'btcturk',
    'paribu',
    'fon',
    'yatırım fonu',
    'emeklilik',
    'bes',
    'bireysel emeklilik',
    'tahvil',
    'bono',
    'mevduat',
    'vadeli mevduat',
    'portföy',
  ],
  refund: [
    'iade',
    'geri ödeme',
    'geri dönüş',
    'cashback',
    'para iadesi',
    'ürün iadesi',
    'iptal',
    'banka iadesi',
    'kredi kartı iadesi',
    'vergi iadesi',
    'kdv iadesi',
    'nakit iade',
  ],
};

export default tr;
